### ISSUE TITLE
Cannot build usingn mix, error message: Error: Mix path not set

### ISSUE THREAD

**Issue by HatsuMora** [KronicDeth/intellij-elixir#1004]
The project contains a empty project generated with:

    mix phoenix.new ProjectName --app gowther --database mysql --no-ecto

Then en Elixir Comiler settings -> compile project with mix (in the default also doesn't work) 

When I try to build I have the following message: 
Error: Mix path not set

Note: If i run from the terminal it works.

IntelliJ idea 2017.3.4
Ubuntu 17.10
Erlang/OTP 20
Elixir 1.5.2
Mix 1.5.2

This is the build log:

018-01-24 22:34:50,866 [  49451]   INFO - .incremental.IncProjectBuilder - Mix path is not set.
org.jetbrains.jps.incremental.ProjectBuildException: Mix path is not set.
	at org.elixir_lang.jps.builder.ElixirBuilder.doBuildWithMix(ElixirBuilder.java:194)
	at org.elixir_lang.jps.builder.ElixirBuilder.build(ElixirBuilder.java:153)
	at org.elixir_lang.jps.builder.ElixirBuilder.build(ElixirBuilder.java:81)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTarget(IncProjectBuilder.java:953)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:934)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:995)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:886)
	at org.jetbrains.jps.incremental.IncProjectBuilder.access$500(IncProjectBuilder.java:68)
	at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer.lambda$queueTask$0(IncProjectBuilder.java:857)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-01-24 22:34:50,889 [  49474]   INFO - .incremental.IncProjectBuilder - Mix path is not set.
org.jetbrains.jps.incremental.ProjectBuildException: Mix path is not set.
	at org.elixir_lang.jps.builder.ElixirBuilder.doBuildWithMix(ElixirBuilder.java:194)
	at org.elixir_lang.jps.builder.ElixirBuilder.build(ElixirBuilder.java:153)
	at org.elixir_lang.jps.builder.ElixirBuilder.build(ElixirBuilder.java:81)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTarget(IncProjectBuilder.java:953)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:934)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:995)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:886)
	at org.jetbrains.jps.incremental.IncProjectBuilder.access$500(IncProjectBuilder.java:68)
	at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer.lambda$queueTask$0(IncProjectBuilder.java:857)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

Does anyone knows how to fix or workaround this error? Thank you so much!

**Comment by ChrisZou** [comment]
+1
