### ISSUE TITLE
Handle :erl_abstract_code backend in :debug_info_v1 in Dbgi chunk for :ets.select

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#1040]
# Version

7.3.0

Jump to definition to erlang module method with `Ctl+click` cause 4 errors.

e.q.
`Ctl+click` on `select` cause these error at the code below. 

```
:ets.select(table_name, query)
```

### Error1

```
Dbgi tuple with :debug_info_v1 tag has unknown backend (erl_abstract_code)

                         ## metadata

                         ```elixir
                         {[{:attribute, 1, :file, {'ets.erl', 1}}, {:attribute, 20, :module, :ets},  ...too many metadatas...
                         ```
java.lang.Throwable:                          Dbgi tuple with :debug_info_v1 tag has unknown backend (erl_abstract_code)

                         ## metadata

                         ```elixir
                         {[{:attribute, 1, :file, {'ets.erl', 1}}, {:attribute, 20, :module, :ets},  ...too many metadatas...
                        ```
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1FromBackend(V1.kt:61)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1(V1.kt:37)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1(V1.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.fromTupleTag(Term.kt:62)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.fromTuple(Term.kt:49)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.from(Term.kt:29)
	at org.elixir_lang.beam.Beam.debugInfo(Beam.kt:88)
	at org.elixir_lang.beam.Cache$debugInfo$2.invoke(Cache.kt:10)
	at org.elixir_lang.beam.Cache$debugInfo$2.invoke(Cache.kt:5)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at org.elixir_lang.beam.Cache.getDebugInfo(Cache.kt)
	at org.elixir_lang.beam.FileEditor.addTab(FileEditor.kt:83)
	at org.elixir_lang.beam.FileEditor.getComponent(FileEditor.kt:40)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.createEditorComponent(EditorComposite.java:184)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.createTabbedPaneWrapper(EditorComposite.java:173)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.<init>(EditorComposite.java:121)
	at com.intellij.openapi.fileEditor.impl.EditorWithProviderComposite.<init>(EditorWithProviderComposite.java:40)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.createComposite(FileEditorManagerImpl.java:984)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$8(FileEditorManagerImpl.java:878)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:653)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:666)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:959)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:786)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:768)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:768)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:699)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:155)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditor$10(FileEditorManagerImpl.java:1113)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1111)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInAnyFileEditor(OpenFileDescriptor.java:145)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:131)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditorOrNativeApp(OpenFileDescriptor.java:127)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:114)
	at com.intellij.psi.impl.PsiElementBase.navigate(PsiElementBase.java:197)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.gotoTargetElement(GotoDeclarationAction.java:198)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.invoke(GotoDeclarationAction.java:125)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$null$0(CodeInsightAction.java:73)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:79)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:70)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:278)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Error 2

```
Worker exited due to exception
java.lang.StackOverflowError
	at com.intellij.refactoring.util.JavaNonCodeSearchElementDescriptionProvider.getElementDescription(JavaNonCodeSearchElementDescriptionProvider.java)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:30)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
....... too many logs ......
```

### Error 3

```
null
java.lang.StackOverflowError
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:36)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:101)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:29)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
....... too many logs ......
```

### Error 4

```
                         Dbgi tuple with :debug_info_v1 tag has unknown backend (erl_abstract_code)

                         ## metadata

                         ```elixir
                        {[{:attribute, 1, :file, {'ets.erl', 1}}, {:attribute, 20, :module, :ets},  .... too many ....
                         ```
java.lang.Throwable:                          Dbgi tuple with :debug_info_v1 tag has unknown backend (erl_abstract_code)

                         ## metadata

                         ```elixir
                         {[{:attribute, 1, :file, {'ets.erl', 1}}, {:attribute, 20, :module, :ets},  .... too many ....
                         ```
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1FromBackend(V1.kt:61)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1(V1.kt:37)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1(V1.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.fromTupleTag(Term.kt:62)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.fromTuple(Term.kt:49)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.from(Term.kt:29)
	at org.elixir_lang.beam.Beam.debugInfo(Beam.kt:88)
	at org.elixir_lang.beam.Cache$debugInfo$2.invoke(Cache.kt:10)
	at org.elixir_lang.beam.Cache$debugInfo$2.invoke(Cache.kt:5)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at org.elixir_lang.beam.Cache.getDebugInfo(Cache.kt)
	at org.elixir_lang.beam.FileEditor.addTab(FileEditor.kt:83)
	at org.elixir_lang.beam.FileEditor.getComponent(FileEditor.kt:40)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.fireSelectedEditorChanged(EditorComposite.java:223)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.access$500(EditorComposite.java:69)
	at com.intellij.openapi.fileEditor.impl.EditorComposite$MyChangeListener.stateChanged(EditorComposite.java:422)
	at com.intellij.ui.JBTabsPaneImpl.fireChanged(JBTabsPaneImpl.java:81)
	at com.intellij.ui.JBTabsPaneImpl.access$100(JBTabsPaneImpl.java:36)
	at com.intellij.ui.JBTabsPaneImpl$2.selectionChanged(JBTabsPaneImpl.java:67)
	at com.intellij.ui.tabs.impl.JBTabsImpl.fireSelectionChanged(JBTabsImpl.java:960)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:916)
	at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:880)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.java:862)
	at com.intellij.ui.tabs.impl.TabLabel$1.mousePressed(TabLabel.java:98)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
Related to #1030.

**Comment by odk211** [comment]
Now fixed. thanks!
