### ISSUE TITLE
ByteSubarray.get ArrayIndexOutOfBoundsException for 0

### ISSUE THREAD

**Issue by horros** [KronicDeth/intellij-elixir#1052]
# Version

7.4.0

# Exception

## Message

Array index out of range: 0

## Stacktrace

```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at org.elixir_lang.beam.ByteSubarray.get(ByteArray.kt:41)
	at org.elixir_lang.beam.ByteSubarray.getUnsignedByte(ByteArray.kt:35)
	at org.elixir_lang.beam.ByteSubarray.toLong(ByteArray.kt:7)
	at org.elixir_lang.beam.term.Integer$Companion.from(Term.kt:176)
	at org.elixir_lang.beam.term.Term$Companion.from(Term.kt:37)
	at org.elixir_lang.beam.chunk.code.Operation$Companion.from(Operation.kt:222)
	at org.elixir_lang.beam.chunk.Code$Companion.from(Code.kt:209)
	at org.elixir_lang.beam.chunk.Code$Companion.from$default(Code.kt:171)
	at org.elixir_lang.beam.Beam.code(Beam.kt:85)
	at org.elixir_lang.beam.Cache$code$2.invoke(Cache.kt:11)
	at org.elixir_lang.beam.Cache$code$2.invoke(Cache.kt:8)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at org.elixir_lang.beam.Cache.getCode(Cache.kt)
	at org.elixir_lang.beam.assembly.Controls.computeDocumentText(Controls.kt:178)
	at org.elixir_lang.beam.assembly.Controls.<init>(Controls.kt:36)
	at org.elixir_lang.beam.chunk.code.NamespaceKt.component(namespace.kt:14)
	at org.elixir_lang.beam.FileEditor.addTab(FileEditor.kt:79)
	at org.elixir_lang.beam.FileEditor.getComponent(FileEditor.kt:38)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.a(EditorComposite.java:184)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.a(EditorComposite.java:173)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.<init>(EditorComposite.java:121)
	at com.intellij.openapi.fileEditor.impl.EditorWithProviderComposite.<init>(EditorWithProviderComposite.java:40)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:984)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:878)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:653)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:666)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:959)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:786)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:768)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:768)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:699)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:155)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:1113)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1111)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInAnyFileEditor(OpenFileDescriptor.java:145)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:131)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditorOrNativeApp(OpenFileDescriptor.java:127)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:114)
	at com.intellij.psi.impl.PsiElementBase.navigate(PsiElementBase.java:197)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:198)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.invoke(GotoDeclarationAction.java:125)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$null$0(CodeInsightAction.java:73)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:79)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:70)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:278)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by sh41** [comment]
Fixed in #3947.

The crash was a decoding bug, not a corrupt file. In the compact term format an integer whose tag has
bits 7-5 set to `111` does not carry its byte length in those bits — they are an escape. The length
follows as its own compact term, and the real length is that value plus 9. The plugin read the byte
after the tag as the length directly, so a nested length tag of `0x00` was taken as a length of zero,
and converting a zero-length subarray read byte 0 of it. A length of zero is unrepresentable here; the
smallest this form can express is 9.

The same branch was also decoding every integer literal of 9 bytes or more to the wrong value, silently.
That is fixed too.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but
it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us
why.
