### ISSUE TITLE
header typeID (null) did not match expected (FOR1) Elixir.Absinthe.Blueprint.Document.Fragment.beam

### ISSUE THREAD

**Issue by mmacheerpuppy** [KronicDeth/intellij-elixir#1058]
# Version

7.4.0

# Exception

## Message

header typeID (null) did not match expected (FOR1) from C:/Users/cleach/Documents/git/DFMS-GraphQL-API/_build/dev/lib/absinthe/ebin/Elixir.Absinthe.Blueprint.Document.Fragment.beam

## Stacktrace

```
java.lang.Throwable: header typeID (null) did not match expected (FOR1) from C:/Users/cleach/Documents/git/DFMS-GraphQL-API/_build/dev/lib/absinthe/ebin/Elixir.Absinthe.Blueprint.Document.Fragment.beam
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at org.elixir_lang.beam.Beam$Companion.from(Beam.kt:116)
	at org.elixir_lang.beam.Beam$Companion.from(Beam.kt:182)
	at org.elixir_lang.beam.Cache$Companion.from(Cache.kt:38)
	at org.elixir_lang.beam.Cache$Companion.from(Cache.kt:28)
	at org.elixir_lang.beam.chunk.lines.file_names.Indexer.map(Indexer.kt:9)
	at org.elixir_lang.beam.chunk.lines.file_names.Indexer.map(Indexer.kt:7)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:273)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:98)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:213)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1654)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$19(FileBasedIndexImpl.java:1582)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:511)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1541)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1529)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1508)
	at com.intellij.util.indexing.FileBasedIndexProjectHandler.lambda$reindexRefreshedFiles$2(FileBasedIndexProjectHandler.java:161)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:227)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
I can view this just fine, so I'm going to guess that is some sort of race with the file being read while it is being built and written to disk.  I'll add more logging to see if it becomes more obvious.
