### ISSUE TITLE
Cannot read scheme MixRunConfigurationType-Local_ factoryName_ Elixir Mix.xml

### ISSUE THREAD

**Issue by evilosa** [KronicDeth/intellij-elixir#1074]
# Version

7.4.0

# Exception

## Message

Cannot read scheme MixRunConfigurationType-Local_ factoryName_ Elixir Mix.xml

## Stacktrace

```
java.lang.AssertionError
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:92)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:54)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:216)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:170)
	at com.intellij.configurationStore.KotlinAwareBeanBinding.deserialize(xmlSerializer.kt:189)
	at com.intellij.configurationStore.XmlSerializer.deserialize(xmlSerializer.kt:75)
	at com.intellij.execution.configurations.RunConfigurationBase.readExternal(RunConfigurationBase.java:207)
	at com.intellij.execution.configurations.ModuleBasedConfiguration.readExternal(ModuleBasedConfiguration.java:111)
	at org.elixir_lang.mix.runner.MixRunConfigurationBase.readExternal(MixRunConfigurationBase.java:140)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:218)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:51)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:34)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:20)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:69)
	at com.intellij.configurationStore.SchemeManagerImpl.loadScheme(SchemeManagerImpl.kt:503)
	at com.intellij.configurationStore.SchemeManagerImpl.access$loadScheme(SchemeManagerImpl.kt:64)
	at com.intellij.configurationStore.SchemeManagerImpl$loadSchemes$2.invoke(SchemeManagerImpl.kt:335)
	at com.intellij.configurationStore.SchemeManagerImpl$loadSchemes$2.invoke(SchemeManagerImpl.kt:64)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren(SchemeManagerIprProvider.kt:31)
	at com.intellij.configurationStore.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:333)
	at com.intellij.configurationStore.SchemeManagerImpl.reload(SchemeManagerImpl.kt:381)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:572)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:47)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:375)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:331)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:121)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:96)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:43)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.requestLoadWorkspaceAndProjectRunConfiguration(ProjectRunConfigurationInitializer.kt:47)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.access$requestLoadWorkspaceAndProjectRunConfiguration(ProjectRunConfigurationInitializer.kt:24)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer$1.projectComponentsInitialized(ProjectRunConfigurationInitializer.kt:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy65.projectComponentsInitialized(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:279)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:274)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectWithProgress(ProjectManagerImpl.java:535)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$200(ProjectManagerImpl.java:54)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:481)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:478)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:320)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by sh41** [comment]
Fixed — apologies for the eight-year silence on this.

Reading the stack trace rather than the message: the failure is `java.lang.AssertionError` raised from the IDE's own `OptionTagBinding` while deserializing your saved configuration's `module` option. That option declares a value attribute, and the assertion fired on the branch reached when the attribute is missing but the element has children. A bare `AssertionError` with no message, which is what your report shows.

Both halves of that path are gone now:

- `OptionTagBinding` no longer exists in the IDE. It is `TagBinding` now, and when an option declares a value attribute it reads that attribute and stops — it no longer branches on child elements, so the assertion has nowhere left to fire.
- `MixRunConfigurationBase`, the plugin frame directly below it in your trace, no longer exists either; the run configurations were rewritten from Java to Kotlin.

To be straight about the limits: I did not reproduce your original scenario, and nobody ever collected the saved configuration file that triggered it. What I did instead was add a regression test that feeds the exact malformed shape the assertion needed — a `module` element with children and no name attribute — through the current reader, and it no longer throws.

Writing that test also exposed two real defects in the same save/load path, now fixed: every Elixir run configuration wrote its `module` element twice, and the "include system environment variables" setting was accepted in the editor and then silently discarded on save. Both are in #3918, along with the test.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
