### ISSUE TITLE
accessExpressions should be flattened with buildAccessExpressionChildren

### ISSUE THREAD

**Issue by LogaJ** [KronicDeth/intellij-elixir#1075]
# Version

7.4.0

# Exception

## Message

accessExpressions should be flattened with buildAccessExpressionChildren

## Stacktrace

```
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren
	at org.elixir_lang.formatter.Block.<init>(Block.java:306)
	at org.elixir_lang.formatter.Block.buildChild(Block.java:790)
	at org.elixir_lang.formatter.Block.lambda$buildMapUpdateArgumentsChildren$27(Block.java:1516)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:325)
	at org.elixir_lang.formatter.Block.buildMapUpdateArgumentsChildren(Block.java:1506)
	at org.elixir_lang.formatter.Block.lambda$buildMapArgumentsChildren$24(Block.java:1419)
	at org.elixir_lang.formatter.Block.lambda$buildContainerChildren$14(Block.java:1079)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:325)
	at org.elixir_lang.formatter.Block.buildContainerChildren(Block.java:1069)
	at org.elixir_lang.formatter.Block.buildMapArgumentsChildren(Block.java:1407)
	at org.elixir_lang.formatter.Block.lambda$buildMapChildren$25(Block.java:1439)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:325)
	at org.elixir_lang.formatter.Block.buildMapChildren(Block.java:1434)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:876)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:963)
	at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:61)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:164)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:264)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:136)
	at com.intellij.formatting.engine.WrapBlocksState.doIteration(WrapBlocksState.java:47)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:41)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:107)
	at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:507)
	at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:493)
	at com.intellij.formatting.FormatterImpl.adjustLineIndentsForRange(FormatterImpl.java:386)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$3.doPerform(CodeStyleManagerImpl.java:390)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:106)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.adjustLineIndent(CodeStyleManagerImpl.java:393)
	at com.intellij.codeInsight.editorActions.PasteHandler.b(PasteHandler.java:306)
	at com.intellij.codeInsight.editorActions.PasteHandler.a(PasteHandler.java:237)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.intellij.codeInsight.editorActions.PasteHandler.a(PasteHandler.java:225)
	at com.intellij.codeInsight.editorActions.PasteHandler.execute(PasteHandler.java:121)
	at com.intellij.codeInsight.editorActions.PasteHandler.doExecute(PasteHandler.java:74)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:207)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:110)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:86)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by sh41** [comment]
Fixed in #3948.

The map update's left operand was the one place the formatter built a child block without first
flattening an access expression. It needed a literal or an aggregate on that side — a map, list or
tuple literal, an alias, a string, atom or number, an anonymous function, or anything parenthesised.
A bare name, `a.b`, `a[:b]` and `f(a)` all parse as something else and never reached it, and it fired
through paste and Auto-Indent Lines rather than a whole-file reformat. That combination is why it went
eight years without a second report.

Most of the affected shapes aren't valid Elixir — `%{1 | k: 1}` means nothing — but they are states
you type through, and the editor has to survive them.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but
it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us
why.
