### ISSUE TITLE
NPE for finalArguments of Structure navigationElement

### ISSUE THREAD

**Issue by ctk0418** [KronicDeth/intellij-elixir#1095]
# Version

7.4.0

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.structure_view.element.structure.Structure.getChildren(Structure.java:73)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:50)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:214)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:54)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:46)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.getChildren(StructureViewComponent.java:755)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:62)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:229)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:139)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:175)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:576)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:551)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:444)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:410)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:105)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:114)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:76)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
Final arguments is `null` when it is expected not to be.

https://github.com/KronicDeth/intellij-elixir/blob/815c0553d26f58af2cea0a7d77dcb0742d2c52c8/src/org/elixir_lang/structure_view/element/structure/Structure.java#L69-L73

**Comment by sh41** [comment]
Fixed — and this turned out to be the same defect as #2107, from the other end.

`Call.finalArguments` catches a `NullPointerException`, logs it and returns null. That null then reached `Structure.getChildren`, which asserted it wasn't null. So whether this surfaced as the NPE in your title or as the `AssertionError` in #2107 depended only on whether assertions were enabled — one chain, two faces.

The trigger was a `defstruct` or `defexception` written with a `do` block:

```elixir
defstruct do
  :ok
end
```

Not valid Elixir, but the editor parses what you type before it compiles. The check deciding whether to build a struct node asks how many arguments Elixir passes, where a `do` block counts as one; the code building the node's children reads the arguments written inside the call, where there are none.

There's now a `finalArity` for the written count alongside the existing resolved arity, and the checks that go on to read written arguments use it, with a test covering sixteen `defstruct`/`defexception` shapes.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
