### ISSUE TITLE
Worker exited due to exception: org.elixir_lang.psi.impl.ElixirParenthesesArgumentsImpl cannot be cast to org.elixir_lang.psi.ElixirList

### ISSUE THREAD

**Issue by JohnBat26** [KronicDeth/intellij-elixir#1130]
# Version

7.5.0

# Exception

## Message

Worker exited due to exception: org.elixir_lang.psi.impl.ElixirParenthesesArgumentsImpl cannot be cast to org.elixir_lang.psi.ElixirList

## Stacktrace

```
java.lang.ClassCastException: org.elixir_lang.psi.impl.ElixirParenthesesArgumentsImpl cannot be cast to org.elixir_lang.psi.ElixirList
	at org.elixir_lang.psi.ElementDescriptionProvider.getElementDescription(ElementDescriptionProvider.kt:80)
	at org.elixir_lang.psi.ElementDescriptionProvider.getElementDescription(ElementDescriptionProvider.kt:38)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:30)
	at com.intellij.usageView.UsageViewUtil.getType(UsageViewUtil.java:71)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$8.getInfo(CtrlMouseHandler.java:595)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.c(CtrlMouseHandler.java:837)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$3500(CtrlMouseHandler.java:772)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:815)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/blob/c7dc51bbd2a2cb60a2a031a51739edd5302adfe3/src/org/elixir_lang/psi/ElementDescriptionProvider.kt#L77-L89

**Comment by sh41** [comment]
This is fixed.

The line you pinned in your comment above — the unchecked cast that assumed a keyword pair's enclosing
collection was always a `[...]` list literal — was changed to a safe cast in 31683c1b93cbf2abdc42f5993debdb0e9180830b. Trailing keywords written directly in a call's parentheses, like `foo(x: 1)`, parse with a different parent than a list literal does, which is exactly the shape that made the old cast throw. It first shipped in v8.0.0 and is unchanged (still a safe cast) in the current release, v24.0.1.

That commit's own description names three of several near-identical reports it fixed, and this issue wasn't one of the ones listed even though it's the same crash — easy to miss among that many duplicates.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
