### ISSUE TITLE
org.elixir_lang.beam.chunk.Code needs to add OTP 21 opcodes (>= 163)

### ISSUE THREAD

**Issue by jxljf** [KronicDeth/intellij-elixir#1155]
# Version

7.5.0

# Exception

## Message

Max opcode (163) exceeds expected max opcode (159).  Additional opcodes have been added to the end of https://github.com/erlang/otp/blob/master/lib/compiler/src/genop.tab.

## Stacktrace

```
java.lang.Throwable: Max opcode (163) exceeds expected max opcode (159).  Additional opcodes have been added to the end of https://github.com/erlang/otp/blob/master/lib/compiler/src/genop.tab.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at org.elixir_lang.beam.chunk.Code$Companion.from(Code.kt:193)
	at org.elixir_lang.beam.chunk.Code$Companion.from$default(Code.kt:171)
	at org.elixir_lang.beam.Beam.code(Beam.kt:82)
	at org.elixir_lang.beam.Cache$code$2.invoke(Cache.kt:11)
	at org.elixir_lang.beam.Cache$code$2.invoke(Cache.kt:8)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at org.elixir_lang.beam.Cache.getCode(Cache.kt)
	at org.elixir_lang.beam.assembly.Controls.computeDocumentText(Controls.kt:178)
	at org.elixir_lang.beam.assembly.Controls.<init>(Controls.kt:36)
	at org.elixir_lang.beam.chunk.code.Component.addChildren(Component.kt:30)
	at org.elixir_lang.beam.chunk.code.Component.ensureChildrenAdded(Component.kt:40)
	at org.elixir_lang.beam.chunk.code.Component.stateChanged(Component.kt:23)
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:416)
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
	at com.intellij.ui.components.JBTabbedPane.setSelectedIndex(JBTabbedPane.java:84)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
	at java.awt.Component.processMouseEvent(Component.java:6545)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:723)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by KronicDeth** [comment]
Test case:

1. `git clone https://github.com/C-S-D/alembic`
2. `cd alembic`
3. `brew switch elixir 1.7.1`
4. `brew switch erlang 21.0.4`
5. `rm -rf _build`
6. `mix compile`
7. Open `_build/dev/lib/alembic/ebin/Elixir.Alembic.Fetch.Includes.beam` in IntelliJ Elixir
8. Click BEAM Chunks tab
9. Click Code Tab

## Actual

Error

## Expected

`get_tl` operation is shown.
