### ISSUE TITLE
BeamFileImpl throws UnsupportedOperationException on PsiElementBase.checkDelete

### ISSUE THREAD

**Issue by maxmedvedev** [KronicDeth/intellij-elixir#1201]
```
java.lang.UnsupportedOperationException: org.elixir_lang.beam.psi.BeamFileImpl
	at com.intellij.psi.impl.PsiElementBase.checkDelete(PsiElementBase.java:144)
	at com.intellij.ide.util.DeleteHandler.doDelete(DeleteHandler.java:267)
	at com.intellij.ide.util.DeleteHandler.lambda$null$0(DeleteHandler.java:217)
	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.disableChecksDuring(NonProjectFileWritingAccessProvider.java:181)
	at com.intellij.ide.util.DeleteHandler.lambda$deleteInCommand$1(DeleteHandler.java:202)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:139)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:97)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:87)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:73)
	at com.intellij.ide.util.DeleteHandler.deleteInCommand(DeleteHandler.java:202)
	at com.intellij.ide.util.DeleteHandler.deletePsiElement(DeleteHandler.java:187)
	at com.intellij.ide.util.DeleteHandler.deletePsiElement(DeleteHandler.java:113)
	at com.intellij.ide.projectView.impl.ProjectViewImpl$MyDeletePSIElementProvider.deleteElement(ProjectViewImpl.java:972)
	at com.intellij.ide.actions.DeleteAction.actionPerformed(DeleteAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by sh41** [comment]
This is still there, thanks for the report.

`BeamFileImpl` — the plugin's decompiled view of a `.beam` file — never overrides `checkDelete()` or `delete()`, so both fall through to the platform's default, which throws exactly the unchecked exception in your trace instead of the graceful "can't delete this" message a user would normally see.

The class already handles a different disallowed edit the right way: renaming a decompiled file throws a proper, checked exception with a clear message ("Cannot modify decompiled Beam files"), and it already declares itself non-writable. Delete is the one case that was never given the same treatment. The fix is small — two more overrides reusing that same message — but hasn't been done yet, so I'm leaving this open rather than closing it out.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
