### ISSUE TITLE
intellij-erlang is now a required dependency

### ISSUE THREAD

**Issue by adrienmo** [KronicDeth/intellij-elixir#1227]
# Exception

## Stacktrace

```
java.lang.AssertionError
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getOrCache(VirtualFilePointerContainerImpl.java:216)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getFiles(VirtualFilePointerContainerImpl.java:307)
	at com.intellij.openapi.projectRoots.impl.RootsAsVirtualFilePointers.getFiles(RootsAsVirtualFilePointers.java:45)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl$MyRootProvider.getFiles(ProjectJdkImpl.java:279)
	at org.elixir_lang.Erl.prependCodePaths(Erl.kt:39)
	at org.elixir_lang.Erl.setErl(Erl.kt:48)
	at org.elixir_lang.Erl.commandLine(Erl.kt:16)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:20)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.mix.importWizard.MixProjectRootStep$1.run(MixProjectRootStep.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:574)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by adrienmo** [comment]
just need to also install erlang plugin

**Comment by KronicDeth** [comment]
I wasn't able to reproduce when removing all SDKs and uninstall the Erlang plugin, so I don't think it was related.
