### ISSUE TITLE
com.ericsson.otp.erlang.OtpErlangExit: noconnection from debugger

### ISSUE THREAD

**Issue by simapetr85** [KronicDeth/intellij-elixir#1240]
# Version

8.0.0

# Exception

## Message

com.ericsson.otp.erlang.OtpErlangExit: noconnection

## Stacktrace

```
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: noconnection
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.elixir_lang.MailBox.wait(MailBox.kt:202)
	at org.elixir_lang.MailBox.receive(MailBox.kt:176)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:126)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:113)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:100)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:44)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:38)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.ericsson.otp.erlang.OtpErlangExit: noconnection
	at com.ericsson.otp.erlang.OtpMbox.receiveMsg(OtpMbox.java:272)
	at com.ericsson.otp.erlang.OtpMbox.receive(OtpMbox.java:168)
	at org.elixir_lang.MailBox.loop(MailBox.kt:218)
	at org.elixir_lang.MailBox.access$loop(MailBox.kt:21)
	at org.elixir_lang.MailBox$1.run(MailBox.kt:25)
	... 6 more

```

**Comment by KronicDeth** [comment]
This would indicate that the debugger wasn't able to connect to `epmd` or the debugged node itself.  On macOS you may see a prompt to allow either `beam.smp` or your JetBrains IDE to accept connections, which you need to OK.  I'm not sure what could block the connection on Windows or Linux.

**Comment by KronicDeth** [comment]
No feedback received.
