### ISSUE TITLE
com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getOrCache AssertionError

### ISSUE THREAD

**Issue by vmptk** [KronicDeth/intellij-elixir#1242]
# Exception

## Stacktrace

```
java.lang.AssertionError
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getOrCache(VirtualFilePointerContainerImpl.java:216)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getFiles(VirtualFilePointerContainerImpl.java:307)
	at com.intellij.openapi.projectRoots.impl.RootsAsVirtualFilePointers.getFiles(RootsAsVirtualFilePointers.java:45)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl$MyRootProvider.getFiles(ProjectJdkImpl.java:279)
	at org.elixir_lang.file.LevelPropertyPusher.rootUpdateTaskList(LevelPropertyPusher.java:225)
	at org.elixir_lang.file.LevelPropertyPusher.access$000(LevelPropertyPusher.java:47)
	at org.elixir_lang.file.LevelPropertyPusher$1.lambda$performInDumbMode$0(LevelPropertyPusher.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at org.elixir_lang.file.LevelPropertyPusher$1.performInDumbMode(LevelPropertyPusher.java:197)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runSingleTask$9(DumbServiceImpl.java:541)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.project.DumbServiceImpl.runSingleTask(DumbServiceImpl.java:534)
	at com.intellij.openapi.project.DumbServiceImpl.runBackgroundProcess(DumbServiceImpl.java:517)
	at com.intellij.openapi.project.DumbServiceImpl.access$400(DumbServiceImpl.java:51)
	at com.intellij.openapi.project.DumbServiceImpl$4.run(DumbServiceImpl.java:474)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sh41** [comment]
This is fixed.

The file this crash came from, `LevelPropertyPusher.java`, doesn't exist anymore — it was removed entirely in 679a9689cfe097018b9baa4e894d4550a84d7aac, when support for Elixir versions before 1.6 was dropped. Nothing in the plugin registers a file-property pusher today, so the code path that reached this platform assertion can't be reached anymore. First shipped in v12.0.0 and gone from the codebase ever since, including the current release, v24.0.1.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
