### ISSUE TITLE
Clear Buffer is not supported in IEx or IEx Mix Run Configurations

### ISSUE THREAD

**Issue by OmanF** [KronicDeth/intellij-elixir#1247]
# Exception

When trying to clear the `run` window (after trying to use a user-defined configuration), using the shortcut `Cmd-K` (the default shortcut), got an error, buffer was not cleared.

## Stacktrace

```
java.lang.NoSuchMethodException: com.intellij.terminal.JBTerminalPanel.clearBuffer(java.lang.Boolean)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at org.elixir_lang.run.TerminalExecutionConsole$MyJBTerminalPanel.clearBuffer(TerminalExecutionConsole.java:365)
	at com.jediterm.terminal.ui.TerminalPanel.lambda$getActions$8(TerminalPanel.java:1352)
	at com.jediterm.terminal.ui.TerminalAction$1.actionPerformed(TerminalAction.java:149)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
The JBTerminal version that ships changed part way through the 2018.X
line.  I had compensated for part of change with reflection, but I guessing
this is another incompatibility.  Which IDE and version are you using?

**Comment by OmanF** [comment]
I'm on IntelliJ IDEA 2018.2 Community version (and just in case it matters, on macOS High Sierra).

<img width="674" alt="intellij-version" src="https://user-images.githubusercontent.com/7848797/44980857-4e9edf00-af71-11e8-8a97-0b0e23efb03b.png">

**Comment by KronicDeth** [comment]
Well, it definitely should work there because I develop against IDEA Community Edition.  What is Cmd+K supposed to do in your Keymap.  It opens Commit Changes for me and doesn't trigger an error.

**Comment by KronicDeth** [comment]
I can get it to trigger with 

1. Run an IEx or IEX Mix Run configuration (since they use JBTerminal)
2. Right-click to get the context menu
3. Be :trollface: ed  that Cmd+K is bound to Clear Buffer, but the outer IDE binding of Commit Changes still fires
4. Click Clear Buffer in the context menu.

## Actual

Get error

## Expected

Buffer clears

**Comment by KronicDeth** [comment]
I suppose I need to bind Clear Buffer to not clear using JBTerminal, but instead to do whatever typing `clear` does in the `iex` normally since `iex` is in charge of its own screen rewriting.  That's why tab completion works in the terminal.

**Comment by KronicDeth** [comment]
@OmanF as a work-around for now, use `clear` typed into `iex` directly.  That works.

**Comment by OmanF** [comment]
Didn't think about checking the general binding-vs-plugin ones... good catch.
I got the buffer cleared by calling the context menu and selecting the action... no problem getting it cleared, I opened this issue to let you know it's there.

My binding, the default ones, are also `Cmd-K` - `Clear buffer` (plugin) cs `Commit changes` (General/IDE settings).

Seriously, this is *not* a big deal... just have it in the backlog for when "you have time". 😆

**Comment by sh41** [comment]
This was fixed in v10.2.0 (2018-12-23).

The error came from the plugin's own forked `org.elixir_lang.run.TerminalExecutionConsole`, whose `MyJBTerminalPanel.clearBuffer` reflected against `JBTerminalPanel.clearBuffer` — the method the platform changed mid-2018.

Commit 84f8d4fd5 deleted that forked class outright. Both the IEx and IEx Mix run configurations now construct the platform's `com.intellij.terminal.TerminalExecutionConsole` directly, so Clear Buffer is the platform's own action with no plugin override in the way.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
