### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.Icons

### ISSUE THREAD

**Issue by trikanna** [KronicDeth/intellij-elixir#1265]
# Version

2.9.0-pre1

# Description

just opened an Elixir --umbrella project

# Exception

## Stacktrace

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.Icons
	at org.elixir_lang.module.ElixirModuleType.getNodeIcon(ElixirModuleType.java:54)
	at com.intellij.openapi.module.ModuleType.getIcon(ModuleType.java:39)
	at com.intellij.psi.impl.JavaDirectoryIconProvider.getIcon(JavaDirectoryIconProvider.java:46)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.setupIcon(PsiDirectoryNode.java:171)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.updateImpl(PsiDirectoryNode.java:118)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:925)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:126)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:280)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:262)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:256)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:235)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:139)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:175)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetRoot.getNode(AsyncTreeModel.java:473)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:442)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:408)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:117)
	at com.intellij.util.concurrency.Invoker.invokeLaterIfNeeded(Invoker.java:90)
	at com.intellij.util.concurrency.Command$Processor.process(Command.java:48)
	at com.intellij.ui.tree.AsyncTreeModel$1.process(AsyncTreeModel.java:51)
	at com.intellij.util.ui.tree.TreeModelAdapter.treeStructureChanged(TreeModelAdapter.java:59)
	at com.intellij.util.ui.tree.TreeModelListenerList.treeStructureChanged(TreeModelListenerList.java:104)
	at com.intellij.util.ui.tree.AbstractTreeModel.treeStructureChanged(AbstractTreeModel.java:47)
	at com.intellij.ui.tree.StructureTreeModel.lambda$invalidate$1(StructureTreeModel.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:121)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:77)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:260)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KronicDeth** [comment]
@trikanna I have no record of a 2.9.0-pre1.  The stacktrace has classes that make sense for this plugin, but the version number does not.

1. Can you please double check which version you have installed according to Preferences > Plugin > Elixir?

**Comment by trikanna** [comment]
hi @KronicDeth looking for your plugin version I've realized that is related to the Material Theme UI package, it matches the version.

Thank you!

![screen shot 2018-09-19 at 9 10 53 am](https://user-images.githubusercontent.com/141816/45752542-332c0900-bbec-11e8-8db5-ea56273e5296.png)

![screen shot 2018-09-19 at 9 11 07 am](https://user-images.githubusercontent.com/141816/45752549-3626f980-bbec-11e8-8b25-9683c115a269.png)
