### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by iKethavel** [KronicDeth/intellij-elixir#1269]
# Version

2.8.2

# Exception

## Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL (class org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoArgumentsCall)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:252)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.<init>(InplaceRefactoring.java:136)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:92)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:83)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:77)
	at org.elixir_lang.refactoring.variable.rename.Inplace.<init>(Inplace.java:32)
	at org.elixir_lang.refactoring.variable.rename.Handler.createRenamer(Handler.kt:69)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:73)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:83)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:52)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:131)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
2.8.2 does make sense as a version number for this plugin.  The versions went from 2.2.0 to 3.0.0.
