### ISSUE TITLE
Log readNameSet when it is logger than limit (10)

### ISSUE THREAD

**Issue by cblage** [KronicDeth/intellij-elixir#1295]
```
java.lang.Throwable: readNameSet nameSetSize (10) is suspect (>= 10).Read ahead read 0 of 0 unexpected bytes ``
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at org.elixir_lang.psi.stub.call.Deserialized.readNameSet(Deserialized.java:191)
	at org.elixir_lang.psi.stub.call.Deserialized.readGuarded(Deserialized.java:152)
	at org.elixir_lang.psi.stub.call.Deserialized.deserializeCanonicalNameSet(Deserialized.java:114)
	at org.elixir_lang.psi.stub.call.Deserialized.deserialize(Deserialized.java:98)
	at org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall.deserialize(UnmatchedUnqualifiedNoParenthesesCall.java:55)
	at org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall.deserialize(UnmatchedUnqualifiedNoParenthesesCall.java:16)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:199)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:215)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:215)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:152)
	at com.intellij.psi.stubs.SerializationManagerImpl.deserialize(SerializationManagerImpl.java:169)
	at com.intellij.psi.stubs.SerializedStubTree.getStub(SerializedStubTree.java:95)
	at com.intellij.psi.stubs.SerializedStubTree.getStub(SerializedStubTree.java:83)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:119)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:53)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:603)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:926)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:231)
	at com.intellij.psi.stubs.StubProcessingHelperBase.lambda$getAllSpines$0(StubProcessingHelperBase.java:76)
	at com.intellij.util.containers.ContainerUtilRt.map2List(ContainerUtilRt.java:393)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1899)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getAllSpines(StubProcessingHelperBase.java:76)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:56)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:321)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:637)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:625)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:61)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$null$0(StubIndexImpl.java:345)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:253)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$null$1(StubIndexImpl.java:343)
	at com.intellij.util.indexing.FileBasedIndexImpl.disableUpToDateCheckIn(FileBasedIndexImpl.java:668)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$doProcessStubs$2(StubIndexImpl.java:342)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:43)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:340)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:312)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at org.elixir_lang.psi.scope.module.Variants.projectNameElements(Variants.kt:117)
	at org.elixir_lang.psi.scope.module.Variants.access$projectNameElements(Variants.kt:23)
	at org.elixir_lang.psi.scope.module.Variants$Companion.lookupElementList(Variants.kt:153)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:16)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:13)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:273)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:137)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:81)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:71)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:125)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:108)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:92)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:118)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:815)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:800)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:266)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:263)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KronicDeth** [comment]
I've just realized this error I made is kinda useless when the read ahead is 0, which it is outside of development.  I suppose I should attempt to log the read name set, to figure out when this happens what it was talking about.
