### ISSUE TITLE
mix phx.server debugging crash upon hitting breakpoint

### ISSUE THREAD

**Issue by gkmlo** [KronicDeth/intellij-elixir#1314]
PyCharm Community 2018.2
Intellij-Elixir: 9.0

I had a similar error on PyCharm Communit 2017.2 & Intellij-Elixir 7.5 before I upgraded to the latest version.

```
[error] GenServer IntelliJElixir.Debugger.Server terminating
** (FunctionClauseError) no function clause matching in Code.ensure_loaded?/1
    (elixir) lib/code.ex:1003: Code.ensure_loaded?({:badmatch, {:error, :econnrefused}})
    /tmp/intellij_elixir69/debugger/lib/intellij_elixir/debugger/server.ex:461: IntelliJElixir.Debugger.Server.source/1
    /tmp/intellij_elixir69/debugger/lib/intellij_elixir/debugger/server.ex:452: anonymous fn/2 in IntelliJElixir.Debugger.Server.snapshot_with_stacks/0
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    /tmp/intellij_elixir69/debugger/lib/intellij_elixir/debugger/server.ex:449: IntelliJElixir.Debugger.Server.snapshot_with_stacks/0
    /tmp/intellij_elixir69/debugger/lib/intellij_elixir/debugger/server.ex:286: IntelliJElixir.Debugger.Server.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:breakpoint_reached, #PID<0.11888.1>}}
State: %IntelliJElixir.Debugger.Server{attached: #PID<8066.6.0>, evaluate_meta_pid_to_froms: %{}}
```

I cannot find solution to the same issue, but based on some other discussion I did the following:

1. Filter all the modules that uses NIFs or could potentially cause issues. I filtered:
Riffed, Riffed.*, ... , Comeonin, Comeonin.*, JOSE, JOSE.*
2. Check the existence of server.ex, debugged.ex, etc

The command was:
`/usr/lib/erlang/bin/erl -pa /usr/lib/erlang/lib/public_key-1.6.2/ebin -pa /usr/lib/erlang/lib/eunit-2.3.7/ebin -pa /usr/lib/erlang/lib/inets-7.0.2/ebin -pa /usr/lib/erlang/lib/syntax_tools-2.1.6/ebin -pa /usr/lib/erlang/lib/runtime_tools-1.13.1/ebin -pa /usr/lib/erlang/lib/debugger-4.2.6/ebin -pa /usr/lib/erlang/lib/kernel-6.1/ebin -pa /usr/lib/erlang/lib/xmerl-1.3.18/ebin -pa /usr/lib/erlang/lib/dialyzer-3.3.1/ebin -pa /usr/lib/erlang/lib/ssl-9.0.2/ebin -pa /usr/lib/erlang/lib/crypto-4.3.3/ebin -pa /usr/lib/erlang/lib/mnesia-4.15.5/ebin -pa /usr/lib/erlang/lib/thrift-0.11.0/ebin -pa /usr/lib/erlang/lib/erts-10.1/ebin -pa /usr/lib/erlang/lib/hipe-3.18.1/ebin -pa /usr/lib/erlang/lib/asn1-5.0.7/ebin -pa /usr/lib/erlang/lib/sasl-3.2.1/ebin -pa /usr/lib/erlang/lib/wx-1.8.5/ebin -pa /usr/lib/erlang/lib/compiler-7.2.5/ebin -pa /usr/lib/erlang/lib/tools-3.0.1/ebin -pa /usr/lib/erlang/lib/parsetools-2.1.8/ebin -pa /usr/lib/erlang/lib/stdlib-3.6/ebin -name debuggede03e41d0-fe39-4a13-9765-799f40e35c87@127.0.0.1 -setcookie e03e41d0-fe39-4a13-9765-799f40e35c87 -eval application:ensure_all_started(elixir) -eval 'Elixir.Code':require_file(<<\"/tmp/intellij_elixir69/debugger/lib/intellij_elixir/debugger/server.ex\">>) -eval 'Elixir.Code':require_file(<<\"/tmp/intellij_elixir69/debugger/lib/intellij_elixir/debugged.ex\">>) -eval 'Elixir.Code':require_file(<<\"/tmp/intellij_elixir69/debugger/lib/mix/tasks/intellij_elixir/debug.ex\">>) -pa /usr/local/lib/elixir/lib/logger/ebin -pa /usr/local/lib/elixir/lib/iex/ebin -pa /usr/local/lib/elixir/lib/elixir/ebin -pa /usr/local/lib/elixir/lib/eex/ebin -pa /usr/local/lib/elixir/lib/mix/ebin -pa /usr/local/lib/elixir/lib/ex_unit/ebin -noshell -s elixir start_cli -elixir ansi_enabled true -extra /usr/local/lib/elixir/bin/mix do intellij_elixir.debug, phx.server`

Potential relevant issues:
https://github.com/KronicDeth/intellij-elixir/issues/837
https://github.com/KronicDeth/intellij-elixir/issues/1225

**Comment by gkmlo** [comment]
Okay, got it working. Had many modules in _build/**/ebin it tried to interpret. Had to add many of them to the filtered list.
