### ISSUE TITLE
While opening autocomplete menu: java.lang.Throwable: readNameSet nameSetSize (10) is suspect (>= 10)

### ISSUE THREAD

**Issue by kvakvs** [KronicDeth/intellij-elixir#1320]
While building autocomplete list (pressed Ctrl+Space on an incomplete module name) low memory warning popped up.
Increased memory from 750 to 2048M, restarted and pressed Ctrl+Space in same location again.
An empty autocomplete menu appeared, 1 CPU core jumped to 100% for some seconds, then this error appeared.
Autocomplete menu was filled with suggestions a few seconds later successfully while I was filling this report error form.

```
java.lang.Throwable: readNameSet nameSetSize (10) is suspect (>= 10).Read ahead read 0 of 0 unexpected bytes ``
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at org.elixir_lang.psi.stub.call.Deserialized.readNameSet(Deserialized.java:191)
	at org.elixir_lang.psi.stub.call.Deserialized.readGuarded(Deserialized.java:152)
	at org.elixir_lang.psi.stub.call.Deserialized.deserializeCanonicalNameSet(Deserialized.java:114)
	at org.elixir_lang.psi.stub.call.Deserialized.deserialize(Deserialized.java:98)
	at org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall.deserialize(UnmatchedUnqualifiedNoParenthesesCall.java:55)
	at org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall.deserialize(UnmatchedUnqualifiedNoParenthesesCall.java:16)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:199)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:215)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:215)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:152)
	at com.intellij.psi.stubs.SerializationManagerImpl.deserialize(SerializationManagerImpl.java:169)
	at com.intellij.psi.stubs.SerializedStubTree.getStub(SerializedStubTree.java:95)
	at com.intellij.psi.stubs.SerializedStubTree.getStub(SerializedStubTree.java:83)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:119)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:53)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:603)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:926)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:231)
	at com.intellij.psi.stubs.StubProcessingHelperBase.lambda$getAllSpines$0(StubProcessingHelperBase.java:76)
	at com.intellij.util.containers.ContainerUtilRt.map2List(ContainerUtilRt.java:393)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1899)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getAllSpines(StubProcessingHelperBase.java:76)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:56)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:321)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:637)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:625)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:61)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$null$0(StubIndexImpl.java:345)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:253)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$null$1(StubIndexImpl.java:343)
	at com.intellij.util.indexing.FileBasedIndexImpl.disableUpToDateCheckIn(FileBasedIndexImpl.java:668)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$doProcessStubs$2(StubIndexImpl.java:342)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:43)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:340)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:312)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at org.elixir_lang.psi.scope.module.Variants.projectNameElements(Variants.kt:117)
	at org.elixir_lang.psi.scope.module.Variants.access$projectNameElements(Variants.kt:23)
	at org.elixir_lang.psi.scope.module.Variants$Companion.lookupElementList(Variants.kt:153)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:16)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:13)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:273)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:137)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:81)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:71)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:125)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:108)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:92)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:118)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:815)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:800)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:266)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:263)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KronicDeth** [comment]
Do you have a public repo that reproduces the problem?  I want to figure out if a specific dependency has that many names or if it is an actual read error.

**Comment by kvakvs** [comment]
The repository is not public.
The app is Phoenix + Ecto + GraphQL application about 5k lines of code.
I was autocompleting a struct name in `seeds`:
```
%{id: x} = AppName.Repo.insert!(
  %AppName.Repo.<Ctrl+Space here>
)
```

**Comment by KronicDeth** [comment]
Ok, so if it's only 5k lines, unless it's something weird that the GraphQL macros are generating, it's probably one of your dependencies.  Can you post your list of dependencies?  That way I can setup a project with the same dependencies and see if I can trigger it.

**Comment by KronicDeth** [comment]
Forgot to ask, is this on `9.0.0` or `10.0.0`?

**Comment by kvakvs** [comment]
```
  defp deps do
    [
      {:absinthe, "~> 1.4"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe_phoenix, github: "absinthe-graphql/absinthe_phoenix", branch: "master"},
      {:absinthe_relay, "~> 1.4"},
      {:jason, "~> 1.0"},
# sub project 2
      {:ecto, "~> 2.2"},
      {:ecto_fields, "~> 1.1"},
      {:postgrex, "~> 0.13.5"},
# other project
      {:absinthe, "~> 1.4"},
      {:bamboo, "1.0.0-rc.1"},
      {:ecto, "~> 2.2"},
      {:ex_aws, github: "jerel/ex_aws", branch: "signed-headers", override: true},
      {:ex_aws_s3, "~> 2.0"},
      {:geo, "~> 3.0"},
      {:httpoison, "~> 0.13.0"},
      {:jason, "~> 1.0"},
      {:timex, "~> 3.1"},
      {:phoenix_pubsub, "~> 1.0"},
      {:polyline, "~> 0.1.2"},
      {:postgrex, "~> 0.13.5"},
      {:geo_postgis, "~> 2.0"},
      {:comeonin, "~> 4.1"},
      {:bcrypt_elixir, "~> 1.0"},
      {:conform, github: "potatosalad/conform", branch: "features-20180816"},
      {:ecto_fields, "~> 1.1"},
# another sub project
      {:absinthe, "~> 1.4"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe_relay, "~> 1.4"},
      {:absinthe_phoenix, github: "absinthe-graphql/absinthe_phoenix", branch: "master"},
      {:apollo_tracing, "~> 0.4"},
      {:ojson, "~> 1.0"},
      {:phoenix, "~> 1.3"},
      {:geo, "~> 3.0", override: true},
      {:topo, "~> 0.1.2"},
      {:conform, github: "potatosalad/conform", branch: "features-20180816"},
      {:propcheck, "~> 1.1", only: :test},
      {:proper, "~> 1.3", only: :test},
# another sub project
      {:jason, "~> 1.0"},
      {:sentry, github: "potatosalad/sentry-elixir", branch: "features-20180713"},
      {:phoenix, "~> 1.3"},
      {:phoenix_html, "~> 2.10.0"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:polyline, "~> 0.1.2"},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:ranch, "~> 1.6.2", override: true},
      {:absinthe, "~> 1.4"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe_relay, "~> 1.4"},
      {:absinthe_phoenix, github: "absinthe-graphql/absinthe_phoenix", branch: "master"},
      {:apollo_tracing, "~> 0.4"},
      {:geo, "~> 3.0", override: true},
      {:timex, "~> 3.1"},
      {:conform, github: "potatosalad/conform", branch: "features-20180816"},
      {:explode, "~> 1.0"}
    ]
  end
```

**Comment by kvakvs** [comment]
This is 10.0.0 updated today earlier
