### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by lhmathias** [KronicDeth/intellij-elixir#1333]
# Version

2.9.6

# Exception

## Stacktrace

```
java.lang.AssertionError
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.b(VirtualFilePointerContainerImpl.java:216)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getUrls(VirtualFilePointerContainerImpl.java:211)
	at com.intellij.openapi.projectRoots.impl.RootsAsVirtualFilePointers.getUrls(RootsAsVirtualFilePointers.java:52)
	at com.intellij.openapi.projectRoots.impl.RootsAsVirtualFilePointers.copyRootsFrom(RootsAsVirtualFilePointers.java:115)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.copyTo(ProjectJdkImpl.java:265)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.clone(ProjectJdkImpl.java:248)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.clone(ProjectJdkImpl.java:30)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.reset(ProjectSdksModel.java:81)
	at org.elixir_lang.facet.SdksService.getModel(SdksService.kt:18)
	at org.elixir_lang.facet.external_library.conversion.ConverterKt.sdkNameSet(Converter.kt:41)
	at org.elixir_lang.facet.external_library.conversion.ConverterKt.missingLibraryNameSet(Converter.kt:38)
	at org.elixir_lang.facet.external_library.conversion.ConverterKt.access$missingLibraryNameSet(Converter.kt:1)
	at org.elixir_lang.facet.external_library.conversion.Converter.isConversionNeeded(Converter.kt:13)
	at com.intellij.conversion.impl.ConversionRunner.isConversionNeeded(ConversionRunner.java:89)
	at com.intellij.impl.ConversionServiceImpl.isConversionNeeded(ConversionServiceImpl.java:165)
	at com.intellij.impl.ConversionServiceImpl.convert(ConversionServiceImpl.java:108)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:522)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:203)
	at com.intellij.ide.actions.OpenFileAction.a(OpenFileAction.java:88)
	at com.intellij.ide.actions.OpenFileAction.a(OpenFileAction.java:66)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:174)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:114)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:91)
	at com.intellij.ide.actions.OpenFileAction.a(OpenFileAction.java:58)
	at com.intellij.ide.actions.OpenFileAction.b(OpenFileAction.java:44)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/blob/124633eeb954130ef8b440295bee2dce41ac6254/src/org/elixir_lang/facet/SdksService.kt#L18

**Comment by KronicDeth** [comment]
https://github.com/JetBrains/intellij-community/blob/ac16fe595e79a893df2bce5ac8e2d5904a483ede/platform/core-impl/src/com/intellij/openapi/vfs/impl/VirtualFilePointerContainerImpl.java#L216

```
assert !myDisposed;
```

So it looks like somehow the `VirtualFile` was disposed of when it was referenced.  I'm not sure how to stop that from happening.
