### ISSUE TITLE
Error when open https://github.com/levelhq/level project

### ISSUE THREAD

**Issue by stgolem** [KronicDeth/intellij-elixir#1345]
# Description

Opened https://github.com/levelhq/level project

# Exception

## Stacktrace

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.4.2` is missing Erlang SDK
	at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:100)
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:34)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.mix.project._import.step.Root$1.run(Root.java:80)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:592)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sh41** [comment]
Closing this as a duplicate of #3328 — same MissingErlangSdk crash, same fix. See the comment there for details.
