### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by jiachen247** [KronicDeth/intellij-elixir#1361]
# Version

7.5.0

# Exception

## Message

Worker exited due to exception: org.elixir_lang.psi.impl.ElixirMapConstructionArgumentsImpl cannot be cast to org.elixir_lang.psi.ElixirList

## Stacktrace

```
java.lang.ClassCastException: org.elixir_lang.psi.impl.ElixirMapConstructionArgumentsImpl cannot be cast to org.elixir_lang.psi.ElixirList
	at org.elixir_lang.psi.ElementDescriptionProvider.getElementDescription(ElementDescriptionProvider.kt:80)
	at org.elixir_lang.psi.ElementDescriptionProvider.getElementDescription(ElementDescriptionProvider.kt:38)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:30)
	at com.intellij.usageView.UsageViewUtil.getType(UsageViewUtil.java:67)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$8.getInfo(CtrlMouseHandler.java:599)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:836)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(Cor

**Comment by KronicDeth** [comment]
You are on an old version.  Update to latest.  This was fixed awhile ago.
