### ISSUE TITLE
org.elixir_lang.psi.impl.PresentationImplKt.locationString(PresentationImpl.kt:91) does not check if element is invalid

### ISSUE THREAD

**Issue by michaelteter** [KronicDeth/intellij-elixir#1363]
# Description

Editing quickly... typing a Map.new() line (which was not complete when the crash happened; but the final line was: ```orders_by_id = Map.new(orders, fn o -> {o.id, o} end)```

# Exception

## Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL (class org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:252)
	at org.elixir_lang.psi.impl.PresentationImplKt.locationString(PresentationImpl.kt:91)
	at org.elixir_lang.structure_view.element.modular.Module.location(Module.kt:58)
	at org.elixir_lang.structure_view.element.modular.Module.getPresentation(Module.kt:54)
	at org.elixir_lang.structure_view.element.CallDefinition.getPresentation(CallDefinition.kt:104)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:42)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:89)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:442)
	at com.intellij.ui.tree.StructureTreeModel$Node.access$200(StructureTreeModel.java:410)
	at com.intellij.ui.tree.StructureTreeModel.lambda$getChildren$14(StructureTreeModel.java:314)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:314)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:559)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:453)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:419)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:152)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:90)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:318)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by michaelteter** [comment]
I experienced the same error, this time while writing the left hand side of a pattern match (extraction from map): ```%{refcode: srefcode}```, and I believe the error occurred when I closed the } brace.

**Comment by sh41** [comment]
This is fixed, and your title called it exactly right.

`locationString` now checks `isValid` before touching `containingFile` — if the element has already been invalidated by the time the structure view gets around to reading it, it returns a placeholder instead of crashing. That's the exact gap your title describes. First shipped in v12.0.0 and unchanged since, including the current release, v24.0.1.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
