### ISSUE TITLE
InvalidMirrorException for rabbit_common/ebin/priority_queue.beam

### ISSUE THREAD

**Issue by kor-and-m** [KronicDeth/intellij-elixir#1376]
# Exception

## Message

file:///home/andrey/lms/course_perm/deps/rabbit_common/ebin/priority_queue.beam

## Stacktrace

```
org.elixir_lang.beam.psi.impl.ModuleElementImpl$InvalidMirrorException: stub:[org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5e537062, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5094e0dd, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@41a321ec, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@678d25dd, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2218892e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@557d07b8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@d09e0ba, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3249f0b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@651337b8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@58eebc65, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1a209bf2, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3ddb837a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4189dd8e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6c295c4e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@72c8a532, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@13e93842, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1c03e21c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3aee06fe, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@d38d5a4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@57c9d769, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@54d9dc8e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1e4ae91d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@55149a85, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4cff7dd1, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@56d8f56c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1f13ecab, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6e229d7e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5904649e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@48669947]; mirror:[UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:43)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.java:74)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.java:633)
	at org.elixir_lang.beam.psi.BeamFileImpl$1.run(BeamFileImpl.java:606)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:185)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.java:604)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:125)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.java:153)
	at org.elixir_lang.psi.scope.atom.Variants.projectLookupElementStream(Variants.java:49)
	at org.elixir_lang.psi.scope.atom.Variants.lookupElementList(Variants.java:24)
	at org.elixir_lang.reference.Atom.getVariants(Atom.java:25)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:273)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:137)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:81)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:71)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:125)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:108)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:92)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:118)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:815)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:800)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:266)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:263)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sh41** [comment]
Fixed in v11.9.1.

`ModuleImpl.setMirror` used to pair compiled stubs with decompiled definitions by position, so any difference in count threw — here, 29 compiled definitions against the 5 that came back out of the decompiled Elixir. Commit a03c8a80c changed it to match by name and arity and skip the rest.

The parse failure behind it had its own fix: Erlang functions whose names are Elixir keywords are now emitted as `def unquote(:name)(...)`. `rabbit_common`'s `priority_queue` exports `in/2`, handled by b777fde87 in v12.0.0 — likely the case here, though not confirmable without the `.beam`.

If this still happens on a current release, please open a new issue and attach the `.beam`.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
