### ISSUE TITLE
autocomplete doesnt work for mewith intellij idea 2018.3

### ISSUE THREAD

**Issue by cocodrino** [KronicDeth/intellij-elixir#1382]
Hi, good day, seems that the autocomplete doesnt works for me, although I've configured both erlang and elixir sdk..

I type Enum. and press ctrl+space...then...for a long time appears a load icon but at the end doesnt show any completions, what can I do here?

please let me know if you need other info about my IDE or elixir configuration...

**Comment by cocodrino** [comment]
additional captures
![captura de pantalla de 2019-01-13 17-58-56](https://user-images.githubusercontent.com/616412/51091160-fec0f780-175c-11e9-9a50-94d6b7855c68.png)

![captura de pantalla de 2019-01-13 18-00-08](https://user-images.githubusercontent.com/616412/51091167-257f2e00-175d-11e9-8531-3a9046239111.png)
![captura de pantalla de 2019-01-13 18-00-26](https://user-images.githubusercontent.com/616412/51091170-2adc7880-175d-11e9-9a62-beaa8d76c981.png)

**Comment by cocodrino** [comment]
ok I've news about this...the autocompletion works for new projects but if I tried to open an existing project the autocompletion fails...

**Comment by KronicDeth** [comment]
For pre-existing projects you can invalidate the cache and have it rebuild it on restart.  This should put you in a similar state as a new project.

1. Select from the menus File > Invalidate Caches / Restart.
2. In the dialog click "Invalidate and Restart".

If this doesn't work, then I'd try change between two different SDKs or deleting and recreating the SDK in IntelliJ.

**Comment by cocodrino** [comment]
thanks for the response @KronicDeth ...I followed this steps without problem
https://github.com/KronicDeth/intellij-elixir#from-existing-sources

also I try invalidating the cache and restarting, but seems not works for me...how can I delete and recreate the sdk in intellij?...thank you

**Comment by cocodrino** [comment]
I try using kiex and other elixir version...I installed the elixir v 1.8.0-rc.1...then I set the elixir sdk path to /home/yo/.kiex/elixirs/elixir-1.8.0-rc.1

but this does't works neither ... I don't know other thing that I could do...

![qwqwq](https://user-images.githubusercontent.com/616412/51092634-edcdb180-176f-11e9-917c-5efee74a881d.png)

**Comment by KronicDeth** [comment]
Deleting the SDK is clicking the red `-` in menu when the SDK is selected.

**Comment by cocodrino** [comment]
yes...I tried removing and selecting other sdk but these doesnt work for me...the plugin generate some log or debug information that can be useful for find the issue here?...thank you

**Comment by cocodrino** [comment]
with projects created from 0 inside intellij works well but when I try to add existing projects (following the steps in the documentation) it doesn't work, is there any other way to add an existing project?...any suggestions? anything I can do?

**Comment by cocodrino** [comment]
@KronicDeth only for testing purpose, I did an elixir project inside intellij, then I copy the .idea folder to one existing elixir project...when I open this, idea tell me that the project is using an old format and needs to be converted, also say this

no longer excludes compiler output paths (` ebin` directories), so that Phoenix View .beans files can be indexed to resolve EEx Template Elixir Line Breakpoints

also I'm getting this error

```
java.lang.Throwable: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field $maxScope in class org.elixir_lang.psi.impl.QualifiableAliasImplKt$getReference$1 has non-equivalent values:
  ElixirStabBodyImpl(STAB_BODY) and
  Elixir File
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:158)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:129)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:125)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:86)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:60)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:148)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference(QualifiableAliasImpl.kt:30)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModular(QualifiableAliasImpl.kt:138)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModular(PsiElementImpl.kt:165)
	at org.elixir_lang.psi.Use.modular(Use.kt:66)
	at org.elixir_lang.psi.Use.callDefinitionClauseCallWhile(Use.kt:20)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:101)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:32)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:289)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:144)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:591)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:63)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1142)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:69)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:66)
	at org.elixir_lang.reference.resolver.Callable.resolveElement(Callable.kt:45)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:20)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:13)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:956)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:106)
	at org.elixir_lang.reference.Callable.resolve(Callable.kt:113)
	at org.elixir_lang.TargetElementEvaluator.getElementByReference(TargetElementEvaluator.kt:21)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:367)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:349)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:223)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:195)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorPsiDataProvider.getPsiElementIn(TextEditorPsiDataProvider.java:193)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorPsiDataProvider.getData(TextEditorPsiDataProvider.java:80)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.getData(FileEditorManagerEx.java:170)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.lambda$createBackgroundDataProvider$1(TextEditorComponent.java:252)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.lambda$createBackgroundDataProvider$0(PsiAwareTextEditorImpl.java:132)
	at com.intellij.openapi.actionSystem.BackgroundableDataProvider.getData(BackgroundableDataProvider.java:20)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:75)
	at com.intellij.ide.impl.DataManagerImpl.getData(DataManagerImpl.java:61)
	at com.intellij.ide.impl.DataManagerImpl.access$200(DataManagerImpl.java:46)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.calcData(DataManagerImpl.java:381)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.doGetData(DataManagerImpl.java:377)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:355)
	at com.intellij.openapi.actionSystem.DataContextWrapper.getData(DataContextWrapper.java:38)
	at com.intellij.openapi.actionSystem.AnActionEvent$1.getData(AnActionEvent.java:161)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:53)
	at com.intellij.codeInsight.documentation.actions.ShowQuickDocInfoAction.update(ShowQuickDocInfoAction.java:80)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:239)
	at com.intellij.codeInsight.actions.CodeInsightAction.beforeActionPerformedUpdate(CodeInsightAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:170)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:623)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

not sure if this info can be helpful

**Comment by sh41** [comment]
Closing this — your fourth screenshot shows the cause.

That kiex SDK (Elixir 1.8.0-rc.1) has 21 Erlang/OTP ebin directories on its Classpath and no Elixir ones at all — no `elixir/ebin`, no `mix/ebin`, no `iex/ebin`. The standard library wasn't on the SDK, so `Enum.` had nothing to complete against.

That was a real bug: the plugin let you select a kiex directory that looked like an Elixir home but had no ebin directories under it. Fixed in 16bc1ac6a, "Check that HomePath has ebin paths when validating", shipped in v10.5.0 — a home like that can no longer be chosen. The stack trace in your last comment was a separate bug, filed as #1416 and fixed by e917680ae in the same release.

Not closed by this: you also reported that completion worked in new projects but not in one added from existing sources. That is a different problem, still unfixed, tracked in #2061, #2940, #2980, #3486 and #3713.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
