### ISSUE TITLE
Debug fails

### ISSUE THREAD

**Issue by acarvajal-gap** [KronicDeth/intellij-elixir#1383]
# Rubymine 2018.3.1
build #RM-183.4588.71, built in December 6, 2018

# Elixir + Earlang + Phoenix
elixir 1.7.3
erlang 21.0
phoenix 1.4.0

# Intellij-elixir plugin version
v10.2.0

# Exception
```
com.ericsson.otp.erlang.OtpErlangExit: timeout
	at org.elixir_lang.MailBox.wait(MailBox.kt:204)
	at org.elixir_lang.MailBox.receive(MailBox.kt:176)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:126)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:113)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:100)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:44)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:38)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KronicDeth** [comment]
The debugger timed out trying to connect.  Did you get a prompt asking if `java` or `beam` would use your network?

**Comment by acarvajal-gap** [comment]
No prompt. Is there a way of setting this manually?

**Comment by martasd** [comment]
Hi @KronicDeth. I am seeing the same error when launching the Phoenix server via Debug configuration. In the Debugger Console, it goes through `Interpreting modules`; these are the last lines that get printed:
```
Interpreting modules under /Users/mdl/divvy/juno/_build/dev/lib/xml_builder/ebin...
  XmlBuilder.Format.Indented in 8823μs
  XmlBuilder.Format.None in 9791μs
  XmlBuilder in 14295μs
  ...completed
```
 I also do not get a prompt at the end.

The IDE error I get is the same as described above (with the exception of different line numbers):
```
com.ericsson.otp.erlang.OtpErlangExit: timeout
	at org.elixir_lang.MailBox.wait(MailBox.kt:205)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Version information
IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 26, 2021
Elixir Plugin: 11.10.0
MacOS 11.2.1

**Comment by KronicDeth** [comment]
@martasd then all your modules are just taking over a minute to interpret.  You can have it interpret less by [telling the IDE to NOT interpret certain patterns of modules explained in the README](https://github.com/KronicDeth/intellij-elixir#excluding-modules).  This setting is also available on a per Run Configuration setting under the Interpreted Modules tab

![Screen Shot 2021-03-11 at 9 46 30 PM](https://user-images.githubusercontent.com/298259/110889182-4f87f880-82b3-11eb-9383-247553c28726.png)
![Screen Shot 2021-03-11 at 9 46 37 PM](https://user-images.githubusercontent.com/298259/110889184-50208f00-82b3-11eb-88da-2e3b3fe760ec.png)

If you want to turn ALL interpretation except the files you place breakpoint in, you can put the pattern as `*`, since that will glob everything.  If that gets you pass the timeout, you can remove that and then make more tuned filters, as running with `*` will make it difficult to see the stack trace for the callers of your marked breakpoints.

**Comment by martasd** [comment]
Thanks for the tip. I've added `*` as suggested in the README:

<img src="https://user-images.githubusercontent.com/591911/111215676-afdcaa00-85d3-11eb-9e27-eb99f393b484.png" width="400">

Having made this change, I am able to actually reach a breakpoint, but the IDE becomes virtually unusable in Debug. Any action I take in the Debugger (stepping, clicking on a variable etc.) takes a very long time to complete. Sometimes, it eventually completes, often it does not and the request times out. 

![image](https://user-images.githubusercontent.com/591911/111206450-a732a680-85c8-11eb-9d43-4dfad9ceddb8.png)

Anything else I can do to ameliorate this situation?

**Comment by KronicDeth** [comment]
@martasd without pairing with you, so that I can see the code base I can't easily guess whether the `:int` Erlang module that interprets your projects code is the cause of the slowness or something in the plugin's code itself.  In my experience the `:int` Erlang module usually goes 3x slower than normal non-interpreted mode for the BEAM, but I do know that if stuff like Postgres or parts of Phoenix get interpreted it gets much worse.  

* When you did `*` as the filter,  do you have the list of all the module it still interpreted in the Console tab?
* If you're open to pairing, we can work out a time that works since you're 6 hours ahead of me.

**Comment by KronicDeth** [comment]
No feedback received.
