### ISSUE TITLE
java.lang.NoSuchMethodError: com.intellij.openapi.vfs.VfsUtil.findFile(Ljava/nio/file/Path;Z)Lcom/intellij/openapi/vfs/VirtualFile;

### ISSUE THREAD

**Issue by belgoros** [KronicDeth/intellij-elixir#1391]
# Version

10.2.0

# Exception

## Message

com.intellij.openapi.vfs.VfsUtil.findFile(Ljava/nio/file/Path;Z)Lcom/intellij/openapi/vfs/VirtualFile;

## Stacktrace

```
java.lang.NoSuchMethodError: com.intellij.openapi.vfs.VfsUtil.findFile(Ljava/nio/file/Path;Z)Lcom/intellij/openapi/vfs/VirtualFile;
	at org.elixir_lang.mix.Dep.virtualFile(Dep.kt:19)
	at org.elixir_lang.mix.watcher.Resolution$Companion.resolution(Resolution.kt:49)
	at org.elixir_lang.mix.watcher.TransitiveResolution.transitiveResolution(TransitiveResolution.kt:17)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:43)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:184)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:167)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:162)
	at org.elixir_lang.mix.Project$createModulesForOtpApps$3.run(Project.kt:90)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
Which IDE and what version of that IDE?

**Comment by belgoros** [comment]
@KronicDeth Thank you for your feedback. Here is the screenshot displaying all the needed build details and the version:

<img width="462" alt="Screenshot 2019-03-18 at 09 04 00" src="https://user-images.githubusercontent.com/83579/54515715-361a7300-495d-11e9-96d2-f65642438bdd.png">

**Comment by KronicDeth** [comment]
Not reported since 2019. Assuming fixed in new plugin/IDE versions.
