### ISSUE TITLE
MixProjectImportBuilder need psi-parser to get info from mix.exs

### ISSUE THREAD

**Issue by zyuyou** [KronicDeth/intellij-elixir#142]
I try to add the `MixProjectImportBuilder` which like [intellij-erlang](https://github.com/ignatov/intellij-erlang)'s `RebarProjectImportBuilder` to the plugin, but this feature need psi-parser to get some information (project-name, application-configure, deps etc ) from `mix.exs`.  I just want to know that when  can the parser have support for detecting the `defmodule` and the other terms. It's really important and helpful to add the other new features. Thank you for the elixir-plugin!!
![2015-06-29 6 49 47](https://cloud.githubusercontent.com/assets/1913492/8406531/d2fd4942-1e8f-11e5-99df-1e0211d1b95b.png)

**Comment by KronicDeth** [comment]
The PSI parser parsing Elixir correctly will be complete in [v1.0.0](https://github.com/KronicDeth/intellij-elixir/milestones/v1.0.0).  #140 is part of [v1.0.0](https://github.com/KronicDeth/intellij-elixir/milestones/v1.0.0).  Currently, #140 is blocked by a bug with `not one ^^^ not two @three four do end` associating the `do end` with `@three` instead of `two`.  Something is special about `@` being a prefix operator.  

Once the PSI parser is complete, if you want to be able to quickly identify modules would be #92 I believe.  This would allow you not have to check each *Call PSI node to determine if it's `defmodule` or a different function/macro call.

**Comment by zyuyou** [comment]
Truely I can’t realize the bug you metioned above, but anyway you will fix it.

**Comment by zyuyou** [comment]
Truely I can’t realize the bug you metioned above, but anyway you will fix it.
Looking forward to your good news！

**Comment by KronicDeth** [comment]
I tried using `createPsi`

```java
public class ImportedOtpApp {
  private static final Pattern pattern = Pattern.compile("(.*)\\.Mixfile");
  public ImportedOtpApp(@NotNull VirtualFile root, @NotNull final VirtualFile appMixFile){
    ElixirFile elixirFile = ElixirScriptFileUtil.createPsi(appMixFile);
    Call[] calls = PsiTreeUtil.getChildrenOfType(elixirFile, Call.class);
    String appName = "";

    if (calls != null) {
      for (Call call : calls) {
        if (org.elixir_lang.structure_view.element.modular.Module.is(call)) {
          String name = call.getName();

          if (name != null) {
            Matcher matcher = pattern.matcher(name);

            if (matcher.matches()) {
              appName = matcher.group(1).toLowerCase();
            }
          }
        }
      }
    }

    myName = appName;
    myRoot = root;

    ApplicationManager.getApplication().runReadAction(new Runnable() {
      @Override
      public void run() {
        addInfoFromAppMixFile(appMixFile);
      }
    });
  }
}
```

 but it's not legal from the thread:



```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 18,4,Idea Thread Group] 1468635568
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.1#IC-145.258.11 IDEA, eap:false, os:Mac OS X 10.11.4, java-version:Oracle Corporation 1.8.0_74-b02,6,main] 716740534
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1054)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:182)
	at com.intellij.psi.impl.source.PsiFileImpl.getTreeElement(PsiFileImpl.java:124)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:796)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:1004)
	at com.intellij.psi.impl.PsiFileFactoryImpl.trySetupPsiForFile(PsiFileFactoryImpl.java:124)
	at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java:100)
	at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java:56)
	at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java:168)
	at org.elixir_lang.mix.util.ElixirScriptFileUtil.createPsi(ElixirScriptFileUtil.java:45)
	at org.elixir_lang.mix.importWizard.ImportedOtpApp.<init>(ImportedOtpApp.java:30)
	at org.elixir_lang.mix.importWizard.MixProjectImportBuilder.createImportedOtpApp(MixProjectImportBuilder.java:353)
	at org.elixir_lang.mix.importWizard.MixProjectImportBuilder.access$300(MixProjectImportBuilder.java:48)
	at org.elixir_lang.mix.importWizard.MixProjectImportBuilder$3$1.visitFile(MixProjectImportBuilder.java:247)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:132)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:261)
	at org.elixir_lang.mix.importWizard.MixProjectImportBuilder$3.run(MixProjectImportBuilder.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

You know anything about working about allowed actions in threads in the API @zyuyou?

**Comment by KronicDeth** [comment]
I pushed up [the change with the error](https://github.com/KronicDeth/intellij-elixir/commit/2f78a8729bd8e2eb6cf271c8df34ee229ac8cf70) on branch 142

**Comment by zyuyou** [comment]
@KronicDeth As I didn't do much work in the `Psi`, I have no idea about this. Sorry!
