### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by kanmaniselvan** [KronicDeth/intellij-elixir#1452]
# Exception

## Stacktrace

```
java.lang.Throwable: readNameSet nameSet of suspect (>= 10) size (11):
1. LiqidCrm.ErrorReporter.ExceptionAdapter.Float
2. LiqidCrm.ErrorReporter.ExceptionAdapter.BitString
3. LiqidCrm.ErrorReporter.ExceptionAdapter.Port
4. LiqidCrm.ErrorReporter.ExceptionAdapter.Reference
5. LiqidCrm.ErrorReporter.ExceptionAdapter.Map
6. LiqidCrm.ErrorReporter.ExceptionAdapter.Atom
7. LiqidCrm.ErrorReporter.ExceptionAdapter.List
8. LiqidCrm.ErrorReporter.ExceptionAdapter.Integer
9. LiqidCrm.ErrorReporter.ExceptionAdapter.Function
10. LiqidCrm.ErrorReporter.ExceptionAdapter.Tuple
11. LiqidCrm.ErrorReporter.ExceptionAdapter.PID

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at org.elixir_lang.psi.stub.call.Deserialized.readNameSet(Deserialized.java:215)
	at org.elixir_lang.psi.stub.call.Deserialized.readGuarded(Deserialized.java:152)
	at org.elixir_lang.psi.stub.call.Deserialized.deserializeCanonicalNameSet(Deserialized.java:114)
	at org.elixir_lang.psi.stub.call.Deserialized.deserialize(Deserialized.java:98)
	at org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall.deserialize(UnmatchedUnqualifiedNoParenthesesCall.java:55)
	at org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall.deserialize(UnmatchedUnqualifiedNoParenthesesCall.java:16)
	at com.intellij.psi.stubs.LazyStubData.deserializeStub(LazyStubList.java:126)
	at com.intellij.psi.stubs.LazyStubList.instantiateStub(LazyStubList.java:86)
	at com.intellij.psi.stubs.LazyStubList.get(LazyStubList.java:56)
	at com.intellij.psi.stubs.LazyStubList.get(LazyStubList.java:16)
	at com.intellij.psi.stubs.StubSpine.getStubPsi(StubSpine.java:45)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.intellij.psi.impl.source.FileTrees.getAllSpinePsi(FileTrees.java:211)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:179)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:214)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:714)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:142)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:100)
	at org.elixir_lang.psi.impl.call.CallImpl.functionNameElement(CallImpl.kt:350)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionNameElement(ElixirPsiImplUtil.java:798)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.functionNameElement(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:85)
	at org.elixir_lang.psi.impl.call.CallImpl.functionName(CallImpl.kt:316)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionName(ElixirPsiImplUtil.java:760)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.functionName(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:80)
	at org.elixir_lang.psi.impl.call.CallImpl.isCalling(CallImpl.kt:395)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCalling(ElixirPsiImplUtil.java:223)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.isCalling(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:117)
	at org.elixir_lang.psi.impl.call.CallImpl.isCalling(CallImpl.kt:418)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCalling(ElixirPsiImplUtil.java:230)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.isCalling(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:121)
	at org.elixir_lang.psi.impl.call.CallImpl.isCallingMacro(CallImpl.kt:459)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCallingMacro(ElixirPsiImplUtil.java:244)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.isCallingMacro(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:129)
	at org.elixir_lang.psi.CallDefinitionClause.isCallingKernelMacroOrHead(CallDefinitionClause.kt:83)
	at org.elixir_lang.psi.CallDefinitionClause.isPrivateFunction(CallDefinitionClause.kt:44)
	at org.elixir_lang.psi.CallDefinitionClause.isFunction(CallDefinitionClause.kt:41)
	at org.elixir_lang.psi.CallDefinitionClause.is(CallDefinitionClause.kt:38)
	at org.elixir_lang.TargetElementEvaluator.getElementByReference(TargetElementEvaluator.kt:26)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:367)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:349)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:223)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:195)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by KronicDeth** [comment]
Already fixed by #1444, which increased the limit to 15.  It will be in the next release or you can install one of the pre-release builds after https://github.com/KronicDeth/intellij-elixir/releases/tag/v10.5.0-pre%2B20190413211141, which include the fix.
