### ISSUE TITLE
This method in class com.intellij.util.containers.WeakHashMap is deprecated and going to be removed soon. Use ContainerUtil.createWeakMap() instead

### ISSUE THREAD

**Issue by G-Rath** [KronicDeth/intellij-elixir#1455]
When looking through my IDEs log file for a bug I was reporting on YouTrack, I noticed this plugin is causing a `DeprecatedMethodException` warning every time the IDE starts.

It's not causing any problems in the actual IDE, and I know it's a warning in a log file, but personally it'd be cool if it could be addressed, as the fix is apparently to "just" call a different method, and it's a ~100 line exception that noises up the log file.

```
2019-04-20 17:10:53,327 [  13730]   WARN - util.DeprecatedMethodException - This method in class com.intellij.util.containers.WeakHashMap is deprecated and going to be removed soon. Use ContainerUtil.createWeakMap() instead 
com.intellij.util.DeprecatedMethodException: This method in class com.intellij.util.containers.WeakHashMap is deprecated and going to be removed soon. Use ContainerUtil.createWeakMap() instead
	at com.intellij.util.DeprecatedMethodException.report(DeprecatedMethodException.java:15)
	at com.intellij.util.containers.WeakHashMap.<init>(WeakHashMap.java:46)
	at org.elixir_lang.sdk.erlang.Type.<init>(Type.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:92)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$ConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:112)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:44)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:46)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:343)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:264)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:34)
	at com.intellij.openapi.projectRoots.SdkType.getAllTypes(SdkType.java:202)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.findSdkTypeByName(ProjectJdkTableImpl.java:235)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.getSdkTypeByName(ProjectJdkTableImpl.java:230)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.readExternal(ProjectJdkImpl.java:157)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.loadState(ProjectJdkTableImpl.java:256)
	at com.intellij.openapi.projectRoots.impl.JavaAwareProjectJdkTableImpl.loadState(JavaAwareProjectJdkTableImpl.java:57)
	at com.intellij.openapi.projectRoots.impl.JavaAwareProjectJdkTableImpl.loadState(JavaAwareProjectJdkTableImpl.java:17)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:375)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:331)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:118)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:94)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:50)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:227)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:209)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:211)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getConstructorArguments(CachingConstructorInjectionComponentAdapter.java:118)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:89)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:458)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:407)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:347)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
Using the deprecated method was necessary for compatibility with older versions of the IDEs that did not have the replacement method.  I can try upgrade it again and see if it breaks compatibility now that 2019.1 is out, which changes my supported versions range.

**Comment by sh41** [comment]
Fixed in [v11.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v11.0.0) (2019-08-15) by [`1a9e4d8`](https://github.com/KronicDeth/intellij-elixir/commit/1a9e4d8eeae1289a3d6995a90b8c83d7977d2cd0) — the `new WeakHashMap<>()` field in the Erlang SDK `Type` became `ContainerUtil.createWeakMap()`, which is exactly what the title asks for. It shipped in [#1545](https://github.com/KronicDeth/intellij-elixir/pull/1545), whose release notes name the change; the PR said `Fixes #1527` and never named this issue, so auto-close missed it and it stayed open.

The field has since been removed entirely, and the reported code path cannot exist on any supported IDE: the plugin's minimum build is 253.28294.1 (2025.3), `com.intellij.util.DeprecatedMethodException` no longer exists in the platform, and `com.intellij.util.containers.WeakHashMap` is now package-private and undeprecated, so a plugin cannot reference it at all.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
