### ISSUE TITLE
org.elixir_lang.refactoring.variable.rename.Inplace.<init>(Inplace.java:32) does not check if element is invalid

### ISSUE THREAD

**Issue by seeekr** [KronicDeth/intellij-elixir#1461]
# Description

Tried to rename a variable in a match expression. 

# Exception

## Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL (class org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoArgumentsCall)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getProject(StubBasedPsiElementBase.java:291)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:61)
	at org.elixir_lang.refactoring.variable.rename.Inplace.<init>(Inplace.java:32)
	at org.elixir_lang.refactoring.variable.rename.Handler.createRenamer(Handler.kt:69)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:73)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:83)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:52)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:131)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:276)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$null$4(ActionManagerImpl.java:1342)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$tryToExecuteNow$5(ActionManagerImpl.java:1302)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:188)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3080)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:159)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:111)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:185)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:63)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecuteNow(ActionManagerImpl.java:1301)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$tryToExecute$2(ActionManagerImpl.java:1285)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecute(ActionManagerImpl.java:1288)
	at com.intellij.ui.mac.touchbar.TBItemAnActionButton._performAction(TBItemAnActionButton.java:191)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
@seeekr can you post the exact code or a minimal repo case?

**Comment by seeekr** [comment]
I'll watch for the next time this comes up and then will do my best to provide minimal repro code.

**Comment by sh41** [comment]
The exception came from the plugin's own in-place variable rename handler. `Inplace` forwarded the element it was handed straight to the platform's `VariableInplaceRenamer` without checking it was still valid, and the platform does not check either — its constructor reads the containing file off the element on trust. So a caret whose earlier resolve result had since been invalidated threw on first access, which is exactly what this issue's title says.

Both `Handler` and `Inplace`, and their `renameHandler` extension-point registrations, were deleted in 2dff82691dce595b694e701cd60df49e5450d07d, first released in [24.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/24.0.0). Elixir rename now runs through the Symbol API: the target holds a `Pointer` that re-derives the occurrence range on each dereference and yields nothing when that range no longer fits, rather than carrying a `PsiElement` captured before the document changed.

The reproduction asked for in 2019 is no longer needed — the code that threw has been removed.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
