### ISSUE TITLE
Debugger Crashes During Breakpoint in Phoenix Application

### ISSUE THREAD

**Issue by mc962** [KronicDeth/intellij-elixir#1466]
**Describe the bug**
When using the Intellij debugger with Phoenix's phx.server, during a breakpoint pause, I attempt to execute an action on a value. In this case, I have a variable 'a' defined before the breakpoint, and I attempt to create a new 'watch' of `a + 2`. This crashes the debugger and the server, and creates a log file.

**To Reproduce**
1. Create a new application (in this case no webpack, no html, no ecto).
2.Create a simple controller with a simple action, and some defined variable.
3. Put in a breakpoint after the defined value, but before the render action.
4. Attempt to set a new watch involving this breakpoint (such as `a + 2`).
5. Observer the debugger/server crashing and an error report being generated.

**Expected behavior**
I would expect a new watch to be made from a + 2, which should evaluate/return the result (7 in this case, where a was equal to 5).

**Logs**
```
java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{elixir,quoted_to_erl,[{'+',[{line,1}],[{a,[{line,1}],nil},2]},#{'__struct__' => 'Elixir.Macro.Env',aliases => [],context => nil,context_modules => [],contextual_vars => [],current_vars => #{{a,nil} => {0,term}},file => #Bin<105>,function => {full_status,0},functions => [{'Elixir.Kernel',[{'!=',2},{'!==',2},{'*',2},{'+',1},{'+',2},{'++',2},{'-',1},{'-',2},{'--',2},{'/',2},{'<',2},{'<=',2},{'==',2},{'===',2},{'=~',2},{'>',2},{'>=',2},{abs,1},{apply,2},{apply,3},{binary_part,3},{bit_size,1},{byte_size,1},{ceil,1},{div,2},{elem,2},{exit,1},{floor,1},{'function_exported?',3},{get_and_update_in,3},{get_in,2},{hd,1},{inspect,1},{inspect,2},{is_atom,1},{is_binary,1},{is_bitstring,1},{is_boolean,1},{is_float,1},{is_function,1},{is_function,2},{is_integer,1},{is_list,1},{is_map,1},{is_number,1},{is_pid,1},{is_port,1},{is_reference,1},{is_tuple,1},{length,1},{'macro_exported?',3},{make_ref,0},{map_size,1},{max,2},{min,2},{node,0},{node,1},{not,1},{pop_in,2},{put_elem,3},{put_in,3},{rem,2},{round,1},{self,0},{send,2},{spawn,1},{spawn,3},{spawn_link,1},{spawn_link,3},{spawn_monitor,1},{spawn_monitor,3},{struct,1},{struct,2},{'struct!',1},{'struct!',2},{throw,1},{tl,1},{trunc,1},{tuple_size,1},{update_in,3}]}],lexical_tracker => nil,line => 10,macro_aliases => [],macros => [{'Elixir.Kernel',[{'!',1},{'&&',2},{'..',2},{'<>',2},{'@',1},{'alias!',1},{and,2},{binding,0},{binding,1},{def,1},{def,2},{defdelegate,2},{defexception,1},{defguard,1},{defguardp,1},{defimpl,2},{defimpl,3},{defmacro,1},{defmacro,2},{defmacrop,1},{defmacrop,2},{defmodule,2},{defoverridable,1},{defp,1},{defp,2},{defprotocol,2},{defstruct,1},{destructure,2},{get_and_update_in,2},{if,2},{in,2},{is_nil,1},{'match?',2},{or,2},{pop_in,1},{put_in,2},{raise,1},{raise,2},{reraise,2},{reraise,3},{sigil_C,2},{sigil_D,2},{sigil_N,2},{sigil_R,2},{sigil_S,2},{sigil_T,2},{sigil_W,2},{sigil_c,2},{sigil_r,2},{sigil_s,2},{sigil_w,2},{to_char_list,1},{to_charlist,1},{to_string,1},{unless,2},{update_in,2},{use,1},{use,2},{'var!',1},{'var!',2},{'|>',2},{'||',2}]}],module => 'Elixir.GeocodexWeb.StatusController',prematch_vars => warn,requires => ['Elixir.Kernel','Elixir.Kernel.Typespec'],unused_vars => #{},vars => [{a,nil}]},{elixir_erl,nil,nil,false,#{{a,nil} => {0,'_a@1'}},nil,[],#{a => 1},false}],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,259}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:656)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{elixir,quoted_to_erl,[{'+',[{line,1}],[{a,[{line,1}],nil},2]},#{'__struct__' => 'Elixir.Macro.Env',aliases => [],context => nil,context_modules => [],contextual_vars => [],current_vars => #{{a,nil} => {0,term}},file => #Bin<105>,function => {full_status,0},functions => [{'Elixir.Kernel',[{'!=',2},{'!==',2},{'*',2},{'+',1},{'+',2},{'++',2},{'-',1},{'-',2},{'--',2},{'/',2},{'<',2},{'<=',2},{'==',2},{'===',2},{'=~',2},{'>',2},{'>=',2},{abs,1},{apply,2},{apply,3},{binary_part,3},{bit_size,1},{byte_size,1},{ceil,1},{div,2},{elem,2},{exit,1},{floor,1},{'function_exported?',3},{get_and_update_in,3},{get_in,2},{hd,1},{inspect,1},{inspect,2},{is_atom,1},{is_binary,1},{is_bitstring,1},{is_boolean,1},{is_float,1},{is_function,1},{is_function,2},{is_integer,1},{is_list,1},{is_map,1},{is_number,1},{is_pid,1},{is_port,1},{is_reference,1},{is_tuple,1},{length,1},{'macro_exported?',3},{make_ref,0},{map_size,1},{max,2},{min,2},{node,0},{node,1},{not,1},{pop_in,2},{put_elem,3},{put_in,3},{rem,2},{round,1},{self,0},{send,2},{spawn,1},{spawn,3},{spawn_link,1},{spawn_link,3},{spawn_monitor,1},{spawn_monitor,3},{struct,1},{struct,2},{'struct!',1},{'struct!',2},{throw,1},{tl,1},{trunc,1},{tuple_size,1},{update_in,3}]}],lexical_tracker => nil,line => 10,macro_aliases => [],macros => [{'Elixir.Kernel',[{'!',1},{'&&',2},{'..',2},{'<>',2},{'@',1},{'alias!',1},{and,2},{binding,0},{binding,1},{def,1},{def,2},{defdelegate,2},{defexception,1},{defguard,1},{defguardp,1},{defimpl,2},{defimpl,3},{defmacro,1},{defmacro,2},{defmacrop,1},{defmacrop,2},{defmodule,2},{defoverridable,1},{defp,1},{defp,2},{defprotocol,2},{defstruct,1},{destructure,2},{get_and_update_in,2},{if,2},{in,2},{is_nil,1},{'match?',2},{or,2},{pop_in,1},{put_in,2},{raise,1},{raise,2},{reraise,2},{reraise,3},{sigil_C,2},{sigil_D,2},{sigil_N,2},{sigil_R,2},{sigil_S,2},{sigil_T,2},{sigil_W,2},{sigil_c,2},{sigil_r,2},{sigil_s,2},{sigil_w,2},{to_char_list,1},{to_charlist,1},{to_string,1},{unless,2},{update_in,2},{use,1},{use,2},{'var!',1},{'var!',2},{'|>',2},{'||',2}]}],module => 'Elixir.GeocodexWeb.StatusController',prematch_vars => warn,requires => ['Elixir.Kernel','Elixir.Kernel.Typespec'],unused_vars => #{},vars => [{a,nil}]},{elixir_erl,nil,nil,false,#{{a,nil} => {0,'_a@1'}},nil,[],#{a => 1},false}],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,259}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	... 12 more
Caused by: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{elixir,quoted_to_erl,[{'+',[{line,1}],[{a,[{line,1}],nil},2]},#{'__struct__' => 'Elixir.Macro.Env',aliases => [],context => nil,context_modules => [],contextual_vars => [],current_vars => #{{a,nil} => {0,term}},file => #Bin<105>,function => {full_status,0},functions => [{'Elixir.Kernel',[{'!=',2},{'!==',2},{'*',2},{'+',1},{'+',2},{'++',2},{'-',1},{'-',2},{'--',2},{'/',2},{'<',2},{'<=',2},{'==',2},{'===',2},{'=~',2},{'>',2},{'>=',2},{abs,1},{apply,2},{apply,3},{binary_part,3},{bit_size,1},{byte_size,1},{ceil,1},{div,2},{elem,2},{exit,1},{floor,1},{'function_exported?',3},{get_and_update_in,3},{get_in,2},{hd,1},{inspect,1},{inspect,2},{is_atom,1},{is_binary,1},{is_bitstring,1},{is_boolean,1},{is_float,1},{is_function,1},{is_function,2},{is_integer,1},{is_list,1},{is_map,1},{is_number,1},{is_pid,1},{is_port,1},{is_reference,1},{is_tuple,1},{length,1},{'macro_exported?',3},{make_ref,0},{map_size,1},{max,2},{min,2},{node,0},{node,1},{not,1},{pop_in,2},{put_elem,3},{put_in,3},{rem,2},{round,1},{self,0},{send,2},{spawn,1},{spawn,3},{spawn_link,1},{spawn_link,3},{spawn_monitor,1},{spawn_monitor,3},{struct,1},{struct,2},{'struct!',1},{'struct!',2},{throw,1},{tl,1},{trunc,1},{tuple_size,1},{update_in,3}]}],lexical_tracker => nil,line => 10,macro_aliases => [],macros => [{'Elixir.Kernel',[{'!',1},{'&&',2},{'..',2},{'<>',2},{'@',1},{'alias!',1},{and,2},{binding,0},{binding,1},{def,1},{def,2},{defdelegate,2},{defexception,1},{defguard,1},{defguardp,1},{defimpl,2},{defimpl,3},{defmacro,1},{defmacro,2},{defmacrop,1},{defmacrop,2},{defmodule,2},{defoverridable,1},{defp,1},{defp,2},{defprotocol,2},{defstruct,1},{destructure,2},{get_and_update_in,2},{if,2},{in,2},{is_nil,1},{'match?',2},{or,2},{pop_in,1},{put_in,2},{raise,1},{raise,2},{reraise,2},{reraise,3},{sigil_C,2},{sigil_D,2},{sigil_N,2},{sigil_R,2},{sigil_S,2},{sigil_T,2},{sigil_W,2},{sigil_c,2},{sigil_r,2},{sigil_s,2},{sigil_w,2},{to_char_list,1},{to_charlist,1},{to_string,1},{unless,2},{update_in,2},{use,1},{use,2},{'var!',1},{'var!',2},{'|>',2},{'||',2}]}],module => 'Elixir.GeocodexWeb.StatusController',prematch_vars => warn,requires => ['Elixir.Kernel','Elixir.Kernel.Typespec'],unused_vars => #{},vars => [{a,nil}]},{elixir_erl,nil,nil,false,#{{a,nil} => {0,'_a@1'}},nil,[],#{a => 1},false}],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,259}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.elixir_lang.MailBox.wait(MailBox.kt:203)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.evaluate(Node.kt:206)
	at org.elixir_lang.debugger.Process.evaluate(Process.kt:415)
	at org.elixir_lang.debugger.Evaluator.evaluate(Evaluator.kt:19)
	at com.intellij.xdebugger.evaluation.XDebuggerEvaluator.evaluate(XDebuggerEvaluator.java:37)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchNodeImpl$XWatchValue.computePresentation(WatchNodeImpl.java:81)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:57)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchNodeImpl.<init>(WatchNodeImpl.java:31)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.addWatchExpression(WatchesRootNode.java:115)
	at com.intellij.xdebugger.impl.frame.XWatchesViewImpl.addWatchExpression(XWatchesViewImpl.java:226)
	at com.intellij.xdebugger.impl.frame.XWatchesViewImpl.addWatchExpression(XWatchesViewImpl.java:210)
	at com.intellij.xdebugger.impl.frame.WatchInplaceEditor.doOKAction(WatchInplaceEditor.java:66)
	at com.intellij.xdebugger.impl.ui.tree.TreeInplaceEditor$3.actionPerformed(TreeInplaceEditor.java:189)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2883)
	at com.intellij.ui.EditorTextField.processKeyBinding(EditorTextField.java:717)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2944)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2846)
	at java.awt.Component.processEvent(Component.java:6327)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4770)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	... 17 more
Caused by: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{elixir,quoted_to_erl,[{'+',[{line,1}],[{a,[{line,1}],nil},2]},#{'__struct__' => 'Elixir.Macro.Env',aliases => [],context => nil,context_modules => [],contextual_vars => [],current_vars => #{{a,nil} => {0,term}},file => #Bin<105>,function => {full_status,0},functions => [{'Elixir.Kernel',[{'!=',2},{'!==',2},{'*',2},{'+',1},{'+',2},{'++',2},{'-',1},{'-',2},{'--',2},{'/',2},{'<',2},{'<=',2},{'==',2},{'===',2},{'=~',2},{'>',2},{'>=',2},{abs,1},{apply,2},{apply,3},{binary_part,3},{bit_size,1},{byte_size,1},{ceil,1},{div,2},{elem,2},{exit,1},{floor,1},{'function_exported?',3},{get_and_update_in,3},{get_in,2},{hd,1},{inspect,1},{inspect,2},{is_atom,1},{is_binary,1},{is_bitstring,1},{is_boolean,1},{is_float,1},{is_function,1},{is_function,2},{is_integer,1},{is_list,1},{is_map,1},{is_number,1},{is_pid,1},{is_port,1},{is_reference,1},{is_tuple,1},{length,1},{'macro_exported?',3},{make_ref,0},{map_size,1},{max,2},{min,2},{node,0},{node,1},{not,1},{pop_in,2},{put_elem,3},{put_in,3},{rem,2},{round,1},{self,0},{send,2},{spawn,1},{spawn,3},{spawn_link,1},{spawn_link,3},{spawn_monitor,1},{spawn_monitor,3},{struct,1},{struct,2},{'struct!',1},{'struct!',2},{throw,1},{tl,1},{trunc,1},{tuple_size,1},{update_in,3}]}],lexical_tracker => nil,line => 10,macro_aliases => [],macros => [{'Elixir.Kernel',[{'!',1},{'&&',2},{'..',2},{'<>',2},{'@',1},{'alias!',1},{and,2},{binding,0},{binding,1},{def,1},{def,2},{defdelegate,2},{defexception,1},{defguard,1},{defguardp,1},{defimpl,2},{defimpl,3},{defmacro,1},{defmacro,2},{defmacrop,1},{defmacrop,2},{defmodule,2},{defoverridable,1},{defp,1},{defp,2},{defprotocol,2},{defstruct,1},{destructure,2},{get_and_update_in,2},{if,2},{in,2},{is_nil,1},{'match?',2},{or,2},{pop_in,1},{put_in,2},{raise,1},{raise,2},{reraise,2},{reraise,3},{sigil_C,2},{sigil_D,2},{sigil_N,2},{sigil_R,2},{sigil_S,2},{sigil_T,2},{sigil_W,2},{sigil_c,2},{sigil_r,2},{sigil_s,2},{sigil_w,2},{to_char_list,1},{to_charlist,1},{to_string,1},{unless,2},{update_in,2},{use,1},{use,2},{'var!',1},{'var!',2},{'|>',2},{'||',2}]}],module => 'Elixir.GeocodexWeb.StatusController',prematch_vars => warn,requires => ['Elixir.Kernel','Elixir.Kernel.Typespec'],unused_vars => #{},vars => [{a,nil}]},{elixir_erl,nil,nil,false,#{{a,nil} => {0,'_a@1'}},nil,[],#{a => 1},false}],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,259}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at com.ericsson.otp.erlang.OtpMbox.receiveMsg(OtpMbox.java:272)
	at com.ericsson.otp.erlang.OtpMbox.receive(OtpMbox.java:168)
	at org.elixir_lang.MailBox.loop(MailBox.kt:219)
	at org.elixir_lang.MailBox.access$loop(MailBox.kt:22)
	at org.elixir_lang.MailBox$1.run(MailBox.kt:26)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Desktop:**
 - OS: Linux Mint
 - Version 18.1 (Serena)

**Erlang:**
- Installer: asdf
- Version: 21.3

**Elixir:**
- Installer: asdf
- Version: 1.8.1

**Plugin:**
- Version: 10.5.0

**Additional context**
From my quick skim of the log file, it seems like it could be a security issue of some sort, maybe with a file the IDE does not have access to that it should. However, I'm not really sure which one that is or if that is the true problem.

**Comment by mc962** [comment]
I noticed, there was also an Elixir crash log as well that might be helpful, where it appears to be trying to call an undefined/private function `quoted_to_erl/3`:
```
[error] GenServer IntelliJElixir.Debugger.Server terminating
** (UndefinedFunctionError) function :elixir.quoted_to_erl/3 is undefined or private
    (elixir) :elixir.quoted_to_erl({:+, [line: 1], [{:a, [line: 1], nil}, 2]}, %Macro.Env{aliases: [], context: nil, context_modules: [], contextual_vars: [], current_vars: %{{:a, nil} => {0, :term}}, file: "/home/my_user/elixir_projects/phoenix_projects/my_app/lib/my_app_web/controllers/status_controller.ex", function: {:full_status, 0}, functions: [{Kernel, [!=: 2, !==: 2, *: 2, +: 1, +: 2, ++: 2, -: 1, -: 2, --: 2, /: 2, <: 2, <=: 2, ==: 2, ===: 2, =~: 2, >: 2, >=: 2, abs: 1, apply: 2, apply: 3, binary_part: 3, bit_size: 1, byte_size: 1, ceil: 1, div: 2, elem: 2, exit: 1, floor: 1, function_exported?: 3, get_and_update_in: 3, get_in: 2, hd: 1, inspect: 1, inspect: 2, is_atom: 1, is_binary: 1, is_bitstring: 1, is_boolean: 1, is_float: 1, ...]}], lexical_tracker: nil, line: 10, macro_aliases: [], macros: [{Kernel, [!: 1, &&: 2, ..: 2, <>: 2, @: 1, alias!: 1, and: 2, binding: 0, binding: 1, def: 1, def: 2, defdelegate: 2, defexception: 1, defguard: 1, defguardp: 1, defimpl: 2, defimpl: 3, defmacro: 1, defmacro: 2, defmacrop: 1, defmacrop: 2, defmodule: 2, defoverridable: 1, defp: 1, defp: 2, defprotocol: 2, defstruct: 1, destructure: 2, get_and_update_in: 2, if: 2, in: 2, is_nil: 1, match?: 2, or: 2, pop_in: 1, ...]}], module: MyAppWeb.StatusController, prematch_vars: :warn, requires: [Kernel, Kernel.Typespec], unused_vars: %{}, vars: [a: nil]}, {:elixir_erl, nil, nil, false, %{{:a, nil} => {0, :_a@1}}, nil, [], %{a: 1}, false})
    /tmp/intellij_elixir8/debugger/lib/intellij_elixir/debugger/server.ex:259: IntelliJElixir.Debugger.Server.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<7489.4.0>): {:evaluate, %{env: %{file: "/home/my_user/elixir_projects/phoenix_projects/my_app/lib/my_app_web/controllers/status_controller.ex", function: {:full_status, 0}, line: 10, module: MyAppWeb.StatusController}, expression: "a + 2", pid: #PID<0.7090.0>, stack_pointer: 10}}
State: %IntelliJElixir.Debugger.Server{attached: #PID<7489.4.0>, evaluate_meta_pid_to_froms: %{}}
Client #PID<7489.4.0> is remote on node :"debuggereb3c1590-758c-4957-9bad-c5279856ffd6@127.0.0.1"
```

**Comment by KronicDeth** [comment]
Duplicate of #1421
