### ISSUE TITLE
[auto-generated] Code evaluation during debugger breakpoint

### ISSUE THREAD

**Issue by kekko1212** [KronicDeth/intellij-elixir#1474]
# Description

Start debugger with a breakpoint, try to evaluate any elixir code -> get this error

# Exception

## Stacktrace

```
java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{elixir,quoted_to_erl,[{{'.',[{line,1}],[{comparable_input,[{line,1}],nil},address]},[{line,1}],[]},#{'__struct__' => 'Elixir.Macro.Env',aliases => [],context => nil,context_modules => [],contextual_vars => [],current_vars => #{{comparable_input,nil} => {0,term}},file => #Bin<105>,function => {add_autogenerated_fields,1},functions => [{'Elixir.Kernel',[{'!=',2},{'!==',2},{'*',2},{'+',1},{'+',2},{'++',2},{'-',1},{'-',2},{'--',2},{'/',2},{'<',2},{'<=',2},{'==',2},{'===',2},{'=~',2},{'>',2},{'>=',2},{abs,1},{apply,2},{apply,3},{binary_part,3},{bit_size,1},{byte_size,1},{ceil,1},{div,2},{elem,2},{exit,1},{floor,1},{'function_exported?',3},{get_and_update_in,3},{get_in,2},{hd,1},{inspect,1},{inspect,2},{is_atom,1},{is_binary,1},{is_bitstring,1},{is_boolean,1},{is_float,1},{is_function,1},{is_function,2},{is_integer,1},{is_list,1},{is_map,1},{is_number,1},{is_pid,1},{is_port,1},{is_reference,1},{is_tuple,1},{length,1},{'macro_exported?',3},{make_ref,0},{map_size,1},{max,2},{min,2},{node,0},{node,1},{not,1},{pop_in,2},{put_elem,3},{put_in,3},{rem,2},{round,1},{self,0},{send,2},{spawn,1},{spawn,3},{spawn_link,1},{spawn_link,3},{spawn_monitor,1},{spawn_monitor,3},{struct,1},{struct,2},{'struct!',1},{'struct!',2},{throw,1},{tl,1},{trunc,1},{tuple_size,1},{update_in,3}]}],lexical_tracker => nil,line => 118,macro_aliases => [],macros => [{'Elixir.Kernel',[{'!',1},{'&&',2},{'..',2},{'<>',2},{'@',1},{'alias!',1},{and,2},{binding,0},{binding,1},{def,1},{def,2},{defdelegate,2},{defexception,1},{defguard,1},{defguardp,1},{defimpl,2},{defimpl,3},{defmacro,1},{defmacro,2},{defmacrop,1},{defmacrop,2},{defmodule,2},{defoverridable,1},{defp,1},{defp,2},{defprotocol,2},{defstruct,1},{destructure,2},{get_and_update_in,2},{if,2},{in,2},{is_nil,1},{'match?',2},{or,2},{pop_in,1},{put_in,2},{raise,1},{raise,2},{reraise,2},{reraise,3},{sigil_C,2},{sigil_D,2},{sigil_N,2},{sigil_R,2},{sigil_S,2},{sigil_T,2},{sigil_W,2},{sigil_c,2},{sigil_r,2},{sigil_s,2},{sigil_w,2},{to_char_list,1},{to_charlist,1},{to_string,1},{unless,2},{update_in,2},{use,1},{use,2},{'var!',1},{'var!',2},{'|>',2},{'||',2}]}],module => 'Elixir.Comparables.Domain.Models.Comparable',prematch_vars => warn,requires => ['Elixir.Kernel','Elixir.Kernel.Typespec'],unused_vars => #{},vars => [{comparable_input,nil}]},{elixir_erl,nil,nil,false,#{{comparable_input,nil} => {0,'_comparable_input@1'}},nil,[],#{comparable_input => 1},false}],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/private/var/folders/z4/pf84ntgx56s9f0txf0l5k7mw0000gp/T/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,259}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{elixir,quoted_to_erl,[{{'.',[{line,1}],[{comparable_input,[{line,1}],nil},address]},[{line,1}],[]},#{'__struct__' => 'Elixir.Macro.Env',aliases => [],context => nil,context_modules => [],contextual_vars => [],current_vars => #{{comparable_input,nil} => {0,term}},file => #Bin<105>,function => {add_autogenerated_fields,1},functions => [{'Elixir.Kernel',[{'!=',2},{'!==',2},{'*',2},{'+',1},{'+',2},{'++',2},{'-',1},{'-',2},{'--',2},{'/',2},{'<',2},{'<=',2},{'==',2},{'===',2},{'=~',2},{'>',2},{'>=',2},{abs,1},{apply,2},{apply,3},{binary_part,3},{bit_size,1},{byte_size,1},{ceil,1},{div,2},{elem,2},{exit,1},{floor,1},{'function_exported?',3},{get_and_update_in,3},{get_in,2},{hd,1},{inspect,1},{inspect,2},{is_atom,1},{is_binary,1},{is_bitstring,1},{is_boolean,1},{is_float,1},{is_function,1},{is_function,2},{is_integer,1},{is_list,1},{is_map,1},{is_number,1},{is_pid,1},{is_port,1},{is_reference,1},{is_tuple,1},{length,1},{'macro_exported?',3},{make_ref,0},{map_size,1},{max,2},{min,2},{node,0},{node,1},{not,1},{pop_in,2},{put_elem,3},{put_in,3},{rem,2},{round,1},{self,0},{send,2},{spawn,1},{spawn,3},{spawn_link,1},{spawn_link,3},{spawn_monitor,1},{spawn_monitor,3},{struct,1},{struct,2},{'struct!',1},{'struct!',2},{throw,1},{tl,1},{trunc,1},{tuple_size,1},{update_in,3}]}],lexical_tracker => nil,line => 118,macro_aliases => [],macros => [{'Elixir.Kernel',[{'!',1},{'&&',2},{'..',2},{'<>',2},{'@',1},{'alias!',1},{and,2},{binding,0},{binding,1},{def,1},{def,2},{defdelegate,2},{defexception,1},{defguard,1},{defguardp,1},{defimpl,2},{defimpl,3},{defmacro,1},{defmacro,2},{defmacrop,1},{defmacrop,2},{defmodule,2},{defoverridable,1},{defp,1},{defp,2},{defprotocol,2},{defstruct,1},{destructure,2},{get_and_update_in,2},{if,2},{in,2},{is_nil,1},{'match?',2},{or,2},{pop_in,1},{put_in,2},{raise,1},{raise,2},{reraise,2},{reraise,3},{sigil_C,2},{sigil_D,2},{sigil_N,2},{sigil_R,2},{sigil_S,2},{sigil_T,2},{sigil_W,2},{sigil_c,2},{sigil_r,2},{sigil_s,2},{sigil_w,2},{to_char_list,1},{to_charlist,1},{to_string,1},{unless,2},{update_in,2},{use,1},{use,2},{'var!',1},{'var!',2},{'|>',2},{'||',2}]}],module => 'Elixir.Comparables.Domain.Models.Comparable',prematch_vars => warn,requires => ['Elixir.Kernel','Elixir.Kernel.Typespec'],unused_vars => #{},vars => [{comparable_input,nil}]},{elixir_erl,nil,nil,false,#{{comparable_input,nil} => {0,'_comparable_input@1'}},nil,[],#{comparable_input => 1},false}],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/private/var/folders/z4/pf84ntgx56s9f0txf0l5k7mw0000gp/T/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,259}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	... 12 more
Caused by: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{elixir,quoted_to_erl,[{{'.',[{line,1}],[{comparable_input,[{line,1}],nil},address]},[{line,1}],[]},#{'__struct__' => 'Elixir.Macro.Env',aliases => [],context => nil,context_modules => [],contextual_vars => [],current_vars => #{{comparable_input,nil} => {0,term}},file => #Bin<105>,function => {add_autogenerated_fields,1},functions => [{'Elixir.Kernel',[{'!=',2},{'!==',2},{'*',2},{'+',1},{'+',2},{'++',2},{'-',1},{'-',2},{'--',2},{'/',2},{'<',2},{'<=',2},{'==',2},{'===',2},{'=~',2},{'>',2},{'>=',2},{abs,1},{apply,2},{apply,3},{binary_part,3},{bit_size,1},{byte_size,1},{ceil,1},{div,2},{elem,2},{exit,1},{floor,1},{'function_exported?',3},{get_and_update_in,3},{get_in,2},{hd,1},{inspect,1},{inspect,2},{is_atom,1},{is_binary,1},{is_bitstring,1},{is_boolean,1},{is_float,1},{is_function,1},{is_function,2},{is_integer,1},{is_list,1},{is_map,1},{is_number,1},{is_pid,1},{is_port,1},{is_reference,1},{is_tuple,1},{length,1},{'macro_exported?',3},{make_ref,0},{map_size,1},{max,2},{min,2},{node,0},{node,1},{not,1},{pop_in,2},{put_elem,3},{put_in,3},{rem,2},{round,1},{self,0},{send,2},{spawn,1},{spawn,3},{spawn_link,1},{spawn_link,3},{spawn_monitor,1},{spawn_monitor,3},{struct,1},{struct,2},{'struct!',1},{'struct!',2},{throw,1},{tl,1},{trunc,1},{tuple_size,1},{update_in,3}]}],lexical_tracker => nil,line => 118,macro_aliases => [],macros => [{'Elixir.Kernel',[{'!',1},{'&&',2},{'..',2},{'<>',2},{'@',1},{'alias!',1},{and,2},{binding,0},{binding,1},{def,1},{def,2},{defdelegate,2},{defexception,1},{defguard,1},{defguardp,1},{defimpl,2},{defimpl,3},{defmacro,1},{defmacro,2},{defmacrop,1},{defmacrop,2},{defmodule,2},{defoverridable,1},{defp,1},{defp,2},{defprotocol,2},{defstruct,1},{destructure,2},{get_and_update_in,2},{if,2},{in,2},{is_nil,1},{'match?',2},{or,2},{pop_in,1},{put_in,2},{raise,1},{raise,2},{reraise,2},{reraise,3},{sigil_C,2},{sigil_D,2},{sigil_N,2},{sigil_R,2},{sigil_S,2},{sigil_T,2},{sigil_W,2},{sigil_c,2},{sigil_r,2},{sigil_s,2},{sigil_w,2},{to_char_list,1},{to_charlist,1},{to_string,1},{unless,2},{update_in,2},{use,1},{use,2},{'var!',1},{'var!',2},{'|>',2},{'||',2}]}],module => 'Elixir.Comparables.Domain.Models.Comparable',prematch_vars => warn,requires => ['Elixir.Kernel','Elixir.Kernel.Typespec'],unused_vars => #{},vars => [{comparable_input,nil}]},{elixir_erl,nil,nil,false,#{{comparable_input,nil} => {0,'_comparable_input@1'}},nil,[],#{comparable_input => 1},false}],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/private/var/folders/z4/pf84ntgx56s9f0txf0l5k7mw0000gp/T/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,259}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.elixir_lang.MailBox.wait(MailBox.kt:203)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.evaluate(Node.kt:206)
	at org.elixir_lang.debugger.Process.evaluate(Process.kt:415)
	at org.elixir_lang.debugger.Evaluator.evaluate(Evaluator.kt:19)
	at com.intellij.xdebugger.evaluation.XDebuggerEvaluator.evaluate(XDebuggerEvaluator.java:37)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.startEvaluation(XDebuggerEvaluationDialog.java:342)
	at com.intellij.xdebugger.impl.ui.tree.nodes.EvaluatingExpressionRootNode$EvaluatingResultContainer.computeChildren(EvaluatingExpressionRootNode.java:36)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.startComputingChildren(XValueContainerNode.java:58)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.loadChildren(XValueContainerNode.java:52)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.getChildren(XValueContainerNode.java:242)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XDebuggerTreeNode.getChildCount(XDebuggerTreeNode.java:55)
	at javax.swing.tree.DefaultTreeModel.getChildCount(DefaultTreeModel.java:186)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1479)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
	at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
	at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
	at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
	at javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:365)
	at javax.swing.tree.DefaultTreeModel.setRoot(DefaultTreeModel.java:135)
	at com.intellij.xdebugger.impl.ui.tree.XDebuggerTree.setRoot(XDebuggerTree.java:279)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.evaluate(XDebuggerEvaluationDialog.java:295)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.doOKAction(XDebuggerEvaluationDialog.java:187)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1875)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1835)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog$4.actionPerformed(XDebuggerEvaluationDialog.java:196)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	... 17 more
Caused by: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{elixir,quoted_to_erl,[{{'.',[{line,1}],[{comparable_input,[{line,1}],nil},address]},[{line,1}],[]},#{'__struct__' => 'Elixir.Macro.Env',aliases => [],context => nil,context_modules => [],contextual_vars => [],current_vars => #{{comparable_input,nil} => {0,term}},file => #Bin<105>,function => {add_autogenerated_fields,1},functions => [{'Elixir.Kernel',[{'!=',2},{'!==',2},{'*',2},{'+',1},{'+',2},{'++',2},{'-',1},{'-',2},{'--',2},{'/',2},{'<',2},{'<=',2},{'==',2},{'===',2},{'=~',2},{'>',2},{'>=',2},{abs,1},{apply,2},{apply,3},{binary_part,3},{bit_size,1},{byte_size,1},{ceil,1},{div,2},{elem,2},{exit,1},{floor,1},{'function_exported?',3},{get_and_update_in,3},{get_in,2},{hd,1},{inspect,1},{inspect,2},{is_atom,1},{is_binary,1},{is_bitstring,1},{is_boolean,1},{is_float,1},{is_function,1},{is_function,2},{is_integer,1},{is_list,1},{is_map,1},{is_number,1},{is_pid,1},{is_port,1},{is_reference,1},{is_tuple,1},{length,1},{'macro_exported?',3},{make_ref,0},{map_size,1},{max,2},{min,2},{node,0},{node,1},{not,1},{pop_in,2},{put_elem,3},{put_in,3},{rem,2},{round,1},{self,0},{send,2},{spawn,1},{spawn,3},{spawn_link,1},{spawn_link,3},{spawn_monitor,1},{spawn_monitor,3},{struct,1},{struct,2},{'struct!',1},{'struct!',2},{throw,1},{tl,1},{trunc,1},{tuple_size,1},{update_in,3}]}],lexical_tracker => nil,line => 118,macro_aliases => [],macros => [{'Elixir.Kernel',[{'!',1},{'&&',2},{'..',2},{'<>',2},{'@',1},{'alias!',1},{and,2},{binding,0},{binding,1},{def,1},{def,2},{defdelegate,2},{defexception,1},{defguard,1},{defguardp,1},{defimpl,2},{defimpl,3},{defmacro,1},{defmacro,2},{defmacrop,1},{defmacrop,2},{defmodule,2},{defoverridable,1},{defp,1},{defp,2},{defprotocol,2},{defstruct,1},{destructure,2},{get_and_update_in,2},{if,2},{in,2},{is_nil,1},{'match?',2},{or,2},{pop_in,1},{put_in,2},{raise,1},{raise,2},{reraise,2},{reraise,3},{sigil_C,2},{sigil_D,2},{sigil_N,2},{sigil_R,2},{sigil_S,2},{sigil_T,2},{sigil_W,2},{sigil_c,2},{sigil_r,2},{sigil_s,2},{sigil_w,2},{to_char_list,1},{to_charlist,1},{to_string,1},{unless,2},{update_in,2},{use,1},{use,2},{'var!',1},{'var!',2},{'|>',2},{'||',2}]}],module => 'Elixir.Comparables.Domain.Models.Comparable',prematch_vars => warn,requires => ['Elixir.Kernel','Elixir.Kernel.Typespec'],unused_vars => #{},vars => [{comparable_input,nil}]},{elixir_erl,nil,nil,false,#{{comparable_input,nil} => {0,'_comparable_input@1'}},nil,[],#{comparable_input => 1},false}],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/private/var/folders/z4/pf84ntgx56s9f0txf0l5k7mw0000gp/T/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,259}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at com.ericsson.otp.erlang.OtpMbox.receiveMsg(OtpMbox.java:272)
	at com.ericsson.otp.erlang.OtpMbox.receive(OtpMbox.java:168)
	at org.elixir_lang.MailBox.loop(MailBox.kt:219)
	at org.elixir_lang.MailBox.access$loop(MailBox.kt:22)
	at org.elixir_lang.MailBox$1.run(MailBox.kt:26)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by KronicDeth** [comment]
Is this on Elixir 1.8 or 1.9?  If you look inside the OtpExit, there is an `undef` Erlang error.

**Comment by kekko1212** [comment]
@KronicDeth 

```
elixir 1.8.1-otp-21
erlang 21.0.8
```

**Comment by KronicDeth** [comment]
Duplicate of #1421
