### ISSUE TITLE
Falsely recognizes a binding in an outer block as the same as a new one with the same name in an inner block (anonymous function blocks)

### ISSUE THREAD

**Issue by seeekr** [KronicDeth/intellij-elixir#1479]
# Description

plugin falsely recognizes a binding in an outer block as the same as a new one with the same name in an inner block (anonymous function blocks):

```elixir
{schema, fields} =
        code
        |> Macro.prewalk({}, fn
          {:schema, _, [schema, _]} = node, {} ->
            fields = Macro.prewalk([], fn
              {ty, _, attrs} = node, {schema, fields} -> {node, {schema, fields ++ [{ty, attrs}]}} 
            end)
            {node, {schema, []}}
          node, acc -> {node, acc}
        end)
```

`node` is the variable in question, which I tried to call the "rename" refactoring on, just to see what would happen, since syntax highlighting was already doing the wrong thing in highlighting both bindings of the same name

# Exception

## Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type MATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL (class org.elixir_lang.psi.stub.type.MatchedUnqualifiedNoArgumentsCall)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getProject(StubBasedPsiElementBase.java:291)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:61)
	at org.elixir_lang.refactoring.variable.rename.Inplace.<init>(Inplace.java:32)
	at org.elixir_lang.refactoring.variable.rename.Handler.createRenamer(Handler.kt:73)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:77)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:87)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:54)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:131)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:276)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$null$4(ActionManagerImpl.java:1342)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$tryToExecuteNow$5(ActionManagerImpl.java:1302)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:188)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3080)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:159)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:111)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:185)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:63)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecuteNow(ActionManagerImpl.java:1301)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$tryToExecute$2(ActionManagerImpl.java:1285)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecute(ActionManagerImpl.java:1288)
	at com.intellij.ui.mac.touchbar.TBItemAnActionButton._performAction(TBItemAnActionButton.java:191)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by sh41** [comment]
You were right, and the mechanism is narrower than it looks: resolution was correct, the usage search was not.

Go To Declaration and completion have always treated the inner binding correctly — an `fn` parameter, a `case` clause pattern or a `for` generator that reuses an outer name resolves to itself. Find Usages, Highlight Usages at caret and Rename share a *different* search, and that one matched candidates by name and search scope alone, with no resolution step. A search scope is a text range, and an inner binding sits inside the outer binding's range, so the outer variable's usages swept up the inner one's.

That is why highlighting showed both bindings, and why rename followed: the two features read the same search. Direction mattered — outer to inner leaked, inner to outer did not — so renaming the outer `node` in your snippet also rewrote the inner `fn`'s independent `node`, and the result still compiled.

The search now resolves each occurrence before counting it, so a binding that shadows another is no longer reported as a usage of it. Fixed in #3965.

The exception in your report is a separate matter: it came from the legacy in-place rename handler, removed in 24.0.0 by 2dff82691, and Elixir rename has gone through the Symbol API only since. Your report was about the shadowing, and that is what this close is for.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
