### ISSUE TITLE
Stub index points to a file without PSI: com.intellij.openapi.fileTypes.UnknownFileType@4e7e9366, used scope Project and Libraries 

### ISSUE THREAD

**Issue by amoein** [KronicDeth/intellij-elixir#1481]
# Exception

## Stacktrace

```
java.lang.Throwable: Stub index points to a file without PSI: com.intellij.openapi.fileTypes.UnknownFileType@4e7e9366, used scope Project and Libraries
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:51)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:285)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:597)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:585)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:61)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$null$0(StubIndexImpl.java:309)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:253)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$null$1(StubIndexImpl.java:307)
	at com.intellij.util.indexing.FileBasedIndexImpl.disableUpToDateCheckIn(FileBasedIndexImpl.java:667)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$doProcessStubs$2(StubIndexImpl.java:306)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:43)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:304)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:276)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:121)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:109)
	at org.elixir_lang.psi.scope.atom.Variants.projectLookupElementStream(Variants.java:40)
	at org.elixir_lang.psi.scope.atom.Variants.lookupElementList(Variants.java:24)
	at org.elixir_lang.reference.Atom.getVariants(Atom.java:25)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:274)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:137)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:82)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:71)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:125)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:108)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:96)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:63)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:827)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:272)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sh41** [comment]
The message is the platform's — `com.intellij.psi.stubs.StubProcessingHelperBase` logs it when the stub index names a file the IDE cannot build PSI for. It is attributed to this plugin because the IDE picks the first plugin class on the stack, and `org.elixir_lang.psi.scope.atom.Variants` is there as the caller of `StubIndex.getElements`.

There is still something to fix here. `StubIndexEx` skips any file the caller's search scope does not contain, before that error is logged. The atom and module completion paths pass an unrestricted `GlobalSearchScope.allScope`, so a stale entry of any file type reaches the check. `GlobalSearchScope.getScopeRestrictedByFileTypes` tests a file's current type at query time and would skip it; the plugin already uses that for LiveEEx assigns. Leaving this open for that change.

Impact is limited: the platform re-indexes the file in the same call and carries on over the others, so the cost is one file's entries missing from one completion popup.

This report's message text predates a November 2019 change to the platform's wording, so it cannot be reproduced on a currently supported IDE — the above is from reading current code, not from reproducing this trace.

---

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.

**Comment by sh41** [comment]
Two more call sites for this: the atom reference resolvers `Exact` and `Pattern` also query `elixir.all.name`. They pass a scope narrowed to the module and its dependencies rather than the whole project, but that narrowing is not a file-type restriction and does not guard this — a stale id under the module's own `_build` output is inside it. They need the same restriction as the completion paths.

The restriction also covers more than the unknown-file-type message. `StubIndexEx.processElements` tests the caller's scope before it asks `StubProcessingHelper` for a stub id list, so it guards the "without indexed stub tree" message on that path as well. #3354 is `Exact`'s own report of it, on a file that is plain text rather than unknown, and is closed as a duplicate here.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
