### ISSUE TITLE
OtpErlangExit: timeout in debugger

### ISSUE THREAD

**Issue by MarkSRobinson** [KronicDeth/intellij-elixir#1537]
# Exception

## Stacktrace

```
com.ericsson.otp.erlang.OtpErlangExit: timeout
	at org.elixir_lang.MailBox.wait(MailBox.kt:205)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:111)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:98)
	at org.elixir_lang.MailBox.rpcUnmonitoredCall(MailBox.kt:86)
	at org.elixir_lang.MailBox.processWhereIs(MailBox.kt:54)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:36)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.evaluate(Node.kt:206)
	at org.elixir_lang.debugger.Process.evaluate(Process.kt:415)
	at org.elixir_lang.debugger.Evaluator.evaluate(Evaluator.kt:19)
	at com.intellij.xdebugger.evaluation.XDebuggerEvaluator.evaluate(XDebuggerEvaluator.java:37)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchNodeImpl$XWatchValue.computePresentation(WatchNodeImpl.java:81)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:57)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchNodeImpl.<init>(WatchNodeImpl.java:31)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.<init>(WatchesRootNode.java:59)
	at com.intellij.xdebugger.impl.frame.XWatchesViewImpl.doCreateNewRootNode(XWatchesViewImpl.java:240)
	at com.intellij.xdebugger.impl.frame.XVariablesViewBase.createNewRootNode(XVariablesViewBase.java:97)
	at com.intellij.xdebugger.impl.frame.XVariablesViewBase.buildTreeAndRestoreState(XVariablesViewBase.java:74)
	at com.intellij.xdebugger.impl.frame.XVariablesView.lambda$processSessionEvent$0(XVariablesView.java:71)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by sh41** [comment]
Closing as a duplicate of #2715, which has the fuller diagnosis.

Short version: every request the IDE makes of the debugged node is wrapped in a hard-coded 60 second
timeout that has never been configurable, and when it expires you get this exit. #2715 also covers a
second effect — because `interpret` runs before `attach` and a timeout abandons the remaining
start-up steps, a slow interpret can mean the session never attaches at all.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
