### ISSUE TITLE
Invalid range specified: (-1, 0) at org.elixir_lang.inspection.NoParenthesesManyStrict$1.visitElement(NoParenthesesManyStrict.java:88)

### ISSUE THREAD

**Issue by kurtlenfesty** [KronicDeth/intellij-elixir#1544]
# Description

Typing in function into file factorial1.exs (so I was in the middle of typing):
defmodule Factorial do
  def of(0), do: 1
  def of(n), do: n * of(n - 1)
end

# Exception

## Stacktrace

```
java.lang.Throwable: Invalid range specified: (-1, 0); 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:252)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:247)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:243)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:56)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:45)
	at org.elixir_lang.inspection.NoParenthesesManyStrict$1.visitElement(NoParenthesesManyStrict.java:88)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnqualifiedNoParenthesesManyArgumentsCallImpl.accept(ElixirUnqualifiedNoParenthesesManyArgumentsCallImpl.java:39)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at org.elixir_lang.inspection.NoParenthesesManyStrict$1.visitElement(NoParenthesesManyStrict.java:101)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at org.elixir_lang.inspection.NoParenthesesManyStrict.checkFile(NoParenthesesManyStrict.java:48)
	at org.elixir_lang.inspection.NoParenthesesManyStrict.checkFile(NoParenthesesManyStrict.java:43)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by sh41** [comment]
This is still there, thanks for the report — same crash as #1219, at the same line.

The "Ambiguous nested calls" inspection flags an argument as ambiguous and then looks for the comma that makes it ambiguous inside that argument's own text. For at least one shape it checks, the comma that actually makes the call ambiguous lives outside that argument, so nothing is found, and building a text range from "not found" is what throws.

I tried retyping your factorial example character by character to catch it happening, and it didn't reproduce that way — so it looks like it needs a more specific edit sequence than typing straight through, which matches "in the middle of typing" rather than any particular finished line. The fix itself is small and clear regardless of the exact keystrokes: skip flagging when no comma is actually there, since there's nothing coherent to highlight in that case. It hasn't been written yet, so I'm leaving this open rather than closing it out.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
