### ISSUE TITLE
[auto-generated] Error report when trying to run in debug mode

### ISSUE THREAD

**Issue by lerox** [KronicDeth/intellij-elixir#1559]
# Description

I am receiving an error report when I try to run a phoenix app in debug mode. It works well when I run via IDEA in the regular mode.

Can someone give me a hand? I am not sure If I have something miss configured.

# Exception

## Stacktrace

```
java.io.IOException: Nameserver not responding on 127.0.0.1 when publishing debuggerdb7d4679-a722-4970-807f-7fc0f87a513b
	at com.ericsson.otp.erlang.OtpEpmd.r4_publish(OtpEpmd.java:344)
	at com.ericsson.otp.erlang.OtpEpmd.publishPort(OtpEpmd.java:141)
	at com.ericsson.otp.erlang.OtpNode$Acceptor.publishPort(OtpNode.java:784)
	at com.ericsson.otp.erlang.OtpNode$Acceptor.<init>(OtpNode.java:776)
	at com.ericsson.otp.erlang.OtpNode.init(OtpNode.java:232)
	at com.ericsson.otp.erlang.OtpNode.<init>(OtpNode.java:196)
	at com.ericsson.otp.erlang.OtpNode.<init>(OtpNode.java:149)
	at org.elixir_lang.ServerKt.waitForNameServer(Server.kt:51)
	at org.elixir_lang.ServerKt.access$waitForNameServer(Server.kt:1)
	at org.elixir_lang.Server.localNode(Server.kt:35)
	at org.elixir_lang.Server.mailBox(Server.kt:17)
	at org.elixir_lang.debugger.Node$mailBox$2.invoke(Node.kt:58)
	at org.elixir_lang.debugger.Node$mailBox$2.invoke(Node.kt:35)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.elixir_lang.debugger.Node.getMailBox(Node.kt)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

and also:
```
java.lang.reflect.InvocationTargetException
  at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:214)
  at com.sun.proxy.$Proxy17.processTerminated(Unknown Source)
  at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:172)
  at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:247)
  at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:155)
  at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:151)
  at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:123)
  at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
  at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:168)
  at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:99)
  at com.intellij.execution.process.ProcessWaitFor.lambda$null$0(ProcessWaitFor.java:61)
  at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
  at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:43)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Nameserver not responding on 127.0.0.1 when publishing debugger9ba86967-8abc-40eb-a045-0f25d742f37b
  at com.ericsson.otp.erlang.OtpEpmd.r4_publish(OtpEpmd.java:344)
  at com.ericsson.otp.erlang.OtpEpmd.publishPort(OtpEpmd.java:141)
  at com.ericsson.otp.erlang.OtpNode$Acceptor.publishPort(OtpNode.java:784)
  at com.ericsson.otp.erlang.OtpNode$Acceptor.<init>(OtpNode.java:776)
  at com.ericsson.otp.erlang.OtpNode.init(OtpNode.java:232)
  at com.ericsson.otp.erlang.OtpNode.<init>(OtpNode.java:196)
  at com.ericsson.otp.erlang.OtpNode.<init>(OtpNode.java:149)
  at org.elixir_lang.ServerKt.waitForNameServer(Server.kt:51)
  at org.elixir_lang.ServerKt.access$waitForNameServer(Server.kt:1)
  at org.elixir_lang.Server.localNode(Server.kt:35)
  at org.elixir_lang.Server.mailBox(Server.kt:17)
  at org.elixir_lang.debugger.Node$mailBox$2.invoke(Node.kt:58)
  at org.elixir_lang.debugger.Node$mailBox$2.invoke(Node.kt:35)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
  at org.elixir_lang.debugger.Node.getMailBox(Node.kt)
  at org.elixir_lang.debugger.Node.stop(Node.kt:74)
  at org.elixir_lang.debugger.Process.stop(Process.kt:395)
  at com.intellij.xdebugger.XDebugProcess.stopAsync(XDebugProcess.java:171)
  at com.intellij.xdebugger.impl.XDebugSessionImpl.stopImpl(XDebugSessionImpl.java:918)
  at com.intellij.xdebugger.impl.XDebugSessionImpl.access$000(XDebugSessionImpl.java:70)
  at com.intellij.xdebugger.impl.XDebugSessionImpl$1.processTerminated(XDebugSessionImpl.java:291)
  ... 21 more

```

```
$ ~/.asdf/installs/erlang/21.1/erts-10.1/bin/epmd -debug
epmd: Fri Aug 23 21:25:31 2019: epmd running - daemon = 0
epmd: Fri Aug 23 21:25:41 2019: ** got ALIVE2_REQ
epmd: Fri Aug 23 21:25:41 2019: registering 'debugged805730c1-63bb-4557-be69-9fd4664fd904:3', port 51781
epmd: Fri Aug 23 21:25:41 2019: type 77 proto 0 highvsn 5 lowvsn 5
epmd: Fri Aug 23 21:25:41 2019: ** sent ALIVE2_RESP for "debugged805730c1-63bb-4557-be69-9fd4664fd904"
epmd: Fri Aug 23 21:25:51 2019: unregistering 'debugged805730c1-63bb-4557-be69-9fd4664fd904:3', port 51781
```

```
IntelliJ IDEA 2019.2.1 (Community Edition)
Build #IC-192.6262.58, built on August 20, 2019
Runtime version: 11.0.3+12-b304.39 x86_64

macOS 10.14.6

erlang & elixir installed via asdf
erlang  v 21.1
elixir v 1.7.4

plugin v 11.0.1
```

Best,

**Comment by lerox** [comment]
and also:

```
java.lang.reflect.InvocationTargetException
  at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:214)
  at com.sun.proxy.$Proxy17.processTerminated(Unknown Source)
  at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:172)
  at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:247)
  at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:155)
  at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:151)
  at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:123)
  at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
  at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:168)
  at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:99)
  at com.intellij.execution.process.ProcessWaitFor.lambda$null$0(ProcessWaitFor.java:61)
  at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
  at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:43)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Nameserver not responding on 127.0.0.1 when publishing debugger9ba86967-8abc-40eb-a045-0f25d742f37b
  at com.ericsson.otp.erlang.OtpEpmd.r4_publish(OtpEpmd.java:344)
  at com.ericsson.otp.erlang.OtpEpmd.publishPort(OtpEpmd.java:141)
  at com.ericsson.otp.erlang.OtpNode$Acceptor.publishPort(OtpNode.java:784)
  at com.ericsson.otp.erlang.OtpNode$Acceptor.<init>(OtpNode.java:776)
  at com.ericsson.otp.erlang.OtpNode.init(OtpNode.java:232)
  at com.ericsson.otp.erlang.OtpNode.<init>(OtpNode.java:196)
  at com.ericsson.otp.erlang.OtpNode.<init>(OtpNode.java:149)
  at org.elixir_lang.ServerKt.waitForNameServer(Server.kt:51)
  at org.elixir_lang.ServerKt.access$waitForNameServer(Server.kt:1)
  at org.elixir_lang.Server.localNode(Server.kt:35)
  at org.elixir_lang.Server.mailBox(Server.kt:17)
  at org.elixir_lang.debugger.Node$mailBox$2.invoke(Node.kt:58)
  at org.elixir_lang.debugger.Node$mailBox$2.invoke(Node.kt:35)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
  at org.elixir_lang.debugger.Node.getMailBox(Node.kt)
  at org.elixir_lang.debugger.Node.stop(Node.kt:74)
  at org.elixir_lang.debugger.Process.stop(Process.kt:395)
  at com.intellij.xdebugger.XDebugProcess.stopAsync(XDebugProcess.java:171)
  at com.intellij.xdebugger.impl.XDebugSessionImpl.stopImpl(XDebugSessionImpl.java:918)
  at com.intellij.xdebugger.impl.XDebugSessionImpl.access$000(XDebugSessionImpl.java:70)
  at com.intellij.xdebugger.impl.XDebugSessionImpl$1.processTerminated(XDebugSessionImpl.java:291)
  ... 21 more
```

**Comment by lerox** [comment]
After I removed my changes related with `ERL_EPMD_PORT` env var everything worked well as expected.

**Comment by KronicDeth** [comment]
@lerox what changes had to made to `ERL_EPMD_PORT`, so that others can understand if they are having the same issue and can fix it the same way?

**Comment by lerox** [comment]
Hi @KronicDeth

It was 24001:
```
$ echo $ERL_EPMD_PORT
24001
```

And now (nothing):
```
$ echo $ERL_EPMD_PORT

```

So it's going to use the default port.

Best,
