### ISSUE TITLE
KotlinNullPointerException at org.elixir_lang.structure_view.element.CallDefinitionSpecification$Companion.typeNameArity(CallDefinitionSpecification.kt:100)

### ISSUE THREAD

**Issue by virtual-light** [KronicDeth/intellij-elixir#1564]
# Exception

## Stacktrace

```
kotlin.KotlinNullPointerException
	at org.elixir_lang.structure_view.element.CallDefinitionSpecification$Companion.typeNameArity(CallDefinitionSpecification.kt:100)
	at org.elixir_lang.reference.resolver.CallDefinitionClause.resolve(CallDefinitionClause.kt:18)
	at org.elixir_lang.reference.resolver.CallDefinitionClause.resolve(CallDefinitionClause.kt:13)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:171)
	at org.elixir_lang.reference.CallDefinitionClause.multiResolve(CallDefinitionClause.java:79)
	at org.elixir_lang.reference.CallDefinitionClause.resolve(CallDefinitionClause.java:95)
	at org.elixir_lang.TargetElementEvaluator.getElementByReference(TargetElementEvaluator.kt:21)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:381)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:363)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:235)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:207)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by sh41** [comment]
Reproduced on current main. `CallDefinitionSpecification.typeNameArity` force-unwraps `Call.functionName()`, which is declared `@Nullable`: `functionNameElement()` returns null for anonymous-function calls (`foo.()`), `not in` operations and module attributes. A `@spec` whose head parses to one of those shapes — `@spec foo.() :: term`, `@spec bar not in baz :: term` — crashes the structure view tree walk, which backs the Structure tool window, the Ctrl+F12 file structure popup and the method separators. The unchecked `!!` has been there since the `NameArity` commit in 2018 and was never touched after it.

Fixed in #3963: `typeNameArity` returns null when the head has no name, so a malformed spec is left out of the tree instead of throwing — every caller already handled a null result. Regression test added.

Kotlin 2 compiles `!!` to a plain `NullPointerException`, so this crash reports under that name now rather than `KotlinNullPointerException`.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
