### ISSUE TITLE
Error trying to debug tests :-)

### ISSUE THREAD

**Issue by sergiobrr** [KronicDeth/intellij-elixir#1584]
# Version

4.5.1

# Exception

## Stacktrace

```
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{int,interpretable,['Elixir.Hex.API.Auth'],[]},{'Elixir.IntelliJElixir.Debugger.Server','-interpret_modules_in/2-fun-4-',1,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,368}]},{'Elixir.Stream','-filter/2-fun-0-',4,[{file,"lib/stream.ex"},{line,481}]},{'Elixir.Enumerable.List',reduce,3,[{file,"lib/enum.ex"},{line,3325}]},{'Elixir.Enumerable.Stream',do_each,4,[{file,"lib/stream.ex"},{line,1583}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,3023}]},{'Elixir.IntelliJElixir.Debugger.Server',interpret_modules_in,2,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,369}]},{'Elixir.IntelliJElixir.Debugger.Server','-handle_call/3-fun-3-',3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,101}]}]}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.elixir_lang.MailBox.wait(MailBox.kt:203)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{int,interpretable,['Elixir.Hex.API.Auth'],[]},{'Elixir.IntelliJElixir.Debugger.Server','-interpret_modules_in/2-fun-4-',1,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,368}]},{'Elixir.Stream','-filter/2-fun-0-',4,[{file,"lib/stream.ex"},{line,481}]},{'Elixir.Enumerable.List',reduce,3,[{file,"lib/enum.ex"},{line,3325}]},{'Elixir.Enumerable.Stream',do_each,4,[{file,"lib/stream.ex"},{line,1583}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,3023}]},{'Elixir.IntelliJElixir.Debugger.Server',interpret_modules_in,2,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,369}]},{'Elixir.IntelliJElixir.Debugger.Server','-handle_call/3-fun-3-',3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,101}]}]}
	at com.ericsson.otp.erlang.OtpMbox.receiveMsg(OtpMbox.java:272)
	at com.ericsson.otp.erlang.OtpMbox.receive(OtpMbox.java:168)
	at org.elixir_lang.MailBox.loop(MailBox.kt:219)
	at org.elixir_lang.MailBox.access$loop(MailBox.kt:22)
	at org.elixir_lang.MailBox$1.run(MailBox.kt:26)
	... 6 more
```

**Comment by KronicDeth** [comment]
`{int,interpretable,['Elixir.Hex.API.Auth'` makes me think that it is trying to prompt you to do something with `hex`.  Which SDK are you using?

**Comment by sergiobrr** [comment]
Hello, sorry for late reply, i'm using elixir 1.9.1
Probably it's my fault, i saw only yesterday that to debug i need to remove flags on Interpreted modules. Maybe that's the problem
