### ISSUE TITLE
ConcurrentModificationException at org.elixir_lang.sdk.erlang_dependent.Type.getDependencyType(Type.java:56)

### ISSUE THREAD

**Issue by sparta-developers** [KronicDeth/intellij-elixir#1591]
# Exception

## Stacktrace

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at com.intellij.openapi.projectRoots.impl.UnknownSdkType.getInstance(UnknownSdkType.java:31)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.findSdkTypeByName(ProjectJdkTableImpl.java:228)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.getSdkTypeByName(ProjectJdkTableImpl.java:217)
	at org.elixir_lang.sdk.elixir.Type.erlangSdkType(Type.java:339)
	at org.elixir_lang.sdk.erlang_dependent.Type.getDependencyType(Type.java:56)
	at com.intellij.openapi.projectRoots.JavaSdkVersionUtil.getJavaSdkVersion(JavaSdkVersionUtil.java:33)
	at com.intellij.openapi.projectRoots.JavaSdkVersionUtil.getJavaSdkVersion(JavaSdkVersionUtil.java:26)
	at com.intellij.openapi.projectRoots.JavaSdkVersionUtil.isAtLeast(JavaSdkVersionUtil.java:14)
	at com.intellij.openapi.projectRoots.JavaVersionServiceImpl.isAtLeast(JavaVersionServiceImpl.java:33)
	at com.intellij.execution.junit.codeInsight.JUnit5MalformedRepeatedTestInspection.buildVisitor(JUnit5MalformedRepeatedTestInspection.kt:33)
	at com.intellij.codeInspection.LocalInspectionTool.buildVisitor(LocalInspectionTool.java:123)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:53)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by KronicDeth** [comment]
This comes in from part of the API that JetBrains write and errors inside part they write.  I'm not sure how to fix this without their help.  I'll open an issue with them.

**Comment by KronicDeth** [comment]
@sparta-developers which IDE and version are you using?

**Comment by KronicDeth** [comment]
https://youtrack.jetbrains.com/issue/IDEA-223730

**Comment by KronicDeth** [comment]
This is fixed by JetBrains
