### ISSUE TITLE
Probably SDK installed in 'C:/Program Files (x86)/Elixir' is corrupt

### ISSUE THREAD

**Issue by keith-miller** [KronicDeth/intellij-elixir#1597]
Hello. I am getting the following error when trying to set up the Elixir plugin on Windows 10. I installed Elixir using the Windows installer [here](https://elixir-lang.org/install.html) and it seems to work alright outside of the plugin, and the Erland SDK is recognized without issue, but the Elixir SDK is not. 

Versions:
- Elixir - 1.9.1
- Erlang - 10.3
- Plugin - 11.1.0
- IDE: IntelliJ IDEA 2019.2.3 (Ultimate Edition)
- Windows - Microsoft Windows [Version 10.0.17763.737]

Let me know what other information you need and I can provide. Thanks!

**Comment by keith-miller** [comment]
Intellij log stack trace from when the error pops up:

```
2019-10-03 12:13:03,277 [1871069]   WARN - ion.process.BaseProcessHandler - Must specify non-empty 'commandLine' parameter
java.lang.IllegalArgumentException: Must specify non-empty 'commandLine' parameter
        at com.intellij.execution.process.BaseProcessHandler.<init>(BaseProcessHandler.java:34)
        at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:32)
        at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:151)
        at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:35)
        at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:28)
        at org.elixir_lang.sdk.ProcessOutput.execute(ProcessOutput.java:95)
        at org.elixir_lang.sdk.ProcessOutput.getProcessOutput(ProcessOutput.java:85)
        at org.elixir_lang.sdk.ProcessOutput.transformStdoutLine(ProcessOutput.java:61)
        at org.elixir_lang.sdk.elixir.Type.detectSdkVersion(Type.java:470)
        at org.elixir_lang.sdk.elixir.Type.suggestSdkName(Type.java:645)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.createUniqueSdkName(SdkConfigurationUtil.java:278)
        at com.intellij.openapi.projectRoots.impl.DependentSdkType.lambda$createSdkOfType$1(DependentSdkType.java:70)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.lambda$selectSdkHome$6(SdkConfigurationUtil.java:299)
        at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:145)
        at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:112)
        at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:90)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:296)
        at com.intellij.openapi.projectRoots.impl.DependentSdkType.createSdkOfType(DependentSdkType.java:69)
        at com.intellij.openapi.projectRoots.impl.DependentSdkType.showCustomCreateUI(DependentSdkType.java:54)
        at com.intellij.openapi.projectRoots.SdkType.showCustomCreateUI(SdkType.java:263)
        at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:263)
        at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$1.actionPerformed(ProjectSdksModel.java:249)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:256)
        at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:200)
        at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:190)
        at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:184)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
        at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1428)
        at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2464)
        at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:168)
        at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:120)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
        at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1424)
        at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:162)
        at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:318)
        at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
        at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
        at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
        at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
        at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:194)
        at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
        at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:142)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:136)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:132)
        at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
        at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:453)
        at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:407)
        at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:353)
        at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:512)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:566)
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:769)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:693)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:707)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:432)
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1644)
        at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:51)
        at com.intellij.ide.actions.TemplateProjectStructureAction.actionPerformed(TemplateProjectStructureAction.java:21)
        at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen$IconsFreeActionGroup$1.actionPerformed(FlatWelcomeFrame.java:813)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
        at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:148)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:256)
        at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:200)
        at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:190)
        at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:184)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
        at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1428)
        at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2464)
        at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:168)
        at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:120)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
        at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1424)
        at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:162)
        at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:318)
        at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:278)
        at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
        at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
        at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
        at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
        at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:194)
        at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
        at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:142)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:136)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:132)
        at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
        at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:453)
        at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:407)
        at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:353)
        at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:298)
        at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:512)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:566)
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:769)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by KronicDeth** [comment]
This appears to be a quoting issue when passing the code to run on Windows.  Unlike Posix systems, the separated arguments seem to still pass through a shell on Windows.

<img width="1920" alt="Windows Error" src="https://user-images.githubusercontent.com/298259/67113857-250a3c80-f1a0-11e9-8687-688fb13ce268.png">

**Comment by KronicDeth** [comment]
GeneralCommandLine's prepareCommandLine is misescaping the Elixir code
<img width="1920" alt="Windows Error" src="https://user-images.githubusercontent.com/298259/67124253-cfda2500-f1b7-11e9-96f3-c39f429c442c.png">
