### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented: Don't know how to check if class org.elixir_lang.structure_view.element.CallDefinitionHead is decompiled

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#1603]
# Exception

## Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented: Don't know how to check if class org.elixir_lang.structure_view.element.CallDefinitionHead is decompiled
	at org.elixir_lang.navigation.SourcePreferredItemsKt.isDecompiled(SourcePreferredItems.kt:190)
	at org.elixir_lang.navigation.SourcePreferredItemsKt.isDecompiled(SourcePreferredItems.kt:13)
	at org.elixir_lang.navigation.SourcePreferredItems$add$2.apply(SourcePreferredItems.kt:65)
	at org.elixir_lang.navigation.SourcePreferredItems$add$2.apply(SourcePreferredItems.kt:19)
	at java.base/java.util.HashMap.compute(HashMap.java:1228)
	at org.elixir_lang.navigation.SourcePreferredItems.add(SourcePreferredItems.kt:63)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsFromCallDefinitionHead(ChooseByNameContributor.kt:167)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByNameFromCall(ChooseByNameContributor.kt:89)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByName(ChooseByNameContributor.kt:63)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.lambda$getElementsByName$3(ContributorsBasedGotoByModel.java:196)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:693)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:46)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1101)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:1957)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1042)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:58)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:58)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.getElementsByName(ContributorsBasedGotoByModel.java:225)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.processByNames(DefaultChooseByNameItemProvider.java:232)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:96)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.lambda$filterElements$1(DefaultChooseByNameItemProvider.java:55)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:54)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchElements$3(AbstractGotoSEContributor.java:208)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:544)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchElements(AbstractGotoSEContributor.java:193)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ContributorSearchTask.lambda$run$1(MultiThreadSearcher.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ContributorSearchTask.run(MultiThreadSearcher.java:176)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sh41** [comment]
Fixed in v11.12.0.

`SourcePreferredItems` decides whether a navigation item is decompiled by dispatching on its type, and threw from the fallback branch for any type it had no case for. Commit 09df8baf8 — "Any.isDecompiled for CallDefinitionHead" — added the `CallDefinitionHead` case, so a call definition head can no longer reach that branch. That commit closed #1901, which is this same crash: same class, same message, same stack. This issue was never closed alongside it.

The case is still present on current `main`.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
