### ISSUE TITLE
Unable to launch phoenix app because of no function clause matching in :elixir_erl.dynamic_form/1

### ISSUE THREAD

**Issue by clemensm** [KronicDeth/intellij-elixir#1614]
Hi everyone

We've been developing an umbrellas elixir application for some time, and recently decided that we want to try the Intellij Plugin. So for my coworker this is working fine, but on my machine, with identical version of the plugin, intellij, erlang and elixir, I always get the following error when I try to run or debug the application: 

```
** (FunctionClauseError) no function clause matching in :elixir_erl.dynamic_form/1
    (elixir) src/elixir_erl.erl:154: :elixir_erl.dynamic_form(%{attributes: [protocol: [fallback_to_any: false], compile: {:inline, [any_impl_for: 0, struct_impl_for: 1, impl_for?: 1]}, compile: :debug_info], compile_opts: [{:inline, [any_impl_for: 0, struct_impl_for: 1, impl_for?: 1]}, :debug_info], definitions: [{{:__protocol__, 1}, :def, [line: 1, generated: true], [{[line: 1, generated: true], [:module], [], Amnesia.Selection}, {[line: 1, generated: true], [:functions], [], [coerce: 2, next: 1, values: 1]}, {[line: 1, generated: true], [:consolidated?], [], true}, {[line: 1, generated: true], [:impls], [], {:consolidated, [Amnesia.Table.Select, Amnesia.Table.Match, Atom]}}]}, {{:impl_for, 1}, :def, [line: 1, generated: true], [{[line: 1, generated: true], [{:%{}, [line: 1], [__struct__: {:x, [line: 1], Protocol}]}], [{{:., [line: 1], [:erlang, :is_atom]}, [line: 1], [{:x, [line: 1], Protocol}]}], {:struct_impl_for, [line: 1], [{:x, [line: 1], Protocol}]}}, {[line: 1, generated: true], [{:x, [line: 1], Protocol}], [{{:., [line: {:line, [line: 1], Protocol}], [:erlang, :is_atom]}, [line: {:line, [line: 1], Protocol}], [{:x, [line: 1], Protocol}]}], Amnesia.Selection.Atom}, {[line: 1, generated: true], [{:_, [], Protocol}], [], nil}]}, {{:struct_impl_for, 1}, :defp, [line: 1, generated: true], [{[line: 1, generated: true], [Amnesia.Table.Select], [], Amnesia.Selection.Amnesia.Table.Select}, {[line: 1, generated: true], [Amnesia.Table.Match], [], Amnesia.Selection.Amnesia.Table.Match}, {[line: 1, generated: true], [{:_, [], Protocol}], [], nil}]}, {{:values, 1}, :def, [line: 4, generated: true], [{[line: 4, generated: true], [{:term, [counter: -576460752303419386, line: 4], Protocol}], [], {{:., [line: 4], [{:impl_for!, [line: 4], [{:term, [counter: -576460752303419386, line: 4], Protocol}]}, :values]}, [line: 4], [{:term, [counter: -576460752303419386, line: 4], Protocol}]}}]}, {{:next, 1}, :def, [line: 3, generated: true], [{[line: 3, generated: true], [{:term, [counter: -576460752303422360, line: 3], Protocol}], [], {{:., [line: 3], [{:impl_for!, [line: 3], [{:term, [counter: -576460752303422360, line: 3], Protocol}]}, :next]}, [line: 3], [{:term, [counter: -576460752303422360, line: 3], Protocol}]}}]}, {{:impl_for?, 1}, :defp, [line: 1, generated: true], [{[line: 1, generated: true], [{:target, [line: 1], Protocol}], [], {:case, [line: 1], [{{:., [line: 1], [Code, :ensure_compiled?]}, [line: 1], [{:target, [line: 1], Protocol}]}, [do: [{:->, [generated: true, line: 1], [[true], {{:., [], [Kernel, :function_exported?]}, [context: Protocol, import: Kernel, line: 1], [{:target, [line: 1], Protocol}, :__impl__, 1]}]}, {:->, [generated: true, line: 1], [[false], false]}, {:->, [generated: true, line: 1], [[{:other, [line: 1], :elixir_expand}], {{:., [line: 1], [:erlang, :error]}, [line: 1], [{:{}, [], [:badbool, :and, {:other, [line: 1], :elixir_expand}]}]}]}]]]}}]}, {{:impl_for!, 1}, :def, [line: 1, generated: true], [{[line: 1, generated: true], [{:data, [line: 1], Protocol}], [], {:case, [line: 1], [{:impl_for, [line: 1], [{:data, [line: 1], Protocol}]}, [do: [{:->, [line: 1], [[{:when, [line: 1], [{:x, [counter: -576460752303414075, line: 1], Kernel}, {{:., [line: 1], [:erlang, :or]}, [line: 1], [{{:., [line: 1], [:erlang, :"=:="]}, [line: 1], [{:x, [counter: -576460752303414075, line: 1], Kernel}, nil]}, {{:., [line: 1], [:erlang, :"=:="]}, [line: 1], [{:x, [counter: -576460752303414075, line: 1], Kernel}, false]}]}]}], {{:., [line: 1], [:erlang, :error]}, [line: 1], [{{:., [line: 1], [Protocol.UndefinedError, :exception]}, [line: 1], [[protocol: Amnesia.Selection, value: {:data, [line: 1], Protocol}]]}]}]}, {:->, [line: 1], [[{:x, [counter: -576460752303414075, line: 1], Kernel}], {:x, [counter: -576460752303414075, line: 1], Kernel}]}]]]}}]}, {{:coerce, 2}, :def, [line: 2, generated: true], [{[line: 2, generated: true], [{:term, [counter: -576460752303422712, line: 2], Protocol}, {:var2, [counter: -576460752303422712, line: 2], Protocol}], [], {{:., [line: 2], [{:impl_for!, [line: 2], [{:term, [counter: -576460752303422712, line: 2], Protocol}]}, :coerce]}, [line: 2], [{:term, [counter: -576460752303422712, line: 2], Protocol}, {:var2, [counter: -576460752303422712, line: 2], Protocol}]}}]}, {{:any_impl_for, 0}, :defp, [line: 1, generated: true], [{[line: 1, generated: true], [], [], nil}]}], file: "/private/var/folders/1f/zrzqhhln7s5_fclj8qzcbqlc0000gn/T/mix-local-installer-fetcher-Gwft5w/deps/amnesia/lib/amnesia/selection.ex", line: 1, module: Amnesia.Selection, unreachable: []})
    (elixir) src/elixir_erl.erl:126: :elixir_erl.consolidate/3
    (elixir) lib/protocol.ex:651: Protocol.compile/3
    (mix) lib/mix/tasks/compile.protocols.ex:141: Mix.Tasks.Compile.Protocols.consolidate/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

The relevant part for me seems to be the last entry in the map passed to `:elixir_erl.dynamic_form`, i.e. this, which cannot match if I look at the source of `:elixir_erl.dynamic_form`:

```
file: "/private/var/folders/1f/zrzqhhln7s5_fclj8qzcbqlc0000gn/T/mix-local-installer-fetcher-Gwft5w/deps/amnesia/lib/amnesia/selection.ex", line: 1, module: Amnesia.Selection, unreachable: []
```

Does anyone have an idea how to fix this?

Thanks

**Comment by clemensm** [comment]
Sorry, didn't get around to try this again for some time. 

So I believe this was rather specific to my mac only, and I've upadted to Intellij 2019.3 and MacOS Catalina by now, and the problem has disapperead.
