### ISSUE TITLE
Error trying to debug [auto-generated]

### ISSUE THREAD

**Issue by sergiobrr** [KronicDeth/intellij-elixir#1618]
# Version

4.5.2

# Description

created configuration for running a phoenix project (a elixir mix one, adding phx.server as mix argument and the pwd as the project root)
then i launched a debug session. It immediately stops the process and warn for an error.

# Exception

## Stacktrace

```
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{int,interpreted,[],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir/debugger/lib/intellij_elixir/debugger/server.ex"},{line,134}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.elixir_lang.MailBox.wait(MailBox.kt:203)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.setBreakpoint(Node.kt:83)
	at org.elixir_lang.debugger.Process.addBreakpoint(Process.kt:155)
	at org.elixir_lang.debugger.Process.access$addBreakpoint(Process.kt:73)
	at org.elixir_lang.debugger.Process$addBreakpoint$$inlined$let$lambda$1.invoke(Process.kt:133)
	at org.elixir_lang.debugger.Process$addBreakpoint$$inlined$let$lambda$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{int,interpreted,[],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir/debugger/lib/intellij_elixir/debugger/server.ex"},{line,134}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
	at com.ericsson.otp.erlang.OtpMbox.receiveMsg(OtpMbox.java:272)
	at com.ericsson.otp.erlang.OtpMbox.receive(OtpMbox.java:168)
	at org.elixir_lang.MailBox.loop(MailBox.kt:219)
	at org.elixir_lang.MailBox.access$loop(MailBox.kt:22)
	at org.elixir_lang.MailBox$1.run(MailBox.kt:26)
	... 6 more
```

**Comment by KronicDeth** [comment]
Fixed in #1650.  Released in 11.5.0.
