### ISSUE TITLE
debbuger error on start (phx.server)

### ISSUE THREAD

**Issue by JerzyDziala** [KronicDeth/intellij-elixir#1629]
# Exception

## Stacktrace

```
com.ericsson.otp.erlang.OtpErlangExit: timeout
	at org.elixir_lang.MailBox.wait(MailBox.kt:205)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KronicDeth** [comment]
This is a general timeout that means it could not connect to the code-under-test.  There's not enough information to debug this further.  It may be that there are too many libraries being interpreted.   In which case, you should [exclude modules](https://github.com/KronicDeth/intellij-elixir/tree/1fff00c56a69458c44a18480c5628bd173ee996c#excluding-modules) to speed the boot time.
