### ISSUE TITLE
InvalidMirrorException for jsx_decoder.beam

### ISSUE THREAD

**Issue by visd0m** [KronicDeth/intellij-elixir#1633]
# Exception

## Message

.../.elixir_ls/build/test/lib/jsx/ebin/jsx_decoder.beam

## Stacktrace

```
org.elixir_lang.beam.psi.impl.ModuleElementImpl$InvalidMirrorException: stub:[org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4b9a67ba, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4c902b47, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2ff51c7f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2b719ce3, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@334e8980, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7ec946bd, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@79d8abff, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5ee9a6a3, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@192c2677, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2d646741, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@11dfb641, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@210d667, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7af757cc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@74a779bc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1826b4d7, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1c01fa5a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5c089721, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@13ad7f85, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3e00f12b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2d400f9b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3569348d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4d4034f2, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@74f01dd8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5961f80a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@25d072f7, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@697b251b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1d91fb31, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4be6f121, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6d876560, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5de4d636, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4f3ef6c8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@33ad69f7, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@65d7b687, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1e79896d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2649a4dc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7e739333, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@26c861f4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@74a8b6a1, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1fac93ac, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7d247161]; mirror:[UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:43)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.java:105)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.java:633)
	at org.elixir_lang.beam.psi.BeamFileImpl$1.run(BeamFileImpl.java:606)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.java:604)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:125)
	at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.java:110)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByName(ChooseByNameContributor.kt:60)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.lambda$getElementsByName$3(ContributorsBasedGotoByModel.java:196)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:46)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:148)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by sh41** [comment]
Fixed in v11.9.1.

`ModuleImpl.setMirror` used to pair compiled stubs with decompiled definitions by position, so any difference in count threw — here, 40 compiled definitions against the 16 that came back out of the decompiled Elixir. Commit a03c8a80c changed it to match by name and arity and skip the rest.

The parse failure behind it had its own fix: Erlang functions whose names are Elixir keywords are now emitted as `def unquote(:name)(...)`. For a JSON scanner like `jsx_decoder` that would be `true` or `false`, handled by 9f02a2e3a in v11.11.0 — plausible here, though not confirmable without the `.beam`.

If this still happens on a current release, please open a new issue and attach the `.beam`.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
