### ISSUE TITLE
org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.java:366) does not check if element is invalid

### ISSUE THREAD

**Issue by markhu53** [KronicDeth/intellij-elixir#1641]
# Exception

## Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/hgf/Documents/test/gateway/_build/test/lib/gateway/ebin/Elixir.Cmpp.beam is invalid
invalidated at: no info
	at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.java:366)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache$OCCodeBlockModificationListener.a(FileSymbolTablesCache.java:946)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache$OCCodeBlockModificationListener.treeChanged(FileSymbolTablesCache.java:887)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:344)
	at com.intellij.psi.impl.PsiManagerImpl.childRemoved(PsiManagerImpl.java:277)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$filesDeleted$3(PsiVFSListener.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.filesDeleted(PsiVFSListener.java:190)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.fireForGrouped(PsiVFSListener.java:690)
	at one.util.streamex.CollapseSpliterator.lambda$forEachRemaining$0(CollapseSpliterator.java:131)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at one.util.streamex.CollapseSpliterator.forEachRemaining(CollapseSpliterator.java:127)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:306)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.groupAndFire(PsiVFSListener.java:684)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.after(PsiVFSListener.java:673)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$2.after(PsiVFSListener.java:106)
	at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:318)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
	at com.sun.proxy.$Proxy24.fileWithNoDocumentChanged(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:142)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$new$0(FileDocumentManagerImpl.java:122)
	at com.sun.proxy.$Proxy24.fileWithNoDocumentChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.contentsChanged(FileDocumentManagerImpl.java:618)
	at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:132)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:26)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:90)
	at com.sun.proxy.$Proxy21.contentsChanged(Unknown Source)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
	at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:320)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
	at com.sun.proxy.$Proxy20.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:903)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEventsInWriteAction(RefreshSessionImpl.java:199)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:92)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:186)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by sh41** [comment]
The guard isn't missing. `BeamFileImpl.getContainingFile` has checked `isValid()` and thrown `PsiInvalidElementAccessException` since the file was added in 2016 (`358cbe158`), and the `BeamFileImpl.java:366` frame at the top of this trace *is* that `throw`. The guard fired — it didn't fail to run. That matches `com.intellij.psi.impl.compiled.ClsFileImpl`, the platform's own decompiled-file `PsiFile` that `BeamFileImpl` is modelled on, which carries the identical check.

What the trace shows is a caller using the element after it was invalidated, and the caller isn't this plugin: CIDR's `FileSymbolTablesCache$OCCodeBlockModificationListener` handles the platform's `childRemoved` for a `.beam` under `_build` that a rebuild just deleted. Nothing sits between `PsiVFSListener.filesDeleted` and that listener for the plugin to hook. This is also the caller context #2993 — same crash, same call site — was closed for lacking.

Closing on that: there's nothing to change in `BeamFileImpl`, and returning an invalid file rather than throwing would trade a visible error for silent use of stale PSI.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
