### ISSUE TITLE
ParameterInfo.getParametersForLookup(ParameterInfo.kt:115) not implemented

### ISSUE THREAD

**Issue by unixc3t** [KronicDeth/intellij-elixir#1649]
# Version

4.11.5

# Exception

## Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented: not implemented
	at org.elixir_lang.code_insight.ParameterInfo.getParametersForLookup(ParameterInfo.kt:115)
	at com.intellij.codeInsight.hint.ShowParameterInfoHandler.invoke(ShowParameterInfoHandler.java:99)
	at com.intellij.codeInsight.AutoPopupControllerImpl.lambda$autoPopupParameterInfo$1(AutoPopupControllerImpl.java:144)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$null$10(PsiDocumentManagerBase.java:604)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by sh41** [comment]
Fixed. `ParameterInfo.getParametersForLookup` — the method this `NotImplementedError` was thrown from — was deleted in ee8e59080 ("Fix plugin verifier deprecation and internal API warnings"), first shipped in v13.0.0. It was an override of a `ParameterInfoHandler` method that only ever contained a `TODO()` stub; with the override gone the platform's own default runs and nothing throws. There is no `getParametersForLookup` anywhere in the plugin today.

#1766 was the same crash on a later build and is already closed.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
