### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by zodiake** [KronicDeth/intellij-elixir#1690]
# Exception

## Message

ReformatCodeProcessor failure, see the stack trace

## Stacktrace

```
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren
	at org.elixir_lang.formatter.Block.<init>(Block.java:311)
	at org.elixir_lang.formatter.Block.buildChild(Block.java:795)
	at org.elixir_lang.formatter.Block.lambda$buildMapUpdateArgumentsChildren$27(Block.java:1521)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:330)
	at org.elixir_lang.formatter.Block.buildMapUpdateArgumentsChildren(Block.java:1511)
	at org.elixir_lang.formatter.Block.lambda$buildMapArgumentsChildren$24(Block.java:1424)
	at org.elixir_lang.formatter.Block.lambda$buildContainerChildren$14(Block.java:1084)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:330)
	at org.elixir_lang.formatter.Block.buildContainerChildren(Block.java:1074)
	at org.elixir_lang.formatter.Block.buildMapArgumentsChildren(Block.java:1412)
	at org.elixir_lang.formatter.Block.lambda$buildMapChildren$25(Block.java:1444)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:330)
	at org.elixir_lang.formatter.Block.buildMapChildren(Block.java:1439)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:881)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:968)
	at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:47)
	at com.intellij.formatting.InitialInfoBuilder.buildFrom(InitialInfoBuilder.java:146)
	at com.intellij.formatting.InitialInfoBuilder.doIteration(InitialInfoBuilder.java:221)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:118)
	at com.intellij.formatting.engine.WrapBlocksState.doIteration(WrapBlocksState.java:47)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:26)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:107)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:705)
	at com.intellij.formatting.FormatterImpl.execute(FormatterImpl.java:274)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:239)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processText(CodeFormatterFacade.java:198)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$reformatText$3(CodeStyleManagerImpl.java:217)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.formatRanges(CodeStyleManagerImpl.java:251)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:212)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:176)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:159)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$null$0(ReformatCodeProcessor.java:117)
	at com.intellij.openapi.editor.ex.util.EditorScrollingPositionKeeper.perform(EditorScrollingPositionKeeper.java:100)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$1(ReformatCodeProcessor.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$preprocessFile$0(AbstractLayoutCodeProcessor.java:212)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$runProcessFile$2(AbstractLayoutCodeProcessor.java:309)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$null$5(AbstractLayoutCodeProcessor.java:392)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$null$6(AbstractLayoutCodeProcessor.java:390)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by zodiake** [comment]
duplicate
