### ISSUE TITLE
Synchronous execution under ReadAction at LevelPropertyPusher.java:193

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#1764]
# Exception

## Stacktrace

```
java.lang.Throwable: Synchronous execution under ReadAction: /usr/local/Cellar/elixir/1.10.2/bin/elixir -e "System.version |> IO.puts"
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:170)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:115)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:51)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:40)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:64)
	at org.elixir_lang.sdk.ProcessOutput.execute(ProcessOutput.java:96)
	at org.elixir_lang.sdk.ProcessOutput.getProcessOutput(ProcessOutput.java:85)
	at org.elixir_lang.sdk.ProcessOutput.transformStdoutLine(ProcessOutput.java:61)
	at org.elixir_lang.sdk.elixir.Type.detectSdkVersion(Type.java:474)
	at org.elixir_lang.sdk.elixir.Type.getRelease(Type.java:397)
	at org.elixir_lang.file.LevelPropertyPusher.computeLevel(LevelPropertyPusher.java:193)
	at org.elixir_lang.file.LevelPropertyPusher.level(LevelPropertyPusher.java:65)
	at org.elixir_lang.file.LevelPropertyPusher.computeLevel(LevelPropertyPusher.java:128)
	at org.elixir_lang.file.LevelPropertyPusher.level(LevelPropertyPusher.java:96)
	at org.elixir_lang.file.LevelPropertyPusher.getImmediateValue(LevelPropertyPusher.java:325)
	at org.elixir_lang.file.LevelPropertyPusher.getImmediateValue(LevelPropertyPusher.java:48)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.lambda$doPushAll$11(PushedFilePropertiesUpdaterImpl.java:288)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:898)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.doPushAll(PushedFilePropertiesUpdaterImpl.java:282)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.pushAllPropertiesNow(PushedFilePropertiesUpdaterImpl.java:155)
	at com.intellij.util.indexing.UnindexedFilesUpdater.updateUnindexedFiles(UnindexedFilesUpdater.java:65)
	at com.intellij.util.indexing.UnindexedFilesUpdater.performInDumbMode(UnindexedFilesUpdater.java:135)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runSingleTask$10(DumbServiceImpl.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.project.DumbServiceImpl.runSingleTask(DumbServiceImpl.java:728)
	at com.intellij.openapi.project.DumbServiceImpl.runBackgroundProcess(DumbServiceImpl.java:705)
	at com.intellij.openapi.project.DumbServiceImpl.access$500(DumbServiceImpl.java:64)
	at com.intellij.openapi.project.DumbServiceImpl$7.run(DumbServiceImpl.java:659)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sh41** [comment]
This is fixed.

Two things had to be true for this crash, and neither is true anymore.

The frame that ran the subprocess, `LevelPropertyPusher.computeLevel`, is gone. The whole file was removed in 679a9689cfe097018b9baa4e894d4550a84d7aac, when support for Elixir versions before 1.6 was dropped, and the plugin registers no file-property pusher of any kind today — so nothing of ours runs inside the `PushedFilePropertiesUpdaterImpl` read action that this trace goes through. That shipped in v12.0.0 and the class has stayed gone ever since, including in the current release, v24.0.1.

The work it was doing has also changed shape. Detecting the Elixir SDK version no longer runs `elixir -e "System.version |> IO.puts"` at all: `ElixirVersionDetector` reads the version out of `lib/elixir/ebin/elixir.app` under the SDK home, so there is no process to spawn and nothing to wait on. That is covered by tests which point at a directory containing only that `.app` file, with no `elixir` executable anywhere, and still get the right version back.

Thanks for reporting it.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
