### ISSUE TITLE
Non-idempotent computation at org.elixir_lang.reference.Module.multiResolve(Module.kt:29)

### ISSUE THREAD

**Issue by felipeloha** [KronicDeth/intellij-elixir#1778]
```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  3 != 2
  which is length of [PsiElementResolveResult with class org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl: Ecto.Query, PsiElementResolveResult with class org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl: Ecto.Query, PsiElementResolveResult with class org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl: Ecto.Query] and [PsiElementResolveResult with class org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl: Ecto.Query, PsiElementResolveResult with class org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl: Ecto.Query]

Recomputation gives [Lcom.intellij.psi.PsiElementResolveResult;@6ffe4f3 (class [Lcom.intellij.psi.PsiElementResolveResult;) which is equivalent to 'fresh'
Recomputation log:
  Resolving org.elixir_lang.reference.Module(ElixirMatchedQualifiedAliasImpl(MATCHED_QUALIFIED_ALIAS):(0,10)) of class org.elixir_lang.reference.Module
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:91)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:78)
	at com.intellij.psi.impl.source.resolve.ResolveCache.cache(ResolveCache.java:286)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:214)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:152)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:29)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.fullyResolve(QualifiableAliasImpl.kt:46)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModular(QualifiableAliasImpl.kt:150)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModular(QualifiableAliasImpl.kt:138)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModular(PsiElementImpl.kt:170)
	at org.elixir_lang.psi.Import.modular(Import.kt:153)
	at org.elixir_lang.psi.Import.callDefinitionClauseCallWhile(Import.kt:41)
	at org.elixir_lang.psi.QuoteMacro.callDefinitionClauseCallWhile(QuoteMacro.kt:26)
	at org.elixir_lang.psi.Using.callDefinitionClauseCallWhile(Using.kt:26)
	at org.elixir_lang.psi.Using$callDefinitionClauseCallWhile$$inlined$let$lambda$1.invoke(Using.kt:40)
	at org.elixir_lang.psi.Using$callDefinitionClauseCallWhile$$inlined$let$lambda$1.invoke(Using.kt:15)
	at org.elixir_lang.psi.Modular.callDefinitionClauseCallWhile(Modular.kt:29)
	at org.elixir_lang.psi.Using.callDefinitionClauseCallWhile(Using.kt:38)
	at org.elixir_lang.psi.Use.callDefinitionClauseCallWhile(Use.kt:28)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:101)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:89)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:32)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:77)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:567)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:168)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1150)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:65)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:62)
	at org.elixir_lang.reference.resolver.Callable.resolveElement(Callable.kt:52)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:22)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:14)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:152)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:225)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:203)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:152)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:880)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:106)
	at org.elixir_lang.reference.Callable.resolve(Callable.kt:113)
	at org.elixir_lang.TargetElementEvaluator.getElementByReference(TargetElementEvaluator.kt:21)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:172)
	at com.intellij.codeInsight.TargetEvaluatorAwareReference.getTargetElement(TargetEvaluatorAwareReference.java:75)
	at com.intellij.codeInsight.TargetEvaluatorAwareReference.resolveReference(TargetEvaluatorAwareReference.java:61)
	at com.intellij.model.psi.impl.TargetsKt.referencedSymbols(targets.kt:28)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:18)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:233)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:225)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:90)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:410)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by sh41** [comment]
Still there. The cause looks like a race, not a computation that disagrees with itself.

`IdempotenceChecker`'s random re-check only runs in unit tests, so a report from a released IDE has to come from `ResolveCache` comparing two concurrent resolves of the same reference. They disagree because of us: `org.elixir_lang.reference.resolver.Module` and the module scope walk both consult the stub index only when the project isn't indexing. Resolving the same module either side of that boundary gives nothing during indexing and the module after, so two threads straddling the end of indexing get different results — different lengths, same alias, as in your trace.

Correcting an earlier note of mine here: this is not fixed by the deduplication released in v12.0.0. That change is deterministic and doesn't touch indexing state or thread safety.

Leaving it open. The race means I can't give you repro steps, but the mechanism is in current code and doesn't depend on your project.

Separately, the `reference.Callable` and `__module__.Reference` reports — #2205, #2428, #3320, #3477, #3495, #3517, #3592, #3593 — are tracked separately and this doesn't cover them.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
