### ISSUE TITLE
Run the Debugger led to this error

### ISSUE THREAD

**Issue by katebushgg** [KronicDeth/intellij-elixir#1785]
# Exception

## Stacktrace

```
com.ericsson.otp.erlang.OtpErlangExit: timeout
	at org.elixir_lang.MailBox.wait(MailBox.kt:205)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KronicDeth** [comment]
That means the debugger was unable to connect to the process being debugged.  It may be that you did not allow `beam.smp` to accept incoming connections if on macOS, or you need to ignore some modules for interpretation, so that the debugged node starts sooner.

Did you see any `Interpreting ...` messages in the console before this happened?

**Comment by sh41** [comment]
Closing as a duplicate of #2715, which has the fuller diagnosis.

Short version: every request the IDE makes of the debugged node is wrapped in a hard-coded 60 second
timeout that has never been configurable, and this exit is that timeout expiring. The trace here is
the `interpret` step during session start-up, which is the case #2715 also covers — because
`interpret` runs before `attach` and a timeout abandons the remaining start-up steps, a slow
interpret can mean the session never attaches at all.

That is what the question about `Interpreting ...` messages was getting at in 2020. It turned out not
to need an answer: the cause was identified later on #2715, and the constant is still there in `Node`
on `main` today, so #2715 is where a fix would be tracked.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
