### ISSUE TITLE
Error at openning project

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#1804]
```
java.lang.Throwable: Path conflict. Existing symlink: SymlinkData{139768, //var -> /private/var} vs. new symlink: SymlinkData{139779, //var -> /private/var}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.openapi.vfs.impl.local.WatchRootsManager.updateSymlink(WatchRootsManager.java:109)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.symlinkUpdated(LocalFileSystemImpl.java:163)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.writeAttributesToRecord(PersistentFSImpl.java:298)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.makeChildRecord(PersistentFSImpl.java:1377)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.persistAllChildren(PersistentFSImpl.java:177)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.listAll(PersistentFSImpl.java:202)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.loadAllChildren(VirtualDirectoryImpl.java:363)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.getChildren(VirtualDirectoryImpl.java:355)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.getChildren(PsiDirectoryImpl.java:202)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getPrevSibling(SharedPsiElementImplUtil.java:105)
	at com.intellij.psi.impl.PsiElementBase.getPrevSibling(PsiElementBase.java:62)
	at org.elixir_lang.psi.impl.PsiElementImplKt$prevSiblingSequence$1.invoke(PsiElementImpl.kt:192)
	at org.elixir_lang.psi.impl.PsiElementImplKt$prevSiblingSequence$1.invoke(PsiElementImpl.kt)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:544)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:562)
	at org.elixir_lang.reference.resolver.ModuleAttribute.multiResolveSibling(ModuleAttribute.kt:130)
	at org.elixir_lang.reference.resolver.ModuleAttribute.multiResolveUpFromElement(ModuleAttribute.kt:88)
	at org.elixir_lang.reference.resolver.ModuleAttribute.resolve(ModuleAttribute.kt:51)
	at org.elixir_lang.reference.resolver.ModuleAttribute.resolve(ModuleAttribute.kt:19)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:152)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:225)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:203)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:152)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at org.elixir_lang.reference.ModuleAttribute.multiResolve(ModuleAttribute.kt:65)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.elixir_lang.folding.Builder$1.slowExecute(Builder.java:282)
	at org.elixir_lang.folding.Builder$1.slowExecute(Builder.java:243)
	at org.elixir_lang.folding.Builder$1.execute(Builder.java:99)
	at org.elixir_lang.folding.Builder$1.execute(Builder.java:77)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:885)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedExpressionImpl.accept(ElixirUnmatchedExpressionImpl.java:23)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtOperationImpl.accept(ElixirUnmatchedAtOperationImpl.java:25)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:886)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:881)
	at org.elixir_lang.folding.Builder.buildFoldRegions(Builder.java:57)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:92)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:75)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:248)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:228)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:82)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:66)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:229)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:410)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by KronicDeth** [comment]
`/var` is something managed by your OS and I don't really have control over your OS or how OpenAPI interprets your symlinks.  Please open this as an issue with JetBrains directly.
