### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.elixir_lang.psi.scope.call_definition_clause.ArityInterval

### ISSUE THREAD

**Issue by fahadnaeemkhan** [KronicDeth/intellij-elixir#1819]
# Exception

## Stacktrace

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.psi.scope.call_definition_clause.ArityInterval
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.executeOnCallDefinitionClause(MultiResolve.kt:24)
	at org.elixir_lang.psi.scope.CallDefinitionClause$implicitImports$1$1.invoke(CallDefinitionClause.kt:146)
	at org.elixir_lang.psi.scope.CallDefinitionClause$implicitImports$1$1.invoke(CallDefinitionClause.kt:20)
	at org.elixir_lang.psi.Modular.callDefinitionClauseCallWhile(Modular.kt:29)
	at org.elixir_lang.psi.scope.CallDefinitionClause$implicitImports$1.fun(CallDefinitionClause.kt:142)
	at org.elixir_lang.psi.scope.CallDefinitionClause$implicitImports$1.fun(CallDefinitionClause.kt:20)
	at org.elixir_lang.Reference.forEachNavigationElement(Reference.java:59)
	at org.elixir_lang.Reference.forEachNavigationElement(Reference.java:41)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImports(CallDefinitionClause.kt:133)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:97)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:32)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:77)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:567)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:168)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1162)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:65)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:62)
	at org.elixir_lang.reference.resolver.Callable.resolveElement(Callable.kt:52)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:22)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:14)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:155)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:227)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:205)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:155)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:170)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:163)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:851)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:106)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:98)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:42)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:338)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:271)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:214)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by sh41** [comment]
Closing this without having worked out what actually went wrong, so here is what the report does and doesn't establish.

`NoClassDefFoundError: Could not initialize class X` is a secondary failure. A class's static initializer runs once; if it throws, the class is left permanently in an erroneous state and the real failure surfaces exactly once, as an `ExceptionInInitializerError` carrying the cause. Every later touch of that class — including the one in this trace — gets this bare message with no cause chain. So the class named here is the victim rather than the defect, and whatever threw first would have appeared as a separate error in the same session, which isn't attached here. There's no plugin version, IDE or reproduction either, so there is nothing left to work back from.

Separately, the class named no longer exists. `org.elixir_lang.psi.scope.call_definition_clause.ArityInterval` was replaced by `org.elixir_lang.psi.ArityInterval` in "Support arity intervals for `unquote_splicing` in parameters" (d64b0632c3), first released in v11.12.0. The old class's only non-trivial initialization — a table of special-form arities — moved to `NameArityInterval`, and what remains in the new class is a single constant. `MultiResolve.executeOnCallDefinitionClause`, which this trace crashed in, is still there, but it now depends on a differently-initialized class. That is not evidence the original trigger is gone, since nothing here identifies the trigger — but this exact message can no longer be produced.

This hasn't come up again on the tracker since it was filed, and it doesn't appear in the plugin's recent crash reports. If it does recur, the useful report is the *first* exception in that session, the `ExceptionInInitializerError`, rather than this one.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
