### ISSUE TITLE
AlreadyDisposedException: Cannot create com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable because container is already disposed when switching between projects

### ISSUE THREAD

**Issue by 03juan** [KronicDeth/intellij-elixir#1850]
# Description

Opened and closed projects successively

# Exception

ERROR - intellij.openapi.progress.Task - IntelliJ IDEA 2020.2.3  Build #IU-202.7660.26
ERROR - intellij.openapi.progress.Task - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
ERROR - intellij.openapi.progress.Task - OS: Linux
ERROR - intellij.openapi.progress.Task - Plugin to blame: Elixir version: 11.8.1
ERROR - intellij.openapi.progress.Task - Last Action: CloseProject
ERROR - intellij.openapi.progress.Task - com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable because container is already disposed

## Stacktrace

```
java.lang.RuntimeException: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable because container is already disposed: Project(name=[redacted], containerState=DISPOSE_COMPLETED, componentStore=/home/[redacted])
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:475)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:480)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:67)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:44)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:184)
	at org.elixir_lang.DepsWatcher.syncLibrary(DepsWatcher.kt:165)
	at org.elixir_lang.DepsWatcher.access$syncLibrary(DepsWatcher.kt:31)
	at org.elixir_lang.DepsWatcher$syncLibraries$$inlined$let$lambda$6.run(DepsWatcher.kt:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable because container is already disposed: Project(name=[redacted], containerState=DISPOSE_COMPLETED, componentStore=/home/[redacted])
	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:447)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:423)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:395)
	at com.intellij.openapi.roots.impl.libraries.LibraryTablesRegistrarImpl.getLibraryTable(LibraryTablesRegistrarImpl.java:34)
	at org.elixir_lang.mix.Watcher$syncLibraries$3$1.run(Watcher.kt:69)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:980)
	at org.elixir_lang.mix.Watcher$syncLibraries$3.run(Watcher.kt:68)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:475)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by KronicDeth** [comment]
IIRC there's someway in the API to chain disposing things so this doesn't happen.  I'll have to find it again.

**Comment by sh41** [comment]
Fixed. `Watcher.syncLibraries` queued a write action onto the EDT with `invokeAndWait` from a
background task, and nothing in that chain checked the project was still there when the queued work
finally ran. Close a project mid-sync and it reached `LibraryTablesRegistrar.getLibraryTable` on a
container already at `DISPOSE_COMPLETED` — the `Caused by` half of your trace.

`f4e399504` replaced `Watcher` and `DepsWatcher` with `MixDepsSyncService`, a project-level service
whose coroutine scope the platform cancels on project close, and which checks `project.isDisposed`
immediately before that same `getLibraryTable` call. The blocking `invokeAndWait` round trip went with
it. First released in 24.0.0.

The 2021 comment above expected the fix to be a `Disposer` chain; it turned out to be the service
scope plus the explicit check.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
