### ISSUE TITLE
[error] GenServer IntelliJElixir.Debugger.Server terminating

### ISSUE THREAD

**Issue by mjsommer** [KronicDeth/intellij-elixir#1857]
During a debugging session, the debugger randomly crashed with the following error:

```
[error] GenServer IntelliJElixir.Debugger.Server terminating
** (FunctionClauseError) no function clause matching in Code.ensure_loaded?/1
    (elixir) lib/code.ex:869: Code.ensure_loaded?({%Phoenix.Router.NoRouteError{conn: %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, 
    assigns: %{}, before_send: [#Function<1.44798538/1 in Plug.Logger.call/2>, #Function<0.832222/1 in Phoenix.LiveReloader.before_send_inject_reloader/2>], body_params: %{}, 
    cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "GET", owner: #PID<0.11960.0>, params: %{}, path_info: ["css", "app.css"], 
    path_params: %{}, port: 4000, private: %{MyAppWeb.Router => {[], %{}}, :phoenix_endpoint => MyAppWeb.Endpoint, :phoenix_pipelines => [], :phoenix_router => MyAppWeb.Router, 
    :plug_session_fetch => #Function<1.45862765/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, 
    req_headers: [{"host", "localhost:4000"}, {"connection", "keep-alive"}, {"sec-ch-ua", "\"Google Chrome\";v=\"87\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"87\""}, {"sec-ch-ua-mobile", "?0"}, 
    {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}, {"accept", "text/css,*/*;q=0.1"}, {"sec-fetch-site", 
    "same-origin"}, {"sec-fetch-mode", "no-cors"}, {"sec-fetch-dest", "style"}, {"referer", "http://localhost:4000/org-requests"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", 
    "en-US,en;q=0.9"}], request_path: "/css/app.css", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", 
    "FlD1K8EOQsrNQh4AAAaB"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}, message: "no route found for GET /css/app.css (MyAppWeb.Router)", 
    plug_status: 404, router: MyAppWeb.Router}, [{MyAppWeb.Router, :__match_route__, 4, [file: 'lib/my_app_web/router.ex', line: 1]}, {MyAppWeb.Router, :"call (overridable 2)", 2, 
    [file: 'lib/phoenix/router.ex', line: 303]}, {MyAppWeb.Router, :call, 2, [file: 'lib/plug/error_handler.ex', line: 64]}, {MyAppWeb.Endpoint, :plug_builder_call, 2, 
    [file: 'lib/my_app_web/endpoint.ex', line: 1]}, {MyAppWeb.Endpoint, :"call (overridable 3)", 2, [file: 'lib/plug/debugger.ex', line: 122]}, {MyAppWeb.Endpoint, :call, 2, 
    [file: 'lib/my_app_web/endpoint.ex', line: 1]}, {Plug.Adapters.Cowboy.Handler, :upgrade, 4, [file: 'lib/plug/cowboy/handler.ex', line: 18]}, {:cowboy_protocol, :execute, 4, 
    [file: '/Users/Projects/my-app/deps/cowboy/src/cowboy_protocol.erl', line: 442]}]})
    /private/var/folders/tv/62sj7tlx3478xqzb9pl7cwb00000gp/T/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex:493: IntelliJElixir.Debugger.Server.source/1
    /private/var/folders/tv/62sj7tlx3478xqzb9pl7cwb00000gp/T/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex:484: anonymous fn/2 in IntelliJElixir.Debugger.Server.snapshot_with_stacks/0
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    /private/var/folders/tv/62sj7tlx3478xqzb9pl7cwb00000gp/T/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex:481: IntelliJElixir.Debugger.Server.snapshot_with_stacks/0
    /private/var/folders/tv/62sj7tlx3478xqzb9pl7cwb00000gp/T/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex:304: IntelliJElixir.Debugger.Server.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:breakpoint_reached, #PID<0.11988.0>}}
```
Please let me know, what additional info you might need.

**Comment by mjsommer** [comment]
Luke, the `[error] GenServer IntelliJElixir.Debugger.Server terminating` error, is making the debugger unusable. After one hit on break points, the `IntelliJElixir.Debugger.Server` is done!

**Comment by sh41** [comment]
Still live, and this explains why the whole debugger dies rather than just one frame going wrong.

**The crash.** To build the process list, the debug server asks `:int` for a snapshot and, for each
process, inspects the info it gets back. It treats *any* two-element tuple there as
`{break_module, break_line}` — without checking that the process is actually stopped at a breakpoint.
When a process exits with an unhandled error, the BEAM reports its reason as `{exception, stacktrace}`,
which is also a two-element tuple. So the exception struct gets bound where a module atom is expected
and handed to `Code.ensure_loaded?`, which has no clause for a struct. Hence
`no function clause matching in Code.ensure_loaded?/1` with a `%Phoenix.Router.NoRouteError{}` in the
argument. Notably, `safely_interpret/1` in the same file does guard its input; this path doesn't.

So a route that 404s in your app is enough to trigger it — the failing process has nothing to do with
whatever you were debugging.

**Why the session then stops responding**, which is the part neither report could see. The server is
supervised, so it restarts — but its `attached` state resets to `nil` while `:int`'s `auto_attach`
registration is global and survives. The next breakpoint fires a cast the restarted server has no
matching clause for, so it crashes again. That repeats until the supervisor exceeds its restart
intensity and shuts down. Because the server was unlinked from its supervisor at startup, that shutdown
is silent: nothing is logged, the process is simply gone, and every later request from the IDE fails
with `{:noproc, ...}`. From your side the debugger just stops answering.

The follow-up report on this thread, of everything dying after a single breakpoint, is exactly this.

Nothing in the plugin has guarded that path since it was written. Now tracked under #3936, and it is
one of the defects listed in #3944.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this
reply before it was posted. If any of it is wrong, please say so here.

**Comment by mjsommer** [comment]
Thanks for staying on top of this. I went back to doing Ruby projects, but still get requests for Elixir ... Let's see, what the future brings! :)
