### ISSUE TITLE
nonempty text is not covered by block in Elixir formatter

### ISSUE THREAD

**Issue by Zorgatone** [KronicDeth/intellij-elixir#1862]
# Exception

## Message

nonempty text is not covered by block in #Elixir #formatter
Range: [539,542], text fragment: [539,542]

## Stacktrace

```
com.intellij.diagnostic.PluginException:  [Plugin: org.elixir_lang]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:337)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:59)
	at com.intellij.formatting.RangesAssert.assertInvalidRanges(RangesAssert.java:60)
	at com.intellij.formatting.WhiteSpace.changeEndOffset(WhiteSpace.java:126)
	at com.intellij.formatting.InitialInfoBuilder.buildFrom(InitialInfoBuilder.java:140)
	at com.intellij.formatting.InitialInfoBuilder.doIteration(InitialInfoBuilder.java:220)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:117)
	at com.intellij.formatting.engine.WrapBlocksState.doIteration(WrapBlocksState.java:47)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:26)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:108)
	at com.intellij.formatting.FormatterImpl.buildProcessorAndWrapBlocks(FormatterImpl.java:428)
	at com.intellij.formatting.FormatterImpl.buildProcessorAndWrapBlocks(FormatterImpl.java:405)
	at jdk.internal.reflect.GeneratedMethodAccessor223.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at indent.rainbow.IrIndentHelperKt.invokeWithRethrow(IrIndentHelper.kt:187)
	at indent.rainbow.IrIndentHelperKt.access$invokeWithRethrow(IrIndentHelper.kt:1)
	at indent.rainbow.IrFormatterIndentHelper$Companion.doGetInstance(IrIndentHelper.kt:133)
	at indent.rainbow.IrFormatterIndentHelper$Companion.access$doGetInstance(IrIndentHelper.kt:120)
	at indent.rainbow.IrFormatterIndentHelper$Companion$getInstance$1.invoke(IrIndentHelper.kt:121)
	at indent.rainbow.IrFormatterIndentHelper$Companion$getInstance$1.invoke(IrIndentHelper.kt:120)
	at indent.rainbow.IrIndentHelperKt.retry(IrIndentHelper.kt:175)
	at indent.rainbow.IrIndentHelperKt.retry$default(IrIndentHelper.kt:172)
	at indent.rainbow.IrFormatterIndentHelper$Companion.getInstance(IrIndentHelper.kt:121)
	at indent.rainbow.IrAnnotatorImpl$Companion.getInstance(IrAnnotatorImpl.kt:156)
	at indent.rainbow.annotators.IrFormatterIncrementalAnnotator.getOrCreateAnnotatorImpl(IrFormatterIncrementalAnnotator.kt:27)
	at indent.rainbow.annotators.IrFormatterIncrementalAnnotator.tryAnnotate(IrFormatterIncrementalAnnotator.kt:17)
	at indent.rainbow.annotators.IrAnnotatorProxy.annotate(IrAnnotatorProxy.kt:19)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:35)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by sh41** [comment]
The block model really can leave a text range uncovered, and nothing on `main` fixes that. But this report carries only the byte range `[539,542]` into a file we don't have, so there's no way to tell which construct produced the gap — the same reason #1432 and #1476 were closed.

Closing as cannot-reproduce. If it recurs, attach the `.ex` file it happened in and I'll reopen; that file is the one thing that would make this actionable.
