### ISSUE TITLE
Colours inside of editor stop working randomly

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#1868]
**Describe the bug**
Randomly the colours inside the text editor will stop working, and I need to reopen the file. This happens on 2020.1, so I upgraded to 2020.2 (since v11.9.0 is now supported?)

**To Reproduce**
1. Open a file
2. Edit it
3. It will randomly stop working,

**Expected behavior**
It will work.

**Screenshots**

**Logs**
Last error seems to be:
```
file:///home/josh/.asdf/installs/elixir/1.11.2-otp-23/lib/elixir/ebin/Elixir.Kernel.beam

org.elixir_lang.beam.psi.impl.ModuleElementImpl$InvalidMirrorException: stub:[org.elixir_lang.beam.psi.impl.CallDefinitionImpl@53dd5abb, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5301d7cb, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7389031d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@55c664e4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6cf7e465, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3195d9bf, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@abfb57b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6c38118c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3f3f04a2, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@20786adb, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@579b07c2, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7b83c8cc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3cded90a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5f9352f8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@50b9fbdf, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@35999cac, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7fc5159c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3a849c0e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@257cef82, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5c796b7d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@bc7fc9b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@153d6501, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@57ff98db, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@404a23da, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@74dd2c6c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@a364a9b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@21243246, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3061914b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2dc26567, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@151890d6, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@15ae3631, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@29790606, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@17aea713, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@46610b10, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@229ab253, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@43b2c930, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@21c6686a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6f31cec9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@18cee156, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4de04036, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5ff7f4d8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3e512e69, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@517abca4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1ed4b74d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7ee5c17b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@49709aa8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4deb90be, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@76be2891, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2680d124, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6be8ba86, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7a97b925, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7deaec46, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5d430b2e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7351b68a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@34c87754, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1eea3557, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5bb557df, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@25ae5fc5, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@522beef3, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1d24296c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6cde8eb8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3b59b491, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3608997f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@a5bb99b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@12e85d26, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@64e39ed6, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@16522054, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4112c464, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1143a00d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@69ae99dd, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6ef9543c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@391f9c63, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@35501085, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@28ad0783, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@cd1fe1e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@49e89763, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7c8972e3, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3cd8e3ee, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3ffacb65, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@32a41076, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@50d62ab, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7e312677, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@17796b37, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@54cfe0e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6bbacc36, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1c4f5da8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4033bdc5, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@226d9743, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1f0b3444, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@794f9810, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@24cfdf69, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6a56833c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2c393326, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@29b3b1a9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@73dd0761, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2d4c3545, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@488993c9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7c835d88, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@677ebb76, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2bd44cc1, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2fc785a9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@49cef2c4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5bf95580, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@52c2b87a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@413b9546, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7f5d1777, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6e191849, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@295f7c98, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@34534d50, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@23221202, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@55f9d7f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@57368af0, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7921748b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4aa0cbaf, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@336d13e1, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@50ef7e76, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2218cdcc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6ea99793, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@350063bc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1eb7a7a4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7aa57f13, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@58126adb, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6eb9efe6, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4d90ef12, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1c9c4c54, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5793a9ae, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@76f4aa65, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3c5633d6, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@42d626e4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@84229c9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5b360d26, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@56735d15, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2561b039, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3c74c93d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5740bca8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1b17c8a0, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@335f5383, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@297859f4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7b0f158f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5ef88086, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@17721391, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7cae4f72, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7f0e9e05, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@65e8cdd2, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6201a465, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6c5ab288, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@672ff7b0, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@440a30da, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2bc796b2, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@12b0bfb0, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@aba5821, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1f23254c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@8c6421c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1f1c318b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@473f0919, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@41b05df7, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7b5c217f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5b2d7f6, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3afa6198, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7966dcd5, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@63ab4d5f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@70352bbb, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@192a6284, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@56659500, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6f9dfb26, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@36ac7d9d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7cd8178e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6ef5080, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6abdfb0, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@533e0a6d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6f6613e3, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@137135df, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4b7f2e5e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6831383e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3717d7d0, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2dd2c320, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1fed151a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7e7c2e11, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@775cdf59, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4c2cc951, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3b1e400b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@248deddf, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@353a4800, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1f7679b7, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@56a16c4a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1d899054, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7a94b1ad, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5603d489, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@b9d313f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5a471b28, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@501d014, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4d6eeba1, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2f182ffa, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4de4ff6a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@466e17b2, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7ce7df3d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@12ee48a4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@781bfa3c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4e7eb10a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@c2291cf, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6ce95387, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4b048e3c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@704990b7, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@68fdcb98, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4eaec86b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@21b4caec, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1dc43a45, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1b63936e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2336edf9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@24d2b0d9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@18f8a014, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1f07a886, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@b4ac7ba, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3a2ffa72, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@678a1523, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@456bd2cc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@18c1bacc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5df83fcc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6a6c1a5d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@718a486e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@64089b49, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7892ce5b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@72a69de6, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@51cc62e4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@713e7947, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1fb0912d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@59bf6690, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6bd6e401, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@69205c7d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7202918d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@50abf2bb, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@c81e243]; mirror:[UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:43)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.java:105)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.java:634)
	at org.elixir_lang.beam.psi.BeamFileImpl$1.run(BeamFileImpl.java:607)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.java:605)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:125)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.java:156)
	at org.elixir_lang.Reference.forEachNavigationElement(Reference.java:59)
	at org.elixir_lang.Reference.forEachNavigationElement(Reference.java:41)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImports(CallDefinitionClause.kt:113)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:97)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:32)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:77)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:572)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:168)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1162)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:65)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:62)
	at org.elixir_lang.reference.resolver.Callable.resolveElement(Callable.kt:52)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:22)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:14)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:155)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:227)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:205)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:155)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:170)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:163)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:851)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:106)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:98)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:338)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:271)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:214)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
![image](https://user-images.githubusercontent.com/225131/104090275-b3d90c80-52b0-11eb-971d-c9c47a84579b.png)

**Desktop:**
 - OS: Ubuntu 20.10

**Erlang:**
- Installer: asdf
- Version: 23.1.5

**Elixir:**
- Installer asdf
- Version 1.11.2

**Plugin:**
- Version: 11.9.0

**Additional context**
Thanks for such an awesome plugin <3

**Comment by KronicDeth** [comment]
I'm seeing the same.  The better decompilation in #1834 broke the correspondence needed between the binary and decompiled call definitions, probably because for some modules, the `DbgI` is slightly full of lies and does not include all the functions in the binary code chunk.

**Comment by KronicDeth** [comment]
The attached build has a first pass fix to stop the mirror error by matching the binary stub and the decompiled source by not assuming they match 1-to-1, in-order as before, but by assuming the binary stubs as the source of truth and checking if there is a source call definition with the same name and arity.  Give it a try and report what happens for you.

[intellij-elixir-11.9.1-pre+20210113040732.zip](https://github.com/KronicDeth/intellij-elixir/files/5806328/intellij-elixir-11.9.1-pre%2B20210113040732.zip)


This is temporary, as it is not a full fix because I realized part of the problem is that the decompiled code now contains default arguments, so unlike in the original assumption that the decompiled source can now have an single arity doesn't hold and instead an arity range (like in human-written source) is possible.

**Comment by joshuataylor** [comment]
I've been using the above build for a couple of hours and no errors or breaking has occurred so far.
