### ISSUE TITLE
Cannot create class org.elixir_lang.facet.Type

### ISSUE THREAD

**Issue by Deni7777** [KronicDeth/intellij-elixir#1873]
# Version

11.9.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
com.intellij.diagnostic.PluginException: Cannot create class org.elixir_lang.facet.Type [Plugin: org.elixir_lang]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:652)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.instantiateClass(ExtensionComponentAdapter.java:54)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:132)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:45)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:68)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:446)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:433)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.access$100(ExtensionPointImpl.java:38)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$1.next(ExtensionPointImpl.java:336)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:18)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.facet.impl.FacetTypeRegistryImpl.loadExtensions(FacetTypeRegistryImpl.kt:146)
	at com.intellij.facet.impl.FacetTypeRegistryImpl.findFacetType(FacetTypeRegistryImpl.kt:124)
	at com.intellij.facet.ui.FacetDependentToolWindow.lambda$getFacetTypes$0(FacetDependentTool

**Comment by KronicDeth** [comment]
@Deni7777 which IDE and version of that IDE are you running?

**Comment by sh41** [comment]
Sorry for the long silence on this.

`PluginException: Cannot create class …` is the platform's wrapper around whatever actually threw while it was constructing the facet type. The real cause is on the `Caused by:` line, and the trace pasted here is cut off before it. `Type`'s constructor takes no arguments and has not changed since 11.9.0, so there is nothing in the class itself that explains the failure. Closing as not actionable as filed.

If you still hit this, please reopen with the full trace including every `Caused by:` section — the untruncated copy is in `idea.log` (Help | Show Log in Explorer/Finder) — and your IDE version plus the other plugins you had installed. The failing call enumerates every installed plugin's facet types, so the trigger may not be Elixir's.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
