### ISSUE TITLE
 Read access is allowed from event dispatch thread or inside read-action only at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:173)

### ISSUE THREAD

**Issue by mjaow** [KronicDeth/intellij-elixir#1900]
# Version

11.9.2

# What I was doing

After install elixir plugin in goland, it report this error

# Exceptions

### Stacktrace

```
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1013)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.getSortedModules(ModuleManagerImpl.java:586)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.getContentRootsFromAllModules(ProjectRootManagerImpl.java:183)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:173)
	at org.elixir_lang.mix.project.DirectoryConfigurator$configureRootOtpApp$2.run(DirectoryConfigurator.kt:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sh41** [comment]
Fixed. `DirectoryConfigurator` spawned its own background task to sync dependencies, and that task
called `DepsWatcher.syncLibraries`, which read the project's content roots without holding a read
action — which is the assertion in your trace.

`f4e399504` removed that background task and replaced `DepsWatcher` with a coroutine pipeline,
`MixDepsSyncService`. The configurator now just queues a sync request; the equivalent read of content
roots and modules happens inside `SyncPlanBuilder`, inside a read action. First released in 24.0.0.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
