### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by altuntasfatih** [KronicDeth/intellij-elixir#1927]
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
com.intellij.util.indexing.impl.MapReduceIndex$MapInputException: Failed to map data for input 1889414 for index Trigram.Index
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:232)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.updateBaseIndex(MergedInvertedIndex.java:328)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.mapInputAndPrepareUpdate(MergedInvertedIndex.java:116)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.mapInputAndPrepareUpdate(MergedInvertedIndex.java:38)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1476)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1358)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:555)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1328)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1255)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1216)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1544)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1541)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:64)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:33)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1563)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:727)
	at com.intellij.psi.stubs.StubIndexImpl.processAllKeys(StubIndexImpl.java:423)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:66)
	at com.intellij.psi.stubs.StubIndexImpl.getAllKeys(StubIndexImpl.java:411)
	at org.elixir_lang.navigation.ChooseByNameContributor.getNames(ChooseByNameContributor.kt:244)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:127)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:86)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:80)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:25)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$0(JobLauncherImpl.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:50)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/fatih.altuntas/Library/Caches/JetBrains/IntelliJIdea2020.3/index/.persistent/trigram.index/values
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:165)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:46)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:226)
	... 43 more
Caused by: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/fatih.altuntas/Library/Caches/JetBrains/IntelliJIdea2020.3/index/.persistent/trigram.index/values
	at com.intellij.util.io.PersistentBTreeEnumerator.getNonNegativeValue(PersistentBTreeEnumerator.java:310)
	at com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:626)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:602)
	at com.intellij.util.indexing.impl.forward.PersistentMapBasedForwardIndex.get(PersistentMapBasedForwardIndex.java:37)
	at com.intellij.util.indexing.snapshot.SnapshotInputMappings.readContents(SnapshotInputMappings.java:292)
	at com.intellij.util.indexing.snapshot.SnapshotInputMappings.doReadData(SnapshotInputMappings.java:134)
	at com.intellij.util.indexing.snapshot.SnapshotInputMappings.readData(SnapshotInputMappings.java:103)
	at com.intellij.util.indexing.snapshot.SnapshotInputMappings.readData(SnapshotInputMappings.java:32)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:157)
	... 45 more
Caused by: java.lang.IllegalStateException: Index corrupted
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.hashIndex(IntToIntBtree.java:1106)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.search(IntToIntBtree.java:421)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.locate(IntToIntBtree.java:992)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.access$000(IntToIntBtree.java:404)
	at com.intellij.util.io.IntToIntBtree.get(IntToIntBtree.java:195)
	at com.intellij.util.io.PersistentBTreeEnumerator.getNonNegativeValue(PersistentBTreeEnumerator.java:302)
	... 53 more
```

**Comment by ethan-tqa** [comment]
Are you using IntelliJ 2011? Try rolling back to 2020.3.3

**Comment by KronicDeth** [comment]
I think you need to file this with JetBrains.  There shouldn't be any way for my code using this API to break it in this way without it being a bug in the library.
