### ISSUE TITLE
com.ericsson.otp.erlang.OtpErlangExit: timeout when starting debugger

### ISSUE THREAD

**Issue by kapoc3** [KronicDeth/intellij-elixir#1929]
# Version

11.10.0

# What I was doing

im try to configure my debugger

# Exceptions

### Stacktrace

```
com.ericsson.otp.erlang.OtpErlangExit: timeout
	at org.elixir_lang.MailBox.wait(MailBox.kt:205)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KronicDeth** [comment]
Some users report having the start the debugger twice to get it to attach.

If the debugger Console tab shows modules being interpreted, then the Elixir-side of the debugger is taking over a minute to interpret all the modules in your project and so the IDE plugin-side counts it as a timeout.  If this is the case, you can [ignore some of the modules from being interpreted](https://github.com/KronicDeth/intellij-elixir#excluding-modules) to speed up the launching.
