### ISSUE TITLE
OtpErlangExit timeout at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)

### ISSUE THREAD

**Issue by ssbais22** [KronicDeth/intellij-elixir#1932]
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
com.ericsson.otp.erlang.OtpErlangExit: timeout
	at org.elixir_lang.MailBox.wait(MailBox.kt:205)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:340)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:73)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:377)
	at org.elixir_lang.debugger.Process.access$runInitializers(Process.kt:73)
	at org.elixir_lang.debugger.Process$asyncRunInitializers$1.run(Process.kt:359)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sh41** [comment]
Closing as a duplicate of #2715, which has the fuller diagnosis.

This trace is the 60 second timeout expiring on the `interpret` step during session start-up. That
timeout is hard-coded and exposed by no setting, and because start-up abandons its remaining steps when
one raises, `attach` never runs afterwards — so the session can hang rather than report anything. #2715
covers both halves.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
