### ISSUE TITLE
Don't know if Mix.Dep option `warn_missing` is important for determining location of dependency

### ISSUE THREAD

**Issue by m-bilal-dev4** [KronicDeth/intellij-elixir#1941]
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.Throwable: Don't know if Mix.Dep option `warn_missing` is important for determining location of dependency
	at org.elixir_lang.errorreport.Logger.error(Logger.java:42)
	at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:55)
	at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:34)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:141)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:44)
	at org.elixir_lang.mix.DepGathererKt.access$deps(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:36)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:21)
	at org.elixir_lang.mix.DepGathererKt.foldDepsDefinersWhile(DepGatherer.kt:64)
	at org.elixir_lang.mix.DepGathererKt.access$foldDepsDefinersWhile(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer.visitElement(DepGatherer.kt:35)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:750)
	at org.elixir_lang.mix.DepGatherer$visitFile$$inlined$runReadAction$1.compute(actions.kt:58)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:830)
	at org.elixir_lang.mix.DepGatherer.visitFile(DepGatherer.kt:143)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$$inlined$runReadAction$1$lambda$1.compute(Resolution.kt:111)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$$inlined$runReadAction$1.compute(actions.kt:58)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:834)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packagePsiFileToDepSet(Resolution.kt:122)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packageVirtualFileToDepSet(Resolution.kt:97)
	at org.elixir_lang.mix.watcher.Resolution$Companion.rootVirtualFileToDepSet(Resolution.kt:80)
	at org.elixir_lang.mix.watcher.Resolution$Companion.resolution(Resolution.kt:38)
	at org.elixir_lang.mix.watcher.TransitiveResolution.transitiveResolution(TransitiveResolution.kt:17)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:57)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:198)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:181)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:176)
	at org.elixir_lang.DepsWatcher$syncLibraries$$inlined$let$lambda$1.run(DepsWatcher.kt:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KronicDeth** [comment]
`warning_missing` is not a valid option according to `mix help docs`.  I think your code is using an unsupported option. 

```
                                    mix deps

Lists all dependencies and their status.

Dependencies must be specified in the `mix.exs` file in one of the following
formats:

    {app, requirement}
    {app, opts}
    {app, requirement, opts}

Where:

  • app is an atom
  • requirement is a `Version` requirement or a regular expression
  • opts is a keyword list of options

For example:

    {:plug, ">= 0.4.0"}
    {:gettext, git: "https://github.com/elixir-lang/gettext.git", tag: "0.1"}
    {:local_dependency, path: "path/to/local_dependency"}

By default, dependencies are fetched using the Hex package manager
(https://hex.pm/):

    {:plug, ">= 0.4.0"}

By specifying such dependencies, Mix will automatically install Hex (if it
wasn't previously installed) and download a package suitable to your project.
Note Hex expects the dependency requirement to always be given and it will warn
otherwise.

Mix also supports Git and path dependencies:

    {:foobar, git: "https://github.com/elixir-lang/foobar.git", tag: "0.1"}
    {:foobar, path: "path/to/foobar"}

And also in umbrella dependencies:

    {:my_app, in_umbrella: true}

Path and in umbrella dependencies are automatically recompiled by the parent
project whenever they change. While fetchable dependencies, like the ones using
`:git`, are recompiled only when fetched/updated.

The dependencies' versions are expected to be formatted according to Semantic
Versioning and the requirements must be specified as defined in the `Version`
module.

## Options

Below we provide a more detailed look into the available options.

### Dependency definition options

  • `:app` - when set to `false`, does not read the app file for this
    dependency. By default, the app file is read
  • `:env` - the environment (as an atom) to run the dependency on;
    defaults to `:prod`
  • `:compile` - a command (string) to compile the dependency; defaults to
    a `mix`, `rebar` or `make` command
  • `:optional` - marks the dependency as optional. In such cases, the
    current project will always include the optional dependency but any other
    project that depends on the current project won't be forced to use the
    optional dependency. However, if the other project includes the optional
    dependency on its own, the requirements and options specified here will
    also be applied.
  • `:only` - the dependency is made available only in the given
    environments, useful when declaring dev- or test-only dependencies; by
    default the dependency will be available in all environments. The value of
    this option can either be a single environment (like `:dev`) or a list of
    environments (like `[:dev, :test]`)
  • `:targets` - the dependency is made available only for the given
    targets. By default the dependency will be available in all environments.
    The value of this option can either be a single target (like `:host`) or a
    list of environments (like `[:host, :rpi3]`)
  • `:override` - if set to `true` the dependency will override any other
    definitions of itself by other dependencies
  • `:manager` - Mix can also compile Rebar, Rebar3 and makefile projects
    and can fetch sub dependencies of Rebar and Rebar3 projects. Mix will try
    to infer the type of project but it can be overridden with this option by
    setting it to `:mix`, `:rebar3`, `:rebar` or `:make`. In case there are
    conflicting definitions, the first manager in the list above will be picked
    up. For example, if a dependency is found with `:rebar3` and `:rebar`
    managers in different part of the trees, `:rebar3` will be automatically
    picked. You can find the manager by running `mix deps` and override it by
    setting the `:override` option in a top-level project.
  • `:runtime` - whether the dependency is part of runtime applications. If
    the `:applications` key is not provided in `def application` in your
    `mix.exs` file, Mix will automatically include all dependencies as a
    runtime application, except if `runtime: false` is given. Defaults to true.
  • `:system_env` - an enumerable of key-value tuples of binaries to be set
    as environment variables when loading or compiling the dependency

### Git options (`:git`)

  • `:git` - the Git repository URI
  • `:github` - a shortcut for specifying Git repos from GitHub, uses
    `:git`
  • `:ref` - the reference to checkout (may be a branch, a commit SHA or a
    tag)
  • `:branch` - the Git branch to checkout
  • `:tag` - the Git tag to checkout
  • `:submodules` - when `true`, initialize submodules for the repo
  • `:sparse` - checkout a single directory inside the Git repository and
    use it as your Mix dependency. Search "sparse Git checkouts" for more
    information.

If your Git repository requires authentication, such as basic username:password
HTTP authentication via URLs, it can be achieved via Git configuration, keeping
the access rules outside of source control.

    git config --global url."https://YOUR_USER:YOUR_PASS@example.com/".insteadOf "https://example.com/"

For more information, see the `git config` documentation:
https://git-scm.com/docs/git-config#git-config-urlltbasegtinsteadOf

### Path options (`:path`)

  • `:path`        - the path for the dependency
  • `:in_umbrella` - when `true`, sets a path dependency pointing to
    "../#{app}", sharing the same environment as the current application

### Hex options (`:hex`)

See the Hex usage documentation (https://hex.pm/docs/usage) for Hex options.

## Deps task

`mix deps` task lists all dependencies in the following format:

    APP VERSION (SCM) (MANAGER)
    [locked at REF]
    STATUS

It supports the following options:

  • `--all` - lists all dependencies, regardless of specified environment
```
