### ISSUE TITLE
ElixirFlexLexer could not match input on "~m{"

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#196]
Whenever I type `~m{` (I have ShortMaps imported that provides this sigil)

```
org.elixir_lang.ElixirFlexLexer: Error: could not match input
java.lang.Error: org.elixir_lang.ElixirFlexLexer: Error: could not match input
	at org.elixir_lang.ElixirFlexLexer.zzScanError(ElixirFlexLexer.java:979)
	at org.elixir_lang.ElixirFlexLexer.advance(ElixirFlexLexer.java:1980)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
	at com.intellij.lexer.FlexAdapter.getTokenStart(FlexAdapter.java:64)
	at com.intellij.lexer.DelegateLexer.getTokenStart(DelegateLexer.java:55)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenEnd(MergingLexerAdapterBase.java:59)
	at com.intellij.lexer.LookAheadLexer.addToken(LookAheadLexer.java:47)
	at com.intellij.lexer.LookAheadLexer.advanceAs(LookAheadLexer.java:176)
	at com.intellij.lexer.LookAheadLexer.advanceLexer(LookAheadLexer.java:172)
	at com.intellij.lexer.LookAheadLexer.lookAhead(LookAheadLexer.java:56)
	at com.intellij.lexer.LookAheadLexer.doLookAhead(LookAheadLexer.java:73)
	at com.intellij.lexer.LookAheadLexer.advance(LookAheadLexer.java:65)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:241)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:795)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:731)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:504)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaretNoScrolling(EditorModificationUtil.java:132)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:97)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:89)
	at com.intellij.openapi.editor.EditorModificationUtil.typeInStringAtCaretHonorBlockSelection(EditorModificationUtil.java:345)
	at com.intellij.codeInsight.editorActions.TypedHandler.type(TypedHandler.java:244)
	at com.intellij.codeInsight.editorActions.TypedHandler.access$100(TypedHandler.java:64)
	at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:208)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:152)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:91)
	at com.intellij.openapi.editor.actionSystem.TypedAction$TypingCommand$1.run(TypedAction.java:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.openapi.editor.actionSystem.TypedAction$TypingCommand.run(TypedAction.java:123)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:107)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1085)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5215)
	at com.intellij.openapi.editor.impl.EditorImpl$10.keyTyped(EditorImpl.java:915)
	at java.awt.Component.processKeyEvent(Component.java:6490)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:539)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
Testing lexing `~m{` I get the `{` tokenizes as `ElixirTypes.SIGIL_PROMOTER` correctly, but instead of transitioning to `ElixirFlexLexer.GROUP` (32) it goes back to `ElixirFlexLexer.YYINITIAL` (0).

I'll post more when I've debugged the transitions.

**Comment by KronicDeth** [comment]
Nope, that was just a test error that I was checking the final state was `ElixirFlexLexer.YYINITIAL` instead of `ElixirFlexLexer.GROUP` because of the test file I copied, so the lexer can lex `~m{` correctly.  This might be some odd interaction with the error recovery in the parser since the parser in some cases resets the lexer, but the stack I use to track interpolation isn't reset in that method.

Testing `~m{` in sandbox plugin next so that the full parser with error recovery will be used.

**Comment by KronicDeth** [comment]
Having ShortMaps imported doesn't affect anything in the plugin.  It's not import aware yet.  All letters in a-z and A-Z are accepted as sigil names by the lexer and parser.

Typing just `~m{` at the beginning of a file doesn't trigger the `could not match error`, so it must be some interaction between `~m{` and the other text in the file.  Do you have the full text of the file where there was no error before you typed `~m{` and the error after you did @Havvy?

**Comment by Havvy** [comment]
Alright, the `m` is a misnomer. I get the error with the following code block. Remove and re-add the `~` if you don't get it.

```
defmodule Test do
  def test (~) do
    nil
  end
end
```

**Comment by KronicDeth** [comment]
```ruby
test ()
```

to

```ruby
test(~)
```

**does not** trigger the error, but

```ruby
def test() do
end
```

to

```ruby
def test(~) do
end
```

**does** trigger the error

**Comment by KronicDeth** [comment]
I have a test that triggers the bug in 79e6636:

| Text | Token                    | New State                  | Match Error |
|------|--------------------------|----------------------------|-------------|
| def  | IDENTIFIER               | CALL_OR_KEYWORD_PAIR_MAYBE | No          |
| ' '  | WHITE_SPACE              | YYINITIAL                  | No          |
| f    | IDENTIFIER               | CALL_OR_KEYWORD_PAIR_MAYBE | No          |
| ' '  | WHITE_SPACE              | YYINITIAL                  | No          |
| (    | OPENING_PARENTHESIS      | YYINITIAL                  | No          |
| ~    | TILDE                    | SIGIL                      | No          |
| )    | BAD_CHARACTER            | SIGIL                      | No          |
| ' '  | BAD_CHARACTER            | SIGIL                      | No          |
| d    | INTERPOLATING_SIGIL_NAME | NAMED_SIGIL                | No          |
| o    | BAD_CHARACTER            | NAMED_SIGIL                | No          |
| \n   |                          |                            | Yes         |

So, the problem is that `EOL`, including `\n` is not matched at all in the `NAMED_SIGIL` state when it's trying to find the promoter (`(`, `{`, `/`, etc).
