### ISSUE TITLE
MissingSdk module in project is missing an Elixir SDK at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.dialyzerWarnings(DialyzerServiceImpl.kt:29)

### ISSUE THREAD

**Issue by marcel862** [KronicDeth/intellij-elixir#1964]
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
org.elixir_lang.mix.MissingSdk: dice-master module in dice-master project is missing an Elixir SDK
	at org.elixir_lang.mix.StateKt.ensureMostSpecificSdk(State.kt:22)
	at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.dialyzerWarnings(DialyzerServiceImpl.kt:29)
	at org.elixir_lang.dialyzer.inspection.Global.dialyzerWarnsByModule(Global.kt:53)
	at org.elixir_lang.dialyzer.inspection.Global.runInspection(Global.kt:23)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runGlobalTools$17(GlobalInspectionContextImpl.java:605)
	at com.intellij.codeInspection.ex.InspectionEventsKt.reportWhenInspectionFinished(inspectionEvents.kt:9)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runGlobalTools$18(GlobalInspectionContextImpl.java:600)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runGlobalTools(GlobalInspectionContextImpl.java:618)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:275)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$4(GlobalInspectionContextBase.java:261)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContex

**Comment by KronicDeth** [comment]
Duplicate of #1923
