### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.elixir_lang.Icons

### ISSUE THREAD

**Issue by lianhj** [KronicDeth/intellij-elixir#1966]
# Exception

## Stacktrace

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.Icons
	at org.elixir_lang.ElixirFileType.getIcon(ElixirFileType.java:40)
	at com.intellij.psi.impl.ElementBase.getBaseIcon(ElementBase.java:119)
	at com.intellij.psi.impl.ElementBase.computeBaseIcon(ElementBase.java:101)
	at com.intellij.psi.impl.ElementBase.lambda$computeIcon$2(ElementBase.java:75)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:75)
	at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:57)
	at org.elixir_lang.psi.ElixirFile.getIcon(ElixirFile.java:44)
	at com.intellij.ide.navigationToolbar.NavBarPresentation.lambda$getIcon$1(NavBarPresentation.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:844)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.ide.navigationToolbar.NavBarPresentation.getIcon(NavBarPresentation.java:81)
	at com.intellij.ide.navigationToolbar.NavBarPanel.isRebuildUiNeeded(NavBarPanel.java:420)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue.rebuildUi(NavBarUpdateQueue.java:177)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$2.lambda$after$0(NavBarUpdateQueue.java:170)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$2.after(NavBarUpdateQueue.java:170)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$AfterModelUpdate.run(NavBarUpdateQueue.java:278)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:148)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2136)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:284)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by KronicDeth** [comment]
This is an odd error report in that it does not show the plugin version.  What version of the plugin are you running?

**Comment by sh41** [comment]
Sorry for the long silence.

`Could not initialize class X` is a secondary failure: `Icons`'s static initializer threw earlier in that session, and every later touch — including `ElixirFileType.getIcon()` here — reports this bare message with no cause. So `Icons` is the victim, not the defect, and the real error was a separate one in the same session that isn't in this report.

`Icons` has thrown that way for one confirmed reason: it referenced `AllIcons.General.Run`, which a newer IDE removed, giving `NoSuchFieldError` — see #1854 and #1654. Fixed in `8b80cfb7d`, released in v11.6.0 on 2020-04-11. A second fragility, the deprecated stack-frame-counting `IconLoader.getIcon(path)`, was still present when you filed and was replaced in `9b3367c0a`, released in v13.0.0; nothing ever tied it to a failure. Today's class has neither.

With no `Caused by:` and no version — the question above was never answered — I can't tell which, if either, you hit. Closing on that basis: the causes we know of are fixed, not that yours was one of them.

If it recurs on a current release, the useful report is the *first* exception in that session, the `ExceptionInInitializerError` with its `Caused by:` chain, from `idea.log` (Help | Show Log in Explorer/Finder).

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
