### ISSUE TITLE
Read access is allowed from event dispatch thread or inside read-action only at org.elixir_lang.psi.impl.PsiNamedElementImpl.getName(PsiNamedElementImpl.kt:21)

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#1975]
# Version

11.11.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:992)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:424)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:224)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:145)
	at org.elixir_lang.psi.impl.PsiNamedElementImpl.getName(PsiNamedElementImpl.kt:21)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getName(ElixirPsiImplUtil.java:1070)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedAliasImpl.getName(ElixirMatchedQualifiedAliasImpl.java:60)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.fullyQualifiedName(QualifiableAliasImpl.kt:119)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyQualifiedName(ElixirPsiImplUtil.java:792)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedAliasImpl.fullyQualifiedName(ElixirMatchedQualifiedAliasImpl.java:55)
	at org.elixir_lang.structure_view.element.modular.Implementation$Companion.protocolName(Implementation.kt:206)
	at org.elixir_lang.structure_view.element.modular.Implementation$Companion.protocolName(Implementation.kt:189)
	at org.elixir_lang.structure_view.element.modular.Implementation$Companion.nameCollection(Implementation.kt:179)
	at org.elixir_lang.structure_view.element.modular.Implementation$Companion.name(Implementation.kt:176)
	at org.elixir_lang.psi.impl.PsiNamedElementImpl.getName(PsiNamedElementImpl.kt:44)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getName(ElixirPsiImplUtil.java:1076)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.getName(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:102)
	at org.elixir_lang.ReferencesSearch.processQuery(ReferencesSearch.java:31)
	at org.elixir_lang.ReferencesSearch.processQuery(ReferencesSearch.java:17)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:77)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:28)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:108)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:39)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:83)
	at com.intellij.find.findUsages.FindUsagesHandlerBase.processElementUsages(FindUsagesHandlerBase.java:76)
	at com.intellij.find.findUsages.FindUsagesManager.lambda$createUsageSearcher$10(FindUsagesManager.java:399)
	at com.intellij.find.findUsages.FindUsagesManager$1.run(FindUsagesManager.java:318)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by odk211** [comment]
I really thank you for this updates! I was looking forward to it! ❤️ 
I applied to my project, and Code completion looks fine! 👍 
But some error is occurred periodically in a specific file. It's troublesome...
I write reproduction procedure in https://github.com/KronicDeth/intellij-elixir/issues/1977 
Please check.

Thanks a lot.
