### ISSUE TITLE
2 times of `use` brakes IDE functions after upgrade plugin to version 11.11.0.

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#1980]
**Describe the bug**
2 times of `use` brakes IDE functions... 😢 
e.g.
```elixir
defmodule WorkTest do
  use ExUnit.Case, async: true
  use Bitwise

  test "test" do
    assert 1 == 1
  end
end
```
brakes

- Code completion
- Live template
- Syntax highlighting

<img width="280" alt="スクリーンショット 2021-06-23 12 12 41" src="https://user-images.githubusercontent.com/1321120/123029596-5549ba00-d41c-11eb-9286-9232fb32e4c7.png">

**Logs**
```
java.lang.StackOverflowError
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:58)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:86)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:81)
	at com.intellij.psi.impl.source.tree.AstBufferUtil$BufferVisitor.visitComposite(AstBufferUtil.java:96)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:117)
	at com.intellij.psi.impl.source.tree.AstBufferUtil.toBuffer(AstBufferUtil.java:22)
	at com.intellij.psi.impl.source.tree.AstBufferUtil.toBuffer(AstBufferUtil.java:17)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:230)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:145)
	at org.elixir_lang.psi.impl.call.CallImpl.functionName$lambda-1$lambda-0(CallImpl.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:830)
	at org.elixir_lang.mix.project.OtpAppKt.computeReadAction(OtpApp.kt:73)
	at org.elixir_lang.psi.impl.call.CallImpl.functionName(CallImpl.kt:349)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionName(ElixirPsiImplUtil.java:798)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.functionName(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:82)
	at org.elixir_lang.psi.impl.call.CallImpl.isCalling(CallImpl.kt:427)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCalling(ElixirPsiImplUtil.java:229)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.isCalling(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:122)
	at org.elixir_lang.psi.impl.call.CallImpl.isCalling(CallImpl.kt:450)
```

**Desktop:**
 - OS: macOS Catalina
 - Version 10.15.7

**Erlang:**
- Installer asdf
- erlang 22.0.7

**Elixir:**
- Installer asdf
- elixir 1.10.3-otp-22

**Plugin:**
- Version 11.11.0

**Comment by KronicDeth** [comment]
The test fix I added to make sure that lexically nested modules could be resolved with their relative names broke this.
