### ISSUE TITLE
Don't know if Mix.Dep option `repo` is important for determining location of dependency

### ISSUE THREAD

**Issue by simonmcconnell** [KronicDeth/intellij-elixir#1983]
# Version

11.11.0

# What I was doing

Can't handle custom hex repo?  Oban Pro uses a private hex repo. See its [docs](https://hexdocs.pm/oban/pro_installation.html).

# Exceptions

### Stacktrace

```
java.lang.Throwable: Don't know if Mix.Dep option `repo` is important for determining location of dependency
	at org.elixir_lang.errorreport.Logger.error(Logger.java:42)
	at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:55)
	at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:34)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:141)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:44)
	at org.elixir_lang.mix.DepGathererKt.access$deps(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:36)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:35)
	at org.elixir_lang.mix.DepGathererKt.foldDepsDefinersWhile(DepGatherer.kt:64)
	at org.elixir_lang.mix.DepGathererKt.access$foldDepsDefinersWhile(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer.visitElement(DepGatherer.kt:35)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:39)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:750)
	at org.elixir_lang.mix.DepGatherer$visitFile$$inlined$runReadAction$1.compute(actions.kt:61)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:830)
	at org.elixir_lang.mix.DepGatherer.visitFile(DepGatherer.kt:143)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$1$1.compute(Resolution.kt:111)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$$inlined$runReadAction$1.compute(actions.kt:61)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:834)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packagePsiFileToDepSet(Resolution.kt:122)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packageVirtualFileToDepSet(Resolution.kt:97)
	at org.elixir_lang.mix.watcher.Resolution$Companion.rootVirtualFileToDepSet(Resolution.kt:80)
	at org.elixir_lang.mix.watcher.Resolution$Companion.resolution(Resolution.kt:38)
	at org.elixir_lang.mix.watcher.TransitiveResolution.transitiveResolution(TransitiveResolution.kt:17)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:57)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:198)
	at org.elixir_lang.DepsWatcher.syncLibrary(DepsWatcher.kt:179)
	at org.elixir_lang.DepsWatcher.access$syncLibrary(DepsWatcher.kt:32)
	at org.elixir_lang.DepsWatcher$fileCreated$1$3.run(DepsWatcher.kt:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KronicDeth** [comment]
The dep will be handled fine because the accumulated Dep is returned when the error is logged.  These errors are to alert me if a new option _might_ change the path on the file system for the dep, but repo doesn’t.  It will work fine for you, I just need to add repo to the ignore list in Dep.my.
