### ISSUE TITLE
version 1.2.0 breaks rename feature

### ISSUE THREAD

**Issue by leiyangyou** [KronicDeth/intellij-elixir#199]
With the exception

 IllegalStateException: @NotNull method org/elixir_lang/FindUsagesProvider.getDescriptiveName must not return null

**Comment by chris-martin** [comment]
Same thing when trying to delete an elixir file.

```
@NotNull method org/elixir_lang/FindUsagesProvider.getDescriptiveName must not return null
java.lang.IllegalStateException: @NotNull method org/elixir_lang/FindUsagesProvider.getDescriptiveName must not return null
	at org.elixir_lang.FindUsagesProvider.getDescriptiveName(FindUsagesProvider.java:120)
	at com.intellij.lang.findUsages.DescriptiveNameUtil.getDescriptiveName(DescriptiveNameUtil.java:46)
	at com.intellij.refactoring.util.RefactoringUIUtil.calculatePsiElementDescriptionList(RefactoringUIUtil.java:66)
	at com.intellij.ide.util.DeleteHandler.deletePsiElement(DeleteHandler.java:188)
	at com.intellij.ide.util.DeleteHandler.deletePsiElement(DeleteHandler.java:111)
	at com.intellij.ide.projectView.impl.ProjectViewImpl$MyDeletePSIElementProvider.deleteElement(ProjectViewImpl.java:940)
	at com.intellij.ide.actions.DeleteAction.actionPerformed(DeleteAction.java:42)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:483)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
I guess FindUsageProvider is used everywhere to supply human-readable names.  Good thing I used `@NotNull` and default `null` return so I could catch all these uses I didn't know about.

I probably should open a PR against [Jetbrains/intellij-community](https://github.com/JetBrains/intellij-community) to add to the javadocs for [`com.intellij.lang.findUsages.FindUsagesProvider`](https://github.com/JetBrains/intellij-community/blob/master/platform/indexing-api/src/com/intellij/lang/findUsages/FindUsagesProvider.java) to say that it's used for more than Find Usage.  Looks like it gets triggered because it's trying to do safe rename/delete and so going through the refactoring system, which of course does a Find Usage.  So, when I trace it out, that makes sense, but not obvious enough that I new this would break.
