### ISSUE TITLE
No decompiled source function with name (Pricing.Securities.-signoff_security/2-fun-0-)

### ISSUE THREAD

**Issue by suryatejamuthyala** [KronicDeth/intellij-elixir#2004]
# Version

11.12.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.Throwable: No decompiled source function with name (Pricing.Securities.-signoff_security/2-fun-0-)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:70)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:411)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda-6$lambda-5(BeamFileImpl.kt:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:391)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.kt:65)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByName(ChooseByNameContributor.kt:61)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.lambda$getElementsByName$5(ContributorsBasedGotoByModel.java:206)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:814)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:149)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:45)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.getElementsByName(ContributorsBasedGotoByModel.java:235)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.processByNames(DefaultChooseByNameItemProvider.java:263)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:126)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.lambda$filterElementsWithWeights$3(DefaultChooseByNameItemProvider.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElementsWithWeights(DefaultChooseByNameItemProvider.java:83)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$4(AbstractGotoSEContributor.java:284)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchWeightedElements(AbstractGotoSEContributor.java:310)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KronicDeth** [comment]
The decompiler already handles the `fun` functions in general, so there must be something special about this name.

**Comment by suryatejamuthyala** [comment]
Sure will check that 

Thanks & Regards
Surya Teja Muthyala
+17164231296
***@***.***
https://www.linkedin.com/in/suryatejamuthyala/

This e-mail communication (including any attachments) may contain confidential information intended solely for the use of the intended recipient. If you are not the intended recipient, you should immediately stop reading this message and delete it from your system. Any unauthorized reading, distribution, copying or other use of this communication (or its attachments) is strictly prohibited.

**Comment by KronicDeth** [comment]
@suryatejamuthyala sorry, that comment was a note for myself.  You don't need to check anything.  

If you have the `.beam` file `Elixir.Pricing.Securities.beam` that I can use as a test file that would be helpful though, so I don't need to reproduce a test case myself.

**Comment by suryatejamuthyala** [comment]
Please find below

`# Source code recreated from a .beam file by IntelliJ Elixir
defmodule Pricing.Securities do
  @moduledoc ~S"""
  BQSecurity context

  """

  # Functions

  def __info__(p0) do
    # body not decompiled
  end

  def add_new_details(user, new_work_date, from_work_date) do
    # body not decompiled
  end

  def add_new_details_subset(user, new_work_date, from_work_date) do
    # body not decompiled
  end

  def add_percent_change(s) do
    # body not decompiled
  end

  def add_securities(user, work_date, sec_summaries, subset?) do
    # body not decompiled
  end

  def add_security(attrs, user, work_date, subset?) do
    # body not decompiled
  end

  def base_query() do
    # body not decompiled
  end

  def base_query_valid() do
    # body not decompiled
  end

  def broadcast(error, event) do
    # body not decompiled
  end

  def build_security_from_sum_master(summary, master, user, work_date, subset?) do
    # body not decompiled
  end

  def calcDummySmsecId(map) do
    # body not decompiled
  end

  def change_security(p0) do
    # body not decompiled
  end

  def change_security(security, attrs \\ %{}) do
    # body not decompiled
  end

  def count_bq_details(criteria) do
    # body not decompiled
  end

  def delete_by_work_date(work_date) do
    # body not decompiled
  end

  def delete_security(security) do
    # body not decompiled
  end

  def dummySmsecId(ids) do
    # body not decompiled
  end

  def getNextDummySmsecId() do
    # body not decompiled
  end

  def get_detail_by_work_date(work_date) do
    # body not decompiled
  end

  def get_security(id) do
    # body not decompiled
  end

  def get_security!(id) do
    # body not decompiled
  end

  def insert_securities(sum_securities, user, work_date, subset?) do
    # body not decompiled
  end

  def list_bq_details(criteria) do
    # body not decompiled
  end

  def module_info() do
    # body not decompiled
  end

  def module_info(p0) do
    # body not decompiled
  end

  def normalize_add_input(add_form) do
    # body not decompiled
  end

  def normalize_signoff_params(user, params) do
    # body not decompiled
  end

  def normalize_update_params(user, params) do
    # body not decompiled
  end

  def query_bq_details_for_criteria(criteria) do
    # body not decompiled
  end

  def query_by_bqsecurityids(query, ids) do
    # body not decompiled
  end

  def query_by_smsec_ids(query, ids) do
    # body not decompiled
  end

  def query_by_work_date(query, work_date) do
    # body not decompiled
  end

  def query_for_subset(query, bool) do
    # body not decompiled
  end

  def query_instrtype_signoff(query) do
    # body not decompiled
  end

  def query_instrtype_signoff_highvol(query) do
    # body not decompiled
  end

  def query_non_subset(query) do
    # body not decompiled
  end

  def query_non_subset_order_by(query) do
    # body not decompiled
  end

  def query_order_signoff(query) do
    # body not decompiled
  end

  def query_order_signoff_highvol(query) do
    # body not decompiled
  end

  def query_security_highvol(work_date) do
    # body not decompiled
  end

  def query_select_details_for_new_worksheet(new_work_date, from_work_date) do
    # body not decompiled
  end

  def query_status_equals(query, status) do
    # body not decompiled
  end

  def query_status_in(query, statuses) do
    # body not decompiled
  end

  def query_status_not_2(query) do
    # body not decompiled
  end

  def query_subset(query) do
    # body not decompiled
  end

  def query_subset_order_by(query) do
    # body not decompiled
  end

  def signoff_highvol_all(user, work_date) do
    # body not decompiled
  end

  def signoff_security(security, attrs) do
    # body not decompiled
  end

  def signoff_security_highvol(security, attrs) do
    # body not decompiled
  end

  def signoff_success(arg1) do
    # body not decompiled
  end

  def split_by_deleted(sec_summaries, work_date, subset?) do
    # body not decompiled
  end

  def split_by_existing_securities(sec_summaries, work_date, subset?) do
    # body not decompiled
  end

  def str_subset(bool) do
    # body not decompiled
  end

  def subscribe() do
    # body not decompiled
  end

  def undelete_insert_securities(deleted_summaries, new_summaries, user, work_date, subset?) do
    # body not decompiled
  end

  def undelete_securities(sec_summaries, user, work_date, subset?) do
    # body not decompiled
  end

  def update_calculated_fields(error) do
    # body not decompiled
  end

  def update_security(security, attrs) do
    # body not decompiled
  end

  def validate_add_input(add_form) do
    # body not decompiled
  end

  # Private Functions

  defp unquote(:"-add_securities/4-fun-0-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-add_securities/4-fun-1-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-build_security_log/2-fun-0-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-empty_value_in_params/2-fun-0-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-insert_securities/4-fun-0-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-insert_securities/4-fun-1-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-insert_securities/4-fun-2-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-insert_securities/4-fun-3-")(p0, p1, p2, p3, p4) do
    # body not decompiled
  end

  defp unquote(:"-insert_securities/4-fun-4-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-list_bq_details/1-fun-0-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-normalize_nillable_params/2-fun-0-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-query_bq_details_for_criteria/1-fun-0-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-signoff_highvol_all/2-fun-0-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-signoff_highvol_all/2-fun-1-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-signoff_highvol_all/2-fun-2-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-signoff_highvol_all/2-fun-3-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-signoff_highvol_all/2-fun-4-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-signoff_security_core/2-fun-0-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-split_by_deleted/3-fun-0-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-split_by_deleted/3-fun-1-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-split_by_deleted/3-fun-2-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-split_by_existing_securities/3-fun-0-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-split_by_existing_securities/3-fun-1-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-split_by_existing_securities/3-fun-2-")(p0, p1) do
    # body not decompiled
  end

  defp unquote(:"-undelete_insert_securities/5-fun-0-")(p0, p1, p2, p3, p4) do
    # body not decompiled
  end

  defp unquote(:"-undelete_securities/4-fun-0-")(p0) do
    # body not decompiled
  end

  defp unquote(:"-undelete_securities/4-fun-1-")(p0) do
    # body not decompiled
  end

  defp add_details_or_subset(p0, p1, p2, p3) do
    # body not decompiled
  end

  defp build_security_log(p0, p1) do
    # body not decompiled
  end

  defp cusip_or_security_name(p0) do
    # body not decompiled
  end

  defp empty_value_in_params(p0, p1) do
    # body not decompiled
  end

  defp log_for_existing(p0) do
    # body not decompiled
  end

  defp log_for_new(p0) do
    # body not decompiled
  end

  defp log_for_undeleted(p0) do
    # body not decompiled
  end

  defp normalize_nillable_params(p0, p1) do
    # body not decompiled
  end

  defp signoff_security_core(p0, p1) do
    # body not decompiled
  end
end
`

**Comment by KronicDeth** [comment]
@ suryatejamuthyala  I need the the `.beam` file, not the text that was decompiled in correctly.  Please take the `Elixir.Pricing.Securities.beam `, zip the file, then attach the zip as an attachment to a comment here.

**Comment by suryatejamuthyala** [comment]
> @ suryatejamuthyala I need the the `.beam` file, not the text that was decompiled in correctly. Please take the `Elixir.Pricing.Securities.beam `, zip the file, then attach the zip as an attachment to a comment here.

Please find attached
[Elixir.Pricing.Securities.beam.zip](https://github.com/KronicDeth/intellij-elixir/files/7816990/Elixir.Pricing.Securities.beam.zip)

**Comment by KronicDeth** [comment]
Thanks @suryatejamuthyala.   I can't reproduce this on `main`. I can't build 11.12.0 to confirm that though because it uses BinTray and that was taken offline by JFrog in May.  You opened this bug against 11.12.0 when that was current, so likely one of the many decompiler changes since then fixed the orignal bug.

Please upgrade to the latest version of the plugin, 12.0.1, to see if the problem is fixed for you too. 

We'll reopen if you're still having the issue.
