### ISSUE TITLE
NotImplementedError at org.elixir_lang.structure_view.element.CallDefinitionClause$Companion.time(CallDefinitionClause.kt:197)

### ISSUE THREAD

**Issue by rahulkoo** [KronicDeth/intellij-elixir#2009]
# Version

11.12.0

# What I was doing

Writing some elixir code.

# Exceptions

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented: Should not happen
	at org.elixir_lang.structure_view.element.CallDefinitionClause$Companion.time(CallDefinitionClause.kt:197)
	at org.elixir_lang.structure_view.element.CallDefinition$Companion.fromCall(CallDefinition.kt:243)
	at org.elixir_lang.structure_view.element.CallDefinitionClause$Companion.fromCall(CallDefinitionClause.kt:220)
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderCallDefinitionClause(CallDefinitionClause.java:60)
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderCall(CallDefinitionClause.java:54)
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderPsiElement(CallDefinitionClause.java:118)
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderElement(CallDefinitionClause.java:44)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:404)
	at com.intellij.codeInsight.lookup.LookupElementPresentation.renderElement(LookupElementPresentation.java:223)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:272)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$addItemToLookup$4(CompletionProgressIndicator.java:457)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:163)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:574)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:162)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItemToLookup(CompletionProgressIndicator.java:456)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:446)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$flushBatchResult$2(CompletionThreading.java:162)
	at com.intellij.codeInsight.completion.BaseCompletionLookupArranger.batchUpdate(BaseCompletionLookupArranger.java:194)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.withSingleUpdate(CompletionProgressIndicator.java:368)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$flushBatchResult$3(CompletionThreading.java:160)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$flushBatchResult$4(CompletionThreading.java:159)
	at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:113)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KronicDeth** [comment]
I need to log more context when this fails as I don't even have the macro defining the clause from this log.
