### ISSUE TITLE
org.elixir_lang.mix.MissingSdk at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.dialyzerWarnings(DialyzerServiceImpl.kt:29)

### ISSUE THREAD

**Issue by mithenji** [KronicDeth/intellij-elixir#2021]
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
org.elixir_lang.mix.MissingSdk: beeline_miniprograms module in beeline_miniprograms project is missing an Elixir SDK
	at org.elixir_lang.mix.StateKt.ensureMostSpecificSdk(State.kt:22)
	at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.dialyzerWarnings(DialyzerServiceImpl.kt:29)
	at org.elixir_lang.dialyzer.inspection.Global.dialyzerWarnsByModule(Global.kt:53)
	at org.elixir_lang.dialyzer.inspection.Global.runInspection(Global.kt:23)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runGlobalTools$17(GlobalInspectionContextImpl.java:605)
	at com.intellij.codeInspection.ex.InspectionEventsKt.reportWhenInspectionFinished(inspectionEvents.kt:9)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runGlobalTools$18(GlobalInspectionContextImpl.java:600)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runGlobalTools(GlobalInspectionContextImpl.java:618)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:275)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$4(GlobalInspectionContextBase.java:261)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:261)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:214)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sh41** [comment]
Fixed in v11.12.0, released 2021-07-01 — three weeks before this was filed. The report names plugin version 11.10.0, so the build that crashed predates the fix; updating the plugin is all this needs.

The Dialyzer global inspection collected every module the files in its scope belonged to and asked each one for its SDK through `ensureMostSpecificSdk`, which throws `MissingSdk` when a module has none. Nothing guarded that, so a single module without an Elixir SDK anywhere in scope aborted the whole inspection — which is why it can fire while you are working in a project that isn't Elixir at all. aee22be6d ("Don't error if SDK not setup for module in Dialyzer") took `DialyzerServiceImpl` off that call: no SDK now means no warnings for that module rather than an exception. a33144b19 later moved the lookup into a read action and routed the missing-SDK case to a notification, shipped in 24.0.0.

#2028, #2030, #2031 and #2032 are the same crash from other reporters and close alongside this one.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
