### ISSUE TITLE
IndexOutOfBoundsException at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:160)

### ISSUE THREAD

**Issue by yordis** [KronicDeth/intellij-elixir#2050]
# Version

11.13.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.IndexOutOfBoundsException: Wrong offset: 1085. Should be in range: [0, 1077]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:166)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1005)
	at org.elixir_lang.errorreport.Logger.excerpt(Logger.java:95)
	at org.elixir_lang.errorreport.Logger.message(Logger.java:109)
	at org.elixir_lang.errorreport.Logger.error(Logger.java:44)
	at org.elixir_lang.errorreport.Logger.error(Logger.java:28)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:160)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:135)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.fullyQualifiedName(QualifiableAliasImpl.kt:119)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyQualifiedName(ElixirPsiImplUtil.java:787)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.fullyQualifiedName(ElixirAliasImpl.java:37)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation.getPresentableText(ItemPresentation.kt:58)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation.access$getPresentableText(ItemPresentation.kt:16)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation$_presentableText$2.invoke(ItemPresentation.kt:28)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation$_presentableText$2.invoke(ItemPresentation.kt:25)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation.get_presentableText(ItemPresentation.kt:25)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation.getPresentableText(ItemPresentation.kt:19)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.update(PsiElement2UsageTargetAdapter.java:279)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:63)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:68)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:90)
	at org.elixir_lang.UsageTargetProvider.getTargets(UsageTargetProvider.kt:29)
	at org.elixir_lang.UsageTargetProvider.getTargets(UsageTargetProvider.kt:22)
	at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:42)
	at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:27)
	at com.intellij.ide.impl.dataRules.UsageTargetsRule.getData(UsageTargetsRule.java:13)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRule$4(DataManagerImpl.java:116)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:73)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:126)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.ensureSlowDataKeysPreCached(ActionUpdater.java:344)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:273)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$16(ActionUpdater.java:298)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$17(ActionUpdater.java:295)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$18(ActionUpdater.java:294)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$19(ActionUpdater.java:292)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sh41** [comment]
Two separate defects are stacked here, and the crash is not the one in the title.

**The trigger.** `QualifiableAliasImpl.prependQualifiers` walks up from an alias to build its fully-qualified name, and met an ancestor shape it does not handle. That case is deliberate — it logs "Don't know how to prepend qualifier" and carries on with a placeholder. Same trigger as #2414, #2468 and #3658.

**The crash.** Building that log message is what threw. `errorreport.Logger.excerpt` asks the document for the line numbers of the element's text range without checking those offsets against the document's current length, so a range that has gone stale relative to the document throws. The error reporter crashed while reporting an error — which is why this report cannot say what you were editing. That code is unchanged since 9feaff3dc (2016) and sits in the path shared by every plugin diagnostic that points at a source element, so it is not specific to aliases.

To rule one thing out: #2179, in v12.0.0, fixed a different branch of the same function — a null qualifier that used to throw `NotImplementedError`. It does not touch the branch your trace goes through.

Keeping this open as the tracker for the reporting-path crash; it is the only report of it. The fix is a bounds check, and nothing is in flight yet.

> This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
