### ISSUE TITLE
Cannot highlight types at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1050)

### ISSUE THREAD

**Issue by yordis** [KronicDeth/intellij-elixir#2052]
# Version

11.13.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.Throwable: Cannot highlight types
	at org.elixir_lang.errorreport.Logger.error(Logger.java:42)
	at org.elixir_lang.errorreport.Logger.error(Logger.java:28)
	at org.elixir_lang.annotator.ModuleAttribute.error(ModuleAttribute.kt:123)
	at org.elixir_lang.annotator.ModuleAttribute.cannotHighlightTypes(ModuleAttribute.kt:119)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1050)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1062)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1194)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1025)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1062)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1173)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1017)
	at org.elixir_lang.annotator.ModuleAttribute.highlightSpecification(ModuleAttribute.kt:549)
	at org.elixir_lang.annotator.ModuleAttribute.highlightSpecification(ModuleAttribute.kt:209)
	at org.elixir_lang.annotator.ModuleAttribute.access$highlightSpecification(ModuleAttribute.kt:31)
	at org.elixir_lang.annotator.ModuleAttribute$annotate$1.visitDeclaration(ModuleAttribute.kt:88)
	at org.elixir_lang.annotator.ModuleAttribute$annotate$1.visitElement(ModuleAttribute.kt:61)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:40)
	at org.elixir_lang.annotator.ModuleAttribute.annotate(ModuleAttribute.kt:47)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:134)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:114)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by KronicDeth** [comment]
Not enough context to determine the problematic element
