### ISSUE TITLE
null cannot be cast to non-null type org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:34)

### ISSUE THREAD

**Issue by Koziolek** [KronicDeth/intellij-elixir#2145]
# Version

11.13.0

Elixir 1.12.2
Erlang 24.0.5
IntelliJ 2021.2 on Java OpenJDK 11.0.11

# What I was doing

1. Create new phoenix project in command line
2. Open IntelliJ
3. Old, java, project loaded
4. Import new project from sources – select my new project
5. open new project in new window
6. get error indicator 

# Exceptions

### Stacktrace

```
kotlin.TypeCastException: null cannot be cast to non-null type org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:34)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.mix.project._import.step.Root$1.run(Root.java:80)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by octotherp** [comment]
I'm getting this error on fresh install of intellij community edition, new elixir project, on any mix/iex run.
This renders this plugin useless IMO.
Getting back to emacs, see you in another 20 years.

**Comment by KronicDeth** [comment]
@Koziolek, @octotherp are you getting the error even though you have your Elixir and Erlang SDK set in the Project Structure?

**Comment by KronicDeth** [comment]
Too long without feedback
