### ISSUE TITLE
NullPointerException getting Call.finalArguments() at org.elixir_lang.psi.impl.call.CallImplKt.finalArguments(CallImpl.kt:145)

### ISSUE THREAD

**Issue by digitsu** [KronicDeth/intellij-elixir#2159]
# Version

11.13.0

# What I was doing

entered a newline at the bottom of a test .exs file, just before the second last 'end'

# Exceptions

### Stacktrace

```
java.lang.Throwable: NullPointerException getting Call.finalArguments()
	at org.elixir_lang.errorreport.Logger.error(Logger.java:42)
	at org.elixir_lang.errorreport.Logger.error(Logger.java:28)
	at org.elixir_lang.psi.impl.call.CallImplKt.finalArguments(CallImpl.kt:145)
	at org.elixir_lang.psi.impl.call.CallImplKt.keywordArguments(CallImpl.kt:171)
	at org.elixir_lang.psi.impl.call.CallImplKt.keywordArgument(CallImpl.kt:162)
	at org.elixir_lang.psi.impl.call.CallImpl.hasDoBlockOrKeyword(CallImpl.kt:406)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasDoBlockOrKeyword(ElixirPsiImplUtil.java:1182)
	at org.elixir_lang.psi.impl.ElixirUnmatchedGreaterThanOrEqualToOnePointSixCaptureNonNumericOperationImpl.hasDoBlockOrKeyword(ElixirUnmatchedGreaterThanOrEqualToOnePointSixCaptureNonNumericOperationImpl.java:79)
	at org.elixir_lang.structure_view.element.modular.Unknown$Companion.is(Unknown.kt:26)
	at org.elixir_lang.structure_view.element.modular.Module$Companion.childCallTreeElements(Module.kt:173)
	at org.elixir_lang.structure_view.element.modular.Module$Companion.callChildren(Module.kt:89)
	at org.elixir_lang.structure_view.element.modular.Module.getChildren(Module.kt:47)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:50)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:207)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:41)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:33)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.getChildren(StructureViewComponent.java:796)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:62)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:383)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:299)
	at com.intellij.ui.tree.StructureTreeModel$Node.isLeaf(StructureTreeModel.java:559)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:335)
	at com.intellij.ui.tree.LeafState.get(LeafState.java:64)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:574)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:547)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:316)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:205)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:183)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:541)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sh41** [comment]
Fixed in [v14.0.1](https://github.com/KronicDeth/intellij-elixir/releases/tag/v14.0.1) (2023-04-07).

`Call.finalArguments()` maps its arguments through `it!!`. For a prefix operator that array came from `primaryArguments(prefix: Prefix)`, which was `arrayOf(prefix.operand())` — one element holding `null` whenever the operator had no parseable operand, which is what a dangling `&` or `!` mid-edit produces. [`f1fb17b0`](https://github.com/KronicDeth/intellij-elixir/commit/f1fb17b00b7cc4a05d03052f405f1ff88b06f744) returns `emptyArray()` instead.

That was the last of three null sources feeding this `catch`; [`1e2e4a9e`](https://github.com/KronicDeth/intellij-elixir/commit/1e2e4a9eda24a2c0f39205c60a9c7d2adbf54cff) (`Infix`, #1876) and [`c6a6143e`](https://github.com/KronicDeth/intellij-elixir/commit/c6a6143e5f1e6a4d16d881f2e666134c3ab459ab) (`NotIn`, #2725) closed the others. Nothing else reaching it can hold a `null` — every other path builds its array from `getChildren()`.

The class in your trace, `ElixirUnmatchedGreaterThanOrEqualToOnePointSixCaptureNonNumericOperationImpl`, is also gone: [`679a9689`](https://github.com/KronicDeth/intellij-elixir/commit/679a9689cfe097018b9baa4e894d4550a84d7aac) dropped Elixir <= 1.6 in v12.0.0. Capture operators now parse to `(un)matchedCaptureNonNumericOperation`, which reaches the same fixed code path.

#2415, #2532 and #2558 report this defect and close with it. Sorry it took so long to answer.
