### ISSUE TITLE
@NotNull method org/elixir_lang/code_insight/lookup/element_renderer/Variable.color must not return null

### ISSUE THREAD

**Issue by Hammer2900** [KronicDeth/intellij-elixir#2164]
# Version

11.13.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.IllegalStateException: @NotNull method org/elixir_lang/code_insight/lookup/element_renderer/Variable.color must not return null
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.$$$reportNull$$$0(Variable.java)
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.color(Variable.java:106)
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.renderElement(Variable.java:52)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:404)
	at com.intellij.codeInsight.lookup.LookupElementPresentation.renderElement(LookupElementPresentation.java:223)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:272)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$addItemToLookup$4(CompletionProgressIndicator.java:457)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:163)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:574)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:162)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItemToLookup(CompletionProgressIndicator.java:456)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:446)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.lambda$consume$0(CompletionThreading.java:145)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.lambda$consume$1(CompletionThreading.java:145)
	at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:113)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sh41** [comment]
Fixed in [v13.1.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v13.1.0) (2022-05-31). Note v13.0.0 does **not** have it — the fix landed two days after that release.

`Variable.color` seeded the colour with `JBColor.foreground()` and then let each branch overwrite it with `ElixirSyntaxHighlighter.<KEY>.getDefaultAttributes().getForegroundColor()`. That is `null` whenever the active colour scheme sets no foreground for the key, so on some schemes the default was gone by the time the method returned and the `@NotNull` contract threw — while the completion popup was being drawn, which is why you saw it as a crash on typing.

[`c7d04b78`](https://github.com/KronicDeth/intellij-elixir/commit/c7d04b780ccabf2ef552ad594e5403d56fdbd339) moves the default to a guard *after* every branch has run, so a null scheme foreground now falls back instead of being returned.

#2463 and #2511 report this same crash and close with it. Sorry it took so long to answer.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
