### ISSUE TITLE
Don't know how process element as type

### ISSUE THREAD

**Issue by jwmorrow1s** [KronicDeth/intellij-elixir#2206]
# Version

11.13.0

# What I was doing

I loaded an elixir file

# Exceptions

### Stacktrace

```
java.lang.Throwable: Don't know how process element as type
	at org.elixir_lang.errorreport.Logger.error(Logger.java:42)
	at org.elixir_lang.errorreport.Logger.error(Logger.java:28)
	at org.elixir_lang.psi.scope.Type$Companion.error(Type.kt:191)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:49)
	at org.elixir_lang.psi.scope.Type$executeOnChildren$1.invoke(Type.kt:110)
	at org.elixir_lang.psi.scope.Type$executeOnChildren$1.invoke(Type.kt:109)
	at org.elixir_lang.psi.impl.PsiElementImplKt.whileInChildExpressions(PsiElementImpl.kt:251)
	at org.elixir_lang.psi.impl.PsiElementImplKt.whileInChildExpressions$default(PsiElementImpl.kt:192)
	at org.elixir_lang.psi.scope.Type.executeOnChildren(Type.kt:109)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:45)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:303)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:645)
	at org.elixir_lang.psi.impl.ElixirMatchedTypeOperationImpl.processDeclarations(ElixirMatchedTypeOperationImpl.java:125)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1218)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults(MultiResolve.kt:74)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:69)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:42)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:23)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:18)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:15)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:40)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:134)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:114)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

# Attachments

## `/Users/jeff/Exercism/elixir/secrets/lib/secrets.ex`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.
## `induced.txt`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by KronicDeth** [comment]
@jwmorrow1s the error reporter in 11.13.0 drops the except of the file text that I need to reproduce this error.  Can you post the entire contents of your `/Users/jeff/Exercism/elixir/secrets/lib/secrets.ex` please?

**Comment by jwmorrow1s** [comment]
Yes, sorry about the late reply:
`defmodule Secrets do
  @spec secret_add(secret :: integer()) :: (integer() -> integer())
  def secret_add(secret) do
    fn (num) -> num + secret end
  end

  @spec secret_subtract(secret :: integer()) :: (integer() -> integer())
  def secret_subtract(secret) do
    fn (num) -> num - secret end
  end

  @spec secret_multiply(secret :: integer()) :: (integer() -> integer())
  def secret_multiply(secret) do
    fn (num) -> num * secret end
  end

  @spec secret_divide(secret :: integer() | float()) :: float()
  def secret_divide(secret) do
    fn (num) -> num / secret end
  end

  @spec secret_and(secret :: integer()) :: integer()
  def secret_and(secret) do
    fn (num) -> Bitwise.band(num, secret) end
  end

  @spec secret_xor(secret :: integer()) :: integer()
  def secret_xor(secret) do
    fn (num) -> Bitwise.bxor(num, secret) end
  end

  @type a    :: term()
  @type b    :: term()
  @type c    :: term()
  @type ABfn :: (a -> b)
  @type BCfn :: (b -> c)
  @type ACfn :: (a -> c)
  @spec secret_combine(secret_function1 :: ABfn, secret_function2 :: BCfn) :: ACfn
  def secret_combine(secret_function1, secret_function2) do
    #&secret_function2/1.(&secret_function1/1.(term))
    fn (term) -> term |> secret_function1 |> secret_function2 end
  end
end
`

**Comment by KronicDeth** [comment]
Improved error reporting in later plugin versions will make this easier, so closing this.
