### ISSUE TITLE
Don't know how to walk unquoted variable value at org.elixir_lang.psi.Unquote.treeWalkUpValue(Unquote.kt:141)

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#2217]
# Version

12.0.0-pre+20211121044005

# Event

### Excerpt

```
to_rendered_struct(handle_end(state), {:untainted, %{}}, %{})
```

From: `apps/app_name/assets/node_modules/phoenix_live_view/lib/phoenix_live_view/engine.ex:317`
To: `apps/app_name/assets/node_modules/phoenix_live_view/lib/phoenix_live_view/engine.ex:317`

### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedParenthesesCallImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to walk unquoted variable value
	at org.elixir_lang.errorreport.Logger.error(Logger.java:42)
	at org.elixir_lang.errorreport.Logger.error(Logger.java:28)
	at org.elixir_lang.psi.Unquote.treeWalkUpValue(Unquote.kt:141)
	at org.elixir_lang.psi.Unquote.treeWalkUpValue(Unquote.kt:122)
	at org.elixir_lang.psi.Unquote.treeWalkUpUnquotedVariable(Unquote.kt:76)
	at org.elixir_lang.psi.Unquote.treeWalkUpUnquoted(Unquote.kt:61)
	at org.elixir_lang.psi.Unquote.treeWalkUp(Unquote.kt:52)
	at org.elixir_lang.psi.Unquote.treeWalkUp(Unquote.kt:27)
	at org.elixir_lang.psi.QuoteMacro.treeWalkUp(QuoteMacro.kt:44)
	at org.elixir_lang.psi.QuoteMacro.treeWalkUp(QuoteMacro.kt:18)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:169)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:38)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:147)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:581)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:141)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1218)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:206)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:193)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:126)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:100)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.inspection.References$buildVisitor$1.registerProblem(References.kt:95)
	at org.elixir_lang.inspection.References$buildVisitor$1.registerProblem(References.kt:84)
	at org.elixir_lang.inspection.References$buildVisitor$1.visitCall(References.kt:47)
	at org.elixir_lang.inspection.References$buildVisitor$1.visitElement(References.kt:20)
	at org.elixir_lang.psi.ElixirVisitor.visitPsiElement(ElixirVisitor.java:1226)
	at org.elixir_lang.psi.ElixirVisitor.visitUnmatchedExpression(ElixirVisitor.java:978)
	at org.elixir_lang.psi.ElixirVisitor.visitUnmatchedUnqualifiedNoParenthesesCall(ElixirVisitor.java:1093)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:32)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:37)
```

**Comment by KronicDeth** [comment]
Fuller context is 

```
  def handle_body(state) do
    {:ok, rendered} = to_rendered_struct(handle_end(state), {:untainted, %{}}, %{})

    quote do
      require Phoenix.LiveView.Engine
      unquote(rendered)
    end
  end
 ```
 
 So, it is likely trying to find out if `rendereded` is a `quote` block, but gets stuff on  `to_rendered_struct(handle_end(state), {:untainted, %{}}, %{})`.
