### ISSUE TITLE
No decompiled source function with name (:queue.snoc) 	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:70)

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#2221]
# Version

12.0.0-pre+20211124050928

# Event

### Stacktrace

```
java.lang.Throwable: No decompiled source function with name (:queue.snoc)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:70)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:411)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda-6$lambda-5(BeamFileImpl.kt:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:391)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:111)
	at org.elixir_lang.Reference.forEachNavigationElement(Reference.java:59)
	at org.elixir_lang.Reference.forEachNavigationElement(Reference.java:41)
	at org.elixir_lang.reference.resolver.atom.resolvable.Exact.resolve(Exact.java:26)
	at org.elixir_lang.reference.resolver.Atom.resolve(Atom.java:20)
	at org.elixir_lang.reference.resolver.Atom.resolve(Atom.java:11)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Atom.multiResolve(Atom.java:43)
	at org.elixir_lang.psi.impl.ElixirAtomImplKt.maybeModularNameToModulars(ElixirAtomImpl.kt:22)
	at org.elixir_lang.psi.impl.ElixirAtomImplKt.maybeModularNameToModulars(ElixirAtomImpl.kt:18)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:180)
	at org.elixir_lang.psi.impl.call.qualification.QualifiedImplKt.qualifiedToModulars(QualifiedImpl.kt:19)
	at org.elixir_lang.reference.resolver.Callable.resolveQualified(Callable.kt:142)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:98)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.inspection.References$buildVisitor$1.registerProblem(References.kt:95)
	at org.elixir_lang.inspection.References$buildVisitor$1.registerProblem(References.kt:84)
	at org.elixir_lang.inspection.References$buildVisitor$1.visitCall(References.kt:47)
	at org.elixir_lang.inspection.References$buildVisitor$1.visitElement(References.kt:20)
	at org.elixir_lang.psi.ElixirVisitor.visitPsiElement(ElixirVisitor.java:1226)
	at org.elixir_lang.psi.ElixirVisitor.visitMatchedExpression(ElixirVisitor.java:608)
	at org.elixir_lang.psi.ElixirVisitor.visitMatchedQualifiedParenthesesCall(ElixirVisitor.java:686)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.accept(ElixirMatchedQualifiedParenthesesCallImpl.java:32)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.accept(ElixirMatchedQualifiedParenthesesCallImpl.java:37)
```

**Comment by KronicDeth** [comment]
The spec can't be parsed because of the `::` in the return value:

```
  @spec snoc(q1 :: queue(item), item) :: q2 :: queue(item)
  def snoc(q, x), do: in(x, q
```

[The original Erlang source looks] like

```
-spec snoc(Q1 :: queue(Item), Item) -> Q2 :: queue(Item).
snoc(Q, X) ->
    in(X, Q).
```
