### ISSUE TITLE
Range must be inside element being annotated: (8206,8216); but got: (8206,16412) [Plugin: org.elixir_lang] 	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:274)

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#2258]
# Version

12.0.0

# Event

## Message

In file: deps/statix/lib/statix.ex

### Stacktrace

```
com.intellij.diagnostic.PluginException: Range must be inside element being annotated: (8206,8216); but got: (8206,16412) [Plugin: org.elixir_lang]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:274)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:91)
	at com.intellij.codeInsight.daemon.impl.B.range(B.java:176)
	at org.elixir_lang.annotator.Highlighter$highlight$5.invoke(Highlighter.kt:31)
	at org.elixir_lang.annotator.Highlighter$highlight$5.invoke(Highlighter.kt:31)
	at org.elixir_lang.annotator.Highlighter.highlight(Highlighter.kt:39)
	at org.elixir_lang.annotator.Highlighter.highlight(Highlighter.kt:31)
	at org.elixir_lang.annotator.Callable.highlight(Callable.kt:278)
	at org.elixir_lang.annotator.Callable.highlight(Callable.kt:257)
	at org.elixir_lang.annotator.Callable.highlight(Callable.kt:234)
	at org.elixir_lang.annotator.Callable.access$highlight(Callable.kt:28)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:107)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment]
This is likely the same root cause as #2400 and so fixed by 1078f8f1b4eaf2e0570f5ad2c70b65643b682940
