### ISSUE TITLE
Erlang Abst record_field field is unknown at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.error(AbstractCode.kt:91)

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#2333]
# System

Plugin Version: 12.0.0-pre+20211205044259
Application: IntelliJ IDEA Community Edition (2021.2.3)
Operating System: Mac OS X (11.5)

# Event

### Term

{var,67,'_'}

### Stacktrace

```
java.lang.Throwable: Erlang Abst record_field field is unknown
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:66)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.error(AbstractCode.kt:91)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.fieldToString(RecordField.kt:28)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.setFieldString(RecordField.kt:56)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.setToMacroStringDeclaredScope(RecordField.kt:60)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.toMacroStringDeclaredScope(RecordField.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.ifToMacroStringDeclaredScope(RecordField.kt:11)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:73)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedMacroStringDeclaredScope(Sequence.kt:42)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedMacroStringDeclaredScope(Sequence.kt:37)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.creationRecordFieldsMacroStringDeclaredScope(Record.kt:50)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.creationToMacroStringDeclaredScope(Record.kt:39)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.toMacroStringDeclaredScope(Record.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.ifToMacroStringDeclaredScope(Record.kt:13)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:72)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedMacroStringDeclaredScope(Sequence.kt:42)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedString(Sequence.kt:33)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedString$default(Sequence.kt:32)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.argumentsToString(Call.kt:48)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.argumentsToString(Call.kt:52)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.remoteNamedFunctionCallToString(Call.kt:113)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.access$remoteNamedFunctionCallToString(Call.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call$namedFunctionCallToString$1.invoke(Call.kt:104)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call$namedFunctionCallToString$1.invoke(Call.kt:103)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Remote.ifTo(Remote.kt:60)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.namedFunctionCallToString(Call.kt:103)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.toString(Call.kt:138)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.toMacroStringDeclaredScope(Call.kt:22)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.ifToMacroStringDeclaredScope(Call.kt:19)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:55)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Case.expressionMacroStringDeclaredScope(Case.kt:43)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Case.toString(Case.kt:50)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Case.toMacroStringDeclaredScope(Case.kt:15)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Case.ifToMacroStringDeclaredScope(Case.kt:12)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:56)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:93)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.clause.Body.toMacroStringDeclaredScope(Body.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Clause.bodyString(Clause.kt:15)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.function.Clause.toMacroString(Clause.kt:20)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function$toMacroString$1.invoke(Function.kt:34)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function$toMacroString$1.invoke(Function.kt:34)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3344)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3361)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3360)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function.toMacroString(Function.kt:34)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:419)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:404)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:395)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:264)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:214)
	at org.elixir_lang.beam.Decompiler$Companion.decompiled(Decompiler.kt:71)
	at org.elixir_lang.beam.Decompiler$Companion.access$decompiled(Decompiler.kt:33)
	at org.elixir_lang.beam.Decompiler.decompile(Decompiler.kt:31)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:536)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.loadText(FileDocumentManagerBase.java:89)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:46)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:377)
	at org.elixir_lang.beam.psi.BeamFileImpl.getDecompiledPsiFile(BeamFileImpl.kt:60)
```

**Comment by sh41** [comment]
Same defect as #2728: an Erlang wildcard variable (`{var, _, '_'}`) used as a record-field name. Fixed in **v23.0.7** — not in v23.0.5 — see #2728 for the commits. Closing as a duplicate of that one.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
