### ISSUE TITLE
java.lang.RuntimeException: com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: calendar at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157)

### ISSUE THREAD

**Issue by AlfUA** [KronicDeth/intellij-elixir#2369]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Community Edition (2021.2.3)
Operating System: Mac OS X (11.6.1)

# Event

### Stacktrace

```
java.lang.RuntimeException: com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: calendar
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:451)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:33)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:26)
	at com.intellij.projectImport.ProjectOpenProcessorBase.importToProject(ProjectOpenProcessorBase.kt:185)
	at com.intellij.projectImport.ProjectOpenProcessorBase.access$importToProject(ProjectOpenProcessorBase.kt:33)
	at com.intellij.projectImport.ProjectOpenProcessorBase$doOpenProject$1.invoke(ProjectOpenProcessorBase.kt:165)
	at com.intellij.projectImport.ProjectOpenProcessorBase$doOpenProject$1.invoke(ProjectOpenProcessorBase.kt:33)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:281)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:57)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:119)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:57)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:94)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: calendar
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.newModule(ModifiableModuleModelBridgeImpl.kt:83)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.newModule(ModifiableModuleModelBridgeImpl.kt:51)
	at org.elixir_lang.mix.Project.createModuleForOtpApp(Project.kt:103)
	at org.elixir_lang.mix.Project.createModulesForOtpApps(Project.kt:77)
	at org.elixir_lang.mix.project._import.Builder.commit(Builder.kt:104)
```

**Comment by KronicDeth** [comment]
@ AlfUA does your umbrella application's root directory and an app inside it have the same name?

**Comment by AlfUA** [comment]
absolutely right, that's the case.

**Comment by KronicDeth** [comment]
I really should fix this by just renaming the root module or adding numbers on collision, but until I do that you’ll have to work around it by renaming the root directory to <name>_umbrella, which is what later phx.new versions did.

**Comment by AlfUA** [comment]
Sure, thank you!

**Comment by J3RN** [comment]
I get this same error, but likely do to my directory convention rather than the existence of an umbrella (we don't use one).

My directory convention is `~/Code/<user>/<repo>/<branch>`. Branches are checked out into separate worktrees under `~/Code/<user>/<repo>`. Thus, the `main` branch of my work project is located at `~/Code/joydrive/joydrive/main`. I tried changing the path to `~/Code/joydrive/joydrive_app/main`, but that still resulted in this error. I got it to not crash by just cloning the repository into my home directory (i.e. at `~/joydrive`).

**Comment by sh41** [comment]
Fixed. You confirmed here in 2021 that your umbrella root and one of its apps shared a name, and that
is exactly the cause: each OTP app's `.iml` was named after the app, so the root and the `calendar`
under `apps/` resolved to one path and the second `newModule` call threw.

`fc3c45133` disambiguates the module names first — the root app keeps its plain name, the others get a
suffix from their path relative to it. The `<name>_umbrella` rename you were asked to do as a
workaround is no longer needed. First released in v23.0.5.

Closing as a duplicate of #2003, which describes the same collision and is where the fix is recorded.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
