### ISSUE TITLE
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)

### ISSUE THREAD

**Issue by ulmentflam** [KronicDeth/intellij-elixir#2375]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (12.0.1)

# Event

### Stacktrace

```
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:266)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:257)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:583)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:545)
	at com.intellij.util.indexing.impl.ValueContainerMap.lambda$getModifiableValueContainer$0(ValueContainerMap.java:77)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:98)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:77)
	at com.intellij.util.indexing.impl.MergedValueContainer$1.<init>(MergedValueContainer.java:27)
	at com.intellij.util.indexing.impl.MergedValueContainer.getValueIterator(MergedValueContainer.java:25)
	at com.intellij.util.indexing.impl.MergedValueContainer.getValueIterator(MergedValueContainer.java:11)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:45)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$getContainingIds$8(StubIndexImpl.java:528)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:234)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$getContainingIds$9(StubIndexImpl.java:527)
	at com.intellij.util.indexing.IndexUpToDateCheckIn.disableUpToDateCheckIn(IndexUpToDateCheckIn.kt:13)
	at com.intellij.util.indexing.FileBasedIndexImpl.disableUpToDateCheckIn(FileBasedIndexImpl.java:768)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$getContainingIds$10(StubIndexImpl.java:527)
	at com.intellij.util.indexing.diagnostic.IndexAccessValidator.validate(IndexAccessValidator.java:42)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:524)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:318)
	at org.elixir_lang.reference.resolver.Module.multiResolveProject(Module.kt:113)
	at org.elixir_lang.reference.resolver.Module.resolveAll(Module.kt:75)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:67)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:34)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:30)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:22)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:92)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:80)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:181)
	at org.elixir_lang.psi.Use.modulars(Use.kt:80)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:31)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:65)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:39)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:147)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:581)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:400)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:399)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:302)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:403)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:379)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:235)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:621)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:137)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:128)
	at org.elixir_lang.reference.resolver.Module.resolveInScope(Module.kt:78)
	at org.elixir_lang.reference.resolver.Module.resolveAll(Module.kt:73)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:67)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:34)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:30)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:22)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.reference.Module.resolve(Module.kt:38)
```

**Comment by KronicDeth** [comment]
This looks like it is happening due to corruption in the Stub indexes. Please file this with JetBrains as the APIs hide the on-disk format of the index for the most part, so it may be a bug in their libraries.

For now, I would recommend rebuilding the index for your project 

1. Go to FIle > Invalidate Caches in the menus
2. Click "Invalidate and Restart" in the dialog
