### ISSUE TITLE
Don't know how to check if variable at org.elixir_lang.reference.Callable$Companion.error(Callable.kt:419)

### ISSUE THREAD

**Issue by Chr1s603** [KronicDeth/intellij-elixir#2376]
# System

Plugin Version: 12.0.1
Application: RubyMine (2021.3)
Operating System: Windows 10 (10.0)

# Event

### Excerpt

```
fn exec do
     stream =
       File.stream!("day1.txt")
       |> Stream.map(&String.to_integer(String.trim(&1)))
     IO.po
  end
end
```

From: `D:/workspace/advent_of_code/lib/day1.ex:1`
To: `D:/workspace/advent_of_code/lib/day1.ex:7`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirAnonymousFunctionImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to check if variable
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.reference.Callable$Companion.error(Callable.kt:419)
	at org.elixir_lang.reference.Callable$Companion.isVariable(Callable.kt:367)
	at org.elixir_lang.reference.Callable$Companion.isVariable(Callable.kt:469)
	at org.elixir_lang.reference.Callable$Companion.isVariable(Callable.kt:360)
	at org.elixir_lang.reference.Callable$Companion.isVariable(Callable.kt:480)
	at org.elixir_lang.reference.Callable$Companion.isVariable(Callable.kt:360)
	at org.elixir_lang.ReadWriteAccessDetector.isReadWriteAccessible(ReadWriteAccessDetector.kt:34)
	at org.elixir_lang.ReadWriteAccessDetector.isReadWriteAccessible(ReadWriteAccessDetector.kt:26)
```

**Comment by sh41** [comment]
Fixed.

`fn exec do ... end` has no `->`, so its body parses straight onto the anonymous function — and that
was the one ancestor type the walk deciding "is this a variable?" had no branch for. It enumerates
the types it knows and raises an error report for anything else. It now searches above the anonymous
function, as it already does for the other shapes that only turn up mid-typing. Your snippet is the
regression test, in #3976.

Sorry it took this long to answer.

---

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
