### ISSUE TITLE
java.nio.BufferOverflowException at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:409)

### ISSUE THREAD

**Issue by ulmentflam** [KronicDeth/intellij-elixir#2377]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (12.0.1)

# Event

## Message

In file: file:///Users/evanowen/FirstFoundry/Workspace/forte/bridge/forte_bridge_custodian/heimdall/mix.exs

### Stacktrace

```
java.nio.BufferOverflowException
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:409)
	at com.intellij.util.io.DirectBufferWrapper.putFromArray(DirectBufferWrapper.java:116)
	at com.intellij.util.io.PagedFileStorage.put(PagedFileStorage.java:233)
	at com.intellij.util.io.ResizeableMappedFile.put(ResizeableMappedFile.java:232)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.flushKeyStoreBuffer(AppendableStorageBackedByResizableMappedFile.java:47)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.force(AppendableStorageBackedByResizableMappedFile.java:55)
	at com.intellij.util.indexing.impl.storage.IntLog$doForce$1.invoke(IntLog.kt:154)
	at com.intellij.util.indexing.impl.storage.IntLog$doForce$1.invoke(IntLog.kt:39)
	at com.intellij.util.indexing.impl.storage.IntLog.withLock(IntLog.kt:167)
	at com.intellij.util.indexing.impl.storage.IntLog.doForce(IntLog.kt:154)
	at com.intellij.util.indexing.impl.storage.IntLog.processEntries(IntLog.kt:60)
	at com.intellij.psi.search.LogFileTypeIndex$LogBasedIntIntIndex.getIndexedData(LogFileTypeIndex.java:419)
	at com.intellij.psi.search.LogFileTypeIndex.getIndexedFileTypeId(LogFileTypeIndex.java:230)
	at com.intellij.psi.search.LogFileTypeIndex.getIndexingStateForFile(LogFileTypeIndex.java:128)
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndexingState(FileBasedIndexImpl.java:1852)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$27(FileBasedIndexImpl.java:1397)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:627)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1376)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1330)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1298)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1635)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1632)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1652)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:823)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:514)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:318)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
	at org.elixir_lang.Reference.namedElementCollection(Reference.java:81)
	at org.elixir_lang.Reference.namedElementCollection(Reference.java:70)
	at org.elixir_lang.Reference.forEachNavigationElement(Reference.java:39)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImports(CallDefinitionClause.kt:260)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:166)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:38)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:147)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:581)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:203)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:190)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:126)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:100)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment]
This seems to be a problem with getting stubs back out of an index and so related to APIs that JetBrains controls. These needs to be filed with JetBrains.
