### ISSUE TITLE
Don't know how to find variable use scope at org.elixir_lang.reference.Callable$Companion.error(Callable.kt:419)

### ISSUE THREAD

**Issue by imcvampire** [KronicDeth/intellij-elixir#2389]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.2)
Operating System: Mac OS X (12.0.1)

# Event

### Excerpt

```
<%= render Web.FragmentView, "title.html", title= "haha" %>
```

From: `/lib/web/templates/page/index.html.heex:4`
To: `/lib/web/templates/page/index.html.heex:4`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirEexTagImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to find variable use scope
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.reference.Callable$Companion.error(Callable.kt:419)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:573)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:485)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:566)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:523)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:564)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:416)
	at org.elixir_lang.psi.impl.declarations.UseScopeImpl.get(UseScopeImpl.kt:119)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getUseScope(ElixirPsiImplUtil.java:991)
	at org.elixir_lang.psi.impl.ElixirMatchedUnqualifiedNoArgumentsCallImpl.getUseScope(ElixirMatchedUnqualifiedNoArgumentsCallImpl.java:100)
```

**Comment by KronicDeth** [comment]
Not that I think it affects the bug report, but so you're aware, the EEx support only supports the EEx tags if you use it on `.heex`.  It won't support the new HEEx-only syntax.  That needs to be added in #2102.

**Comment by sh41** [comment]
Fixed. The report's element class is `ElixirEexTagImpl`, and `variableUseScope` gained an `ElixirEexTag` case in [`85c0951`](https://github.com/KronicDeth/intellij-elixir/commit/85c0951801ee626c8de88bf201b3c9b5d8ef4633) ("Don't look for variable use scope above EEx tags"), first shipped in [v14.0.1](https://github.com/KronicDeth/intellij-elixir/releases/tag/v14.0.1) on 2023-04-07: a variable written in an EEx tag has no declaration to find, so its use scope is empty rather than an error report. This was filed against 12.0.1; every current build has the fix.

For anyone arriving from the title — [#3358](https://github.com/KronicDeth/intellij-elixir/issues/3358) had the same message and the same `Callable$Companion.error` frame but a different element class (`ElixirFile`). It was a separate defect, fixed in [#3979](https://github.com/KronicDeth/intellij-elixir/pull/3979).
