### ISSUE TITLE
Do not use module level message bus at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:196)

### ISSUE THREAD

**Issue by rgfaber** [KronicDeth/intellij-elixir#2396]
# System

Plugin Version: 12.0.1
Application: JetBrains Rider (2021.3.1)
Operating System: Linux (5.11.0-41-generic)

# Event

### Stacktrace

```
java.lang.Throwable: Do not use module level message bus
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:196)
	at org.elixir_lang.facet.configurable.Project.setFacetSdk(Project.kt:61)
	at org.elixir_lang.facet.configurable.Project.addFacet(Project.kt:69)
	at org.elixir_lang.facet.configurable.Project.access$addFacet(Project.kt:16)
	at org.elixir_lang.facet.configurable.Project$createModuleConfigurable$1.applySdk$lambda-1(Project.kt:30)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at org.elixir_lang.facet.configurable.Project$createModuleConfigurable$1.applySdk(Project.kt:29)
	at org.elixir_lang.facet.Configurable.apply(Configurable.kt:33)
```

### `logs.tar.xz`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by rgfaber** [comment]
sorry already reported. closing the issue
