### ISSUE TITLE
Do not use module level message bus at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:196)

### ISSUE THREAD

**Issue by EpicHigh** [KronicDeth/intellij-elixir#2402]
# System

Plugin Version: 12.0.1
Application: WebStorm (2021.3)
Operating System: Mac OS X (12.0.1)

# Event

### Stacktrace

```
java.lang.Throwable: Do not use module level message bus
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:196)
	at org.elixir_lang.facet.configurable.Project.setFacetSdk(Project.kt:61)
	at org.elixir_lang.facet.configurable.Project.addFacet(Project.kt:69)
	at org.elixir_lang.facet.configurable.Project.access$addFacet(Project.kt:16)
	at org.elixir_lang.facet.configurable.Project$createModuleConfigurable$1.applySdk$lambda-1(Project.kt:30)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at org.elixir_lang.facet.configurable.Project$createModuleConfigurable$1.applySdk(Project.kt:29)
	at org.elixir_lang.facet.Configurable.apply(Configurable.kt:33)
```

**Comment by petros** [comment]
Would this issue, #2393, #2093, and #2090 be duplicates of #2063?

**Comment by EpicHigh** [comment]
Yep, this one will be closed because it is a duplicate.
