### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented. at org.elixir_lang.documentation.ElixirDocumentationProvider.formatDocs(ElixirDocumentationProvider.kt:123)

### ISSUE THREAD

**Issue by rgfaber** [KronicDeth/intellij-elixir#2412]
# System

Plugin Version: 12.0.1
Application: JetBrains Rider (2021.3.1)
Operating System: Linux (5.11.0-43-generic)

# Event

## Message

Unhandled exception in [StandaloneCoroutine{Cancelling}@524fd77, EdtCoroutineDispatcher@6ebb16f]

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented.
	at org.elixir_lang.documentation.ElixirDocumentationProvider.formatDocs(ElixirDocumentationProvider.kt:123)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:27)
```

### `logs.tar.xz`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by sh41** [comment]
Fixed in [v13.1.1](https://github.com/KronicDeth/intellij-elixir/releases/tag/v13.1.1) (2022-06-17).

`ElixirDocumentationProvider` had a bare `TODO()` where it should have rendered the `Deprecated`
section for a function whose BEAM documentation chunk carries `deprecated` metadata, so asking for
docs on any such function threw `NotImplementedError` instead.
[Implement Deprecated metadata handling for docs from BEAM files](https://github.com/KronicDeth/intellij-elixir/commit/362973da6dedc4278868d21ce1c61862b59ccf8b)
replaced it with the real rendering.

Two other reports of the same crash corroborate it: #2569 was closed as a duplicate of this issue, and
#2704 — the same defect against a later build — was closed by that commit itself.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
> but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
> tell us why.
