### ISSUE TITLE
Don't know how to prepend qualifier at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:193)

### ISSUE THREAD

**Issue by samwightt** [KronicDeth/intellij-elixir#2414]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Community Edition (2021.3)
Operating System: Mac OS X (12.1)

# Event

### Excerpt

```
<%= IntellijIdeaRulezzz  %>
```

            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirEexTagImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to prepend qualifier
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:193)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:147)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.fullyQualifiedName(QualifiableAliasImpl.kt:125)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyQualifiedName(ElixirPsiImplUtil.java:787)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.fullyQualifiedName(ElixirAliasImpl.java:37)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.computeReference(QualifiableAliasImpl.kt:39)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference$lambda-0(QualifiableAliasImpl.kt:54)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference(QualifiableAliasImpl.kt:53)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1184)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.getReference(ElixirAliasImpl.java:57)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.getReference(ElixirAliasImpl.java:19)
```

**Comment by sh41** [comment]
Fixed and released.

`QualifiableAliasImpl.prependQualifiers` matches every ancestor it walks against a `when`, and an EEx tag was missing from it — so an alias inside `<%= … %>` fell through to the catch-all that logs "Don't know how to prepend qualifier". Your report names the ancestor it did not recognise: `ElixirEexTagImpl`.

`ca0b1ae5` *Stop prependingQualifiers at EEx tags.* added EEx tags to that list. First stable release carrying it: [v15.1.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v15.1.0), 2023-07-08.

Same defect as #2468, #3278 and #3658.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
