### ISSUE TITLE
NullPointerException getting Call.finalArguments() at org.elixir_lang.psi.impl.call.CallImplKt.finalArguments(CallImpl.kt:143)

### ISSUE THREAD

**Issue by rgfaber** [KronicDeth/intellij-elixir#2415]
# System

Plugin Version: 12.0.1
Application: JetBrains Rider (2021.3.1)
Operating System: Linux (5.11.0-43-generic)

# Event

Occurs after attempting refactoring using Shift+F6 (rename) of a module

### Excerpt

```
-
```

From: `/home/rl/work/github.com/rgfaber/robex/test/streams_test.exs:16`
To: `/home/rl/work/github.com/rgfaber/robex/test/streams_test.exs:16`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedUnaryOperationImpl
```

### Stacktrace

```
java.lang.Throwable: NullPointerException getting Call.finalArguments()
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.impl.call.CallImplKt.finalArguments(CallImpl.kt:143)
	at org.elixir_lang.psi.impl.call.CallImplKt.keywordArguments(CallImpl.kt:169)
	at org.elixir_lang.psi.impl.call.CallImplKt.keywordArgument(CallImpl.kt:160)
	at org.elixir_lang.psi.impl.call.CallImpl.hasDoBlockOrKeyword(CallImpl.kt:404)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasDoBlockOrKeyword(ElixirPsiImplUtil.java:1199)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:234)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:407)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:63)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:377)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:46)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:377)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:46)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:294)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:637)
	at org.elixir_lang.psi.impl.ElixirUnmatchedMatchOperationImpl.processDeclarations(ElixirUnmatchedMatchOperationImpl.java:124)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:400)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:399)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:299)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:403)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:379)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:235)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:621)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveInScope(MultiResolve.kt:133)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveResultList(MultiResolve.kt:116)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:117)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:100)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

### `logs.tar.xz`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by sh41** [comment]
Same defect as #2159: `primaryArguments(prefix: Prefix)` returned `arrayOf(prefix.operand())`, holding a `null` when a prefix operator has no parseable operand. Fixed by [`f1fb17b0`](https://github.com/KronicDeth/intellij-elixir/commit/f1fb17b00b7cc4a05d03052f405f1ff88b06f744) in [v14.0.1](https://github.com/KronicDeth/intellij-elixir/releases/tag/v14.0.1) (2023-04-07); full explanation on #2159. Sorry it took so long to answer.
