### ISSUE TITLE
Stub index points to a file (file = file:///usr/local/Cellar/erlang/24.2/lib/erlang/lib/wx-2.1.1/doc/chunks/wxXmlResource.chunk, file type = com.intellij.openapi.fileTypes.UnknownFileType@4a46143f, indexed file type = com.intellij.openapi.fileTypes.UnknownFileType@4a46143f) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0 at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)

### ISSUE THREAD

**Issue by marcellanz** [KronicDeth/intellij-elixir#2420]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (12.1)

# Event

### Stacktrace

```
java.lang.Throwable: Stub index points to a file (file = file:///usr/local/Cellar/erlang/24.2/lib/erlang/lib/wx-2.1.1/doc/chunks/wxXmlResource.chunk, file type = com.intellij.openapi.fileTypes.UnknownFileType@4a46143f, indexed file type = com.intellij.openapi.fileTypes.UnknownFileType@4a46143f) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$4(StubIndexImpl.java:339)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:338)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
	at org.elixir_lang.Reference.namedElementCollection(Reference.java:81)
	at org.elixir_lang.Reference.namedElementCollection(Reference.java:70)
	at org.elixir_lang.Reference.forEachNavigationElement(Reference.java:39)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImports(CallDefinitionClause.kt:280)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:166)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:38)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:147)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:581)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:203)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:190)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:126)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:100)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment]
🤔 I never added explicit support to the plugin for .chunk files AND it is saying it is an unknown file type.  I wonder why it is trying to index the file then?

Please also report to JetBrains directly.  Maybe they’ll point out some reason why an unknown file type is being indexed instead of just the file types I registered.

Finally, how did you install Erlang?  I don’t have chunk files in my SDK as far as I can tell with asdf, but maybe 24.2 added them?

**Comment by marcellanz** [comment]
> I don’t have chunk files in my SDK as far as I can tell with asdf, but maybe 24.2 added them?

I really don't know, there seem to be quite a few under /usr/local/Cellar/erlang/24.2:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/12616445/147494097-70510239-1423-48bc-aa27-ded1cca42ed8.png">

which is the installation of Erlang I get with it installed with brew on macOS.

>I wonder why it is trying to index the file then?

Good question, I don't know :) I might have added wrong directories to lib/src/doc in Modules configuration?

**Comment by KronicDeth** [comment]
If the docs are in the chunks we want them to be able to get the docs.  Perhaps the doc code looks for chunks?  It was a community contribution.

Either way I’m still surprised that the Stub I Dec API doesn’t ignore unknown file types.

If this is a homebrew install I can install it locally easily enough to try to reproduce it.

**Comment by marcellanz** [comment]
>If this is a homebrew install I can install it locally easily enough to try to reproduce it.

Cool, let me know if I should share further configuration from my side.

**Comment by sh41** [comment]
Answering the question left open here — the Stub Index API does let you ignore unknown file types,
but you have to ask it to.

`StubIndexEx.processElements` tests `scope.contains(file)` immediately before
`StubProcessingHelper.retrieveStubIdList`, where this error is logged. A scope built with
`GlobalSearchScope.getScopeRestrictedByFileTypes` filters on the file's *current* type, so a `.chunk`
file under an Erlang SDK root is skipped before the platform looks for a stub tree.

The plugin uses that guard in exactly one place today, the LEEx assign resolver, and not on the
module-name stub index lookups — which run against a scope uniting each SDK's source roots, where
your `doc/chunks` files sit. `.chunk` bytes are read directly for documentation now, but no
`FileType` is registered for them, so they stay unknown to the index.

The crashing frames in the report were removed in v12.2.1; that commit changed which stub index is
queried and added no file-type restriction, so it moved the exposure rather than closing it.

Keeping this open. Restricting the shared scope helper by file type is a small change, but the list
has to cover Elixir, Elixir Script and BEAM or resolution breaks quietly.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this
reply before it was posted. If any of it is wrong, please say so here.
