### ISSUE TITLE
Stub index points to a file (file = file:///usr/local/Cellar/erlang/24.2/lib/erlang/lib/wx-2.1.1/doc/chunks/wxGraphicsPen.chunk, file type = com.intellij.openapi.fileTypes.UnknownFileType@4a46143f, indexed file type = com.intellij.openapi.fileTypes.UnknownFileType@4a46143f) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0 at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)

### ISSUE THREAD

**Issue by marcellanz** [KronicDeth/intellij-elixir#2421]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (12.1)

# Event

### Stacktrace

```
java.lang.Throwable: Stub index points to a file (file = file:///usr/local/Cellar/erlang/24.2/lib/erlang/lib/wx-2.1.1/doc/chunks/wxGraphicsPen.chunk, file type = com.intellij.openapi.fileTypes.UnknownFileType@4a46143f, indexed file type = com.intellij.openapi.fileTypes.UnknownFileType@4a46143f) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$4(StubIndexImpl.java:339)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:338)
	at org.elixir_lang.reference.resolver.Module.multiResolveProject(Module.kt:113)
	at org.elixir_lang.reference.resolver.Module.resolveAll(Module.kt:75)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:67)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:34)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:30)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:22)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:92)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:80)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:181)
	at org.elixir_lang.psi.impl.call.qualification.QualifiedImplKt.qualifiedToModulars(QualifiedImpl.kt:19)
	at org.elixir_lang.reference.resolver.Callable.resolveQualified(Callable.kt:142)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:98)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.accept(ElixirUnmatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by marcellanz** [comment]
duplicate, sorry.
