### ISSUE TITLE
java.nio.charset.spi.CharsetProvider: sun.nio.cs.ext.ExtendedCharsets Unable to get public no-arg constructor

### ISSUE THREAD

**Issue by marcellanz** [KronicDeth/intellij-elixir#2426]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (12.1)

# Event

### Stacktrace

```
java.util.ServiceConfigurationError: java.nio.charset.spi.CharsetProvider: sun.nio.cs.ext.ExtendedCharsets Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:673)
	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:899)
	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1077)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at java.base/java.nio.charset.Charset$1.getNext(Charset.java:344)
	at java.base/java.nio.charset.Charset$1.hasNext(Charset.java:359)
	at java.base/java.nio.charset.Charset$3.run(Charset.java:581)
	at java.base/java.nio.charset.Charset$3.run(Charset.java:571)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.nio.charset.Charset.availableCharsets(Charset.java:570)
	at org.elixir_lang.debugger.stack_frame.value.Presentation.toUtf8String(Presentation.java:194)
	at org.elixir_lang.debugger.stack_frame.value.Presentation.renderBitstr(Presentation.java:140)
	at org.elixir_lang.debugger.stack_frame.value.Presentation.renderObject(Presentation.java:49)
	at org.elixir_lang.debugger.stack_frame.value.Presentation.renderValue(Presentation.java:223)
	at org.elixir_lang.beam.term.InspectKt.inspect(Inspect.kt:10)
	at org.elixir_lang.Macro.otherToString(Macro.kt:193)
	at org.elixir_lang.Macro.toString(Macro.kt:907)
	at org.elixir_lang.Macro$keywordListToString$1.invoke(Macro.kt:204)
	at org.elixir_lang.Macro$keywordListToString$1.invoke(Macro.kt:197)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3344)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3361)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3360)
	at org.elixir_lang.Macro.keywordListToString(Macro.kt:197)
	at org.elixir_lang.Macro.argumentsToString(Macro.kt:382)
	at org.elixir_lang.Macro.callToStringWithArguments(Macro.kt:481)
	at org.elixir_lang.Macro.otherCallToString(Macro.kt:461)
	at org.elixir_lang.Macro.ifCallToString(Macro.kt:429)
	at org.elixir_lang.Macro.toString(Macro.kt:904)
	at org.elixir_lang.Macro.ifDeinlineToString(Macro.kt:437)
	at org.elixir_lang.Macro.ifCallToString(Macro.kt:428)
	at org.elixir_lang.Macro.toString(Macro.kt:904)
	at org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.definition.Clause.toMacroString(Clause.kt:46)
	at org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.Definition.toMacroString(Definition.kt:49)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:433)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:406)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:395)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:264)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:214)
	at org.elixir_lang.beam.Decompiler$Companion.decompiled(Decompiler.kt:71)
	at org.elixir_lang.beam.Decompiler$Companion.access$decompiled(Decompiler.kt:33)
	at org.elixir_lang.beam.Decompiler.decompile(Decompiler.kt:31)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:536)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.loadText(FileDocumentManagerBase.java:89)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:46)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:377)
```

**Comment by marcellanz** [comment]
The biggest impact this error has to my work environment is, that I find my IntelliJ in an unusable state afterwards. Some UI does not respond anymore. Then I have to restart the IDE often.

**Comment by KronicDeth** [comment]
Are you using a very new or alternative JDK implementation?  I’m at a loss for how something from java.nio is missing

**Comment by marcellanz** [comment]
Let me check. Usually Intellij comes with its own JRE I assume.

**Comment by marcellanz** [comment]
This is what my IntelliJ is running on.
```
IU-213.6461.79, JRE 11.0.13+7-b1751.21x64 JetBrains s.r.o., OS Mac OS X(x86_64) v12.1, screens 3840.0x2160.0; Retina
```

**Comment by KronicDeth** [comment]
Please file this with JetBrains’ bug tracker too.  They may be able to advise on what changed and the correct API to use now.

**Comment by sh41** [comment]
The trace shows this failing inside the JVM, not the plugin. `Charset.availableCharsets()` asks the JDK's own `ServiceLoader` to instantiate every registered `CharsetProvider`, and it is the JDK's built-in `sun.nio.cs.ext.ExtendedCharsets` that has no usable no-arg constructor — the plugin only asked the JVM for UTF-8, and the error was raised entirely within `java.base`. Since you were on the stock JetBrains-bundled JRE 11.0.13+7 rather than an alternative JDK, that points at a damaged or incomplete runtime install on that machine; reinstalling the IDE's bundled runtime, or pointing it at a different boot JRE, should clear it. The plugin code involved is unchanged since you filed this and there is nothing in it to fix, so I am closing this as an environment fault outside the plugin. If it still happens on a freshly installed runtime, please reopen and say so — that would be a different problem from this one.

---

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
