### ISSUE TITLE
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name

### ISSUE THREAD

**Issue by marcellanz** [KronicDeth/intellij-elixir#2427]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (12.1)

# Event

### Stacktrace

```
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name, file = file:///Users/some_directory/eigr/massa/_build/test/lib/grpc/ebin/Elixir.GRPC.Transport.Utils.beam, file type = BEAM, indexed file type = BEAM
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:65)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$4(StubIndexImpl.java:339)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:338)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:51)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:185)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:90)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
```

**Comment by KronicDeth** [comment]
I'm not sure why this wouldn't just return no results and instead error.

You can force the indexes to rebuild using the following steps:

1. FIle > Invalidate Caches
2. Click Invalidate and Restart.

**Comment by marcellanz** [comment]
I will try that next time. Many errors I got with the plugin recently, even let intellij tell me that the index/state of project is inconsistent or damaged (sorry I dont have the correct term it reported) and that I should restart, Then usually everything got indexed after the restart.

**Comment by sh41** [comment]
Fixed in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0) (2026-05-15).

The frame in your trace, `Callable.nameArityInAnyModule`, was removed outright — not renamed — by [`60a8386986`](https://github.com/KronicDeth/intellij-elixir/commit/60a8386986b131504a30fc137c7b994462496728). It was a global fallback that searched the `elixir.all.name` stub index for every function with a matching name whenever in-scope resolution found nothing, and it was the only `StubIndex.processElements(AllName.KEY, …)` call reachable from `Callable`'s resolve chain. Nothing in that chain queries that index now, so this path can no longer reach the consistency check that threw. `Issue463Test.testUnresolvedAliasQualifier` pins the removal.

The throw itself is the platform detecting a stub-tree/index disagreement, and it is still reachable from other plugin call sites — Go to Symbol and module-qualifier autocomplete among them — which is why the sibling `elixir.all.name` reports stay open. This one closes because its own call site is gone.
