### ISSUE TITLE
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads

### ISSUE THREAD

**Issue by marcellanz** [KronicDeth/intellij-elixir#2428]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (12.1)

# Event

### Stacktrace

```
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  0 != 1
  which is length of [] and [PsiElementResolveResult with class org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl: alias]

Recomputation gives [Lcom.intellij.psi.ResolveResult;@7f7c9e1 (class [Lcom.intellij.psi.ResolveResult;) which is equivalent to 'fresh'
Recomputation log:
  Resolving org.elixir_lang.reference.Callable(UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL:null) of class org.elixir_lang.reference.Callable [Plugin: org.elixir_lang]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.psi.impl.source.resolve.ResolveCache.cache(ResolveCache.java:322)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:249)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:92)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:118)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:96)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:80)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:181)
	at org.elixir_lang.psi.Import.modulars(Import.kt:229)
	at org.elixir_lang.psi.Import.treeWalkUp(Import.kt:48)
	at org.elixir_lang.psi.QuoteMacro.treeWalkUp(QuoteMacro.kt:43)
	at org.elixir_lang.psi.QuoteMacro.treeWalkUp(QuoteMacro.kt:18)
```

**Comment by sh41** [comment]
Still reproducible in principle on `main`, and it is neither of the two things it resembles.

[`resolver.Callable.resolveInScope`](https://github.com/KronicDeth/intellij-elixir/blob/8f5189e5430f90a23963721c2ed2803228ee70a3/src/org/elixir_lang/reference/resolver/Callable.kt#L113-L132) has two doors that return `emptyList()` as an ordinary, cacheable value:

```kotlin
return RecursionManager.doPreventingRecursion(element, true) {
    try { … }
    catch (_: StackOverflowError) { Logger.error(…); emptyList() }   // (b)
} ?: emptyList()                                                     // (a)
```

Door (b) is present verbatim in v12.0.1, the version reported here, and is still there. Door (a) was added by [`abc6e0e8e`](https://github.com/KronicDeth/intellij-elixir/commit/abc6e0e8ef036af565932da53d927efda2ef2cba), first shipped in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0).

Neither `[]` is distinguishable from a genuine empty result, so `ResolveCache` caches it. `ResolveCache.cache` then calls `IdempotenceChecker.checkEquivalence` unconditionally whenever another thread has already cached a different value for the same reference — which is what "or on different threads" in the message is. `0 != 1` is one resolve that took a door and one that did not.

Two things this is **not**:

- **Not** the `__MODULE__` non-idempotence group (#2205, #3320, #3467, #3477, #3495, #3517, #3592, #3593) fixed by #3977. That group is a `CachedValue` dependency-array mismatch in `psi/__module__/Reference`; this is a result-count mismatch raised by `ResolveCache` on `reference.Callable`. Different mechanism, different class.
- **Not** a duplicate of #3980. Door (a) postdates this report by four years, so what was reported here came through door (b). But #3980's containment is a second live source of the same symptom: `RecursionManager.prohibitResultCaching` only stamps frames *above* the loop start, so the loop-start reference is still cached and still idempotence-checked. A fix for #3980 that stops the cycle forming would address this too.

Filed as part of an AI-assisted review of the backlog. A human checked this one before it was filed, but it might still be wrong — if any of it is, please say so here.
