### ISSUE TITLE
Don't know how to find ancestorTypeSpec at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245) for ElixirUnmatchedAtOperationImpl

### ISSUE THREAD

**Issue by marcellanz** [KronicDeth/intellij-elixir#2432]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.1)
Operating System: Mac OS X (12.1)

# Event

### Excerpt

```
@spec()
```

From: `/Users/lanzm/Documents/Business/marcellanz/eigr/massa/apps/massa_proxy/lib/massa_proxy/orchestrator.ex:30`
To: `/Users/lanzm/Documents/Business/marcellanz/eigr/massa/apps/massa_proxy/lib/massa_proxy/orchestrator.ex:30`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedAtOperationImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to find ancestorTypeSpec
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:222)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeCallableReference(CallImpl.kt:122)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeReference(CallImpl.kt:77)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference$lambda-4(CallImpl.kt:149)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference(CallImpl.kt:148)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1164)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedParenthesesCallImpl.getReference(ElixirUnmatchedUnqualifiedParenthesesCallImpl.java:101)
```

**Comment by sh41** [comment]
Fixed by 859515eee ("Ignore `@callback(unquote(spec))` when trying to find typespecs", 2022-07-25), which added an `is AtOperation` arm to `ancestorTypeSpec` in `psi/scope/Type.kt`. The element reported here, `ElixirUnmatchedAtOperationImpl`, implements `AtOperation`, so it no longer falls through to the catch-all that logged this.

First release with the fix: v13.2.0. Last release without it: v13.1.1.
