### ISSUE TITLE
java.lang.AssertionError: ParserDefinition absent for language: '' (com.intellij.lang.Language$1), for elementType: 'FILE' (com.intellij.psi.tree.IFileElementType) at com.intellij.lang.impl.PsiBuilderFactoryImpl.getParserDefinition(PsiBuilderFactoryImpl.java:60)

### ISSUE THREAD

**Issue by alexnogueirasilva** [KronicDeth/intellij-elixir#2443]
# System

Plugin Version: 12.0.1
Application: PhpStorm (2021.3.1)
Operating System: Linux (5.15.8-76051508-generic)

# Event

### Stacktrace

```
java.lang.AssertionError: ParserDefinition absent for language: '' (com.intellij.lang.Language$1), for elementType: 'FILE' (com.intellij.psi.tree.IFileElementType)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.getParserDefinition(PsiBuilderFactoryImpl.java:60)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:32)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:56)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:175)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:174)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:226)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:24)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:37)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:744)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:230)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:223)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:531)
	at org.elixir_lang.UsageTargetProvider.getTargets(UsageTargetProvider.kt:21)
```

**Comment by KronicDeth** [comment]
There's not enough context to reproduce this since it is saying there is an empty language name.  It may be due to something outside of this plugin.
