### ISSUE TITLE
Don't know how to find reference variables in Ecto query at org.elixir_lang.ecto.Query.executeOnInReference(Query.kt:216)

### ISSUE THREAD

**Issue by lilpacy** [KronicDeth/intellij-elixir#2451]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.2.3)
Operating System: Mac OS X (12.0.1)

# Event

### Excerpt

```
count(t)
```

From: `/Users/lilpacy/go/src/github.com/lilpacy/blockscout/apps/explorer/lib/explorer/graphql.ex:80`
To: `/Users/lilpacy/go/src/github.com/lilpacy/blockscout/apps/explorer/lib/explorer/graphql.ex:80`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedParenthesesCallImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to find reference variables in Ecto query
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.ecto.Query.executeOnInReference(Query.kt:216)
	at org.elixir_lang.ecto.Query.executeOnIn$Elixir(Query.kt:197)
	at org.elixir_lang.ecto.From.walk(Query.kt:59)
	at org.elixir_lang.psi.NameArityRangeWalker.walk(NameArityRangeWalker.kt:29)
	at org.elixir_lang.psi.ModuleWalker.walkChild(ModuleWalker.kt:23)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:250)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:65)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:155)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:581)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedParenthesesCallImpl.java:141)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1218)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveInScope(MultiResolve.kt:133)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveResultList(MultiResolve.kt:116)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:117)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:100)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by sh41** [comment]
Sorry for the long silence on this — it is still live on `main` today. [`executeOnInReference`](https://github.com/KronicDeth/intellij-elixir/blob/280dcbbcddf4273d5e5aa10923424c43bc7575be/src/org/elixir_lang/ecto/Query.kt#L310-L333) recognises only four shapes for the left operand of `in`: an access expression, a list, a keyword list, and a bare no-arguments call. Your `count(t)` is an `ElixirUnmatchedUnqualifiedParenthesesCall` — a call *with* an argument list — so it falls through to the `else` that logs this error.

Worth saying explicitly, since #2088 and #2175 report the identical message at the identical call site: this is not those. Their fix shipped in [v12.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v12.0.0) (2021-12-05) and you filed against 12.0.1, so you already had it. It added the list and keyword-list cases and never added one for a call with arguments.

The left operand of `in` is an Ecto binding, so a call with arguments can never bind anything — there is nothing for the walker to resolve there and no reason to report an error. The `when` already treats a bare identifier that turns out to resolve to a real call (arity ≠ 0) that way. Leaving this open as the unfixed case.
