### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///home/ndlarsen/src/exercism/elixir/kitchen-calculator/_build/test/lib/kitchen_calculator/ebin/Elixir.KitchenCalculator.beam (invalid) is invalid, invalidated at: no info at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:213)

### ISSUE THREAD

**Issue by ndlarsen** [KronicDeth/intellij-elixir#2460]
# System
Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.1)
Operating System: Linux (5.11.0-43-generic)

```shell
$ mix --version
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Mix 1.13.0 (compiled with Erlang/OTP 24)
```

# Context
Happened while I was running `mix test` in an external terminal and as such I do not know what caused it. My best guess is some attempt at compiling or otherwise parsing the code (which was in fact unable to compile).

# Event
### Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///home/ndlarsen/src/exercism/elixir/kitchen-calculator/_build/test/lib/kitchen_calculator/ebin/Elixir.KitchenCalculator.beam (invalid) is invalid
invalidated at: no info
	at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:213)
	at org.jetbrains.plugins.scala.externalHighlighters.TriggerCompilerHighlightingOnPsiChangeListener$PsiChangeListener.$anonfun$childRemoved$2(TriggerCompilerHighlightingOnPsiChangeListener.scala:35)
	at org.jetbrains.plugins.scala.externalHighlighters.TriggerCompilerHighlightingOnPsiChangeListener$PsiChangeListener.$anonfun$childRemoved$2$adapted(TriggerCompilerHighlightingOnPsiChangeListener.scala:33)
	at org.jetbrains.plugins.scala.extensions.NullSafe$.foreach$extension(NullSafe.scala:50)
	at org.jetbrains.plugins.scala.externalHighlighters.TriggerCompilerHighlightingOnPsiChangeListener$PsiChangeListener.childRemoved(TriggerCompilerHighlightingOnPsiChangeListener.scala:33)
	at com.intellij.psi.impl.PsiManagerImpl.notifyPsiTreeChangeListener(PsiManagerImpl.java:394)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:349)
	at com.intellij.psi.impl.PsiManagerImpl.childRemoved(PsiManagerImpl.java:271)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$filesDeleted$2(PsiVFSListener.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.filesDeleted(PsiVFSListener.java:228)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$fireForGrouped$9(PsiVFSListener.java:759)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.fireForGrouped(PsiVFSListener.java:759)
	at one.util.streamex.CollapseSpliterator.accept(CollapseSpliterator.java:152)
	at one.util.streamex.CollapseSpliterator.forEachRemaining(CollapseSpliterator.java:142)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:351)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.groupAndFire(PsiVFSListener.java:753)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.after(PsiVFSListener.java:742)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$1.after(PsiVFSListener.java:147)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy100.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.fireAfterEvents(PersistentFSImpl.java:1188)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.applyMultipleEvents(PersistentFSImpl.java:1167)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEventsImpl(PersistentFSImpl.java:1130)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.processEventsFromRefresh(AsyncEventSupport.java:150)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEventsInWriteAction(RefreshSessionImpl.java:226)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.lambda$fireEvents$1(RefreshSessionImpl.java:205)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$11(ApplicationImpl.java:911)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$12(ApplicationImpl.java:911)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:935)
	at com.intellij.openapi.application.impl.ApplicationImpl.runEdtProgressWriteAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithNonCancellableProgressInDispatchThread(ApplicationImpl.java:890)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.lambda$fireEvents$2(RefreshSessionImpl.java:199)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:935)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:961)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:198)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.lambda$runAsyncListeners$9(RefreshQueueImpl.java:148)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:577)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by KronicDeth** [comment]
A PsiElement being invalid means that the parser tree was updated, but the code held a reference to an old tree’s element. This could happen due to the file monitor seeing the code changed on disk.

I can fix this by checking `PsiElement#isValid` near the call site for this error.

**Comment by sh41** [comment]
Thanks for this, and sorry it sat so long.

Reading past the top frame: the caller in your trace is the Scala plugin's `TriggerCompilerHighlightingOnPsiChangeListener`, reached through `PsiManagerImpl.childRemoved` and `PsiVFSListener.filesDeleted`. That is the IDE delivering a file-deleted event for the `.beam` your `mix test` run had just rewritten under `_build`, and that listener calls `getContainingFile()` on the element without first checking `isValid()`.

The 2022 reply above offered to add an `isValid` check near the call site. That turns out to be wrong twice over. The check was already there — it has been in `BeamFileImpl` since the class was added in `358cbe158` (December 2016) and has not changed since. And the call site that needs one is not in this plugin. `BeamFileImpl` is modelled on the platform's `ClsFileImpl` for decompiled files, which raises the same exception on an invalid file; dropping the throw would hand callers an invalid `PsiFile` and move the failure somewhere harder to diagnose than an exception that names the file.

So there is nothing here for this plugin to change, and I am closing this as an upstream issue rather than one we can fix. For context on the silence since: as of v19.0.1 (`8c6df9896`) crash reports go to the JetBrains Marketplace exception analyzer instead of opening issues here, which is why reports of this shape stop in early 2024.

#3316, #3528, #3539, #3546, #3548, #3550 and #3551 are the same crash and close as duplicates of this one.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
