### ISSUE TITLE
java.lang.IllegalStateException: @NotNull method org/elixir_lang/code_insight/lookup/element_renderer/Variable.color must not return null at org.elixir_lang.code_insight.lookup.element_renderer.Variable.$$$reportNull$$$0(Variable.java)

### ISSUE THREAD

**Issue by hisnamewasjaan** [KronicDeth/intellij-elixir#2463]
# System

Plugin Version: 12.1.0
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (12.0.1)

# Event

### Stacktrace

```
java.lang.IllegalStateException: @NotNull method org/elixir_lang/code_insight/lookup/element_renderer/Variable.color must not return null
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.$$$reportNull$$$0(Variable.java)
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.color(Variable.java:106)
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.renderElement(Variable.java:52)
```

**Comment by sh41** [comment]
Same defect as #2164: `Variable.color` let a branch overwrite its `JBColor.foreground()` default with a scheme foreground that was `null`, then returned it through an `@NotNull` contract while the completion popup was rendering. Fixed by [`c7d04b78`](https://github.com/KronicDeth/intellij-elixir/commit/c7d04b780ccabf2ef552ad594e5403d56fdbd339) in [v13.1.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v13.1.0) (2022-05-31) — not v13.0.0; full explanation on #2164. Sorry it took so long to answer.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
