### ISSUE TITLE
Don't know how to find ancestorTypeSpec at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245) for ElixirMultipleAliasesImpl

### ISSUE THREAD

**Issue by rgfaber** [KronicDeth/intellij-elixir#2464]
# System

Plugin Version: 12.1.0
Application: JetBrains Rider (2021.3.2)
Operating System: Linux (5.11.0-44-generic)

# Event

### Excerpt

```
{:noreply, new_state}
```

From: `/home/rl/work/github.com/rgfaber/robex/03-todo-application/todo/lib/todo/server.ex:16`
To: `/home/rl/work/github.com/rgfaber/robex/03-todo-application/todo/lib/todo/server.ex:16`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMultipleAliasesImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to find ancestorTypeSpec
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:222)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeCallableReference(CallImpl.kt:122)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeReference(CallImpl.kt:77)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference$lambda-4(CallImpl.kt:149)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference(CallImpl.kt:148)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1048)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.getReference(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:96)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:92)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

### `logs.tar.xz`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by KronicDeth** [comment]
Ooo... cool transient bug during typing.  These are the best as fixing them ensures the editor remains useful while you're typing and the code may not compile.

**Comment by sh41** [comment]
Fixed by a68253127 ("Look above ElixirMultipleAliases for ancestorTypeSpec", 2022-05-20), which added an `is ElixirMultipleAliases` arm to `ancestorTypeSpec` in `psi/scope/Type.kt`, so the transient node you hit while typing walks up to its parent instead of falling through to the catch-all.

First release with the fix: v13.1.0. Last release without it: v13.0.0.
