### ISSUE TITLE
No decompiled source function with name (:expr1.named_fun) at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:70)

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [KronicDeth/intellij-elixir#2475]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Community Edition (2021.3.1)
Operating System: Mac OS X (12.1)

# Event

### Stacktrace

```
java.lang.Throwable: No decompiled source function with name (:expr1.named_fun)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:70)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:411)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda-6$lambda-5(BeamFileImpl.kt:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:391)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:111)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByName(ChooseByNameContributor.kt:62)
```

**Comment by KronicDeth** [comment]
Please upload the `expr1.beam` file:

1. Zip the `expr1.beam`
2. Attach the zip in a comment to this issue.
