### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented. at org.elixir_lang.leex.reference.resolver.Assign.resolveInToRendered(Assign.kt:573)

### ISSUE THREAD

**Issue by mithenji** [KronicDeth/intellij-elixir#2485]
# System

Plugin Version: 12.2.0
Application: WebStorm (2021.3.1)
Operating System: Mac OS X (11.6.2)

# Event

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented.
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInToRendered(Assign.kt:573)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInToRendered(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInToRendered$argumentsAccumulatorContinue$1.invoke(Assign.kt:532)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInToRendered$argumentsAccumulatorContinue$1.invoke(Assign.kt:531)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:42)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:22)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInToRendered(Assign.kt:531)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInToRendered(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInToRendered$1.invoke(Assign.kt:497)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInToRendered$1.invoke(Assign.kt:496)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:28)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.childExpressionsFoldWhile(Modular.kt:19)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressionsFoldWhile(PsiElementImpl.kt:210)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInToRendered(Assign.kt:496)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInToRendered(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInToRendered$3.invoke(Assign.kt:558)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInToRendered$3.invoke(Assign.kt:557)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:42)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInToRendered(Assign.kt:557)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInToRendered(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInToRendered$1.invoke(Assign.kt:497)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInToRendered$1.invoke(Assign.kt:496)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:28)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.childExpressionsFoldWhile(Modular.kt:19)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressionsFoldWhile(PsiElementImpl.kt:210)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInToRendered(Assign.kt:496)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInnerContent$lambda-16(Assign.kt:481)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:74)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:300)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:346)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:51)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInnerContent(Assign.kt:478)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInPhoenixLiveView(Assign.kt:466)
	at org.elixir_lang.leex.reference.resolver.Assign.resolve(Assign.kt:44)
	at org.elixir_lang.leex.reference.resolver.Assign.resolve(Assign.kt:21)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.leex.reference.Assign.multiResolve(Assign.kt:18)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.elixir_lang.folding.Builder$buildFoldRegions$1.slowExecute(Builder.kt:218)
	at org.elixir_lang.folding.Builder$buildFoldRegions$1.slowExecute(Builder.kt:183)
	at org.elixir_lang.folding.Builder$buildFoldRegions$1.execute(Builder.kt:72)
	at org.elixir_lang.folding.Builder$buildFoldRegions$1.execute(Builder.kt:47)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:923)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedExpressionImpl.accept(ElixirUnmatchedExpressionImpl.java:27)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtOperationImpl.accept(ElixirUnmatchedAtOperationImpl.java:29)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:67)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:24)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:76)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:924)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:920)
	at org.elixir_lang.folding.Builder.buildFoldRegions(Builder.kt:40)
```

**Comment by sh41** [comment]
Fixed and released. The `else -> TODO()` in `resolveInToRendered` that this trace ends in was replaced in `b8d2bd2a2`, which removed all six such branches in `Assign.kt` in one pass — first shipped in v14.0.1, with v14.0.0 the last release without it.

The crash is gone, but that branch still doesn't resolve the assign for shapes the resolver doesn't handle: it now logs a diagnostic naming the element and returns, so resolution continues instead of aborting. That remaining gap is tracked in #3981.

Apologies for the long silence here.
