### ISSUE TITLE
Don't know how to find reference variables for keyword key groupby at org.elixir_lang.ecto.From.executeOnFromKeywords(Query.kt:93)

### ISSUE THREAD

**Issue by russpitre** [KronicDeth/intellij-elixir#2492]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.2)
Operating System: Mac OS X (12.1)

# Event

### Excerpt

```
groupby: t
```

From: `/Users/russp/workspace/learn-elixir/programming_ecto_book/priv/repo/playground.exs:76`
To: `/Users/russp/workspace/learn-elixir/programming_ecto_book/priv/repo/playground.exs:76`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirNoParenthesesKeywordPairImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to find reference variables for keyword key groupby
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.ecto.From.executeOnFromKeywords(Query.kt:93)
	at org.elixir_lang.ecto.From.executeOnFromKeywords(Query.kt:75)
	at org.elixir_lang.ecto.From.walk(Query.kt:61)
	at org.elixir_lang.psi.NameArityRangeWalker.walk(NameArityRangeWalker.kt:29)
	at org.elixir_lang.psi.ModuleWalker.walkChild(ModuleWalker.kt:23)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:188)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:38)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:155)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:600)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:203)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:190)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:126)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:100)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.reference.Callable.resolve(Callable.kt:112)
```

**Comment by KronicDeth** [comment]
This is a typo in your code.  Group by has an underscore in it: https://hexdocs.pm/ecto/Ecto.Query.html#group_by/3
