### ISSUE TITLE
java.lang.IllegalStateException: mirror must not be null at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.kt:65)

### ISSUE THREAD

**Issue by tyt0223** [KronicDeth/intellij-elixir#2503]
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Community Edition (2021.2.3)
Operating System: Mac OS X (11.6.1)

# Event

### Stacktrace

```
java.lang.IllegalStateException: mirror must not be null
	at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.kt:65)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByName(ChooseByNameContributor.kt:62)
```

**Comment by KronicDeth** [comment]
Sorry, without file information about the specific `.beam` file I can't triage or reproduce this.
