### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented. at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:275)

### ISSUE THREAD

**Issue by AttafHabib** [KronicDeth/intellij-elixir#2507]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.1)
Operating System: Linux (5.13.0-28-generic)

# Event

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented.
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:275)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:91)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:71)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:70)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:28)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.childExpressionsFoldWhile(Modular.kt:19)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressionsFoldWhile(PsiElementImpl.kt:210)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:67)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:256)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$5.invoke(Assign.kt:243)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$5.invoke(Assign.kt:242)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:42)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:242)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:210)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:91)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:71)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:70)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:28)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.childExpressionsFoldWhile(Modular.kt:19)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressionsFoldWhile(PsiElementImpl.kt:210)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:67)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClause$1.invoke(Assign.kt:59)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClause$1.invoke(Assign.kt:59)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClause(Assign.kt:740)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClause(Assign.kt:59)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInViewModule(Assign.kt:55)
	at org.elixir_lang.leex.reference.resolver.Assign.resolve(Assign.kt:28)
	at org.elixir_lang.leex.reference.resolver.Assign.resolve(Assign.kt:21)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.leex.reference.Assign.multiResolve(Assign.kt:18)
```

**Comment by sh41** [comment]
Fixed and released. The `else -> TODO()` in `resolveInCallDefinitionClauseExpression` that this trace ends in was replaced in `b8d2bd2a2`, which removed all six such branches in `Assign.kt` in one pass — first shipped in v14.0.1, with v14.0.0 the last release without it.

The crash is gone, but that branch still doesn't resolve the assign for shapes the resolver doesn't handle: it now logs a diagnostic naming the element and returns, so resolution continues instead of aborting. That remaining gap is tracked in #3981.

Apologies for the long silence here.
