### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL (class org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoArgumentsCall) at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2508]
Occurred when rename variable like below with Shift + F7, but not always.
From: 
```elixir
defp foo(%{foo_id: foo_id}, %{foo_id: foo_id}), do: :ok
```
To:
```elixir
defp foo(%{foo_id: id}, %{foo_id: id}), do: :ok
```

# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.1)
Operating System: Mac OS X (11.6.3)

# Event

### Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL (class org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoArgumentsCall)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:239)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getProject(StubBasedPsiElementBase.java:276)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:67)
	at org.elixir_lang.refactoring.variable.rename.Inplace.<init>(Inplace.java:32)
	at org.elixir_lang.refactoring.variable.rename.Handler.createRenamer(Handler.kt:73)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:77)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:87)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:54)
```

### `invalidation.trace`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by sh41** [comment]
Same defect as #1461. The plugin's own in-place variable rename handler forwarded the element to the platform's `VariableInplaceRenamer` without checking it was still valid, and the platform reads the containing file off it on trust — so a stale element threw on first access.

`Handler` and `Inplace`, and their `renameHandler` extension-point registrations, were deleted in 2dff82691dce595b694e701cd60df49e5450d07d, first released in [24.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/24.0.0). Elixir rename now runs through the Symbol API, which re-derives the occurrence range from a `Pointer` instead of holding a `PsiElement` across a document change. Thank you for the exact snippet — it is the only one on any report of this crash, and the clause you posted, with one name bound in two map patterns, renames correctly on 24.0.0 from either occurrence.

Closing as a duplicate of #1461, the canonical report for this crash since 2020.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
