### ISSUE TITLE
java.lang.IllegalStateException: setSdk: sdk 'Elixir at /usr/lib/elixir' type 'Elixir SDK' is not registered in ProjectJdkTable at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableRootModelBridgeImpl.setSdk(ModifiableRootModelBridgeImpl.kt:565)

### ISSUE THREAD

**Issue by josph4** [KronicDeth/intellij-elixir#2518]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.2.2)
Operating System: Linux (5.13.0-30-generic)

# Event

### Stacktrace

```
java.lang.IllegalStateException: setSdk: sdk 'Elixir at /usr/lib/elixir' type 'Elixir SDK' is not registered in ProjectJdkTable
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableRootModelBridgeImpl.setSdk(ModifiableRootModelBridgeImpl.kt:565)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor$ModifiableRootModelInvocationHandler.invoke(ModuleEditor.java:352)
	at com.sun.proxy.$Proxy234.setSdk(Unknown Source)
	at com.intellij.openapi.roots.ui.configuration.ClasspathEditor.setSdk(ClasspathEditor.java:159)
	at com.intellij.openapi.roots.ui.configuration.ModuleJdkConfigurable$2.actionPerformed(ModuleJdkConfigurable.java:116)
	at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1264)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:589)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.setSelectedItem(JdkComboBox.java:298)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.setSelectedItem(JdkComboBox.java:261)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.lambda$setSelectedItem$4(JdkComboBox.java:290)
	at com.intellij.openapi.roots.ui.configuration.SdkListModelBuilder.lambda$executeAction$6(SdkListModelBuilder.java:281)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:521)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.setupSdk(ProjectSdksModel.java:507)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.addSdk(ProjectSdksModel.java:449)
	at com.intellij.openapi.roots.ui.configuration.SdkListModelBuilder.executeAction(SdkListModelBuilder.java:307)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.setSelectedItem(JdkComboBox.java:289)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaJBPopupComboPopup.lambda$createPopup$0(DarculaJBPopupComboPopup.java:274)
	at com.intellij.ui.popup.list.ComboBoxPopup$MyBasePopupState.lambda$onChosen$1(ComboBoxPopup.java:200)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:699)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1726)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1699)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:262)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:211)
	at com.intellij.openapi.roots.ui.configuration.ModulesConfigurator.showDialog(ModulesConfigurator.java:547)
	at com.intellij.openapi.roots.ui.configuration.IdeaProjectSettingsService.openModuleSettings(IdeaProjectSettingsService.java:54)
	at com.android.tools.idea.gradle.structure.AndroidProjectSettingsServiceImpl.openModuleSettings(AndroidProjectSettingsServiceImpl.java:116)
	at org.elixir_lang.notification.setup_sdk.Provider$Companion.showModuleSettings(Provider.kt:56)
	at org.elixir_lang.notification.setup_sdk.Provider$Companion.createModulePanel$lambda-3$lambda-2(Provider.kt:95)
```

**Comment by sh41** [comment]
This is a platform defect rather than a plugin one. `ModifiableRootModelBridgeImpl.setSdk` threw whenever it was handed an `Sdk` that was not yet in `ProjectJdkTable` — which is exactly what the documented `SdkType.showCustomCreateUI` contract produces, and what this plugin does. It never calls `setSdk` itself.

JetBrains fixed it as IJPL-218412 ([7d2c397439b](https://github.com/JetBrains/intellij-community/commit/7d2c397439b10773b5a7809ca486ab2af86be45b), 2025-11-13): the throw is now a log line that falls through to the existing `setInvalidSdk` path, so the module SDK is marked invalid instead of the IDE crashing. It first shipped in IntelliJ Platform 2026.1 and was not backported to 2025.3.x.

Being honest about what that means: the plugin supports IDEs from 2025.3 onwards, so if you are on 2025.3.x you can still hit this. Upgrading the IDE to 2026.1 or newer is the fix, and there is nothing the plugin can change — the throw happens downstream of the callback it hands the new SDK to. #2590, #2638 and #3104 are the same defect.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
