### ISSUE TITLE
java.lang.IllegalStateException: mirror must not be null at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:111)

### ISSUE THREAD

**Issue by vasyl-zhurba** [KronicDeth/intellij-elixir#2530]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Community Edition (2021.3.2)
Operating System: Mac OS X (12.2.1)

# Event

## Message

In file: file:///Users/vasyl.zhurba/Projects/bynk-admin-2.0/lib/bynk_admin_web/controllers/subscription_controller.ex

### Stacktrace

```
java.lang.IllegalStateException: mirror must not be null
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:111)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:111)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:96)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:80)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:181)
	at org.elixir_lang.psi.impl.call.qualification.QualifiedImplKt.qualifiedToModulars(QualifiedImpl.kt:19)
	at org.elixir_lang.reference.resolver.Callable.resolveQualified(Callable.kt:142)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:98)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.accept(ElixirMatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment]
`getNavigationElement` is no longer called as it led to performance issues with over decompiling, so this bug is no longer relevant.
