### ISSUE TITLE
java.lang.IllegalStateException: mirror must not be null at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.kt:65)

### ISSUE THREAD

**Issue by kyle-neal** [KronicDeth/intellij-elixir#2534]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Community Edition (2021.3.2)
Operating System: Mac OS X (12.2.1)

# Event

### Stacktrace

```
java.lang.IllegalStateException: mirror must not be null
	at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.kt:65)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByName(ChooseByNameContributor.kt:62)
```

**Comment by KronicDeth** [comment]
`ChooseByNameContributor` no longer calls `getNavigationElement`, so this is irrelevant in the current version.
