### ISSUE TITLE
Don't know how to get name of parameter at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:136)

### ISSUE THREAD

**Issue by yordis** [KronicDeth/intellij-elixir#2537]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.2)
Operating System: Mac OS X (12.1)

# Event

### Excerpt

```
result t, (any -> any)
```

From: `/Users/ubi/Developer/github.com/straw-hat-team/one_piece_result/lib/one_piece/result.ex:191`
To: `/Users/ubi/Developer/github.com/straw-hat-team/one_piece_result/lib/one_piece/result.ex:191`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnqualifiedNoParenthesesManyArgumentsCallImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to get name of parameter
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:136)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHeadArguments(MultiResolve.kt:38)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHeadArguments(MultiResolve.kt:33)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHead(MultiResolve.kt:29)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnType(MultiResolve.kt:25)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:91)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:63)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:35)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:64)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:592)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:152)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults(MultiResolve.kt:164)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:159)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:42)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:23)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
```

**Comment by sh41** [comment]
Still open, but the diagnosis has moved. The path these reports came through is fixed; the log call is not.

`MultiResolve.executeOnParameter` is a `when` over the PSI shapes a type parameter can take, and its `else` files this report for anything it does not model. Malformed source is where those shapes come from — `file-` in a head parses as an addition operation missing its right operand, the `ElixirUnmatchedAdditionOperationImpl` #3308 names. No branch was ever added for any of them.

What stopped the reports is 26d7d713a, first stable in 24.0.0: `executeOnTypeHead` now walks a head's arguments only for `@type`, `@typep` and `@opaque`, so a `@spec` or `@callback` head never reaches `executeOnParameter`. Checked against current main on a fixture matching these reports — nothing logged. The three reports in this group that carry a context block all show a `@spec`; the 12.2.0/13.0.0-era Logger emitted no context, so the other four name only the failing element.

The `else` is unchanged and still reachable from a `@type` head, whose arguments are still walked because that is where type variables are genuinely declared: `@type upload(file-) :: {:map, :any}` logs this error seven times on current main. The reports are gone, the gap is not, so this stays open as the canonical for it.

The same fixture trips two more of these in `annotator.ModuleAttribute`. Adding one arm per report is not the fix — #3985 tracks this family and asks what these `when`s should do by default with a shape they do not model. This issue is attached to it.

#2538, #2539, #2650, #3081, #3304 and #3308 are the same defect and closed as duplicates of this one.

> This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
