### ISSUE TITLE
Don't know how to get name of parameter at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:136)

### ISSUE THREAD

**Issue by lilpacy** [KronicDeth/intellij-elixir#2538]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.2.3)
Operating System: Mac OS X (12.2.1)

# Event

### Excerpt

```
aIntellijIdeaRulezzz ()
```

            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnqualifiedNoParenthesesManyArgumentsCallImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to get name of parameter
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:136)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHeadArguments(MultiResolve.kt:38)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHeadArguments(MultiResolve.kt:33)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHead(MultiResolve.kt:29)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnType(MultiResolve.kt:25)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:91)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:63)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:35)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:64)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:592)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:152)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1218)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults(MultiResolve.kt:164)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:159)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:42)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:23)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
```

**Comment by sh41** [comment]
Duplicate of #2537 — the same log call in `MultiResolve.executeOnParameter`, whose `when` has no branch for the shape the element under the caret parses to. The plugin version that filed this report did not include the surrounding code, so it names the failing element and nothing above it; #2537 carries the diagnosis for the whole group.

The reported path is fixed. Since 24.0.0 the resolver no longer walks a `@spec` or `@callback` head's arguments at all, which is where every report in this group with visible context had its malformed argument — checked against current main. The `else` itself is unchanged and stays reachable from a `@type` head, whose arguments are still walked because that is where type variables are genuinely declared. That is what #2537 stays open for.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
