### ISSUE TITLE
Erlang Abst record_field field is unknown at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.error(AbstractCode.kt:91)

### ISSUE THREAD

**Issue by CYPT71** [KronicDeth/intellij-elixir#2544]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.2)
Operating System: Linux (5.15.25-1-MANJARO)

# Event

### Term

{var,{135,68},'_'}

### Stacktrace

```
java.lang.Throwable: Erlang Abst record_field field is unknown
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:66)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.error(AbstractCode.kt:91)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.fieldToString(RecordField.kt:28)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.setFieldString(RecordField.kt:56)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.setToMacroStringDeclaredScope(RecordField.kt:60)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.toMacroStringDeclaredScope(RecordField.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.ifToMacroStringDeclaredScope(RecordField.kt:11)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:73)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedMacroStringDeclaredScope(Sequence.kt:42)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedMacroStringDeclaredScope(Sequence.kt:37)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.creationRecordFieldsMacroStringDeclaredScope(Record.kt:50)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.creationToMacroStringDeclaredScope(Record.kt:39)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.toMacroStringDeclaredScope(Record.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.ifToMacroStringDeclaredScope(Record.kt:13)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:72)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toString(AbstractCode.kt:46)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Match.rightString(Match.kt:29)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Match.toMacroStringDeclaredScope(Match.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Match.ifToMacroStringDeclaredScope(Match.kt:10)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:67)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:93)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.clause.Body.toMacroStringDeclaredScope(Body.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Clause.bodyString(Clause.kt:15)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.function.Clause.toMacroString(Clause.kt:20)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function$toMacroString$1.invoke(Function.kt:34)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function$toMacroString$1.invoke(Function.kt:34)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3344)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3361)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3360)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function.toMacroString(Function.kt:34)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:419)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:404)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:395)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:264)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:214)
	at org.elixir_lang.beam.Decompiler$Companion.decompiled(Decompiler.kt:71)
	at org.elixir_lang.beam.Decompiler$Companion.access$decompiled(Decompiler.kt:33)
	at org.elixir_lang.beam.Decompiler.decompile(Decompiler.kt:31)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:536)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.loadText(FileDocumentManagerBase.java:89)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:46)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:377)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:111)
	at org.elixir_lang.psi.scope.atom.Variants.projectLookupElementStream(Variants.java:49)
	at org.elixir_lang.psi.scope.atom.Variants.lookupElementList(Variants.java:24)
	at org.elixir_lang.reference.Atom.getVariants(Atom.java:25)
```

**Comment by KronicDeth** [comment]
I need to include the file name in the error message in the future.

**Comment by sh41** [comment]
Same defect as #2728: an Erlang wildcard variable (`{var, _, '_'}`) used as a record-field name. Fixed in **v23.0.7** — not in v23.0.5 — see #2728 for the commits. Closing as a duplicate of that one.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
