### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL (class org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoArgumentsCall) at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)

### ISSUE THREAD

**Issue by FilipJakab** [KronicDeth/intellij-elixir#2547]
When renaming variable inside with-else block inside tuple
# System

Plugin Version: 12.2.0
Application: RubyMine (2021.3.2)
Operating System: Linux (5.16.11-arch1-1)

# Event

### Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL (class org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoArgumentsCall)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:239)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.<init>(InplaceRefactoring.java:141)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:82)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:73)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:67)
	at org.elixir_lang.refactoring.variable.rename.Inplace.<init>(Inplace.java:32)
	at org.elixir_lang.refactoring.variable.rename.Handler.createRenamer(Handler.kt:73)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:77)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:87)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:54)
```

**Comment by sh41** [comment]
Same defect as #1461. The plugin's own in-place variable rename handler forwarded the element to the platform's `VariableInplaceRenamer` without checking it was still valid, and the platform reads the containing file off it on trust — so a stale element threw on first access. The `with`/`else` shape you describe is not special here; any caret whose resolve result had been invalidated hit the same unchecked constructor.

`Handler` and `Inplace`, and their `renameHandler` extension-point registrations, were deleted in 2dff82691dce595b694e701cd60df49e5450d07d, first released in [24.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/24.0.0). Elixir rename now runs through the Symbol API, which re-derives the occurrence range from a `Pointer` instead of holding a `PsiElement` across a document change.

Closing as a duplicate of #1461, the canonical report for this crash since 2020.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
