### ISSUE TITLE
typing a module alias that didn't exist yet in the project.

### ISSUE THREAD

**Issue by digitsu** [KronicDeth/intellij-elixir#2550]
# System

Plugin Version: 12.2.0
Application: WebStorm (2021.3.2)
Operating System: Mac OS X (12.3)

# What I was doing

typing a module alias that didn't exist yet in the project.

# Event

### Excerpt

```
@game_over_scene .Scene.GameOver
```

From: `/Users/digitsu/dev/frobots_umbrella/apps/frobots_scenic/lib/scenes/game.ex:17`
To: `/Users/digitsu/dev/frobots_umbrella/apps/frobots_scenic/lib/scenes/game.ex:17`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how process element as type
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.Type$Companion.error(Type.kt:186)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:46)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:322)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:672)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.processDeclarations(ElixirUnmatchedQualifiedAliasImpl.java:85)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:400)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:399)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:302)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:403)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:379)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:235)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:640)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults(MultiResolve.kt:164)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:159)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:42)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:23)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by sh41** [comment]
Fixed. A bare qualified alias — one you have started typing but not yet declared, or one left half-deleted — reached `Type.execute`'s `else` branch, which reported it rather than treating it as "nothing to declare here".

`Skip bare Aliases when resolving Types` added `is QualifiableAlias` to that walker's ignore list, first released in v15.1.0. You were on 12.2.0, well before it.

#2551, #3355 and #3356 are the same defect and close as duplicates of this one. #3165 shares the error message but is a different shape — `opts[:key]` on the right of a match — and stays open. All of them are now tracked under #3985, which asks what this walker should do by default with a shape it does not model, instead of adding one arm per report.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
