### ISSUE TITLE
trying to set the facet elixir SDK

### ISSUE THREAD

**Issue by digitsu** [KronicDeth/intellij-elixir#2562]
# System

Plugin Version: 12.2.0
Application: WebStorm (2021.3.3)
Operating System: Mac OS X (12.3)

# What I was doing

trying to set the facet elixir SDK

# Event

### Stacktrace

```
java.lang.Throwable: Do not use module level message bus
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:196)
	at org.elixir_lang.facet.configurable.Project.setFacetSdk(Project.kt:61)
	at org.elixir_lang.facet.configurable.Project.access$setFacetSdk(Project.kt:16)
	at org.elixir_lang.facet.configurable.Project$createModuleConfigurable$1.applySdk(Project.kt:39)
	at org.elixir_lang.facet.Configurable.apply(Configurable.kt:33)
```

**Comment by digitsu** [comment]
Actually I think that deleting the project.iml file that was left in the project dir, and restarting WebStorm fixed this.  It seems that older versions of the plugin wrote to the project.iml to the project root, and having that old file there confused things.  When I moved the project into an umbrella project the old .iml was still there.  

Deleting it made the plugin write the project.iml into the project/.idea dir, which seems to fix the issue.

**Comment by digitsu** [comment]
closing
