### ISSUE TITLE
Running mix deps.get from a 'elixir mix' run configuration on IDEA, on the top level umbrella project as root module

### ISSUE THREAD

**Issue by digitsu** [KronicDeth/intellij-elixir#2566]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Community Edition (2021.3.3)
Operating System: Mac OS X (12.3)

# What I was doing

Running mix deps.get from a 'elixir mix' run configuration on IDEA, on the top level umbrella project as root module

# Event

### Stacktrace

```
java.lang.Throwable: Stub index points to a file (file = file:///Users/digitsu/dev/frobots_umbrella/deps/mint/src/mint_shims.erl, file type = AbstractFileType Erlang; com.intellij.ide.highlighter.custom.SyntaxTable@5847a1e0, indexed file type = AbstractFileType Erlang; com.intellij.ide.highlighter.custom.SyntaxTable@5847a1e0) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$4(StubIndexImpl.java:339)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:338)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:51)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:185)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:90)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment]
The "mint_shims.erl, file type = AbstractFileType Erlang" would make me think that is a bug with the Erlang plugin OR something with a the JetBrains API itself.  Please report to them.
