### ISSUE TITLE
Stub ids not found for key in index = elixir.all.name, file = file:///Users/digitsu/dev/frobots_umbrella/_build/dev/lib/phoenix/ebin/Elixir.Phoenix.Digester.Compressor.beam, file type = BEAM, indexed file type = BEAM at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:65)

### ISSUE THREAD

**Issue by digitsu** [KronicDeth/intellij-elixir#2567]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Community Edition (2021.3.3)
Operating System: Mac OS X (12.3)

# Event

### Stacktrace

```
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name, file = file:///Users/digitsu/dev/frobots_umbrella/_build/dev/lib/phoenix/ebin/Elixir.Phoenix.Digester.Compressor.beam, file type = BEAM, indexed file type = BEAM
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:65)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$4(StubIndexImpl.java:339)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:338)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:51)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:185)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:90)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by sh41** [comment]
Fixed, and a duplicate of #2427 — the same call site, reported five weeks apart with a different `.beam` file.

The frame above the platform's throw here, `org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule`, was the resolver's global fallback into the `elixir.all.name` stub index. It was removed outright — not renamed — by [`60a8386`](https://github.com/KronicDeth/intellij-elixir/commit/60a8386986b131504a30fc137c7b994462496728), first shipped in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0). `Callable`'s resolve chain no longer queries that index at all, and `Issue463Test.testUnresolvedAliasQualifier` fails if the fallback comes back.

Other `elixir.all.name` reports stay open: the platform throw is still reachable from call sites that do query that index, and each needs checking on its own.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
