### ISSUE TITLE
Account.sign_in(email, password),  parent={:ok, token, _claims} <- Account.sign_in(email, password) at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:284)

### ISSUE THREAD

**Issue by stardustrain** [KronicDeth/intellij-elixir#2571]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Community Edition (2021.3.2)
Operating System: Mac OS X (12.3)

# Event

### Stacktrace

```
java.lang.Throwable: Account.sign_in(email, password)
 parent={:ok, token, _claims} <- Account.sign_in(email, password)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:284)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.getRelativeIdentifier(ElixirMatchedQualifiedParenthesesCallImpl.java:62)
	at org.elixir_lang.psi.impl.call.CallImpl.functionNameElement(CallImpl.kt:376)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionNameElement(ElixirPsiImplUtil.java:857)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.functionNameElement(ElixirMatchedQualifiedParenthesesCallImpl.java:82)
	at org.elixir_lang.psi.impl.call.CallImpl.functionName(CallImpl.kt:346)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionName(ElixirPsiImplUtil.java:825)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.functionName(ElixirMatchedQualifiedParenthesesCallImpl.java:77)
	at org.elixir_lang.psi.impl.call.CallImpl.isCalling(CallImpl.kt:425)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCalling(ElixirPsiImplUtil.java:228)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.isCalling(ElixirMatchedQualifiedParenthesesCallImpl.java:122)
	at org.elixir_lang.psi.impl.call.CallImpl.isCalling(CallImpl.kt:448)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCalling(ElixirPsiImplUtil.java:235)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.isCalling(ElixirMatchedQualifiedParenthesesCallImpl.java:127)
	at org.elixir_lang.psi.impl.call.CallImpl.isCallingMacro(CallImpl.kt:489)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCallingMacro(ElixirPsiImplUtil.java:249)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.isCallingMacro(ElixirMatchedQualifiedParenthesesCallImpl.java:137)
	at org.elixir_lang.psi.CallDefinitionClause.isCallingKernelMacroOrHead(CallDefinitionClause.kt:121)
	at org.elixir_lang.psi.CallDefinitionClause.isPrivateFunction(CallDefinitionClause.kt:75)
	at org.elixir_lang.psi.CallDefinitionClause.isFunction(CallDefinitionClause.kt:70)
	at org.elixir_lang.psi.CallDefinitionClause.is(CallDefinitionClause.kt:67)
	at org.elixir_lang.psi.impl.PsiNameIdentifierOwnerImpl.getNameIdentifier(PsiNameIdentifierOwnerImpl.kt:59)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getNameIdentifier(ElixirPsiImplUtil.java:987)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.getNameIdentifier(ElixirMatchedQualifiedParenthesesCallImpl.java:102)
	at org.elixir_lang.psi.impl.NamedStubbedPsiElementBase.getTextOffset(NamedStubbedPsiElementBase.java:21)
```

**Comment by KronicDeth** [comment]
Something is wrong with the error reporter since I wouldn't expect the source code to just be in the Throwable message like this. I won't be able to decipher the actual bug as is.
