### ISSUE TITLE
No decompiled source function with name/arity (Ecto.Schema.Metadata.__struct__/1) at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:67)

### ISSUE THREAD

**Issue by kxkannan** [KronicDeth/intellij-elixir#2576]
# System

Plugin Version: 12.2.0
Application: RubyMine (2021.2)
Operating System: Mac OS X (12.3)

# Event

### Stacktrace

```
java.lang.Throwable: No decompiled source function with name/arity (Ecto.Schema.Metadata.__struct__/1)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:67)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:411)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda-6$lambda-5(BeamFileImpl.kt:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:391)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:111)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:111)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:96)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:80)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:181)
	at org.elixir_lang.psi.impl.call.qualification.QualifiedImplKt.qualifiedToModulars(QualifiedImpl.kt:19)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:28)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:21)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedQualifiedNoArgumentsCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment]
`getNavigatinElement` is no longer be called in `org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars`, so this is no longer relevant.
