### ISSUE TITLE
Don't know how find type variable restrictions at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationInTypeSpecRestrictions(ProcessDeclarationsImpl.kt:106)

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2577]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.3)
Operating System: Mac OS X (11.6.5)

# Event

### Excerpt
Invoked when writing like below.
```elixir
  @spec map_all(Enum.t(), (x -> {:ok, y} | :error)) :: {:ok, [y]} | :error when x: any, y: any
  defp map_all(enumerable, fun) do
  end
```
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirTupleImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how find type variable restrictions
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationInTypeSpecRestrictions(ProcessDeclarationsImpl.kt:106)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationInTypeSpecArgument(ProcessDeclarationsImpl.kt:87)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationInTypeSpecArgument(ProcessDeclarationsImpl.kt:79)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:66)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:592)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:152)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:137)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:128)
	at org.elixir_lang.reference.resolver.Module.resolveInScope(Module.kt:78)
	at org.elixir_lang.reference.resolver.Module.resolveAll(Module.kt:73)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:67)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:34)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:30)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:22)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:92)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:80)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:181)
	at org.elixir_lang.psi.impl.call.qualification.QualifiedImplKt.qualifiedToModulars(QualifiedImpl.kt:19)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:28)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:21)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.accept(ElixirUnmatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment]
I can't figure out exactly you triggered it, but putting `{}` immediately after `when` does trigger it, so I'll just ignore that the way I do `Call` already.
