### ISSUE TITLE
Importing mix-project does fail with `NoSuchMethodError`

### ISSUE THREAD

**Issue by NobbZ** [KronicDeth/intellij-elixir#258]
On importing a mix-project I do get the stack trace posted below.

Environment: IntelliJ 14.0.2, Ubuntu 14.04 LTS, Java 1.7.0_80-b15 is driving IntelliJ

```plain
com.intellij.openapi.fileChooser.FileChooserDescriptorFactory.createSingleFileDescriptor()Lcom/intellij/openapi/fileChooser/FileChooserDescriptor;
java.lang.NoSuchMethodError: com.intellij.openapi.fileChooser.FileChooserDescriptorFactory.createSingleFileDescriptor()Lcom/intellij/openapi/fileChooser/FileChooserDescriptor;
	at org.elixir_lang.mix.settings.MixConfigurationForm.<init>(MixConfigurationForm.java:39)
	at org.elixir_lang.mix.importWizard.MixProjectRootStep.$$$setupUI$$$(MixProjectRootStep.java)
	at org.elixir_lang.mix.importWizard.MixProjectRootStep.<init>(MixProjectRootStep.java:50)
	at org.elixir_lang.mix.importWizard.MixProjectImportProvider.createSteps(MixProjectImportProvider.java:22)
	at com.intellij.projectImport.ProjectImportProvider.addSteps(ProjectImportProvider.java:90)
	at com.intellij.ide.util.newProjectWizard.modes.ImportMode.createSteps(ImportMode.java:75)
	at com.intellij.ide.util.newProjectWizard.modes.WizardMode.getSteps(WizardMode.java:51)
	at com.intellij.ide.util.newProjectWizard.AddModuleWizard.initModuleWizard(AddModuleWizard.java:113)
	at com.intellij.ide.util.newProjectWizard.AddModuleWizard.<init>(AddModuleWizard.java:76)
	at com.intellij.ide.actions.ImportModuleAction.createImportWizard(ImportModuleAction.java:183)
	at com.intellij.ide.actions.ImportModuleAction.selectFileAndCreateWizard(ImportModuleAction.java:126)
	at com.intellij.ide.actions.ImportModuleAction.selectFileAndCreateWizard(ImportModuleAction.java:104)
	at com.intellij.ide.actions.ImportModuleAction.doImport(ImportModuleAction.java:63)
	at com.intellij.ide.actions.ImportProjectAction.actionPerformed(ImportProjectAction.java:31)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:926)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by zyuyou** [comment]
@NobbZ I'm sorry about that the new api `FileChooserDescriptorFactory.createSingleFileDescriptor()` may not be supported by `IntelliJ 14.0.2`. I tested it on `IntelliJ 14.1`, `IntelliJ 15.0.2`, they just works fine.

**Comment by KronicDeth** [comment]
If it works in later versions we'll have to fix this by changing the declared compatible versions in plugin.XML.  I was expecting to have to change that anyway for the color constant deprecation in Minerva.

**Comment by zyuyou** [comment]
[previous version list](https://confluence.jetbrains.com/display/IntelliJIDEA/Previous+IntelliJ+IDEA+Releases) they are no  `14.0.2`, the latest one is `14.0.4`.

**Comment by NobbZ** [comment]
I'll try to convince sysop to do an update then, pointing to this issue.
Thank you anyway.

Yuyou Chow <notifications@github.com> schrieb am Sa., 19. März 2016 15:07:

**Comment by KronicDeth** [comment]
While working on #250, I read through the ant files, and the travis-ci build is testing against 14.1.6, which was the last release in the 14.1 line, so the build automation is only guaranteeing compatibility with 14.1 right now.  I'm considering adding a build for the latest PATCH for each MAJOR.MINOR pair since it appears that's what JetBrains keeps track of in https://confluence.jetbrains.com/display/IntelliJIDEA/Previous+IntelliJ+IDEA+Releases.

**Comment by KronicDeth** [comment]
@NobbZ bad news: after getting the build working with 14.0 to 2016.1 in #263, I had to drop 14.0 support because the newest GrammarKit (which I use to generate the parser) only generates code compatible with 14.1 to 2016.1, so you'll need to update to at least 14.1 or newer when I release [`v2.3.0`](https://github.com/KronicDeth/intellij-elixir/milestones/v2.3.0).

**Comment by NobbZ** [comment]
I totally forgot about this one. In the meantime I was able to convince my
SysOp to update to 15.x. I have to live with that for now, 16 would break
an addon that is used by another dev-team and we are working on the same
systems image.

Luke Imhoff <notifications@github.com> schrieb am Fr., 25. März 2016 um
05:59 Uhr:
