### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'frobots' (disposed) at com.intellij.serviceContainer.ComponentManagerImpl.checkState(ComponentManagerImpl.kt:184)

### ISSUE THREAD

**Issue by digitsu** [KronicDeth/intellij-elixir#2582]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Community Edition (2021.3.3)
Operating System: Mac OS X (12.3.1)

# Event

### Stacktrace

```
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'frobots' (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkState(ComponentManagerImpl.kt:184)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:533)
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:37)
	at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:182)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:172)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:155)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:182)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:96)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInLibrary(ProjectFileIndexImpl.java:185)
	at com.intellij.openapi.module.ModuleUtilCore.findModuleForPsiElement(ModuleUtilCore.java:108)
	at org.elixir_lang.sdk.elixir.Type$Companion.mostSpecificSdk(Type.kt:505)
	at org.elixir_lang.notification.setup_sdk.Provider.createNotificationPanel(Provider.kt:35)
	at org.elixir_lang.notification.setup_sdk.Provider.createNotificationPanel(Provider.kt:25)
```

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/blob/416d3487b2956fe190a852420a76e81ac8284c0e/src/org/elixir_lang/sdk/elixir/Type.kt#L505

**Comment by KronicDeth** [comment]
Since I am asking the API for the module without knowing it, I'm not sure how I could know the module is not disposed before I try to find it.   I'll check that the `project` is not disposed and just catch the exception as that's the best I can.  🤷🏻‍♀️
