### ISSUE TITLE
java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/hi/.cache/JetBrains/IntelliJIdea2021.2/caches/names.dat at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)

### ISSUE THREAD

**Issue by muneebmj0** [KronicDeth/intellij-elixir#2585]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.2.4)
Operating System: Linux (5.13.0-39-generic)

# Event

### Stacktrace

```
java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/hi/.cache/JetBrains/IntelliJIdea2021.2/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSConnection.handleError(PersistentFSConnection.java:291)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.handleError(FSRecords.java:717)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAndHandleErrors(FSRecords.java:262)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.setName(FSRecords.java:530)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.lambda$writeAttributesToRecord$0(FSRecords.java:98)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAndHandleErrors(FSRecords.java:259)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAttributesToRecord(FSRecords.java:97)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.writeAttributesToRecord(PersistentFSImpl.java:317)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.makeChildRecord(PersistentFSImpl.java:1559)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$findChildInfo$4(PersistentFSImpl.java:421)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.update(FSRecords.java:302)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findChildInfo(PersistentFSImpl.java:432)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:150)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:132)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:78)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:537)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:45)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:56)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java:59)
	at com.intellij.openapi.fileEditor.impl.IdeDocumentHistoryImpl.getChangedFiles(IdeDocumentHistoryImpl.java:393)
	at com.intellij.psi.search.PredefinedSearchScopeProviderImpl.recentFilesScope(PredefinedSearchScopeProviderImpl.java:241)
	at com.intellij.psi.search.PredefinedSearchScopeProviderImpl.getPredefinedScopes(PredefinedSearchScopeProviderImpl.java:99)
	at com.intellij.find.findUsages.FindUsagesOptions.findScopeByName(FindUsagesOptions.java:43)
	at com.intellij.find.findUsages.FindUsagesOptions.<init>(FindUsagesOptions.java:31)
	at com.intellij.find.findUsages.FindUsagesOptions.<init>(FindUsagesOptions.java:27)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:68)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:90)
	at org.elixir_lang.UsageTargetProvider.getTargets(UsageTargetProvider.kt:29)
	at org.elixir_lang.UsageTargetProvider.getTargets(UsageTargetProvider.kt:22)
```

**Comment by KronicDeth** [comment]
Please report this to JetBrains
