### ISSUE TITLE
Failing to evaluate anything in debugger

### ISSUE THREAD

**Issue by solution-al** [KronicDeth/intellij-elixir#2587]
IDEA 2021.3.3 (Ultimate Edition)
Elixir plugin 12.2.0

While trying to evaluate anything in IDEA debugger, I'm getting an exception and the whole Elixir application crashes:

```
java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {{badkey,vars},[{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:807)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {{badkey,vars},[{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	... 17 more
Caused by: java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {{badkey,vars},[{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.elixir_lang.MailBox.wait(MailBox.kt:203)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.evaluate(Node.kt:206)
	at org.elixir_lang.debugger.Process.evaluate(Process.kt:415)
	at org.elixir_lang.debugger.Evaluator.evaluate(Evaluator.kt:19)
	at com.intellij.xdebugger.evaluation.XDebuggerEvaluator.evaluate(XDebuggerEvaluator.java:35)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.startEvaluation(XDebuggerEvaluationDialog.java:344)
	at com.intellij.xdebugger.impl.ui.tree.nodes.EvaluatingExpressionRootNode$EvaluatingResultContainer.computeChildren(EvaluatingExpressionRootNode.java:33)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.startComputingChildren(XValueContainerNode.java:57)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.loadChildren(XValueContainerNode.java:47)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.getChildren(XValueContainerNode.java:263)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XDebuggerTreeNode.getChildCount(XDebuggerTreeNode.java:52)
	at java.desktop/javax.swing.tree.DefaultTreeModel.getChildCount(DefaultTreeModel.java:192)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1457)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:728)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:629)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:4324)
	at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:607)
	at java.desktop/javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:391)
	at java.desktop/javax.swing.tree.DefaultTreeModel.setRoot(DefaultTreeModel.java:141)
	at com.intellij.xdebugger.impl.ui.tree.XDebuggerTree.setRoot(XDebuggerTree.java:298)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.evaluate(XDebuggerEvaluationDialog.java:297)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.doOKAction(XDebuggerEvaluationDialog.java:189)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1858)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1810)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog$4.actionPerformed(XDebuggerEvaluationDialog.java:198)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicRootPaneUI$Actions.actionPerformed(BasicRootPaneUI.java:254)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI$Actions.actionPerformed(BasicComboBoxUI.java:1672)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2903)
	at java.desktop/javax.swing.JComboBox.processKeyBinding(JComboBox.java:1431)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2965)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2865)
	at java.desktop/java.awt.Component.processEvent(Component.java:6431)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:881)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1164)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4910)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	... 22 more
Caused by: com.ericsson.otp.erlang.OtpErlangExit: {{badkey,vars},[{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/tmp/intellij_elixir2/debugger/lib/intellij_elixir/debugger/server.ex"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
	at com.ericsson.otp.erlang.OtpMbox.receiveMsg(OtpMbox.java:272)
	at com.ericsson.otp.erlang.OtpMbox.receive(OtpMbox.java:168)
	at org.elixir_lang.MailBox.loop(MailBox.kt:219)
	at org.elixir_lang.MailBox._init_$lambda-0(MailBox.kt:26)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

To reproduce, set a breakpoint into Phoenix application, start that application with a debugger and if breakpoint is reached then open up evaluation dialog on try to evaluate whatever (for example: 1). Application crashes and debug session ends.

**Comment by solution-al** [comment]
Found out that it is a duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2166

Closing here.
