### ISSUE TITLE
java.lang.IllegalStateException: mirror must not be null at org.elixir_lang.beam.psi.impl.TypeDefinitionImpl.getNavigationElement(TypeDefinitionImpl.kt:66)

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2607]
Write like below, and do Find Usages(⌥F7) at `map`.
```elixir
defmodule Foo do
  @spec bar :: map
  def bar, do: "bar"
end
```

# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.3)
Operating System: Mac OS X (11.6.5)

# Event

### Stacktrace

```
java.lang.IllegalStateException: mirror must not be null
	at org.elixir_lang.beam.psi.impl.TypeDefinitionImpl.getNavigationElement(TypeDefinitionImpl.kt:66)
```

**Comment by KronicDeth** [comment]
I get a StackOverflow at the same time
