### ISSUE TITLE
com.intellij.openapi.util.TraceableDisposable$DisposalException: Already disposed

### ISSUE THREAD

**Issue by GiorgioG** [KronicDeth/intellij-elixir#2623]
# System

Plugin Version: 12.3.0-pre+20220418164904
Application: IntelliJ IDEA Ultimate Edition (2022.1)
Operating System: Mac OS X (12.3.1)

# Event

### Stacktrace

```
com.intellij.openapi.util.TraceableDisposable$DisposalException: Already disposed:
-------------Own trace:
com.intellij.openapi.util.TraceableDisposable$DisposalException: 421628323
	at com.intellij.openapi.util.TraceableDisposable.getStackTrace(TraceableDisposable.java:78)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.checkDisposed(VirtualFilePointerContainerImpl.java:389)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getOrCache(VirtualFilePointerContainerImpl.java:199)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getFiles(VirtualFilePointerContainerImpl.java:290)
	at com.intellij.openapi.projectRoots.impl.RootsAsVirtualFilePointers.getFiles(RootsAsVirtualFilePointers.java:40)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl$MyRootProvider.getFiles(ProjectJdkImpl.java:285)
	at org.elixir_lang.Erl.ebinDirectories(Erl.kt:48)
	at org.elixir_lang.Erl.prependCodePaths(Erl.kt:39)
	at org.elixir_lang.Erl.setErl(Erl.kt:62)
	at org.elixir_lang.Erl.commandLine(Erl.kt:16)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:20)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.mix.project._import.step.Root$1.run(Root.java:80)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:44)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.checkDisposed(VirtualFilePointerContainerImpl.java:389)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getOrCache(VirtualFilePointerContainerImpl.java:199)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getFiles(VirtualFilePointerContainerImpl.java:290)
	at com.intellij.openapi.projectRoots.impl.RootsAsVirtualFilePointers.getFiles(RootsAsVirtualFilePointers.java:40)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl$MyRootProvider.getFiles(ProjectJdkImpl.java:285)
	at org.elixir_lang.Erl.ebinDirectories(Erl.kt:48)
	at org.elixir_lang.Erl.prependCodePaths(Erl.kt:39)
	at org.elixir_lang.Erl.setErl(Erl.kt:62)
	at org.elixir_lang.Erl.commandLine(Erl.kt:16)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:20)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.mix.project._import.step.Root$1.run(Root.java:80)
```

**Comment by KronicDeth** [comment]
It looks like what was previously an `AssertionError` and caught in #1359 turned into a private error and so I need to catch `RuntimeException` too.
