### ISSUE TITLE
java.lang.IllegalArgumentException: several mnemonic markers in...

### ISSUE THREAD

**Issue by GiorgioG** [KronicDeth/intellij-elixir#2630]
Trying to import a basic Phoenix project (works fine on my Windows machine.) If I force quit IntelliJ and then re-open it the project it seems functional.

# System

Plugin Version: 12.3.0-pre+20220418164904
Application: IntelliJ IDEA Ultimate Edition (2022.1)
Operating System: Mac OS X (12.3.1)

# Event

### Stacktrace

```
java.lang.IllegalArgumentException: several mnemonic markers in [32m* creating [0m/Users/giorgiog/.mix/archives/hex-1.0.1[0m

	at com.intellij.openapi.util.text.TextWithMnemonic.fromMnemonicText(TextWithMnemonic.java:188)
	at com.intellij.openapi.MnemonicWrapper.createTextWithMnemonic(MnemonicWrapper.java:146)
	at com.intellij.openapi.MnemonicWrapper.run(MnemonicWrapper.java:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)

**Comment by KronicDeth** [comment]
From the stacktrace this all involves APIs outside of the plugin.  Please report this directly to JetBrains as their automatic Mnemonic handling needs to be fixed to handle this.

**Comment by formingform** [comment]
> Trying to import a basic Phoenix project (works fine on my Windows machine.) If I force quit IntelliJ and then re-open it the project it seems functional.
> 
> # System
> Plugin Version: 12.3.0-pre+20220418164904 Application: IntelliJ IDEA Ultimate Edition (2022.1) Operating System: Mac OS X (12.3.1)
> 
> # Event
> ## Exception
> ### Stacktrace
> ```
> java.lang.IllegalArgumentException: several mnemonic markers in �[32m* creating �[0m/Users/giorgiog/.mix/archives/hex-1.0.1�[0m
> 
> 	at com.intellij.openapi.util.text.TextWithMnemonic.fromMnemonicText(TextWithMnemonic.java:188)
> 	at com.intellij.openapi.MnemonicWrapper.createTextWithMnemonic(MnemonicWrapper.java:146)
> 	at com.intellij.openapi.MnemonicWrapper.run(MnemonicWrapper.java:69)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
> 	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
> 	
> ```

How did you solve this problem? I ran into the same problem.
