### ISSUE TITLE
Erlang Abst record_field field is unknown at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.error(AbstractCode.kt:91)

### ISSUE THREAD

**Issue by GiorgioG** [KronicDeth/intellij-elixir#2635]
# System

Plugin Version: 12.3.0-pre+20220418164904
Application: IntelliJ IDEA Ultimate Edition (2022.1)
Operating System: Windows 11 (10.0)

# Event

### Term

{var,{67,38},'_'}

### Stacktrace

```

java.lang.Throwable: Erlang Abst record_field field is unknown
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:66)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.error(AbstractCode.kt:91)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.fieldToString(RecordField.kt:28)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.setFieldString(RecordField.kt:56)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.setToMacroStringDeclaredScope(RecordField.kt:60)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.toMacroStringDeclaredScope(RecordField.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.RecordField.ifToMacroStringDeclaredScope(RecordField.kt:11)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:73)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedMacroStringDeclaredScope(Sequence.kt:42)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedMacroStringDeclaredScope(Sequence.kt:37)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.creationRecordFieldsMacroStringDeclaredScope(Record.kt:50)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.creationToMacroStringDeclaredScope(Record.kt:39)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.toMacroStringDeclaredScope(Record.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Record.ifToMacroStringDeclaredScope(Record.kt:13)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:72)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedMacroStringDeclaredScope(Sequence.kt:42)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedString(Sequence.kt:33)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toCommaSeparatedString$default(Sequence.kt:32)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.argumentsToString(Call.kt:48)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.argumentsToString(Call.kt:52)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.remoteNamedFunctionCallToString(Call.kt:113)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.access$remoteNamedFunctionCallToString(Call.kt:17)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call$namedFunctionCallToString$1.invoke(Call.kt:104)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call$namedFunctionCallToString$1.invoke(Call.kt:103)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Remote.ifTo(Remote.kt:60)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.namedFunctionCallToString(Call.kt:103)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.toString(Call.kt:138)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.toMacroStringDeclaredScope(Call.kt:22)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Call.ifToMacroStringDeclaredScope(Call.kt:19)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:55)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Case.expressionMacroStringDeclaredScope(Case.kt:43)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Case.toString(Case.kt:50)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Case.toMacroStringDeclaredScope(Case.kt:15)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Case.ifToMacroStringDeclaredScope(Case.kt:12)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:56)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:93)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.clause.Body.toMacroStringDeclaredScope(Body.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Clause.bodyString(Clause.kt:15)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.function.Clause.toMacroString(Clause.kt:20)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function$toMacroString$1.invoke(Function.kt:34)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function$toMacroString$1.invoke(Function.kt:34)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3344)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3361)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3360)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function.toMacroString(Function.kt:34)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:419)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:404)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:395)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:264)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:214)
	at org.elixir_lang.beam.Decompiler$Companion.decompiled(Decompiler.kt:71)
	at org.elixir_lang.beam.Decompiler$Companion.access$decompiled(Decompiler.kt:33)
	at org.elixir_lang.beam.Decompiler.decompile(Decompiler.kt:31)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:536)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.loadText(FileDocumentManagerBase.java:89)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:46)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:383)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:118)
	at org.elixir_lang.psi.scope.atom.Variants.projectLookupElementStream(Variants.java:49)
	at org.elixir_lang.psi.scope.atom.Variants.lookupElementList(Variants.java:24)
	at org.elixir_lang.reference.Atom.getVariants(Atom.java:25)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:243)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:122)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:64)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:75)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:129)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:112)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:73)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:54)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:89)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:25)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:157)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:59)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:132)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$11(CompletionProgressIndicator.java:870)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:202)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:677)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:201)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:866)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:854)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:352)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:344)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-05-03 21:45:44,071 [23631009] SEVERE - #o.e.b.c.d.v.e.a.AbstractCode - IntelliJ IDEA 2022.1  Build #IU-221.5080.210
2022-05-03 21:45:44,079 [23631017] SEVERE - #o.e.b.c.d.v.e.a.AbstractCode - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-05-03 21:45:44,080 [23631018] SEVERE - #o.e.b.c.d.v.e.a.AbstractCode - OS: Windows 11
2022-05-03 21:45:44,082 [23631020] SEVERE - #o.e.b.c.d.v.e.a.AbstractCode - Plugin to blame: Elixir version: 12.3.0-pre+20220418164904
2022-05-03 21:45:44,086 [23631024] SEVERE - #o.e.b.c.d.v.e.a.AbstractCode - ```

**Comment by sh41** [comment]
Same defect as #2728: an Erlang wildcard variable (`{var, _, '_'}`) used as a record-field name. Fixed in **v23.0.7** — not in v23.0.5 — see #2728 for the commits. Closing as a duplicate of that one.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
