### ISSUE TITLE
Incorrect offsets: startOffset=7532, endOffset=7537, text length=5365 at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:512)

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2647]
# System

Plugin Version: 13.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.1)
Operating System: Mac OS X (11.6.5)

# Event

### Stacktrace

```
java.lang.Throwable: Incorrect offsets: startOffset=7532, endOffset=7537, text length=5365
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:512)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:229)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:352)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.<init>(InplaceRefactoring.java:144)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:82)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:73)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.<init>(VariableInplaceRenamer.java:67)
	at org.elixir_lang.refactoring.variable.rename.Inplace.<init>(Inplace.java:32)
	at org.elixir_lang.refactoring.variable.rename.Handler.createRenamer(Handler.kt:73)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:77)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:87)
	at org.elixir_lang.refactoring.variable.rename.Handler.invoke(Handler.kt:54)
```

**Comment by odk211** [comment]
Happens after rename variable(Shift + F6).

**Comment by KronicDeth** [comment]
The start and end offsets are closer together than the text length.  IIRC something like this happened when the offsets were in the wrong file, but I really need access to a repository where I can reproduce it to be sure.

**Comment by sh41** [comment]
The 2022 recollection here was right: the offsets were against the wrong file.

Same root cause as #1461. The plugin's own in-place variable rename handler forwarded the element to the platform's `VariableInplaceRenamer` without checking it, and `InplaceRefactoring`'s constructor takes it on trust — it reads the containing file off the element, then builds a range marker in the editor's document from the element's own text range. The guard between those two steps compares the element's file against itself, so it never checks the element against the document actually open; the platform validates on later use, not at construction, which makes that precondition the caller's. Most reports of this crash died at the first step, on an element already invalid. This one got past it and died at the second, with a range starting at offset 7,532 applied to a document 5,365 characters long.

Same fix: `Handler` and `Inplace`, and their `renameHandler` extension-point registrations, were deleted in 2dff82691dce595b694e701cd60df49e5450d07d, first released in [24.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/24.0.0). Elixir rename now runs through the Symbol API, which re-derives the occurrence range from a `Pointer` on each dereference and yields nothing when that range no longer fits, rather than producing an out-of-range one.

Closing as a duplicate of #1461, the canonical report for this crash since 2020.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
