### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/jens.mehnert/toyrocketscience/dg_stage/_build/dev/lib/dg_stage_core/ebin/Elixir.DgStage.Core.Marketing.DotDigital.DotDigitalDummy.beam (invalid) is invalid, invalidated at: no info at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:217)

### ISSUE THREAD

**Issue by mehnee** [KronicDeth/intellij-elixir#2652]
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.2)
Operating System: Mac OS X (11.5.1)

# Event

### Stacktrace

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/jens.mehnert/toyrocketscience/dg_stage/_build/dev/lib/dg_stage_core/ebin/Elixir.DgStage.Core.Marketing.DotDigital.DotDigitalDummy.beam (invalid) is invalid
invalidated at: no info
	at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:217)
```

**Comment by KronicDeth** [comment]
The issue is I need to check for validity at the caller of `getContainingFile`, but that's not included in the stacktrace, so I don't have enough information to reproduce this.  I'll have to close until it happens in a reproducible manner that I can catch in the debugger, sorry.
