### ISSUE TITLE
I'm viewing an elixir phoenix liveview test.

### ISSUE THREAD

**Issue by kellyfelkins** [KronicDeth/intellij-elixir#2658]
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.2)
Operating System: Mac OS X (11.6.5)

# What I was doing

I'm viewing an elixir phoenix liveview test.

# Event

### Stacktrace

```
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren
	at org.elixir_lang.formatter.Block.<init>(Block.java:272)
	at org.elixir_lang.formatter.Block.buildChild(Block.java:756)
	at org.elixir_lang.formatter.Block.lambda$buildMapUpdateArgumentsChildren$27(Block.java:1482)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildMapUpdateArgumentsChildren(Block.java:1472)
	at org.elixir_lang.formatter.Block.lambda$buildMapArgumentsChildren$24(Block.java:1385)
	at org.elixir_lang.formatter.Block.lambda$buildContainerChildren$14(Block.java:1045)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildContainerChildren(Block.java:1035)
	at org.elixir_lang.formatter.Block.buildMapArgumentsChildren(Block.java:1373)
	at org.elixir_lang.formatter.Block.lambda$buildMapChildren$25(Block.java:1405)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildMapChildren(Block.java:1400)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:842)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:929)
```

**Comment by KronicDeth** [comment]
This isn't specific enough for me to reproduce.  I would need the text of the file before the formatter tried to format it.  Closing for now. If you post a reproduction file I'll reopen.
