### ISSUE TITLE
Refactor rename controller from router.ex

### ISSUE THREAD

**Issue by GiorgioG** [KronicDeth/intellij-elixir#2668]
# System

Plugin Version: 13.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.1.1)
Operating System: Linux (5.17.5-76051705-generic)

# What I was doing

Attempted to refactor->rename "PageController" in router.ex in a Phoenix app.

# Event

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented
	at org.elixir_lang.psi.impl.PsiNamedElementImpl.setName(PsiNamedElementImpl.kt:71)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.setName(ElixirPsiImplUtil.java:1652)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.setName(ElixirAliasImpl.java:77)
```

**Comment by KronicDeth** [comment]
The router aliases don't resolve to modules because I never implemented understanding the router DSL to get the outer module namespace from `scope`.  Once that's done this would just be renaming a module.
