### ISSUE TITLE
AssertionError in Prefix.operator

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#267]
Not sure how I triggered.  Only noticed after the fact, so assuming it was a transient, typing state.

```
null
java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.operator(ElixirPsiImplUtil.java:941)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.operator(ElixirUnmatchedUnaryNonNumericOperationImpl.java:88)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionNameElement(ElixirPsiImplUtil.java:1719)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.functionNameElement(ElixirUnmatchedUnaryNonNumericOperationImpl.java:43)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionName(ElixirPsiImplUtil.java:1684)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.functionName(ElixirUnmatchedUnaryNonNumericOperationImpl.java:38)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.resolvedFunctionName(ElixirPsiImplUtil.java:4046)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.resolvedFunctionName(ElixirUnmatchedUnaryNonNumericOperationImpl.java:128)
	at org.elixir_lang.annonator.Kernel$1.visitCall(Kernel.java:185)
	at org.elixir_lang.annonator.Kernel$1.visitElement(Kernel.java:207)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedExpressionImpl.accept(ElixirUnmatchedExpressionImpl.java:19)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.accept(ElixirUnmatchedUnaryNonNumericOperationImpl.java:21)
	at org.elixir_lang.annonator.Kernel.annotate(Kernel.java:179)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:135)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:99)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by KronicDeth** [comment]
Fixed by #276
