### ISSUE TITLE
org.jetbrains.kotlin.idea.caches.resolve.KotlinIdeaResolutionException: Kotlin resolution encountered a problem while analyzing KtProperty at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:43)

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#2694]
# System

Plugin Version: 13.1.0-pre+20220524145449
Application: IntelliJ IDEA Ultimate Edition (2022.1.1)
Operating System: Mac OS X (12.4)

# Event

### Stacktrace

<details>

<summary>
org.jetbrains.kotlin.idea.caches.resolve.KotlinIdeaResolutionException: Kotlin resolution encountered a problem while analyzing KtProperty
</summary>

```
org.jetbrains.kotlin.idea.caches.resolve.KotlinIdeaResolutionException: Kotlin resolution encountered a problem while analyzing KtProperty
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:43)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.analyze(extendedResolutionApi.kt:105)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.safeAnalyze(extendedResolutionApi.kt:96)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.resolveToDescriptorIfAny(extendedResolutionApi.kt:37)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptorIfAny(resolutionApi.kt:59)
	at org.jetbrains.kotlin.idea.caches.resolve.IDELightClassGenerationSupport.resolveToDescriptor(IDELightClassGenerationSupport.kt:143)
	at org.jetbrains.kotlin.asJava.classes.UltraLightUtilsKt.resolve(ultraLightUtils.kt:156)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternal(ultraLightMembersCreator.kt:399)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternalNonPublishedApi(ultraLightMembersCreator.kt:389)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.computeMethodName(ultraLightMembersCreator.kt:376)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.propertyAccessors(ultraLightMembersCreator.kt:462)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.propertyAccessors$default(ultraLightMembersCreator.kt:406)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.ownMethods(ultraLightClass.kt:276)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass._ownMethods$lambda-7(ultraLightClass.kt:334)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.getOwnMethods(ultraLightClass.kt:474)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.getAllMethods(KotlinClassInnerStuffCache.kt:105)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.access$getAllMethods(KotlinClassInnerStuffCache.kt:22)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$_getMethods$2.invoke(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$_getMethods$2.invoke(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1$holder$1.invoke$lambda-0(LightClassesLazyCreator.kt:21)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.computeValue(LightClassesLazyCreator.kt:26)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.getValue(LightClassesLazyCreator.kt:50)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.get_getMethods(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.getMethods(KotlinClassInnerStuffCache.kt:49)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassBase.getMethods(KtLightClassBase.kt:43)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$1.invoke(LightClassUtil.kt:136)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$1.invoke(LightClassUtil.kt:136)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getPsiMethodWrapper(LightClassUtil.kt:132)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getLightClassMethod(LightClassUtil.kt:113)
	at org.jetbrains.uast.kotlin.BaseKotlinConverter$DefaultImpls.convertDeclaration(BaseKotlinConverter.kt:158)
	at org.jetbrains.uast.kotlin.KotlinConverter.convertDeclaration(KotlinConverter.kt:11)
	at org.jetbrains.uast.kotlin.BaseKotlinConverter$DefaultImpls.convertDeclarationOrElement(BaseKotlinConverter.kt:224)
	at org.jetbrains.uast.kotlin.KotlinConverter.convertDeclarationOrElement(KotlinConverter.kt:11)
	at org.jetbrains.uast.kotlin.KotlinUastLanguagePlugin.convertElementWithParent(KotlinUastLanguagePlugin.kt:49)
	at org.jetbrains.uast.kotlin.KotlinConvertParentUtilsKt.convertParentImpl(kotlinConvertParentUtils.kt:154)
	at org.jetbrains.uast.kotlin.KotlinConvertParentUtilsKt.convertParentImpl(kotlinConvertParentUtils.kt:115)
	at org.jetbrains.uast.kotlin.BaseKotlinUastResolveProviderService$DefaultImpls.convertParent(BaseKotlinUastResolveProviderService.kt:22)
	at org.jetbrains.uast.kotlin.KotlinUastResolveProviderService$DefaultImpls.convertParent(KotlinUastResolveProviderService.kt)
	at org.jetbrains.uast.kotlin.internal.IdeaKotlinUastResolveProviderService.convertParent(IdeaKotlinUastResolveProviderService.kt:24)
	at org.jetbrains.uast.kotlin.KotlinAbstractUElement.convertParent(KotlinAbstractUElement.kt:29)
	at org.jetbrains.uast.kotlin.KotlinUBlockExpression.convertParent(KotlinUBlockExpression.kt:20)
	at org.jetbrains.uast.kotlin.KotlinAbstractUElement$uastParent$2.invoke(KotlinAbstractUElement.kt:25)
	at org.jetbrains.uast.kotlin.KotlinAbstractUElement$uastParent$2.invoke(KotlinAbstractUElement.kt:11)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.uast.kotlin.KotlinAbstractUElement.getUastParent(KotlinAbstractUElement.kt)
	at org.jetbrains.uast.UElementKt$withContainingElements$1.get(UElement.kt:154)
	at kotlin.jvm.internal.PropertyReference1.invoke(PropertyReference1.java:35)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:609)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:421)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at org.jetbrains.uast.UastUtils__UastUtilsKt.getUCallExpression(UastUtils.kt:85)
	at org.jetbrains.uast.UastUtils.getUCallExpression(Unknown Source)
	at org.jetbrains.uast.UastUtils__UastUtilsKt.getUCallExpression$default(UastUtils.kt:78)
	at org.jetbrains.uast.UastUtils.getUCallExpression$default(Unknown Source)
	at com.intellij.patterns.uast.UExpressionPattern$inCall$1.invoke(UastPatterns.kt:224)
	at com.intellij.patterns.uast.UExpressionPattern$inCall$1.invoke(UastPatterns.kt:186)
	at com.intellij.patterns.uast.UElementPattern$filterWithContext$1.accepts(UastPatterns.kt:79)
	at com.intellij.patterns.uast.UElementPattern$filterWithContext$1.accepts(UastPatterns.kt:78)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:58)
	at com.intellij.psi.UastReferenceRegistrar$registerUastReferenceProvider$1.invoke(UastReferenceRegistrar.kt:29)
	at com.intellij.psi.UastReferenceRegistrar$registerUastReferenceProvider$1.invoke(UastReferenceRegistrar.kt)
	at com.intellij.psi.UastPatternAdapter.accepts(UastPatternAdapter.kt:32)
	at com.intellij.patterns.PatternConditionPlus.process(PatternConditionPlus.java:47)
	at com.intellij.patterns.PatternConditionPlus.process(PatternConditionPlus.java:26)
	at com.intellij.patterns.ObjectPattern$2.processValues(ObjectPattern.java:94)
	at com.intellij.patterns.PatternConditionPlus.accepts(PatternConditionPlus.java:42)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:51)
	at com.intellij.psi.impl.source.resolve.reference.NamedObjectProviderBinding.addMatchingProviders(NamedObjectProviderBinding.java:88)
	at com.intellij.psi.impl.source.resolve.reference.SimpleProviderBinding.addAcceptableReferenceProviders(SimpleProviderBinding.java:26)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceRegistrarImpl.getPairsByElement(PsiReferenceRegistrarImpl.java:180)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:139)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at org.jetbrains.kotlin.idea.references.KtIdeReferenceProviderService.getReferences(KtIdeReferenceProviderService.kt:61)
	at org.jetbrains.kotlin.psi.KotlinReferenceProvidersService$Companion.getReferencesFromProviders(KotlinReferenceProvidersService.kt:25)
	at org.jetbrains.kotlin.psi.KotlinReferenceProvidersService.getReferencesFromProviders(KotlinReferenceProvidersService.kt)
	at org.jetbrains.kotlin.psi.KtElementImplStub.getReferences(KtElementImplStub.java:114)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:59)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:33)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:51)
	at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:75)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:238)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:223)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:531)
	at org.elixir_lang.UsageTargetProvider.getTargets(UsageTargetProvider.kt:20)
```

</details>

**Comment by KronicDeth** [comment]
This causes Kotlin analysis to crash when working on the plugin itself 🤣
