### ISSUE TITLE
Highlighting types for `@doc <HEREDOC>`

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#271]
```
Highlighting types for org.elixir_lang.psi.impl.ElixirMatchedAtUnqualifiedNoParenthesesCallImpl PsiElements is not implemented yet.  Please open an issue (https://github.com/KronicDeth/intellij-elixir/issues/new) with the class name of the sample text:
@doc """
  Retrieves the source model to check for authorization before getting {related/3} models.

  The a queryable on an association on `ecto_schema`, so the source is not the `ecto_schema` unlike `owner`, where
  it is the `ecto_schema`.
  """
org.apache.commons.lang.NotImplementedException: Highlighting types for org.elixir_lang.psi.impl.ElixirMatchedAtUnqualifiedNoParenthesesCallImpl PsiElements is not implemented yet.  Please open an issue (https://github.com/KronicDeth/intellij-elixir/issues/new) with the class name of the sample text:
@doc """
  Retrieves the source model to check for authorization before getting {related/3} models.

  The a queryable on an association on `ecto_schema`, so the source is not the `ecto_schema` unlike `owner`, where
  it is the `ecto_schema`.
  """
	at org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:896)
	at org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:750)
	at org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:850)
	at org.elixir_lang.annonator.ModuleAttribute.highlightSpecification(ModuleAttribute.java:473)
	at org.elixir_lang.annonator.ModuleAttribute.highlightSpecification(ModuleAttribute.java:223)
	at org.elixir_lang.annonator.ModuleAttribute.access$400(ModuleAttribute.java:31)
	at org.elixir_lang.annonator.ModuleAttribute$1.visitDeclaration(ModuleAttribute.java:80)
	at org.elixir_lang.annonator.ModuleAttribute$1.visitElement(ModuleAttribute.java:91)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:27)
	at org.elixir_lang.annonator.ModuleAttribute.annotate(ModuleAttribute.java:47)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:135)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:99)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by KronicDeth** [comment]
Closed until the new error reporter can give the context of the entire file

**Comment by KronicDeth** [comment]
Caused by adding a `@type` above a `@doc` once you type `@type name ::` the `@doc heredoc` becomes the effective right operand of `::`.
