### ISSUE TITLE
readNameSet nameSet of suspect (>= 15) size (15)

### ISSUE THREAD

**Issue by hengestone** [KronicDeth/intellij-elixir#2716]
Hi Elle,

I've been getting these recently, seems to be because there are just a gazillion `Jason.Encoder.Geo` modules and 15 is the maximum currently supported?

Thanks!

# System

Plugin Version: 13.1.0
Application: IntelliJ IDEA Ultimate Edition (2022.1.2)
Operating System: Linux (5.15.0-37-lowlatency)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: readNameSet nameSet of suspect (>= 15) size (15):
</summary>

```
java.lang.Throwable: readNameSet nameSet of suspect (>= 15) size (15):
1. if.Jason.Encoder.Geo.MultiPolygonZ
2. if.Jason.Encoder.Geo.MultiPointZ
3. if.Jason.Encoder.Geo.MultiLineString
4. if.Jason.Encoder.Geo.MultiPoint
5. if.Jason.Encoder.Geo.PolygonZ
6. if.Jason.Encoder.Geo.PointZM
7. if.Jason.Encoder.Geo.PointM
8. if.Jason.Encoder.Geo.MultiLineStringZ
9. if.Jason.Encoder.Geo.Point
10. if.Jason.Encoder.Geo.Polygon
11. if.Jason.Encoder.Geo.LineStringZ
12. if.Jason.Encoder.Geo.GeometryCollection
13. if.Jason.Encoder.Geo.LineString
14. if.Jason.Encoder.Geo.PointZ
15. if.Jason.Encoder.Geo.MultiPolygon

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at org.elixir_lang.psi.stub.call.Deserialized.readNameSet(Deserialized.java:224)
	at org.elixir_lang.psi.stub.call.Deserialized.readGuarded(Deserialized.java:161)
	at org.elixir_lang.psi.stub.call.Deserialized.deserializeCanonicalNameSet(Deserialized.java:123)
	at org.elixir_lang.psi.stub.call.Deserialized.deserialize(Deserialized.java:105)
	at org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall.deserialize(UnmatchedUnqualifiedNoParenthesesCall.java:55)
	at org.elixir_lang.psi.stub.type.UnmatchedUnqualifiedNoParenthesesCall.deserialize(UnmatchedUnqualifiedNoParenthesesCall.java:16)
	at com.intellij.psi.stubs.LazyStubData.deserializeStub(LazyStubList.java:131)
	at com.intellij.psi.stubs.LazyStubList.instantiateStub(LazyStubList.java:88)
	at com.intellij.psi.stubs.LazyStubList.get(LazyStubList.java:58)
	at com.intellij.psi.stubs.LazyStubList.get(LazyStubList.java:18)
	at com.intellij.psi.stubs.StubSpine.getStubPsi(StubSpine.java:45)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getStubPsi(StubProcessingHelperBase.java:98)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:71)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:140)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:187)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:50)
	at org.elixir_lang.psi.scope.module.Variants.putProject$lambda-1(Variants.kt:74)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$iterateData$1(PersistentEnumeratorBase.java:410)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.lambda$processAll$3(AppendableStorageBackedByResizableMappedFile.java:115)
	at com.intellij.util.io.PagedFileStorage.lambda$readInputStream$1(PagedFileStorage.java:115)
	at com.intellij.util.io.PagedFileStorage.useChannel(PagedFileStorage.java:144)
	at com.intellij.util.io.PagedFileStorage.readInputStream(PagedFileStorage.java:113)
	at com.intellij.util.io.ResizeableMappedFile.readInputStream(ResizeableMappedFile.java:268)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.processAll(AppendableStorageBackedByResizableMappedFile.java:102)
	at com.intellij.util.io.PersistentEnumeratorBase.doIterateData(PersistentEnumeratorBase.java:422)
	at com.intellij.util.io.PersistentEnumeratorBase.iterateData(PersistentEnumeratorBase.java:410)
	at com.intellij.util.io.PersistentMapImpl.processKeys(PersistentMapImpl.java:488)
	at com.intellij.util.indexing.impl.ValueContainerMap.processKeys(ValueContainerMap.java:73)
	at com.intellij.util.indexing.impl.MapIndexStorage.doProcessKeys(MapIndexStorage.java:368)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.processKeys(VfsAwareMapIndexStorage.java:125)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.processKeys(TransientChangesIndexStorage.java:139)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.lambda$processAllKeys$0(MapReduceIndexBase.java:52)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.processAllKeys(MapReduceIndexBase.java:51)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.processAllKeys(CompositeInvertedIndexBase.java:120)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processAllKeys$8(StubIndexEx.java:284)
	at com.intellij.util.indexing.IndexUpToDateCheckIn.disableUpToDateCheckIn(IndexUpToDateCheckIn.kt:15)
	at com.intellij.util.indexing.FileBasedIndexEx.disableUpToDateCheckIn(FileBasedIndexEx.java:785)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processAllKeys$9(StubIndexEx.java:283)
	at com.intellij.util.indexing.diagnostic.IndexAccessValidator.validate(IndexAccessValidator.java:42)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:283)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:67)
	at org.elixir_lang.psi.scope.module.Variants.putProject(Variants.kt:72)
	at org.elixir_lang.psi.scope.module.Variants.access$putProject(Variants.kt:25)
	at org.elixir_lang.psi.scope.module.Variants$Companion.unfilteredLookupElements(Variants.kt:247)
	at org.elixir_lang.psi.scope.module.Variants$Companion.lookupElements(Variants.kt:107)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:18)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:15)
```

</details>

**Comment by KronicDeth** [comment]
While not the same as #2698 since it's a different protocol, the number of impls is the same at 16 and so #2717 will fix this.

**Comment by hengestone** [comment]
Thanks :)
