### ISSUE TITLE
java.io.FileNotFoundException: /usr/local/Cellar/erlang/24.0.2/lib/erlang/bin/erl does not exist at org.elixir_lang.jps.SdkType.exeFileToExePath(SdkType.java:21)

### ISSUE THREAD

**Issue by dxb-camelrider** [KronicDeth/intellij-elixir#2718]
# System

Plugin Version: 13.1.0
Application: IntelliJ IDEA Community Edition (2022.1.2)
Operating System: Mac OS X (11.4)

# Event

### Stacktrace

<details>

<summary>
java.io.FileNotFoundException: /usr/local/Cellar/erlang/24.0.2/lib/erlang/bin/erl does not exist
</summary>

```
java.io.FileNotFoundException: /usr/local/Cellar/erlang/24.0.2/lib/erlang/bin/erl does not exist
	at org.elixir_lang.jps.SdkType.exeFileToExePath(SdkType.java:21)
	at org.elixir_lang.jps.sdk_type.Erlang.homePathToErlExePath(Erlang.java:44)
	at org.elixir_lang.Erl.exePath(Erl.kt:31)
	at org.elixir_lang.Erl.setErl(Erl.kt:49)
	at org.elixir_lang.Erl.commandLine(Erl.kt:17)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.format(MixFormatExternalFormatProcessor.kt:82)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.access$format(MixFormatExternalFormatProcessor.kt:67)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda-7$lambda-6(MixFormatExternalFormatProcessor.kt:44)
```

</details>

**Comment by dxb-camelrider** [comment]
Thanks team. That was very promt.
