### ISSUE TITLE
java.lang.RuntimeException: com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: app1 at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:119)

### ISSUE THREAD

**Issue by donaldww** [KronicDeth/intellij-elixir#2739]
# System

Plugin Version: 13.1.1
Application: IntelliJ IDEA Ultimate Edition (2022.1.3)
Operating System: Mac OS X (12.4)

# Event

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: app1
</summary>

```
java.lang.RuntimeException: com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: app1
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:503)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:33)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:26)
	at com.intellij.projectImport.ProjectOpenProcessorBase.importToProject(ProjectOpenProcessorBase.kt:185)
	at com.intellij.projectImport.ProjectOpenProcessorBase.access$importToProject(ProjectOpenProcessorBase.kt:33)
	at com.intellij.projectImport.ProjectOpenProcessorBase$doOpenProject$1.invoke(ProjectOpenProcessorBase.kt:165)
	at com.intellij.projectImport.ProjectOpenProcessorBase$doOpenProject$1.invoke(ProjectOpenProcessorBase.kt:33)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:356)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:56)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:127)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:56)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:96)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:72)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: app1
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.newModule(ModifiableModuleModelBridgeImpl.kt:81)
	at org.elixir_lang.mix.Project.createModuleForOtpApp(Project.kt:103)
	at org.elixir_lang.mix.Project.createModulesForOtpApps(Project.kt:77)
	at org.elixir_lang.mix.project._import.Builder.commit(Builder.kt:104)
```

</details>

**Comment by KronicDeth** [comment]
Can you explain what your project structure was? What were the name of the root folder and the apps?

**Comment by sh41** [comment]
Fixed. This is the umbrella module-name collision: each OTP app's `.iml` was named after the app, so an
umbrella root and an `apps/` child both declaring `app: :app1` resolved to one path and the second
`newModule` call threw.

`fc3c45133` disambiguates the module names first — the root app keeps its plain name, the others get a
suffix from their path relative to it. First released in v23.0.5, so the answer the issue was waiting
on is no longer needed.

Closing as a duplicate of #2003, which describes the same collision and is where the fix is recorded.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
