### ISSUE TITLE
Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction()) at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1048)

### ISSUE THREAD

**Issue by bhuntpenn** [KronicDeth/intellij-elixir#2748]
# System

Plugin Version: 13.1.1
Application: IntelliJ IDEA Ultimate Edition (2022.1.3)
Operating System: Mac OS X (12.4)

# Event

## Message

Details: Current thread: Thread[ApplicationImpl pooled thread 84,4,main] 1057839652
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1395179443

### Stacktrace

<details>

<summary>
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
</summary>

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1048)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:424)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:224)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:145)
	at org.elixir_lang.psi.impl.PsiNamedElementImpl.getName(PsiNamedElementImpl.kt:18)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getName(ElixirPsiImplUtil.java:951)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.getName(ElixirAliasImpl.java:42)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.fullyQualifiedName(QualifiableAliasImpl.kt:125)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyQualifiedName(ElixirPsiImplUtil.java:814)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.fullyQualifiedName(ElixirAliasImpl.java:37)
	at org.elixir_lang.psi.Implementation.protocolName(Implementation.kt:126)
	at org.elixir_lang.psi.Implementation.protocolName(Implementation.kt:109)
	at org.elixir_lang.psi.Implementation.nameCollection(Implementation.kt:33)
	at org.elixir_lang.psi.Implementation.name(Implementation.kt:30)
	at org.elixir_lang.psi.impl.PsiNamedElementImpl.getName(PsiNamedElementImpl.kt:56)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getName(ElixirPsiImplUtil.java:967)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.getName(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:101)
	at org.elixir_lang.ReferencesSearch.processQuery(ReferencesSearch.java:31)
	at org.elixir_lang.ReferencesSearch.processQuery(ReferencesSearch.java:17)
```

</details>

renaming  
 
 `alias __MODULE__.Protocol, as: SearchableProtocol`

to 

` alias <name elided>.Searchable.Protocol, as: SearchableProtocol`

**Comment by sh41** [comment]
Fixed, and the code it happened in has since been removed.

`ReferencesSearch.processQuery` ran on a pooled thread and read PSI from it — `Implementation.is`, `Module.is`, `Protocol.is`, `getName()`, `getLanguage()` — with no read action anywhere in the chain, which is why renaming an aliased `defimpl` produced this. Commit 028d4b7c2 ("Fix reference search edt issue") wrapped that whole block in `ReadAction.nonBlocking(...).executeSynchronously()`. First release carrying it: 24.0.0.

Since then find usages has moved to the platform's Symbol API — `ElixirUsageQueries` and `ElixirDirectUsageQuery` — and the old `ReferencesSearch` class and its extension-point registration were deleted outright in the same release. The platform invokes the new search callbacks inside its own read action, so the reported call path no longer exists in any form.

Closing as a duplicate of #1975, which reported the same crash at the same call site.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
