### ISSUE TITLE
Renaming function causes exception

### ISSUE THREAD

**Issue by hunterboerner** [KronicDeth/intellij-elixir#2752]
# System

Plugin Version: 13.1.1
Application: IntelliJ IDEA Ultimate Edition (2022.1.4)
Operating System: Mac OS X (12.3.1)

# Event

I tried to rename a function using the refactoring tools.

### Stacktrace

<details>

<summary>
java.lang.Throwable: MyModule.myrename(params["a"]["b"], params["c"], d)
</summary>

```
java.lang.Throwable: MyModule.myrename(params["a"]["b"], params["c"], d)
 parent=MyModule.myrename(params["a"]["b"], params["c"], d)
    {:noreply, socket}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:284)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.getRelativeIdentifier(ElixirUnmatchedQualifiedParenthesesCallImpl.java:62)
	at org.elixir_lang.psi.impl.call.CallImpl.functionNameElement(CallImpl.kt:384)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionNameElement(ElixirPsiImplUtil.java:858)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.functionNameElement(ElixirUnmatchedQualifiedParenthesesCallImpl.java:88)
	at org.elixir_lang.psi.impl.call.CallImpl.functionName(CallImpl.kt:354)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionName(ElixirPsiImplUtil.java:826)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.functionName(ElixirUnmatchedQualifiedParenthesesCallImpl.java:83)
	at org.elixir_lang.psi.impl.call.CallImpl.isCalling(CallImpl.kt:435)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCalling(ElixirPsiImplUtil.java:229)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.isCalling(ElixirUnmatchedQualifiedParenthesesCallImpl.java:123)
	at org.elixir_lang.psi.impl.call.CallImpl.isCalling(CallImpl.kt:460)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCalling(ElixirPsiImplUtil.java:236)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.isCalling(ElixirUnmatchedQualifiedParenthesesCallImpl.java:128)
	at org.elixir_lang.psi.impl.call.CallImpl.isCallingMacro(CallImpl.kt:505)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.isCallingMacro(ElixirPsiImplUtil.java:250)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.isCallingMacro(ElixirUnmatchedQualifiedParenthesesCallImpl.java:138)
	at org.elixir_lang.psi.Implementation.is(Implementation.kt:22)
	at org.elixir_lang.code_insight.line_marker_provider.Implementation.getLineMarkerInfo(Implementation.kt:34)
	at org.elixir_lang.code_insight.line_marker_provider.Implementation.getLineMarkerInfo(Implementation.kt:29)
```

</details>

**Comment by KronicDeth** [comment]
I am able to reproduce by adding usage and def to a module:

```elixir
  defp aliases do
    [test: ["ecto.create --quiet", "ecto.migrate", "test"]]

    params = %{}
    d = :d

    EExTestWeb.Mixfile.rename1(params["a"]["b"], params["c"], d)
  end

  def rename1(a, b, c) do

  end
```
