### ISSUE TITLE
Intellij 2022.2

### ISSUE THREAD

**Issue by ViseLuca** [KronicDeth/intellij-elixir#2760]
With new version of Intellij released 1-2 days ago the plugin is not working due to new version that is not included. Can we improve it? I don't know if is enough updating the .gradle file only or there are any things to do, in case I can open a PR

**Comment by KronicDeth** [comment]
Yeah, it’s just updating the gradle file unless it breaks compilation due to a break API change.

**Comment by ViseLuca** [comment]
@KronicDeth 
Yeah it has some breaking changes but only 3 problems in total for 2 files

2 problems are identical:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/54796163/181250402-0e94d33b-f265-416a-8073-8e711daf1c8f.png">

and the other one is:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/54796163/181250590-d000eafd-fcfe-4617-8b80-01cc7f30426c.png">
but maybe could be casted as the IDE suggests

**Comment by KronicDeth** [comment]
All I do is take the suggestions unless it breaks the manual testing, so go with the suggestions and see if it work.

**Comment by KronicDeth** [comment]
Sorry about the closing, cramped mobile website and far fingered it

**Comment by ViseLuca** [comment]
@KronicDeth thank you for the answer, is my first time with Kotlin and plugins in general. Now the runIde is working and also the plugin is working but the tests are failing for errors like:
```
org.elixir_lang.structure_view.element.CallDefinitionHeadTest > initializationError FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixtureTestCase
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
....
```
it seems that cannot find that class (that now is deprecated). I find it in my gradle dependencies and IDE is linking it but gradle doesn't want to compile. Any idea?

**Comment by KronicDeth** [comment]
Fixed by #2766
