### ISSUE TITLE
Dbgi :debug_info_v1 version :elixir_erl backend metadata is not a tuple, , ## metadata, , ```elixir, :none, ``` at org.elixir_lang.beam.chunk.debug_info.v1.ElixirErlKt.elixirErl(ElixirErl.kt:20)

### ISSUE THREAD

**Issue by zoewenRB** [KronicDeth/intellij-elixir#2769]
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Community Edition (2021.3.2)
Operating System: Mac OS X (12.3.1)

# Event

### Stacktrace

```
java.lang.Throwable: Dbgi :debug_info_v1 version :elixir_erl backend metadata is not a tuple

## metadata

```elixir
:none
```
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at org.elixir_lang.beam.chunk.debug_info.v1.ElixirErlKt.elixirErl(ElixirErl.kt:20)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1FromBackend(V1.kt:60)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1(V1.kt:38)
	at org.elixir_lang.beam.chunk.debug_info.V1Kt.v1(V1.kt:18)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.fromTupleTag(Term.kt:62)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.fromTuple(Term.kt:49)
	at org.elixir_lang.beam.chunk.debug_info.TermKt.from(Term.kt:29)
	at org.elixir_lang.beam.Beam.debugInfo(Beam.kt:87)
	at org.elixir_lang.beam.Decompiler$Companion.decompiled(Decompiler.kt:68)
	at org.elixir_lang.beam.Decompiler$Companion.access$decompiled(Decompiler.kt:33)
	at org.elixir_lang.beam.Decompiler.decompile(Decompiler.kt:31)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:536)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.loadText(FileDocumentManagerBase.java:89)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:46)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:383)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:118)
```

**Comment by KronicDeth** [comment]
Any idea which `.beam` file this was?  If you do then you can zip the `.beam` and attach it in a comment here and I can use it to reproduce the problem for the regression test to fix this issue

**Comment by sh41** [comment]
Fixed. `:none` is what a module compiled with `debug_info: false` carries in its `Dbgi` metadata,
and the reader treated anything that was not a tuple as an error. 30646138509cd2c3cb483e486d616938b45b6522
in #3815 added an atom branch that handles `:none` as the expected value instead of logging it.

First released in [v23.0.7](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.0.7).

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing
> it, but it might still be a mistake. If you think the reason above is wrong, please reopen the
> issue and tell us why.
