### ISSUE TITLE
Unhandled exception when moving mouse pointer over function name with Ctrl/Cmd pressed

### ISSUE THREAD

**Issue by develop7** [KronicDeth/intellij-elixir#277]
# Version

3.0.0

# Description

* Press `Ctrl` and move mouse  pointer over `foo` in `def foo do…`

# Exception

## Message

Worker exited due to exception: @NotNull method org/elixir_lang/FindUsagesProvider.getType must not return null

## Stacktrace

```
java.lang.IllegalStateException: @NotNull method org/elixir_lang/FindUsagesProvider.getType must not return null
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:139)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:66)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:39)
	at com.intellij.usageView.UsageViewUtil.getType(UsageViewUtil.java:68)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$8.getInfo(CtrlMouseHandler.java:607)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:848)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2500(CtrlMouseHandler.java:786)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:831)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:159)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:223)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:45)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$6$2.run(ProgressIndicatorUtils.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by aphillipo** [comment]
I get this exception as well...

**Comment by KronicDeth** [comment]
It's only sorta a bug.  It was a known incomplete feature when implementing Go To Symbol.  For things to enter the index, they have to implement `PsiNamedElement`, but once an element implements `PsiNamedElement`, OpenAPI assumes that `#getType` will work on it too, but I didn't want to bundle that with Go To Symbol because `#getType` is something I'll cover when implementing Go To Declaration and Find Usage.  If that takes too long, I'll add a fallback of `"unknown call"`.  For now, as the work-around I would recommend ignoring the error.

**Comment by aphillipo** [comment]
Make's total sense!  Thanks for implementing this :+1:

**Comment by KronicDeth** [comment]
Thanks @develop7 for using the new error reporter.  Glad to know if works for someone besides me.
