### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown SDk type: class org.elixir_lang.sdk.elixir.Type at com.intellij.openapi.projectRoots.SdkType.findInstance(SdkType.java:263)

### ISSUE THREAD

**Issue by justteddy** [KronicDeth/intellij-elixir#2770]
# System

Plugin Version: 13.1.1
Application: GoLand (2022.1.2)
Operating System: Mac OS X (12.4)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalArgumentException: Unknown SDk type: class org.elixir_lang.sdk.elixir.Type
</summary>

```
java.lang.IllegalArgumentException: Unknown SDk type: class org.elixir_lang.sdk.elixir.Type
	at com.intellij.openapi.projectRoots.SdkType.findInstance(SdkType.java:263)
	at org.elixir_lang.sdk.elixir.Type$Companion.getInstance(Type.kt:482)
	at org.elixir_lang.Facet$Companion.sdks(Facet.kt:68)
	at org.elixir_lang.Facet$Companion.sdkByName(Facet.kt:70)
	at org.elixir_lang.Facet$Companion.sdk(Facet.kt:37)
	at org.elixir_lang.Facet.getSdk(Facet.kt:20)
	at org.elixir_lang.sdk.elixir.Type$Companion.mostSpecificSdk(Type.kt:522)
	at org.elixir_lang.sdk.elixir.Type$Companion.mostSpecificSdk(Type.kt:541)
	at org.elixir_lang.notification.setup_sdk.Provider.createNotificationPanel(Provider.kt:44)
	at org.elixir_lang.notification.setup_sdk.Provider.collectNotificationData$lambda-0(Provider.kt:32)
```

</details>

**Comment by KronicDeth** [comment]
This seems to indicate that the Facet support may differ in GoLand and Rubymine.  My recommendation until I can do more testing with GoLand is to use IntelliJ Community Edition (it's free) or IntelliJ Ultimate Edition if you have an All Products license and can use Ultimate.

**Comment by sh41** [comment]
Still open and still unfixed. The 2022 diagnosis in this thread needs correcting, though.

The crash is the platform's `SdkType.findInstance`, which throws this exact message when `org.elixir_lang.sdk.elixir.Type` is absent from the `com.intellij.sdkType` extension list. The plugin registers that type unconditionally, and did so in 13.1.1 too, so registration was never the missing piece — and nothing about it is specific to Facets.

Two things remove it from the list, both silently. `ExtensionPointImpl` drops any extension whose instantiation throws, logging the error and swallowing it; and it drops extensions whose plugin classloader is no longer active, which covers disable, uninstall, update-without-restart and IDE shutdown. Either way the type is gone and every subsequent lookup throws. The plugin does not guard against that anywhere.

Masking the extension point in a test reproduces this message verbatim on current `main`, both from `Facet.sdks` — the exact frame in the report above — and from `ElixirSdkLookup`, a path that did not exist in 2022.

What I could not establish is what emptied the list on your machine. I found nothing in the Elixir SDK type's construction that would fail specifically in GoLand, so this may not be a GoLand-only problem — switching to IntelliJ CE or Ultimate, as suggested earlier in the thread, is still worth trying, but it is not a diagnosis.

If you or anyone else still hits this: `idea.log` from the same session should carry the swallowed error just before the crash, and that is the piece that would name the cause.

---

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
