### ISSUE TITLE
java.lang.IllegalStateException: seed must not be null at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions(PsiElementImpl.kt:220)

### ISSUE THREAD

**Issue by rbaezam** [KronicDeth/intellij-elixir#2773]
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Mac OS X (12.5)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: seed must not be null
</summary>

```
java.lang.IllegalStateException: seed must not be null
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions(PsiElementImpl.kt:220)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions$default(PsiElementImpl.kt:213)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment]
`firstChild` or `lastChild` is `null` in 

https://github.com/KronicDeth/intellij-elixir/blob/4ca4cd3ea8de3242c81d964ac6bf9087db1c4483/src/org/elixir_lang/psi/impl/PsiElementImpl.kt#L213-L221

`childExpressions` need to handle being child-less and it hasn't needed to previously I guess 🤷🏻‍♀️
