### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by Anshhuu** [KronicDeth/intellij-elixir#2775]
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Community Edition (2022.1.3)
Operating System: Mac OS X (12.4)

# Event

### Element

```
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "test/"],
        excluded: []
      },
      strict: true,
      checks: [
        {Credo.Check.Design.TagFIXME, [exit_status: 0, priority: :low]},
        {Credo.Check.Design.TagTODO, [exit_status: 0, priority: :low]},
        {Credo.Check.Refactor.Nesting, max_nesting: 3},
        {Credo.Check.Refactor.AppendSingleItem},
        {Credo.Check.Readability.SinglePipe},
        {Credo.Check.Readability.UnnecessaryAliasExpansion},
        {
          Credo.Check.Design.AliasUsage,
          # NOTE: it's clearer to use exception by full name
          excluded_namespaces:
            Credo.Check.Design.AliasUsage.param_defaults()[:excluded_namespaces] ++ ~w[CSV Plug Faker],
          excluded_lastnames: Credo.Check.Design.AliasUsage.param_defaults()[:excluded_lastnames] ++ ~w[Error],
          if_nested_deeper_than: 2
        },

        # Disabled
        {Credo.Check.Warning.LazyLogging, false},
        {Credo.Check.Readability.AliasOrder, false},
        {Credo.Check.Readability.ModuleDoc, false},

        # TODO: probably good idea to enable those back
        {Credo.Check.Refactor.MapInto, false},
        {Credo.Check.Refactor.WithClauses, false},
        {Credo.Check.Refactor.CyclomaticComplexity, false},

        # Disabled until fixed: https://github.com/rrrene/credo/issues/969
        {Credo.Check.Consistency.ExceptionNames, false}
      ]
    }
  ]
}
```

From: `/Users/himanshu.mehra/projects/segmentation_api/config/.credo.exs:0-40`

#### Context

```
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "test/"],
        excluded: []
      },
      strict: true,
      checks: [
        {Credo.Check.Design.TagFIXME, [exit_status: 0, priority: :low]},
        {Credo.Check.Design.TagTODO, [exit_status: 0, priority: :low]},
        {Credo.Check.Refactor.Nesting, max_nesting: 3},
        {Credo.Check.Refactor.AppendSingleItem},
        {Credo.Check.Readability.SinglePipe},
        {Credo.Check.Readability.UnnecessaryAliasExpansion},
        {
          Credo.Check.Design.AliasUsage,
          # NOTE: it's clearer to use exception by full name
          excluded_namespaces:
            Credo.Check.Design.AliasUsage.param_defaults()[:excluded_namespaces] ++ ~w[CSV Plug Faker],
          excluded_lastnames: Credo.Check.Design.AliasUsage.param_defaults()[:excluded_lastnames] ++ ~w[Error],
          if_nested_deeper_than: 2
        },

        # Disabled
        {Credo.Check.Warning.LazyLogging, false},
        {Credo.Check.Readability.AliasOrder, false},
        {Credo.Check.Readability.ModuleDoc, false},

        # TODO: probably good idea to enable those back
        {Credo.Check.Refactor.MapInto, false},
        {Credo.Check.Refactor.WithClauses, false},
        {Credo.Check.Refactor.CyclomaticComplexity, false},

        # Disabled until fixed: https://github.com/rrrene/credo/issues/969
        {Credo.Check.Consistency.ExceptionNames, false}
      ]
    }
  ]
}

```

From: `/Users/himanshu.mehra/projects/segmentation_api/config/.credo.exs:0-41`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMapOperationImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/blob/4ca4cd3ea8de3242c81d964ac6bf9087db1c4483/src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt#L84-L93

should ignore `ElixirMapOperation` the same way it does `ElixirList`.
