### ISSUE TITLE
java.lang.RuntimeException: Unable to get or create settings of #CodeStyleSettings (org.elixir_lang.code_style.CodeStyleSettings) at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.getCustomSettings(CustomCodeStyleSettingsManager.java:52)

### ISSUE THREAD

**Issue by lineargraph** [KronicDeth/intellij-elixir#2780]
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Linux (5.18.16-arch1-1)

# Event

## Message

Error determining tab size

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: Unable to get or create settings of #CodeStyleSettings (org.elixir_lang.code_style.CodeStyleSettings)
</summary>

```
java.lang.RuntimeException: Unable to get or create settings of #CodeStyleSettings (org.elixir_lang.code_style.CodeStyleSettings)
	at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.getCustomSettings(CustomCodeStyleSettingsManager.java:52)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getCustomSettings(CodeStyleSettings.java:129)
	at com.intellij.application.options.CodeStyle.getCustomSettings(CodeStyle.java:168)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.activeForFile(MixFormatExternalFormatProcessor.kt:26)
```

</details>

**Comment by sh41** [comment]
The registration this exception depends on has been correct since v13.1.0, which predates the 13.2.0 in your report.

`CustomCodeStyleSettingsManager.getCustomSettings` throws only when no registered factory produces the class at that instant — and on IntelliJ 2022.2 neither a settings file nor an imported scheme can cause that. So `langCodeStyleSettingsProvider` wasn't in the list right then, and the crash template gives no way to tell why. Best candidate: 2022.2 caches its settings-page providers once per application with no reset, so a provider registered after that cache warms stays invisible until restart.

Keeping this open, but there's been no other report in four years and the formatting tests exercise the mechanism without throwing on current `main`. If it recurs, the useful detail is whether the plugin had just been installed, updated or re-enabled without restarting the IDE.

> This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
