### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by sergeyberezansky** [KronicDeth/intellij-elixir#2782]
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class org.elixir_lang.distillery.configuration.Factory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: org.elixir_lang]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.execution.configurations.ConfigurationFactory.getId(ConfigurationFactory.java:75)
	at com.intellij.execution.impl.RunManagerImplKt.getFactoryKey(RunManagerImpl.kt:1401)
	at com.intellij.execution.impl.RunManagerImplKt.access$getFactoryKey(RunManagerImpl.kt:1)
	at com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate(RunManagerImpl.kt:344)
	at com.jetbrains.cidr.cpp.execution.manager.CLionRunConfigurationManager$UpdateSession.lambda$doUpdateRunConfigurations$2(CLionRunConfigurationManager.java:245)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1790)
	at com.jetbrains.cidr.cpp.execution.manager.CLionRunConfigurationManager$UpdateSession.doUpdateRunConfigurations(CLionRunConfigurationManager.java:245)
	at com.jetbrains.cidr.cpp.execution.manager.CLionRunConfigurationManager$UpdateSession.updateRunConfigurations(CLionRunConfigurationManager.java:216)
	at com.jetbrains.cidr.cpp.execution.manager.CLionRunConfigurationManager.updateRunConfigurations(CLionRunConfigurationManager.java:97)
	at com.jetbrains.cidr.cpp.execution.manager.CLionRunConfigurationManager.updateRunConfigurations(CLionRunConfigurationManager.java:82)
	at com.jetbrains.cidr.cpp.makefile.execution.run.MkRunConfigurationManagerHelper$Listener$targetsUpdated$$inlined$runInEdt$1$lambda$1$1.invoke(MkRunConfigurationManagerHelper.kt:58)
	at com.jetbrains.cidr.cpp.makefile.execution.run.MkRunConfigurationManagerHelper$Listener$targetsUpdated$$inlined$runInEdt$1$lambda$1$1.invoke(MkRunConfigurationManagerHelper.kt:34)
	at com.jetbrains.cidr.cpp.makefile.execution.build.MakefileBuildTargetsManager.lockRead(MakefileBuildTargetsManager.kt:119)
	at com.jetbrains.cidr.cpp.makefile.execution.run.MkRunConfigurationManagerHelper$Listener$targetsUpdated$$inlined$runInEdt$1$lambda$1.compute(actions.kt:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$13(ApplicationImpl.java:1032)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1011)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1032)
	at com.jetbrains.cidr.cpp.makefile.execution.run.MkRunConfigurationManagerHelper$Listener$targetsUpdated$$inlined$runInEdt$1.run(actions.kt:61)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by KronicDeth** [comment]
You're running plugin version 11.10.0 in IDE version 2021.3.  11.10.0 is incompatible with 2021.3.  It was likely marked incompatible in the Market Place after you upgraded to 2021.3.  You need to upgrade to plugin version 12.0.0 or later to get a version that is compatible with 2021.3 IDEs.
