### ISSUE TITLE
Don't know how to prepend qualifier at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:205)

### ISSUE THREAD

**Issue by M1kep** [KronicDeth/intellij-elixir#2799]
# System

Plugin Version: 13.2.0
Application: GoLand (2022.2)
Operating System: Mac OS X (12.5)

# Event

### Element

```
Cldr.Config.territories[:GB]
```

From: `/config.ex:0`

#### Context

```
Cldr.Config.territories[:GB]
%{
  currency: [GBP: %{from: ~D[1694-07-27]}],
  gdp: 2925000000000,
  language_population: %{
    "ar" => %{population_percent: 0.3},
```

From: `/config.ex:0-5`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedBracketOperationImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to prepend qualifier
</summary>

```
java.lang.Throwable: Don't know how to prepend qualifier
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:205)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.fullyQualifiedName(QualifiableAliasImpl.kt:125)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyQualifiedName(ElixirPsiImplUtil.java:834)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.fullyQualifiedName(ElixirUnmatchedQualifiedAliasImpl.java:55)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.computeReference(QualifiableAliasImpl.kt:39)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference$lambda-0(QualifiableAliasImpl.kt:56)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference(QualifiableAliasImpl.kt:55)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1083)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.getReference(ElixirUnmatchedQualifiedAliasImpl.java:75)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.getReference(ElixirUnmatchedQualifiedAliasImpl.java:18)
```

</details>

**Comment by KronicDeth** [comment]
This appears to the Markdown injected Elixir in this doctest in`ex_cldr`:

```elixir
      iex> Cldr.Config.territories[:GB]
      %{
        currency: [GBP: %{from: ~D[1694-07-27]}],
        gdp: 2925000000000,
        language_population: %{
          "ar" => %{population_percent: 0.3},
```
https://github.com/elixir-cldr/cldr/blob/072b201e9a4377e9c49d43b45545cc8b6e0cd83f/lib/cldr/config/config.ex#L1644-L1649
