### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file://E:/ideaUltimate/erlang/src/hw.beam (invalid) is invalid, invalidated at: no info at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)

### ISSUE THREAD

**Issue by ozzyozbourne** [KronicDeth/intellij-elixir#2819]
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Windows 10 (10.0)

# Event

### Stacktrace

<details>

<summary>
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file://E:/ideaUltimate/erlang/src/hw.beam (invalid) is invalid
</summary>

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file://E:/ideaUltimate/erlang/src/hw.beam (invalid) is invalid
invalidated at: no info
	at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)
```

</details>

**Comment by sh41** [comment]
Thanks for the report, and sorry nobody replied to it.

The top frame is a deliberate check on our side: `BeamFileImpl` refuses to hand out a file whose `.beam` on disk has gone away, the same way the platform's `ClsFileImpl` does for decompiled `.class` files. The check has been there since the class was added in `358cbe158` (December 2016). So the exception tells us *something* used a decompiled `.beam` after the file was deleted or replaced — but not what.

Unfortunately the submitted trace is only that one frame, with no caller below it, and `hw.beam` sits directly in `erlang/src` rather than in a `_build` output directory, so there is nothing to tie it to any particular path through the IDE. There is no way to work out from this what to fix, and at plugin 13.2.0 on IDEA 2022.2.1 there is no way to go back and find out now. This is the same reason #2993 was closed.

I am closing it on that basis rather than guessing. If you ever see this again on a current version, please do open a fresh issue with the whole stack trace — the frames below the top one are the part that identifies the caller.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
