### ISSUE TITLE
Don't know how to prepend qualifier at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:205)

### ISSUE THREAD

**Issue by pexarkh** [KronicDeth/intellij-elixir#2839]
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Mac OS X (12.5.1)

# Event

### Element

```
[String]
```

From: `collection_server/lib/collection_server/api/http/v8/user.ex:118`

#### Context

```elixir
          end

          namespace :find do # users/orgs/:entity_id/keyval/find
            desc "gets value associated with the given keys"
            params do
              requires :keys, type: List[String], default: []
            end
            post do
              {conn, user_info} = if FileSystem.Setting.require_admin?(params.keys, :get),
                                 do: Auth.authenticate(conn, :user, admin?: true),
                               else: Auth.authenticate(conn, {:entity, params.entity_id}, admin?: true)
```

From: `collection_server/lib/collection_server/api/http/v8/user.ex:113-123`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirBracketArgumentsImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to prepend qualifier
</summary>

```
java.lang.Throwable: Don't know how to prepend qualifier
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:205)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:147)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.fullyQualifiedName(QualifiableAliasImpl.kt:125)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyQualifiedName(ElixirPsiImplUtil.java:828)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.fullyQualifiedName(ElixirAliasImpl.java:37)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.computeReference(QualifiableAliasImpl.kt:39)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference$lambda-0(QualifiableAliasImpl.kt:56)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference(QualifiableAliasImpl.kt:55)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1083)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.getReference(ElixirAliasImpl.java:57)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.getReference(ElixirAliasImpl.java:19)
```

</details>

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/blob/4ca4cd3ea8de3242c81d964ac6bf9087db1c4483/src/org/elixir_lang/psi/impl/QualifiableAliasImpl.kt#L205
