### ISSUE TITLE
Prefix#operator AssertionError

### ISSUE THREAD

**Issue by MisterDeejay** [KronicDeth/intellij-elixir#286]
# Version

3.0.0

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.operator(ElixirPsiImplUtil.java:946)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.operator(ElixirUnmatchedUnaryNonNumericOperationImpl.java:92)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionNameElement(ElixirPsiImplUtil.java:1731)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.functionNameElement(ElixirUnmatchedUnaryNonNumericOperationImpl.java:47)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionName(ElixirPsiImplUtil.java:1696)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.functionName(ElixirUnmatchedUnaryNonNumericOperationImpl.java:42)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.resolvedFunctionName(ElixirPsiImplUtil.java:4058)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.resolvedFunctionName(ElixirUnmatchedUnaryNonNumericOperationImpl.java:132)
	at org.elixir_lang.annonator.Kernel$1.visitCall(Kernel.java:185)
	at org.elixir_lang.annonator.Kernel$1.visitElement(Kernel.java:207)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedExpressionImpl.accept(ElixirUnmatchedExpressionImpl.java:23)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnaryNonNumericOperationImpl.accept(ElixirUnmatchedUnaryNonNumericOperationImpl.java:25)
	at org.elixir_lang.annonator.Kernel.annotate(Kernel.java:179)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:162)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:354)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

```

**Comment by KronicDeth** [comment]
Any idea what you were typing when the error was triggered?  The `assert` failing would indicate that a prefix operation was doing some sort of error recovery so that it didn't actually have 2 valid child elements at the time the `assert` happened.  I need a regression test to cover this.

**Comment by KronicDeth** [comment]
#287 changes the assert to use the newer error reporting logger that will capture the element and file text, so it is easier to reproduce this error the next time it occurs.
