### ISSUE TITLE
Too many non-blocking read actions submitted at once. Please use coalesceBy, BoundedTaskExecutor or another way of limiting the number of concurrently running threads.: 11 with similar stack traces are currently active at com.intellij.openapi.application.impl.SubmissionTracker.preventTooManySubmissions(SubmissionTracker.java:45)

### ISSUE THREAD

**Issue by tanduong** [KronicDeth/intellij-elixir#2863]
# System

Plugin Version: 13.2.0
Application: RubyMine (2022.2.2)
Operating System: Mac OS X (12.5.1)

# Event

I got this error while trying to load an elixir monorepo.

### Stacktrace

<details>

<summary>
java.lang.Throwable: Too many non-blocking read actions submitted at once. Please use coalesceBy, BoundedTaskExecutor or another way of limiting the number of concurrently running threads.: 11 with similar stack traces are currently active
</summary>

```
java.lang.Throwable: Too many non-blocking read actions submitted at once. Please use coalesceBy, BoundedTaskExecutor or another way of limiting the number of concurrently running threads.: 11 with similar stack traces are currently active
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.openapi.application.impl.SubmissionTracker.preventTooManySubmissions(SubmissionTracker.java:45)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.<init>(NonBlockingReadActionImpl.java:231)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.submit(NonBlockingReadActionImpl.java:191)
	at com.intellij.execution.impl.RunManagerImpl.deleteRunConfigsFromArbitraryFilesNotWithinProjectContent(RunManagerImpl.kt:376)
	at com.intellij.execution.impl.RunManagerImpl.access$deleteRunConfigsFromArbitraryFilesNotWithinProjectContent(RunManagerImpl.kt:78)
	at com.intellij.execution.impl.RunManagerImpl$1.changed(RunManagerImpl.kt:222)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:629)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:470)
	at com.intellij.util.messages.impl.MessagePublisher.publish$intellij_platform_core(MessageBusImpl.kt:448)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:425)
	at jdk.proxy1/jdk.proxy1.$Proxy76.changed(Unknown Source)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.onChanged(WorkspaceModelImpl.kt:113)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.access$onChanged(WorkspaceModelImpl.kt:20)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$updateProjectModel$2.invoke(WorkspaceModelImpl.kt:76)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$updateProjectModel$2.invoke(WorkspaceModelImpl.kt:20)
	at com.intellij.workspaceModel.storage.impl.VersionedEntityStorageImpl.replace(VersionedEntityStorageImpl.kt:183)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.updateProjectModel(WorkspaceModelImpl.kt:76)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableRootModelBridgeImpl.commit(ModifiableRootModelBridgeImpl.kt:536)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1011)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1037)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$modifyModel$11(ModuleRootModificationUtil.java:158)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:492)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:525)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:156)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:146)
	at org.elixir_lang.mix.project.DirectoryConfigurator.configureRootOtpApp(DirectoryConfigurator.kt:63)
	at org.elixir_lang.mix.project.DirectoryConfigurator.configureProject(DirectoryConfigurator.kt:50)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$1$1.invoke(PlatformProjectOpenProcessor.kt:177)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$1$2.run(PlatformProjectOpenProcessor.kt:181)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:492)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:525)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$1.accept(PlatformProjectOpenProcessor.kt:180)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$1.accept(PlatformProjectOpenProcessor.kt:43)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion.runDirectoryProjectConfigurators(PlatformProjectOpenProcessor.kt:175)
	at org.elixir_lang.mix.project.DirectoryConfigurator.newProject(DirectoryConfigurator.kt:121)
	at org.elixir_lang.mix.project.DirectoryConfigurator.configureDescendantOtpApp(DirectoryConfigurator.kt:78)
	at org.elixir_lang.mix.project.DirectoryConfigurator.configureProject(DirectoryConfigurator.kt:52)
```

</details>

**Comment by KronicDeth** [comment]
How many Elixir apps were in the mono repo?

**Comment by sh41** [comment]
Fixed in v19.0.1 (2024-08-20).

The trace bottoms out in `DirectoryConfigurator`, which used to configure every OTP app found under the opened directory in turn. Each one committed a module-root change, and each commit provoked the platform's own `RunManagerImpl` listener into another non-blocking read submission — so on a monorepo that loop ran once per app with no bound, which is what `SubmissionTracker` was complaining about. The plugin never calls `ReadAction.nonBlocking(...).submit(...)` itself; it was driving a platform listener that does.

Since b698fdaec0 (#3643), opening a directory that contains more than one OTP app without going through the New Project Wizard shows an "Umbrella App detected" notification and configures nothing, so that loop no longer runs. You were on 13.2.0 — the fix has shipped in every release since v19.0.1.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
