### ISSUE TITLE
java.lang.Exception at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)

### ISSUE THREAD

**Issue by nichita-pasecinic** [KronicDeth/intellij-elixir#2869]
# System

Plugin Version: 13.2.0
Application: WebStorm (2022.2.1)
Operating System: Windows 10 (10.0)

# Event

## Message

Outdated stub in index: file://C:/elixir/ex_distributed_examples/swarm_background_job/lib/swarm_background_job/database_cleaner.ex indexing timestamp = 1664015249084, binary = false, byte size = 992, char size = 1129, doc=DocumentImpl[file://C:/elixir/ex_distributed_examples/swarm_background_job/lib/swarm_background_job/database_cleaner.ex], docSaved=true, wasIndexedAlready=true, queried at 1664015249084
doc length=949
file length=992
cached PSI class org.elixir_lang.psi.ElixirFile
projects with file: 1
physical file exists; length = 992

### Stacktrace

<details>

<summary>
java.lang.Exception
</summary>

```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:49)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:634)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:956)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:255)
	at com.intellij.psi.stubs.StubProcessingHelperBase.lambda$getAllSpines$0(StubProcessingHelperBase.java:85)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1790)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getAllSpines(StubProcessingHelperBase.java:85)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:65)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:138)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:185)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:50)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:195)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:91)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:928)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.accept(ElixirUnmatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
```

</details>

**Comment by KronicDeth** [comment]
I'm not sure why the stub wouldn't update itself if it was updated.  File this with JetBrains.
