### ISSUE TITLE
java.io.FileNotFoundException: /usr/local/Cellar/erlang/25.0.3/lib/erlang/bin/erl does not exist at org.elixir_lang.jps.SdkType.exeFileToExePath(SdkType.java:21)

### ISSUE THREAD

**Issue by SerafimD** [KronicDeth/intellij-elixir#2881]
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.2)
Operating System: Mac OS X (12.5.1)

# Event

### Stacktrace

<details>

<summary>
java.io.FileNotFoundException: /usr/local/Cellar/erlang/25.0.3/lib/erlang/bin/erl does not exist
</summary>

```
java.io.FileNotFoundException: /usr/local/Cellar/erlang/25.0.3/lib/erlang/bin/erl does not exist
	at org.elixir_lang.jps.SdkType.exeFileToExePath(SdkType.java:21)
	at org.elixir_lang.jps.sdk_type.Erlang.homePathToErlExePath(Erlang.java:44)
	at org.elixir_lang.Erl.exePath(Erl.kt:31)
	at org.elixir_lang.Erl.setErl(Erl.kt:49)
	at org.elixir_lang.Erl.commandLine(Erl.kt:17)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:20)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:85)
```

</details>

**Comment by SerafimD** [comment]
.
