### ISSUE TITLE
org.elixir_lang.dialyzer.service.DialyzerException: Error while running Dialyzer: Elixir SDK `Elixir at /usr/lib/elixir` is missing Erlang SDK at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.dialyzerWarnings(DialyzerServiceImpl.kt:51)

### ISSUE THREAD

**Issue by ojahe** [KronicDeth/intellij-elixir#2913]
# System

Plugin Version: 13.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.1.4)
Operating System: Linux (5.4.0-128-generic)

# Event

### Stacktrace

```
org.elixir_lang.dialyzer.service.DialyzerException: Error while running Dialyzer: Elixir SDK `Elixir at /usr/lib/elixir` is missing Erlang SDK
	at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.dialyzerWarnings(DialyzerServiceImpl.kt:51)
	at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.dialyzerWarnings(DialyzerServiceImpl.kt:34)
	at org.elixir_lang.dialyzer.inspection.Global.dialyzerWarnsByModule(Global.kt:53)
	at org.elixir_lang.dialyzer.inspection.Global.runInspection(Global.kt:23)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runGlobalTools$20(GlobalInspectionContextImpl.java:641)
	at com.intellij.codeInspection.ex.InspectionEventsKt.reportWhenInspectionFinished(inspectionEvents.kt:17)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runGlobalTools$21(GlobalInspectionContextImpl.java:634)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runGlobalTools(GlobalInspectionContextImpl.java:655)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:307)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$3(GlobalInspectionContextBase.java:259)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$4(GlobalInspectionContextBase.java:259)
	at com.intellij.psi.impl.PsiManagerImpl.runInBatchFilesMode(PsiManagerImpl.java:451)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$5(GlobalInspectionContextBase.java:253)
	at com.intellij.codeInspection.reference.RefManagerImpl.runInsideInspectionReadAction(RefManagerImpl.java:455)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:252)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:213)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir at /usr/lib/elixir` is missing Erlang SDK
	at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:34)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.run(DialyzerServiceImpl.kt:59)
	at org.elixir_lang.dialyzer.service.DialyzerServiceImpl.dialyzerWarnings(DialyzerServiceImpl.kt:48)
```

**Comment by KronicDeth** [comment]
I can reproduce this

1. Create an Elixir SDK with an Erlang SDK
2. Delete the Erlang SDK
3. Run the Dialyzer inspection
