### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by arseniocosta1** [KronicDeth/intellij-elixir#2922]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.4 Preview)
Operating System: Mac OS X (13.0)

# Event

### Stacktrace

<details>

<summary>
com.intellij.util.IncorrectOperationException: Sorry but parent: com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl@2955110 (class com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl) has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.roots.impl.JavaModuleExternalPathsImpl@530a8cd2 (class com.intellij.openapi.roots.impl.JavaModuleExternalPathsImpl) will never be disposed
</summary>

```
com.intellij.util.IncorrectOperationException: Sorry but parent: com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl@2955110 (class com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl) has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.roots.impl.JavaModuleExternalPathsImpl@530a8cd2 (class com.intellij.openapi.roots.impl.JavaModuleExternalPathsImpl) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:46)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:118)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl$Companion.loadExtension(RootModelBridgeImpl.kt:150)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl$Companion.loadExtensions$intellij_platform_projectModel_impl(RootModelBridgeImpl.kt:130)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl$extensions$2.invoke(RootModelBridgeImpl.kt:38)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl$extensions$2.invoke(RootModelBridgeImpl.kt:30)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl.getExtensions(RootModelBridgeImpl.kt)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.RootModelBridgeImpl.getModuleExtension(RootModelBridgeImpl.kt:83)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModuleRootComponentBridge.getModuleExtension(ModuleRootComponentBridge.kt:133)
	at com.intellij.openapi.roots.impl.ExcludeCompilerOutputPolicy.getExcludeRootsForModule(ExcludeCompilerOutputPolicy.java:36)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ContentEntryBridge.getExcludeFolderFiles(ContentEntryBridge.kt:42)
	at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:187)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:73)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:160)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:142)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:170)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:96)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isUnderIgnored(ProjectFileIndexImpl.java:87)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isUnderIgnored(ProjectFileIndexFacade.java:60)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.isExcludedOrIgnored(FileManagerImpl.java:425)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:411)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:403)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:168)
	at com.intellij.psi.AbstractFileViewProvider.shouldCreatePsi(AbstractFileViewProvider.java:90)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:144)
	at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:100)
	at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:194)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.areViewProvidersEquivalent(FileManagerImpl.java:542)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.shouldResurrect(FileManagerImpl.java:639)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:607)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:592)
	at com.intellij.psi.impl.source.PsiFileImpl.isValid(PsiFileImpl.java:163)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:123)
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:124)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:112)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:114)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.checkUpToDate(CachedValueBase.java:97)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:93)
	at com.intellij.psi.impl.PsiCachedValueImpl.getUpToDateOrNull(PsiCachedValueImpl.java:13)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:149)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:928)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packagePsiFileToDepSet(Resolution.kt:122)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packageVirtualFileToDepSet(Resolution.kt:97)
	at org.elixir_lang.mix.watcher.Resolution$Companion.rootVirtualFileToDepSet(Resolution.kt:80)
	at org.elixir_lang.mix.watcher.Resolution$Companion.resolution(Resolution.kt:38)
	at org.elixir_lang.mix.watcher.TransitiveResolution.transitiveResolution(TransitiveResolution.kt:17)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:64)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:198)
	at org.elixir_lang.DepsWatcher.syncLibrary(DepsWatcher.kt:179)
	at org.elixir_lang.DepsWatcher.access$syncLibrary(DepsWatcher.kt:32)
	at org.elixir_lang.DepsWatcher$syncLibraries$2$2$2$3$1$1.run(DepsWatcher.kt:143)
```

</details>

**Comment by sh41** [comment]
Fixed in 24.0.0.

The plugin frames in this trace run through `DepsWatcher` and `org.elixir_lang.mix.Watcher` — the old thread-based Mix dependency watcher, which resolved deps inside a blocking `runReadAction`. That held a read lock across a module root-model disposal, which is what produced the `IncorrectOperationException`.

Both classes were deleted outright by the dependency-sync rewrite in #3839, so this isn't a patch to the throwing line: the code that owned every plugin frame in the trace no longer exists. Dependency resolution now runs in a coroutine pipeline. `Resolution` uses the platform's cancellable `readAction`, which restarts the read when a write action preempts it rather than letting it observe half-disposed state, and the `PsiManager.findFile` call is guarded against `IncorrectOperationException` explicitly.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
