### ISSUE TITLE
NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(com.intellij.lang.PsiBuilder, com.intellij.psi.tree.IElementType)

### ISSUE THREAD

**Issue by developerworks** [KronicDeth/intellij-elixir#293]
# Version

3.0.1

# Exception

## Message

com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z

## Stacktrace

```
java.lang.NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
	at org.elixir_lang.parser.ElixirParser.unmatchedCaptureNonNumericOperation(ElixirParser.java:6189)
	at org.elixir_lang.parser.ElixirParser.unmatchedExpression(ElixirParser.java:6070)
	at org.elixir_lang.parser.ElixirParser.expression(ElixirParser.java:2162)
	at org.elixir_lang.parser.ElixirParser.expressionList(ElixirParser.java:2174)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1_0(ElixirParser.java:2047)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1(ElixirParser.java:2038)
	at org.elixir_lang.parser.ElixirParser.elixirFile(ElixirParser.java:2023)
	at org.elixir_lang.parser.ElixirParser.parse_root_(ElixirParser.java:649)
	at org.elixir_lang.parser.ElixirParser.parseLight(ElixirParser.java:643)
	at org.elixir_lang.parser.ElixirParser.parse(ElixirParser.java:19)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.f(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:769)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:439)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:396)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:386)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInjectedElementNoCommit(InjectedLanguageUtil.java:371)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInjectedPsiNoCommit(InjectedLanguageUtil.java:271)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.getEditorForInjectedLanguageNoCommit(InjectedLanguageUtil.java:233)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.getEditorForInjectedLanguageNoCommit(InjectedLanguageUtil.java:170)
	at com.intellij.codeInsight.actions.BaseCodeInsightAction.getInjectedEditor(BaseCodeInsightAction.java:64)
	at com.intellij.codeInsight.actions.BaseCodeInsightAction.getInjectedEditor(BaseCodeInsightAction.java:54)
	at com.intellij.codeInsight.actions.BaseCodeInsightAction.getEditor(BaseCodeInsightAction.java:50)
	at com.intellij.codeInsight.actions.CodeInsightAction.update(CodeInsightAction.java:85)
	at com.intellij.codeInsight.actions.BaseCodeInsightAction.update(BaseCodeInsightAction.java:90)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.update(GotoDeclarationAction.java:293)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:243)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:111)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:483)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by KronicDeth** [comment]
`com.intellij` is something IntellIJ itself should be supplying, so this could be able build error maybe.  I might have a released a version of the plugin built against too new of a IntelliJ.  Which version of IntelliJ are you running in?

**Comment by anolivetree** [comment]
Same error on IntelliJ 15.0

**Comment by Havvy** [comment]
I'm getting it with v2016.1 (built March 17)

**Comment by KronicDeth** [comment]
I just realized when responding to #302 that how to downgrade isn't obvious, so here's the steps:

Try downgrading to 3.0.0 using the [download link on the JetBrains plugin repo}(https://plugins.jetbrains.com/plugin/download?pr=&updateId=24927) by first uninstalling the plugin:
1) Preferences > Plugins
2) Select Elixir
3) Click the Uninstall button
4) Click the Restart IntelliJ Elixir button that replaces the Uninstall button
5) Install the `intellij-elixir.zip` for 3.0.0 using [the instructions in the README](https://github.com/KronicDeth/intellij-elixir#in-ide).

**Comment by KronicDeth** [comment]
Related to #391
