### ISSUE TITLE
Invalid file: xxxx.ex (invalid) at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:357)

### ISSUE THREAD

**Issue by laobaox** [KronicDeth/intellij-elixir#2952]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Community Edition (2022.2.4)
Operating System: Mac OS X (12.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Invalid file: xxx.ex (invalid)
</summary>

```
java.lang.Throwable: Invalid file: file:///xxx.ex (invalid)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:357)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:155)
	at org.elixir_lang.debugger.Process.moduleNameSet(Process.kt:292)
	at org.elixir_lang.debugger.Process.addBreakpoint(Process.kt:124)
	at org.elixir_lang.debugger.line_breakpoint.Handler.registerBreakpoint(Handler.kt:27)
	at org.elixir_lang.debugger.line_breakpoint.Handler.registerBreakpoint(Handler.kt:25)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.handleBreakpoint(XDebugSessionImpl.java:434)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.processBreakpoints(XDebugSessionImpl.java:419)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.processAllBreakpoints(XDebugSessionImpl.java:575)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:314)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.init(XDebugSessionImpl.java:282)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:280)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:232)
	at org.elixir_lang.debugger.Runner.doExecute(Runner.kt:36)
```

</details>

**Comment by KronicDeth** [comment]
There isn't enough context to reproduce this error as I can't tell if there are two files with the same name or something else caused the invalid file error.
