### ISSUE TITLE
java.lang.NoSuchFieldError: Companion at org.elixir_lang.reference.Resolver.moduleForSourceOrLibrary(Resolver.kt:87)

### ISSUE THREAD

**Issue by sh41** [KronicDeth/intellij-elixir#2960]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.4)
Operating System: Linux (5.15.79.1-microsoft-standard-WSL2)

# Event
Shortly after upgrading to v14. Has been logged 6 times in 10 minutes. The only variation on the message added 
```
ExternalJavaDocAction#update@MainMenu (com.intellij.ide.actions.ExternalJavaDocAction), actionId=ExternalJavaDoc, text='External Documentation'
```
to the top of the stack trace. 

### Stacktrace

<details>

<summary>
java.lang.NoSuchFieldError: Companion
</summary>

```
java.lang.NoSuchFieldError: Companion
	at org.elixir_lang.reference.Resolver.moduleForSourceOrLibrary(Resolver.kt:87)
	at org.elixir_lang.reference.Resolver.filterUnderSameModule(Resolver.kt:61)
	at org.elixir_lang.reference.Resolver.preferUnderSameModule(Resolver.kt:40)
	at org.elixir_lang.reference.Resolver.preferElementUnderSameModule(Resolver.kt:32)
	at org.elixir_lang.reference.Resolver.preferred(Resolver.kt:16)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:74)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:35)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:31)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:23)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:95)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:83)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:187)
	at org.elixir_lang.psi.Use.modulars(Use.kt:84)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:35)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:65)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:39)
	at org.elixir_lang.psi.scope.Module$execute$1.invoke(Module.kt:65)
	at org.elixir_lang.psi.scope.Module$execute$1.invoke(Module.kt:65)
	at org.elixir_lang.psi.QuoteMacro.treeWalkUp(QuoteMacro.kt:34)
	at org.elixir_lang.psi.QuoteMacro.treeWalkUp(QuoteMacro.kt:18)
	at org.elixir_lang.psi.Using.treeWalkUpFromLastChildCall(Using.kt:59)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:44)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:27)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:39)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:65)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:39)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:440)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:439)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:303)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:443)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:417)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:265)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:655)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:137)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:128)
	at org.elixir_lang.reference.resolver.Module.resolveInScope(Module.kt:83)
	at org.elixir_lang.reference.resolver.Module.resolveAll(Module.kt:78)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:72)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:35)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:31)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:23)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.reference.Module.resolve(Module.kt:38)
	at org.elixir_lang.structure_view.node_provider.Used$Companion.provideNodesFromChild(Used.kt:97)
	at org.elixir_lang.structure_view.node_provider.Used$Companion.provideNodesFromChildren(Used.kt:201)
	at org.elixir_lang.structure_view.element.modular.Module$Companion.childCallTreeElements(Module.kt:181)
	at org.elixir_lang.structure_view.element.modular.Module$Companion.callChildren(Module.kt:86)
	at org.elixir_lang.structure_view.element.modular.Module.getChildren(Module.kt:44)
```

</details>

### [induced.txt](https://github.com/KronicDeth/intellij-elixir/files/10260489/induced.txt)

**Comment by LThemes** [comment]
Happens too in:
plugin v14
mac Version 13.0.1 (22A400)
WebStorm 2022.2.4

**Comment by kreba** [comment]
Same happens for me since I upgraded today.

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3)
Operating System: Linux (5.19.0-26-generic) (Ubuntu 22.10)

<details>
<summary>java.util.NoSuchElementException</summary>
```
java.util.NoSuchElementException
	at org.elixir_lang.reference.Resolver.moduleForSourceOrLibrary(Resolver.kt:142)
	at org.elixir_lang.reference.Resolver.filterUnderSameModule(Resolver.kt:61)
	at org.elixir_lang.reference.Resolver.preferUnderSameModule(Resolver.kt:40)
	at org.elixir_lang.reference.Resolver.preferElementUnderSameModule(Resolver.kt:32)
	at org.elixir_lang.reference.Resolver.preferred(Resolver.kt:16)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:74)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:35)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:31)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:23)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:95)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:83)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:187)
	at org.elixir_lang.psi.Import.modulars(Import.kt:279)
	at org.elixir_lang.psi.Import.treeWalkUp(Import.kt:52)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:143)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:167)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:44)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:255)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:242)
	at org.elixir_lang.reference.resolver.Callable.resolveQualified(Callable.kt:156)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:101)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:89)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:860)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.reference.Callable.resolve(Callable.kt:112)
```
</details>

**Comment by alabama** [comment]
same same 

Plugin Version: 14.0.0
Application: WebStorm 2022.3
Build #WS-223.7571.168, built on November 28, 2022
Operating System: Linux (5.19.0-26-generic) (Ubuntu 22.10)

same stacktrace with java.util.NoSuchElementException...

The problem after the error is that no code completion for alias modules work anymore. 'GoTo Definition' is also not working for aliased modules.

Current workaround is to install the self build plugin from @laibulle
https://github.com/KronicDeth/intellij-elixir/issues/2942#issuecomment-1334549388

**Comment by KronicDeth** [comment]
Escalated to JetBrains as https://youtrack.jetbrains.com/issue/IDEA-313014/

**Comment by KronicDeth** [comment]
14.0.0 should not be used on < 2022.3.  The compatibility matrix is incorrect in the published version
