### ISSUE TITLE
Do not known whether to inject Markdown in documentation key type at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:49)

### ISSUE THREAD

**Issue by srbaker** [KronicDeth/intellij-elixir#2964]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Community Edition (2022.3)
Operating System: Mac OS X (13.0.1)

# Event

### Element

```
type: :component
```

From: `/Users/srbaker/Projects/roadie/deps/phoenix_live_view/lib/phoenix_component.ex:1868`

#### Context

```
  <.form :let={f} for={@changeset} action={Routes.comment_path(:create, @comment)}>
    <%= text_input f, :body %>
  </.form>
  ```
  """
  @doc type: :component
  attr.(:for, :any, required: true, doc: "The form source data.")

  attr.(:action, :string,
    default: nil,
    doc: """
```

From: `/Users/srbaker/Projects/roadie/deps/phoenix_live_view/lib/phoenix_component.ex:1863-1873`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirNoParenthesesKeywordPairImpl
```


## Exception


### Stacktrace


<details>

<summary>
java.lang.Throwable: Do not known whether to inject Markdown in documentation key type
</summary>

```
java.lang.Throwable: Do not known whether to inject Markdown in documentation key type
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:49)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment]
Duplicate of #3017
