### ISSUE TITLE
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: noconnection at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)

### ISSUE THREAD

**Issue by jmSfernandes** [KronicDeth/intellij-elixir#2965]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.1)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: noconnection
</summary>

```
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: noconnection
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.elixir_lang.MailBox.wait(MailBox.kt:203)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:356)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:352)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:393)
	at org.elixir_lang.debugger.Process.asyncRunInitializers$lambda$14(Process.kt:375)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.ericsson.otp.erlang.OtpErlangExit: noconnection
	at com.ericsson.otp.erlang.OtpMbox.receiveMsg(OtpMbox.java:272)
	at com.ericsson.otp.erlang.OtpMbox.receive(OtpMbox.java:168)
	at org.elixir_lang.MailBox.loop(MailBox.kt:219)
	at org.elixir_lang.MailBox._init_$lambda$0(MailBox.kt:26)
```

</details>

**Comment by KronicDeth** [comment]
This should be turned into a user notification instead of being an error for the error reporter since it is a machine configuration issue that the user can fix.
