### ISSUE TITLE
java.lang.NoSuchFieldError: Companion at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:193)

### ISSUE THREAD

**Issue by SteelzZ** [KronicDeth/intellij-elixir#2968]
# System

Plugin Version: 14.0.0
Application: GoLand (2022.2.5)
Operating System: Mac OS X (12.2.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.NoSuchFieldError: Companion
</summary>

```
java.lang.NoSuchFieldError: Companion
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:193)
	at org.elixir_lang.DepsWatcher.syncLibrary(DepsWatcher.kt:179)
	at org.elixir_lang.DepsWatcher.access$syncLibrary(DepsWatcher.kt:32)
	at org.elixir_lang.DepsWatcher$fileCreated$1$3.run(DepsWatcher.kt:79)
```

</details>

**Comment by KronicDeth** [comment]
I need reproduction steps because I can't see from the code why `ModuleManager.getInstance(project).modules` would fail in this way.
