### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.sdk.elixir.Type at org.elixir_lang.new_project_wizard.Step$setupUI$1$1$sdkTypeFilter$1.invoke(Step.kt:52)

### ISSUE THREAD

**Issue by nimmividya** [KronicDeth/intellij-elixir#2969]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Community Edition (2022.3)
Operating System: Mac OS X (13.0.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.sdk.elixir.Type
</summary>

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.sdk.elixir.Type
	at org.elixir_lang.new_project_wizard.Step$setupUI$1$1$sdkTypeFilter$1.invoke(Step.kt:52)
	at org.elixir_lang.new_project_wizard.Step$setupUI$1$1$sdkTypeFilter$1.invoke(Step.kt:52)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBoxKt.createSdkComboBox$lambda-1(JdkComboBox.kt:93)
	at com.intellij.openapi.roots.ui.configuration.SdkListModelBuilder.lambda$new$0(SdkListModelBuilder.java:81)
	at com.intellij.openapi.roots.ui.configuration.SdkListModelBuilder.lambda$new$2(SdkListModelBuilder.java:91)
	at com.intellij.openapi.roots.ui.configuration.SdkListModelBuilder.reloadSdks(SdkListModelBuilder.java:241)
	at com.intellij.openapi.roots.ui.configuration.SdkComboBoxBase.reloadModel(SdkComboBoxBase.java:73)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.<init>(JdkComboBox.java:108)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.<init>(JdkComboBox.java:87)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBoxKt.createSdkComboBox(JdkComboBox.kt:93)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBoxKt.sdkComboBox(JdkComboBox.kt:70)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBoxKt.sdkComboBox$default(JdkComboBox.kt:54)
	at org.elixir_lang.new_project_wizard.Step$setupUI$1$1.invoke(Step.kt:53)
	at org.elixir_lang.new_project_wizard.Step$setupUI$1$1.invoke(Step.kt:51)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:60)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:47)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:23)
	at org.elixir_lang.new_project_wizard.Step.setupUI(Step.kt:51)
```

</details>

**Comment by KronicDeth** [comment]
I'm not sure how one class in the plugin can't see another one in the class.  If you have reproduction steps I'll reopen.
