### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchFieldError: Companion at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:118)

### ISSUE THREAD

**Issue by dmitriigaidarji** [KronicDeth/intellij-elixir#2975]
# System

Plugin Version: 14.0.0
Application: WebStorm (2022.2.3)
Operating System: Mac OS X (13.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: java.lang.NoSuchFieldError: Companion
</summary>

```
java.lang.RuntimeException: java.lang.NoSuchFieldError: Companion
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:505)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:525)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$1.accept(PlatformProjectOpenProcessor.kt:180)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$1.accept(PlatformProjectOpenProcessor.kt:43)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion.runDirectoryProjectConfigurators(PlatformProjectOpenProcessor.kt:175)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:364)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:60)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:131)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:60)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:95)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NoSuchFieldError: Companion
	at org.elixir_lang.mix.project.DirectoryConfigurator.configureRootOtpApp(DirectoryConfigurator.kt:64)
	at org.elixir_lang.mix.project.DirectoryConfigurator.configureProject(DirectoryConfigurator.kt:52)
```

</details>

**Comment by KronicDeth** [comment]
This appears to be a problem that `ModuleManger.getInstance` fails because `getInstance` is a `companion object` method.  It is defined in a JetBrains API and not a bug in the plugin.

Escalated to JetBrains as https://youtrack.jetbrains.com/issue/IDEA-313014
