### ISSUE TITLE
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\liusp\AppData\Local\JetBrains\IntelliJIdea2022.3\index\fileincludes\.perFileVersion\indexed_versions\indexed_versions at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)

### ISSUE THREAD

**Issue by liuspatt** [KronicDeth/intellij-elixir#2996]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.1)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\liusp\AppData\Local\JetBrains\IntelliJIdea2022.3\index\fileincludes\.perFileVersion\indexed_versions\indexed_versions
</summary>

```
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\liusp\AppData\Local\JetBrains\IntelliJIdea2022.3\index\fileincludes\.perFileVersion\indexed_versions\indexed_versions
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:272)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:263)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:587)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:549)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:169)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator$MyEnumerator.enumerate(PersistentSubIndexerVersionEnumerator.java:22)
	at com.intellij.util.io.CachingEnumerator.enumerate(CachingEnumerator.java:75)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator.enumerate(PersistentSubIndexerVersionEnumerator.java:60)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getFileIndexerId(PersistentSubIndexerRetriever.java:103)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getSubIndexerState(PersistentSubIndexerRetriever.java:93)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getIndexingStateForFile(VfsAwareMapReduceIndex.java:274)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.getIndexingStateForFile(CompositeInvertedIndexBase.java:221)
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndexingState(FileBasedIndexImpl.java:1961)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$25(FileBasedIndexImpl.java:1443)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:670)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1421)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1394)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1342)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1760)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:808)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:390)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:167)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:54)
	at org.elixir_lang.reference.resolver.atom.resolvable.Exact.resolve(Exact.kt:20)
	at org.elixir_lang.reference.resolver.Atom.resolve(Atom.java:20)
	at org.elixir_lang.reference.resolver.Atom.resolve(Atom.java:11)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.Atom.multiResolve(Atom.java:43)
	at org.elixir_lang.reference.Atom.resolve(Atom.java:49)
```

</details>

**Comment by KronicDeth** [comment]
Please report this corrupted storage issue directly to JetBrains.  I don't write the storage directly, but abstracted through their APIs.
