### ISSUE TITLE
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.2` is missing Erlang SDK at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)

### ISSUE THREAD

**Issue by widojansen** [KronicDeth/intellij-elixir#3001]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.1)
Operating System: Mac OS X (11.7.2)

# Event

### Stacktrace

<details>

<summary>
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.2` is missing Erlang SDK
</summary>

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.2` is missing Erlang SDK
	at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:34)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.commandLine(MixFormatExternalFormatProcessor.kt:89)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.format(MixFormatExternalFormatProcessor.kt:84)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.access$format(MixFormatExternalFormatProcessor.kt:69)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda$7$lambda$6(MixFormatExternalFormatProcessor.kt:46)
```

</details>

**Comment by KronicDeth** [comment]
This should be changed to a logged error or notification at most.
