### ISSUE TITLE
java.lang.RuntimeException: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'prometheus' (disposed) at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:120)

### ISSUE THREAD

**Issue by kpy3** [KronicDeth/intellij-elixir#3002]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Community Edition (2022.3.1)
Operating System: Mac OS X (13.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'prometheus' (disposed)
</summary>

```
java.lang.RuntimeException: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'prometheus' (disposed)
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:120)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:421)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:441)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:70)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:65)
	at org.elixir_lang.mix.Watcher$contentsChanged$1$1.run(Watcher.kt:52)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'prometheus' (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkState(ComponentManagerImpl.kt:201)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:593)
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:37)
	at org.elixir_lang.mix.Watcher.syncLibraries$lambda$9$lambda$8(Watcher.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:955)
	at org.elixir_lang.mix.Watcher.syncLibraries$lambda$9(Watcher.kt:71)
```

</details>

**Comment by KronicDeth** [comment]
Line 74 needs to check that the `module` is still valid.

https://github.com/KronicDeth/intellij-elixir/blob/f4663b802aae61c833550feba199b9e0a06fba15/src/org/elixir_lang/mix/Watcher.kt#L70-L74
