### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented. at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:299)

### ISSUE THREAD

**Issue by vincentopensourcetaiwan** [KronicDeth/intellij-elixir#3020]
# System

Plugin Version: 14.0.0
Application: RubyMine (2022.3.1)
Operating System: Mac OS X (12.3.1)

# Event

### Stacktrace

<details>

<summary>
kotlin.NotImplementedError: An operation is not implemented.
</summary>

```
kotlin.NotImplementedError: An operation is not implemented.
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:299)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:87)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:83)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:37)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.childExpressionsFoldWhile(Modular.kt:20)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressionsFoldWhile(PsiElementImpl.kt:219)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:83)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:92)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:112)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:87)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:83)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:37)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.childExpressionsFoldWhile(Modular.kt:20)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressionsFoldWhile(PsiElementImpl.kt:219)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:83)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClause$1.invoke(Assign.kt:69)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClause$1.invoke(Assign.kt:69)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClause(Assign.kt:844)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClause(Assign.kt:64)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInViewModule(Assign.kt:55)
	at org.elixir_lang.leex.reference.resolver.Assign.resolve(Assign.kt:28)
	at org.elixir_lang.leex.reference.resolver.Assign.resolve(Assign.kt:21)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.leex.reference.Assign.multiResolve(Assign.kt:18)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.elixir_lang.folding.Builder$buildFoldRegions$1.slowExecute(Builder.kt:242)
	at org.elixir_lang.folding.Builder$buildFoldRegions$1.slowExecute(Builder.kt:203)
	at org.elixir_lang.folding.Builder$buildFoldRegions$1.execute(Builder.kt:72)
	at org.elixir_lang.folding.Builder$buildFoldRegions$1.execute(Builder.kt:47)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:923)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedExpressionImpl.accept(ElixirUnmatchedExpressionImpl.java:27)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtOperationImpl.accept(ElixirUnmatchedAtOperationImpl.java:29)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:53)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:10)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:924)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:51)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:920)
	at org.elixir_lang.folding.Builder.buildFoldRegions(Builder.kt:39)
```

</details>

**Comment by KronicDeth** [comment]
This `TODO()` needs to be replaced with an error reporter call that can show the element in the report

https://github.com/KronicDeth/intellij-elixir/blob/f4663b802aae61c833550feba199b9e0a06fba15/src/org/elixir_lang/leex/reference/resolver/Assign.kt#L299
