### ISSUE TITLE
java.io.IOException at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)

### ISSUE THREAD

**Issue by evertvankammen** [KronicDeth/intellij-elixir#3024]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.1)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.io.IOException
</summary>

```
java.io.IOException
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)
```

</details>

**Comment by sh41** [comment]
Duplicate of #2721 — same title, same stack trace, same call site, and the same underlying defect: when `mix new` failed, the New Project wizard threw an `IOException` with no message and the notification explaining why was suppressed, so neither you nor the crash report could see what Mix had objected to.

Both halves are fixed. The failure notification is no longer attached to the half-created project, which has no window to show it in (v15.0.1), and Mix's own stderr is now included in the exception message (v15.1.0). A `mix new` failure on a current plugin tells you Mix's reason — #3459 is what that looks like.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
