### ISSUE TITLE
Run/debug configs broken for Mix ExUnit on OTP 25

### ISSUE THREAD

**Issue by leahgoldberg** [KronicDeth/intellij-elixir#3035]
**Describe the bug**
Since upgrading to OTP 25/Elixir 1.14, run/debug configurations no longer run in IntelliJ. They fail with the following error 

```
** (BadArityError) #Function<0.82203088/3 in :elixir.eval_external_handler/1> with arity 3 called with 2 arguments ({Config, :config}, [:argon2_elixir, [parallelism: 2]])
    (stdlib 4.1.1) erl_eval.erl:689: :erl_eval.do_apply/6
    (stdlib 4.1.1) erl_eval.erl:123: :erl_eval.exprs/5
    (elixir 1.14.2) lib/code.ex:425: Code.validated_eval_string/3
    (elixir 1.14.2) lib/config.ex:288: Config.__eval__!/3
    (mix 1.14.2) lib/mix/tasks/loadconfig.ex:54: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.14.2) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
```

**To Reproduce**
1. Install Elixir 1.14.2-otp-25 via asdf
2. Use this as the project SDK
3. Import apps as a Mix project, ensure Elixir 1.14.2-otp-25 is set as the module for each
4. Try to run a mix test via the run/debug configuration

**Expected behavior**
Tests should run

**Logs**
```
** (BadArityError) #Function<0.82203088/3 in :elixir.eval_external_handler/1> with arity 3 called with 2 arguments ({Config, :config}, [:argon2_elixir, [parallelism: 2]])
    (stdlib 4.1.1) erl_eval.erl:689: :erl_eval.do_apply/6
    (stdlib 4.1.1) erl_eval.erl:123: :erl_eval.exprs/5
    (elixir 1.14.2) lib/code.ex:425: Code.validated_eval_string/3
    (elixir 1.14.2) lib/config.ex:288: Config.__eval__!/3
    (mix 1.14.2) lib/mix/tasks/loadconfig.ex:54: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.14.2) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
```

**Desktop:**
 - OS: macOS
 - Version: 13.1

**Erlang:**
- Installer: asdf
- Version: 25

**Elixir:**
- Installer: asdf
- Version: 1.14.2

**Plugin:**
- Version: 14.0.0

**IntelliJ:**
- Version: 2022.3.2

**Additional context**
This is not an issue with my local env since mix exunit tests run just fine in the terminal (whether it's iterm or the intelliJ terminal)

**Comment by leahgoldberg** [comment]
hello wanted to check in here and see if there's been any update! I'm still experiencing this issue on IntelliJ v2023.3.5 and plugin v17.0.0. thanks 🙏

**Comment by sh41** [comment]
This one isn't the plugin's, and the quickest way to see that is to run `mix test` in a terminal with
no IDE involved — it fails the same way.

Every frame in the trace is Elixir or Mix: `Mix.Tasks.Loadconfig`, `Config.__eval__!`,
`Code.validated_eval_string`, `:erl_eval.do_apply`, `:elixir.eval_external_handler`. Mix runs
`loadconfig` before *every* task, so this is reached whether the task was started by the IDE or by you.
The plugin doesn't supply an eval handler, doesn't pass `-eval` on that path, and has no code between
Mix and the error.

What the `BadArityError` says is that something in the project's config is calling
`Config.config/2` in a way the Elixir 1.14 config evaluator doesn't accept. The `argon2_elixir`
settings named in the trace are where to look — either how that block is written, or a version of it
that predates the 1.14 config changes.

Closing because there is nothing in this repository to change. If it turns out the plugin *does*
contribute something here after all — a different Elixir being invoked than the one you use in the
terminal, say — please reopen with both traces, since that would be a different issue from the one
reported.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
