### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes at java.base/java.lang.Class.forName0(Native Method)

### ISSUE THREAD

**Issue by dstockto** [KronicDeth/intellij-elixir#3048]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.2)
Operating System: Mac OS X (13.0.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes
</summary>

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.intellij.psi.stubs.StubElementTypeHolderEP.initializeOptimized(StubElementTypeHolderEP.java:63)
	at com.intellij.psi.stubs.IStubElementType.lambda$loadRegisteredStubElementTypes$0(IStubElementType.java:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:153)
	at com.intellij.psi.stubs.IStubElementType.loadRegisteredStubElementTypes(IStubElementType.java:69)
	at com.intellij.psi.stubs.SerializationManagerImpl.initSerializers(SerializationManagerImpl.java:258)
	at com.intellij.psi.stubs.SerializationManagerImpl.serialize(SerializationManagerImpl.java:207)
	at com.intellij.psi.stubs.SerializedStubTree.serializeStub(SerializedStubTree.java:56)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:196)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:159)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:125)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:30)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:19)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:317)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:308)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:176)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:40)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:253)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:62)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:21)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:284)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:62)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:28)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateIndexInNonCancellableSection(FileBasedIndexImpl.java:1047)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$indexUnsavedDocument$16(FileBasedIndexImpl.java:1021)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:670)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:653)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocument(FileBasedIndexImpl.java:1009)
	at com.intellij.util.indexing.RegisteredIndexes$DocumentUpdateTask.doProcess(RegisteredIndexes.java:182)
	at com.intellij.util.indexing.RegisteredIndexes$DocumentUpdateTask.doProcess(RegisteredIndexes.java:173)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$indexUnsavedDocuments$15(FileBasedIndexImpl.java:976)
	at com.intellij.util.indexing.StorageBufferingHandler.runUpdate(StorageBufferingHandler.java:22)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocuments(FileBasedIndexImpl.java:976)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:810)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:312)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:71)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.nameInAnyQuote(MultiResolve.kt:153)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveResultList(MultiResolve.kt:118)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:122)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:103)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:89)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.reference.Callable.resolve(Callable.kt:112)
```

</details>

**Comment by sh41** [comment]
Sorry for the long silence.

`Could not initialize class X` is a secondary failure: `ModuleStubElementTypes`'s static initializer threw earlier in that IDE session, and every later touch of the class — this stub-serialization pass — reports the bare message with no cause attached. So the real error was a different exception in the same session, and it isn't in this report.

Two things in exactly this path have changed since the 14.0.0 you were running, both first released in v22.0.0.

The frames at the top of your trace are the platform force-initializing the stub holder through `Class.forName`, which it only does when the `<stubElementTypeHolder>` registration has no `externalIdPrefix`. `791eb4711` added one, and the platform now takes a reflection-only branch that never runs the class initializer — so this trace can't be produced again.

Separately, `ModuleStubElementType`'s constructor had been passing `ElixirLanguage.INSTANCE`, the source-file language, rather than the BEAM language these stub types actually describe, from 2016 until `e4af4c6f2`. While that was there, a failure of `ElixirLanguage`'s own initializer — independently reported in #2116, #2120 and #2121 — could take `ModuleStubElementTypes` down with it. That coupling is gone.

Neither commit was written against this report, and with no `Caused by:` here I can't say either was what you hit. So I'm closing on the narrower claim: the ways this could happen that we can identify are fixed and released, not that yours was one of them.

If it recurs on a current release, the useful report is the *first* exception of that session — the `ExceptionInInitializerError` with its `Caused by:` chain — from `idea.log` (Help | Show Log in Explorer/Finder).

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
