### ISSUE TITLE
Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction()) at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:980)

### ISSUE THREAD

**Issue by mlynarczyk** [KronicDeth/intellij-elixir#3051]
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.3)
Operating System: Mac OS X (13.1)

# Event

## Message

Details: Current thread: Thread[Alarm Pool,4,main] 924538676
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 309177402

### Stacktrace

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:980)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:595)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:591)
	at com.intellij.psi.impl.source.PsiFileImpl.isValid(PsiFileImpl.java:163)
	at com.intellij.openapi.module.ModuleUtilCore.findModuleForPsiElement(ModuleUtilCore.java:92)
	at org.elixir_lang.credo.Annotator.generalCommandLine(Annotator.java:336)
	at org.elixir_lang.credo.Annotator.doAnnotate(Annotator.java:311)
	at org.elixir_lang.credo.Annotator.doAnnotate(Annotator.java:44)
```

**Comment by KronicDeth** [comment]
12.2.1 is no longer supported.  Please upgrade to a newer release.
