### ISSUE TITLE
Don't know how to get name of parameter at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:155)

### ISSUE THREAD

**Issue by william-intelligencebank** [KronicDeth/intellij-elixir#3081]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Community Edition (2022.3.2)
Operating System: Mac OS X (13.2.1)

# Event

### Element

```
sIntellijIdeaRulezzz map, map
```

From: `/Users/william/Workspace/ib_mcp/lib/ib_mcp/service/domain.ex:30`

#### Context

```
  @spec create_domain_entry(String.t, map) :: {:ok, map} | {:error, any}
  def create_domain_entry(dbname, data) do
    IbArango.Api.Document.insert_document(Ib.MCP.Domain.table(), data, dbname, [return_new: true])
  end

  @spec update(map, sIntellijIdeaRulezzz map, map) :: {:ok, map} | {:error, any}
  def update(data, key, _update_options, %{:dbname => dbname, "authorizer" => authorizer} = opts) do
    with verifier_columns <- Ib.MCP.Domain.columns(%{:dbname => dbname}),
         {:ok, data} <- Ib.Verifier.verify(data, verifier_columns),
         data <- data
                 |> Ib.Utility.reject_value(nil),
```

From: `/Users/william/Workspace/ib_mcp/lib/ib_mcp/service/domain.ex:25-35`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to get name of parameter
</summary>

```
java.lang.Throwable: Don't know how to get name of parameter
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:155)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHeadArguments(MultiResolve.kt:40)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHeadArguments(MultiResolve.kt:35)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHead(MultiResolve.kt:31)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnType(MultiResolve.kt:27)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:112)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:70)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:37)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:68)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:607)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:152)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults(MultiResolve.kt:186)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:178)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:42)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:23)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
```

</details>

**Comment by sh41** [comment]
Duplicate of #2537 — the same log call in `MultiResolve.executeOnParameter`, whose `when` has no branch for the shape a malformed `@spec` argument parses to. Here it is the half-typed `sIntellijIdeaRulezzz map` in the `@spec update(...)` head.

This is fixed. Since 24.0.0 the resolver no longer walks a `@spec` or `@callback` head's arguments at all, so this log call is never reached from a spec — checked against current main on a fixture matching this report. The `else` itself is unchanged and stays reachable from a `@type` head, whose arguments are still walked because that is where type variables are genuinely declared. That is what #2537 stays open for.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
