### ISSUE TITLE
java.lang.IllegalStateException: setSdk: sdk 'Elixir 1.12.0-otp-24' type 'Elixir SDK' is not registered in ProjectJdkTable at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableRootModelBridgeImpl.setSdk(ModifiableRootModelBridgeImpl.kt:602)

### ISSUE THREAD

**Issue by N-Porsh** [KronicDeth/intellij-elixir#3104]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.2)
Operating System: Mac OS X (13.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: setSdk: sdk 'Elixir 1.12.0-otp-24' type 'Elixir SDK' is not registered in ProjectJdkTable
</summary>

```
java.lang.IllegalStateException: setSdk: sdk 'Elixir 1.12.0-otp-24' type 'Elixir SDK' is not registered in ProjectJdkTable
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableRootModelBridgeImpl.setSdk(ModifiableRootModelBridgeImpl.kt:602)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor$ModifiableRootModelInvocationHandler.invoke(ModuleEditor.java:352)
	at jdk.proxy6/jdk.proxy6.$Proxy207.setSdk(Unknown Source)
	at com.intellij.openapi.roots.ui.configuration.ClasspathEditor.setSdk(ClasspathEditor.java:159)
	at com.intellij.openapi.roots.ui.configuration.ModuleJdkConfigurable$2.actionPerformed(ModuleJdkConfigurable.java:103)
	at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:619)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.setSelectedItem(JdkComboBox.java:279)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.setSelectedItem(JdkComboBox.java:241)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.lambda$setSelectedItem$4(JdkComboBox.java:271)
	at com.intellij.openapi.roots.ui.configuration.SdkListModelBuilder.lambda$executeAction$6(SdkListModelBuilder.java:283)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:521)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.setupSdk(ProjectSdksModel.java:507)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.addSdk(ProjectSdksModel.java:449)
	at com.intellij.openapi.roots.ui.configuration.SdkListModelBuilder.executeAction(SdkListModelBuilder.java:311)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBox.setSelectedItem(JdkComboBox.java:270)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaJBPopupComboPopup.lambda$createPopup$0(DarculaJBPopupComboPopup.java:282)
	at com.intellij.ui.popup.list.ComboBoxPopup$MyBasePopupState.lambda$onChosen$1(ComboBoxPopup.java:200)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:743)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:467)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1676)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1634)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1648)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:277)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:253)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:211)
	at com.intellij.openapi.roots.ui.configuration.ModulesConfigurator.showDialog(ModulesConfigurator.java:543)
	at com.intellij.openapi.roots.ui.configuration.IdeaProjectSettingsService.openModuleSettings(IdeaProjectSettingsService.java:54)
	at org.elixir_lang.notification.setup_sdk.Provider$Companion.showModuleSettings(Provider.kt:64)
	at org.elixir_lang.notification.setup_sdk.Provider$Companion.createModulePanel$lambda$3$lambda$2(Provider.kt:105)
```

</details>

**Comment by sh41** [comment]
Same defect as #2518 — the same platform method, reached the same way, differing only in IDE-version line numbers. Closing as a duplicate; the diagnosis and the upstream fix that resolves it are on #2518.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
