### ISSUE TITLE
Max opcode (178) exceeds expected max opcode (176).

### ISSUE THREAD

**Issue by PhillippOhlandt** [KronicDeth/intellij-elixir#3105]
**Describe the bug**
When I open a `.beam` file in the `_build` directory, then go to `BEAM Chunks` and `Code`, I get the following error:

```
java.lang.Throwable: Max opcode (178) exceeds expected max opcode (176).  Additional opcodes have been added to the end of https://github.com/erlang/otp/blob/master/lib/compiler/src/genop.tab.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at org.elixir_lang.beam.chunk.Code$Companion.from(Code.kt:193)
	at org.elixir_lang.beam.chunk.Code$Companion.from$default(Code.kt:171)
	at org.elixir_lang.beam.Beam.code(Beam.kt:83)
	at org.elixir_lang.beam.Cache$code$2.invoke(Cache.kt:11)
	at org.elixir_lang.beam.Cache$code$2.invoke(Cache.kt:11)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.elixir_lang.beam.Cache.getCode(Cache.kt:11)
	at org.elixir_lang.beam.assembly.Controls.computeDocumentText(Controls.kt:178)
	at org.elixir_lang.beam.assembly.Controls.<init>(Controls.kt:36)
	at org.elixir_lang.beam.chunk.code.Component.addChildren(Component.kt:31)
	at org.elixir_lang.beam.chunk.code.Component.ensureChildrenAdded(Component.kt:41)
	at org.elixir_lang.beam.chunk.code.Component.stateChanged(Component.kt:24)
	at com.intellij.ui.JBTabsPaneImpl.fireChanged(JBTabsPaneImpl.java:47)
	at com.intellij.ui.JBTabsPaneImpl$1.selectionChanged(JBTabsPaneImpl.java:35)
	at com.intellij.ui.tabs.impl.JBTabsImpl.fireSelectionChanged(JBTabsImpl.java:1587)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:1537)
	at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:1491)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.java:1472)
	at com.intellij.ui.tabs.impl.TabLabel$1.mousePressed(TabLabel.java:89)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6645)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**To Reproduce**
1. Open `.beam` file in the `_build` folder
2. Click on `BEAM Chunks`
3. Click on `Code`

**Expected behavior**
Showing the chunk content without throwing the above error

**Screenshots**
-

**Logs**
-

**Desktop:**
 - OS: macOS
 - Version: 12.6.3

**Erlang:**
- Installer: asdf
- Version: 25

**Elixir:**
- Installer: asdf
- Version: 1.14.2

**Plugin:**
- Version: 13.2.1

**Additional context**
[Elixir.NervesMetalDetector.Inventory.Data.ProductUpdateItems.beam.zip](https://github.com/KronicDeth/intellij-elixir/files/10925836/Elixir.NervesMetalDetector.Inventory.Data.ProductUpdateItems.beam.zip)

**Comment by sh41** [comment]
Fixed in 24.0.0.

The BEAM `Code` chunk's opcode table stopped at 176, the last OTP 24 opcode. OTP 25 added `bs_create_bin` (177) and `call_fun2` (178) — the number in your report — so opening BEAM Chunks → Code on a module compiled by OTP 25 or later logged an error, and any instruction actually using one of the new opcodes threw `IllegalArgumentException` out of `Operation.from`, aborting the tab.

Commit c9df46683 added opcodes 177–191, covering OTP 25 through 29, plus the `TypedRegister` operand tag OTP 25 introduced for JIT-annotated operands. Your attached `.beam` uses that tag too — OTP 24's own `beam_disasm` rejects the same file for it. The remaining max-opcode message is now a warning rather than an error, so a file newer than the table no longer surfaces as a crash.

Thanks for attaching the `.beam`; it made the reproduction exact.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
