### ISSUE TITLE
java.lang.IllegalStateException: Seems you haven't called addPlace() at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)

### ISSUE THREAD

**Issue by danvim** [KronicDeth/intellij-elixir#3114]
This event happened when I have the following code:

```ex
defmodule KV.Bucket do
  use Agent

  @doc """
"""
end
```

and pressed <kbd>Enter</kbd> to create a new line inside my heredocs.

# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.3)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Seems you haven't called addPlace()
</summary>

```
java.lang.IllegalStateException: Seems you haven't called addPlace()
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:149)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by danvim** [comment]
Duplicate of #2817
