### ISSUE TITLE
Worker exited due to exception: org/elixir_lang/jps/model/JpsElixirSdkType

### ISSUE THREAD

**Issue by wliirl** [KronicDeth/intellij-elixir#313]
# Version

3.0.1.20160520213720

# Exception

## Message

Worker exited due to exception: org/elixir_lang/jps/model/JpsElixirSdkType

## Stacktrace

```
java.lang.NoClassDefFoundError: org/elixir_lang/jps/model/JpsElixirSdkType
	at org.elixir_lang.sdk.ElixirSdkType.detectSdkVersion(ElixirSdkType.java:179)
	at org.elixir_lang.sdk.ElixirSdkType.getRelease(ElixirSdkType.java:224)
	at org.elixir_lang.sdk.ElixirSdkType.getRelease(ElixirSdkType.java:151)
	at org.elixir_lang.inspection.SetupSDKNotificationProvider.createNotificationPanel(SetupSDKNotificationProvider.java:65)
	at org.elixir_lang.inspection.SetupSDKNotificationProvider.createNotificationPanel(SetupSDKNotificationProvider.java:36)
	at com.intellij.ui.EditorNotificationsImpl$4.performInReadAction(EditorNotificationsImpl.java:146)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:159)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:223)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:45)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$6$2.run(ProgressIndicatorUtils.java:188)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
Maybe related to #295.  Which version of IntellIJ and Java SDK are you using @wliirl?

**Comment by wliirl** [comment]
Thank Kronic, it does not happening any more with upgrade,
