### ISSUE TITLE
java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 3 at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1433)

### ISSUE THREAD

**Issue by alexnogueirasilva** [KronicDeth/intellij-elixir#3137]
# System

Plugin Version: 14.0.0
Application: PhpStorm (2022.3.3)
Operating System: Linux (6.2.6-76060206-generic)

# Event

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 3
</summary>

```
java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 3
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1433)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:1883)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:440)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:360)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:300)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:275)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:129)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:117)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:370)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:346)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.nio.charset.MalformedInputException: Input length = 3
	at java.base/java.lang.String.throwMalformed(String.java:1238)
	at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1120)
	at java.base/java.lang.String.newStringUTF8NoRepl(String.java:726)
	at java.base/java.lang.String.newStringNoRepl1(String.java:754)
	at java.base/java.lang.String.newStringNoRepl(String.java:736)
	at java.base/java.lang.System$2.newStringNoRepl(System.java:2390)
	at java.base/java.nio.file.Files.readString(Files.java:3369)
	at java.base/java.nio.file.Files.readString(Files.java:3325)
	at com.intellij.util.io.PathKt.readText(path.kt:109)
	at com.intellij.grazie.jlanguage.hunspell.LuceneHunspellDictionary.<init>(LuceneHunspellDictionary.kt:14)
	at org.languagetool.rules.spelling.hunspell.Hunspell.getDictionary(Hunspell.java:50)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.init(HunspellRule.java:502)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.ensureInitialized(HunspellRule.java:476)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.match(HunspellRule.java:156)
	at com.intellij.grazie.spellcheck.GrazieSpellchecker$SpellerTool.check$lambda$1$lambda$0(GrazieSpellchecker.kt:48)
	at com.intellij.openapi.util.ClassLoaderUtil.computeWithClassLoader(ClassLoaderUtil.java:31)
	at com.intellij.grazie.spellcheck.GrazieSpellchecker$SpellerTool.check(GrazieSpellchecker.kt:47)
	at com.intellij.grazie.spellcheck.GrazieSpellchecker.isCorrect(GrazieSpellchecker.kt:102)
	at com.intellij.grazie.spellcheck.GrazieDictionary.contains(GrazieDictionary.kt:11)
	at com.intellij.spellchecker.grazie.dictionary.WordListAdapter.contains(WordListAdapter.kt:19)
	at com.intellij.spellchecker.grazie.dictionary.ExtendedWordListWithFrequency.contains(ExtendedWordListWithFrequency.kt:17)
	at ai.grazie.spell.GrazieSpeller.isMisspelled(GrazieSpeller.kt:105)
	at ai.grazie.spell.GrazieSplittingSpeller.isMisspelled(GrazieSplittingSpeller.kt:46)
	at com.intellij.spellchecker.grazie.async.GrazieAsyncSpeller.isMisspelled(GrazieAsyncSpeller.kt:38)
	at com.intellij.spellchecker.grazie.GrazieSpellCheckerEngine.isCorrect(GrazieSpellCheckerEngine.kt:101)
	at com.intellij.spellchecker.SpellCheckerManager.hasProblem(SpellCheckerManager.java:228)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consume(SpellCheckingInspection.java:219)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consume(SpellCheckingInspection.java:177)
	at org.elixir_lang.spell_checking.Splitter.split(Splitter.kt:12)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consumeToken(SpellCheckingInspection.java:204)
	at com.intellij.spellchecker.tokenizer.TokenConsumer.consumeToken(TokenConsumer.java:16)
	at org.elixir_lang.spell_checking.Tokenizer.tokenize(Tokenizer.kt:9)
	at org.elixir_lang.spell_checking.Tokenizer.tokenize(Tokenizer.kt:7)
```

</details>

**Comment by sh41** [comment]
This is a platform bug that named the plugin, not a plugin bug.

Nothing in `org.elixir_lang` reads a file here. The read that throws is `Files.readString`, which hardcodes UTF-8, reached from `com.intellij.grazie.jlanguage.hunspell.LuceneHunspellDictionary`'s constructor as it loads a Hunspell `.dic`/`.aff` pair for the bundled Grazie spellchecker. `Splitter.split` and `Tokenizer.tokenize` do no I/O at all — they hand word ranges to the platform's `TokenConsumer`, and that is what lazily triggered the dictionary load. Any language plugin's spellcheck tokenizer would sit in the same place in this trace.

JetBrains fixed it in [d96e5da376d7](https://github.com/JetBrains/intellij-community/commit/d96e5da376d783fcfdbb490eae25fe9b01f8f7b4) (2023-01-09), replacing both `readText()` calls with `inputStream()` so Hunspell honours the dictionary's own declared encoding instead of the platform decoding it as UTF-8 first. It first shipped in the 2023.1 line and was never backported to 2022.3, so PhpStorm 2022.3.3 keeps hitting it. Upgrading the IDE to 2023.1 or newer stops it.

The fix is in the IDE rather than the plugin, so there is no plugin version that fixes this and nothing here for the plugin to change.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
