### ISSUE TITLE
Cannot highlight types at org.elixir_lang.annotator.ModuleAttribute.error(ModuleAttribute.kt:130)

### ISSUE THREAD

**Issue by xuZhu-lab** [KronicDeth/intellij-elixir#3142]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Community Edition (2022.3.3)
Operating System: Windows 10 (10.0)

# Event

### Element

```
0x80
```

From: `~/elixir-mongodb-driver/lib/bson/types.ex:7`

#### Context

```
  Represents BSON binary type
  """

  @type t :: %__MODULE__{
          binary: binary,
          subtype: :generic | :function | :binary_old | :uuid_old | :uuid | :md5 | 0x80..0xFF
        }
  defstruct binary: nil, subtype: :generic

  defimpl String.Chars, for: BSON.Binary do
    def to_string(%BSON.Binary{binary: value, subtype: subtype}) when subtype in [:uuid, :uuid_old] do
```

From: `~/elixir-mongodb-driver/lib/bson/types.ex:2-12`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirHexadecimalWholeNumberImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Cannot highlight types
</summary>

```
java.lang.Throwable: Cannot highlight types
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.annotator.ModuleAttribute.error(ModuleAttribute.kt:130)
	at org.elixir_lang.annotator.ModuleAttribute.cannotHighlightTypes(ModuleAttribute.kt:126)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1137)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1148)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1007)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:962)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1082)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:970)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1082)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:970)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1082)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:970)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1082)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:970)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1082)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:970)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1082)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:970)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1082)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1148)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1007)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1148)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1007)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1148)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1007)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1148)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1007)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:947)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1053)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1148)
	at org.elixir_lang.annotator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.kt:1007)
	at org.elixir_lang.annotator.ModuleAttribute.highlightType(ModuleAttribute.kt:230)
	at org.elixir_lang.annotator.ModuleAttribute.access$highlightType(ModuleAttribute.kt:33)
	at org.elixir_lang.annotator.ModuleAttribute$annotate$1.visitDeclaration(ModuleAttribute.kt:90)
	at org.elixir_lang.annotator.ModuleAttribute$annotate$1.visitElement(ModuleAttribute.kt:63)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:39)
	at org.elixir_lang.annotator.ModuleAttribute.annotate(ModuleAttribute.kt:49)
```

</details>

**Comment by sh41** [comment]
This was the same defect as #1796 — the same `ElixirHexadecimalWholeNumberImpl` element, from a hexadecimal literal used as a range bound in a `@type`, `0x80..0xFF` here.

`ModuleAttribute`'s type-highlighting dispatch enumerated the numeric literal classes it knew about and reported anything else. It now matches the `WholeNumber` supertype, so hexadecimal, octal and unknown-base literals are all covered. Nothing was wrong with your file; the report was the plugin telling on itself.

Fixed in #3975.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
