### ISSUE TITLE
Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction()), Current thread: Thread[ApplicationImpl pooled thread 10,4,main] 323380776 (EventQueue.isDispatchThread()=false), SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 2133623858 at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)

### ISSUE THREAD

**Issue by ohenecoker** [KronicDeth/intellij-elixir#3163]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.1)
Operating System: Mac OS X (13.3)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
</summary>

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 10,4,main] 323380776 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 2133623858
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:219)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:213)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.workingDirectory(MixFormatExternalFormatProcessor.kt:76)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.access$workingDirectory(MixFormatExternalFormatProcessor.kt:69)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda$7$lambda$6(MixFormatExternalFormatProcessor.kt:44)
```

</details>

**Comment by sh41** [comment]
Fixed in v23.1.0.

The class this stack trace names, `MixFormatExternalFormatProcessor`, no longer exists: commit 8fa667517 (#3816) replaced it with `MixFormatFormattingService`, built on the platform's `AsyncDocumentFormattingService`. The replacement wraps the call that crashed here — `ProjectRootManager`'s `getContentRootForFile` — in `ReadAction.nonBlocking(...).executeSynchronously()`, so the project index is no longer touched from a pooled thread with no read action held.

v23.1.0 is the first release carrying that change; v23.0.7 does not have it.

#3321, #3322 and #3323 are the same crash and are closed as duplicates of this one.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
