### ISSUE TITLE
No decompiled source function with name (:inet_db.set_domain) at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:103)

### ISSUE THREAD

**Issue by GhanashyamSrinivas** [KronicDeth/intellij-elixir#3170]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Community Edition (2022.2.5)
Operating System: Mac OS X (13.2.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: No decompiled source function with name (:inet_db.set_domain)
</summary>

```
java.lang.Throwable: No decompiled source function with name (:inet_db.set_domain)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:103)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:409)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda-6$lambda-5(BeamFileImpl.kt:389)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:222)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:388)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:147)
	at org.elixir_lang.psi.scope.atom.Variants.projectLookupElementStream(Variants.java:49)
	at org.elixir_lang.psi.scope.atom.Variants.lookupElementList(Variants.java:24)
	at org.elixir_lang.reference.Atom.getVariants(Atom.java:25)
```

</details>

**Comment by KronicDeth** [comment]
Please zip the `inet_db.beam` and attach the zip to this issue.

**Comment by KronicDeth** [comment]
I can't find a local version of Erlang with this issue, so I will close for now as there has been no upload of the beam for over a month.
