### ISSUE TITLE
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/halim/.cache/JetBrains/WebStorm2022.3/index/fileincludes/.perFileVersion/indexed_versions/indexed_versions at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)

### ISSUE THREAD

**Issue by halimb** [KronicDeth/intellij-elixir#3182]
# System

Plugin Version: 14.0.0
Application: WebStorm (2022.3.1)
Operating System: Linux (6.0.12-76060006-generic)

# Event

### Stacktrace

<details>

<summary>
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/halim/.cache/JetBrains/WebStorm2022.3/index/fileincludes/.perFileVersion/indexed_versions/indexed_versions
</summary>

```
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/halim/.cache/JetBrains/WebStorm2022.3/index/fileincludes/.perFileVersion/indexed_versions/indexed_versions
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:272)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:263)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:587)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:549)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:169)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator$MyEnumerator.enumerate(PersistentSubIndexerVersionEnumerator.java:22)
	at com.intellij.util.io.CachingEnumerator.enumerate(CachingEnumerator.java:75)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator.enumerate(PersistentSubIndexerVersionEnumerator.java:60)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getFileIndexerId(PersistentSubIndexerRetriever.java:103)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getSubIndexerState(PersistentSubIndexerRetriever.java:93)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getIndexingStateForFile(VfsAwareMapReduceIndex.java:274)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.getIndexingStateForFile(CompositeInvertedIndexBase.java:221)
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndexingState(FileBasedIndexImpl.java:1961)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$25(FileBasedIndexImpl.java:1443)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:670)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1421)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1394)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1342)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1760)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:808)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:305)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:71)
	at com.intellij.psi.stubs.StubIndexEx.getAllKeys(StubIndexEx.java:293)
	at org.elixir_lang.navigation.ChooseByNameContributor.getNames(ChooseByNameContributor.kt:282)
```

</details>

**Comment by KronicDeth** [comment]
Please reopen if this is still an issue in IntelliJ Elixir 15.0.1 and WebStorm 2023.1
