### ISSUE TITLE
java.io.FileNotFoundException: /opt/homebrew/Cellar/erlang/25.3/bin/erl does not exist at org.elixir_lang.jps.SdkType.exeFileToExePath(SdkType.java:21)

### ISSUE THREAD

**Issue by James-Ansley** [KronicDeth/intellij-elixir#3205]
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Ultimate Edition (2023.1)
Operating System: Mac OS X (13.3.1)

# Event

### Stacktrace

<details>

<summary>
java.io.FileNotFoundException: /opt/homebrew/Cellar/erlang/25.3/bin/erl does not exist
</summary>

```
java.io.FileNotFoundException: /opt/homebrew/Cellar/erlang/25.3/bin/erl does not exist
	at org.elixir_lang.jps.SdkType.exeFileToExePath(SdkType.java:21)
	at org.elixir_lang.jps.sdk_type.Erlang.homePathToErlExePath(Erlang.java:44)
	at org.elixir_lang.Erl.exePath(Erl.kt:31)
	at org.elixir_lang.Erl.setErl(Erl.kt:49)
	at org.elixir_lang.Erl.commandLine(Erl.kt:17)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:20)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:120)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.setupProject(AbstractNewProjectWizardMultiStepBase.kt:74)
	at com.intellij.ide.wizard.NewProjectWizardLanguageStep.setupProject(NewProjectWizardLanguageStep.kt:89)
	at com.intellij.ide.wizard.NewProjectWizardChainStep.setupProject(NewProjectWizardChainStep.kt:44)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$commitModule$1.invoke(AbstractNewProjectWizardBuilder.kt:44)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$commitModule$1.invoke(AbstractNewProjectWizardBuilder.kt:43)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.detectCreatedModule(AbstractNewProjectWizardBuilder.kt:80)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.detectCreatedModule(AbstractNewProjectWizardBuilder.kt:68)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.access$detectCreatedModule(AbstractNewProjectWizardBuilder.kt:65)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder.commitModule(AbstractNewProjectWizardBuilder.kt:43)
```

</details>

**Comment by James-Ansley** [comment]
The Erlang version that Homebrew installed for Elixir 1.14.4 is 25.3.1 – however, the plugin seems to be trying to use 25.3.
Related to #3141 where only 25.3 was listed as the Erlang location for homebrew – is there support for the auto-config to use the latest patch releases?

**Comment by KronicDeth** [comment]
An SDK will never be auto-set for a project.  The SDK home directory suggester will suggest the latest version it can find if you click to add a new SDK. It does not automatically create new SDK when you install new versions.

**Comment by KronicDeth** [comment]
Duplicate of #3173
