### ISSUE TITLE
No decompiled source function with name/arity (KaribaMinerals.Reviews.list_reviews/0) at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:100)

### ISSUE THREAD

**Issue by MiyamboJoseph** [KronicDeth/intellij-elixir#3207]
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Community Edition (2023.1.1)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: No decompiled source function with name/arity (KaribaMinerals.Reviews.list_reviews/0)
</summary>

```
java.lang.Throwable: No decompiled source function with name/arity (KaribaMinerals.Reviews.list_reviews/0)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:100)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:409)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda$6$lambda$5(BeamFileImpl.kt:389)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:388)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.kt:70)
	at com.intellij.ide.util.EditSourceUtil.canNavigate(EditSourceUtil.java:65)
	at com.intellij.codeInsight.TargetElementUtil.isNavigatableSource(TargetElementUtil.java:232)
	at com.intellij.codeInsight.TargetElementUtil.getTargetCandidates(TargetElementUtil.java:215)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:178)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:136)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:42)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:24)
	at com.intellij.model.psi.impl.TargetSymbolsDataRule.getData(TargetSymbolsDataRule.kt:14)
	at com.intellij.ide.impl.DataManagerImpl.getRulesData(DataManagerImpl.java:210)
```

</details>

**Comment by KronicDeth** [comment]
Please zip the `Elixir.KaribaMinerals.Reviews.beam` and attach the zip to a comment.
