### ISSUE TITLE
java.lang.IllegalStateException: @NotNull method org/elixir_lang/code_insight/lookup/element_renderer/Variable.color must not return null at org.elixir_lang.code_insight.lookup.element_renderer.Variable.$$$reportNull$$$0(Variable.java)

### ISSUE THREAD

**Issue by krhil** [KronicDeth/intellij-elixir#3233]
# System

Plugin Version: 12.2.1
Application: WebStorm (2021.3.3)
Operating System: Mac OS X (13.3.1)

# Event

### Stacktrace

```
java.lang.IllegalStateException: @NotNull method org/elixir_lang/code_insight/lookup/element_renderer/Variable.color must not return null
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.$$$reportNull$$$0(Variable.java)
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.color(Variable.java:106)
	at org.elixir_lang.code_insight.lookup.element_renderer.Variable.renderElement(Variable.java:52)
```

**Comment by KronicDeth** [comment]
v12.2.1 was released on April 17, 2022 and superseded by v13.0.0 on May 5, 2022.  v12.2.1 is no longer supported.  Please upgrade.
