### ISSUE TITLE
No decompiled source function with name (:hex_http_httpc.request) at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:74)

### ISSUE THREAD

**Issue by krhil** [KronicDeth/intellij-elixir#3237]
# System

Plugin Version: 12.2.1
Application: WebStorm (2021.3.3)
Operating System: Mac OS X (13.4)

# Event

### Stacktrace

```
java.lang.Throwable: No decompiled source function with name (:hex_http_httpc.request)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:74)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:417)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda-6$lambda-5(BeamFileImpl.kt:398)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:397)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:118)
	at org.elixir_lang.psi.scope.atom.Variants.projectLookupElementStream(Variants.java:49)
	at org.elixir_lang.psi.scope.atom.Variants.lookupElementList(Variants.java:24)
	at org.elixir_lang.reference.Atom.getVariants(Atom.java:25)
```

**Comment by KronicDeth** [comment]
Please zip the `hex_http_httpc.beam` file and attach the zip in a comment to this issue, so that it can be used to reproduce the decompiler bug.
