### ISSUE TITLE
java.io.IOException at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:173)

### ISSUE THREAD

**Issue by josephverron** [KronicDeth/intellij-elixir#3238]
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Ultimate Edition (2023.1.2)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.io.IOException
</summary>

```
java.io.IOException
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:173)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.setupProject(AbstractNewProjectWizardMultiStepBase.kt:74)
	at com.intellij.ide.wizard.NewProjectWizardLanguageStep.setupProject(NewProjectWizardLanguageStep.kt:89)
	at com.intellij.ide.wizard.NewProjectWizardChainStep.setupProject(NewProjectWizardChainStep.kt:44)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$commitModule$1.invoke(AbstractNewProjectWizardBuilder.kt:44)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$commitModule$1.invoke(AbstractNewProjectWizardBuilder.kt:43)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.detectCreatedModule(AbstractNewProjectWizardBuilder.kt:80)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.detectCreatedModule(AbstractNewProjectWizardBuilder.kt:68)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.access$detectCreatedModule(AbstractNewProjectWizardBuilder.kt:65)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder.commitModule(AbstractNewProjectWizardBuilder.kt:43)
```

</details>

**Comment by KronicDeth** [comment]
The error message shown in the notification should be added to the `IOException` too.
