### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "value" is null at com.intellij.util.io.EnumeratorStringDescriptor.getHashCode(EnumeratorStringDescriptor.java:25)

### ISSUE THREAD

**Issue by will-zdu** [KronicDeth/intellij-elixir#3255]
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Ultimate Edition (2023.1.2)
Operating System: Linux (6.3.0-060300-generic)

# Event

### Stacktrace

<details>

<summary>
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "value" is null
</summary>

```
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "value" is null
	at com.intellij.util.io.EnumeratorStringDescriptor.getHashCode(EnumeratorStringDescriptor.java:25)
	at com.intellij.util.io.EnumeratorStringDescriptor$EnumeratorStringDescriptorImpl.getHashCode(EnumeratorStringDescriptor.java:16)
	at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:542)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$doEnumerate$0(PersistentEnumeratorBase.java:260)
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:621)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:259)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:250)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:656)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:613)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:197)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator.lambda$valueOf$0(PersistentSubIndexerVersionEnumerator.java:88)
	at com.intellij.util.io.PersistentEnumeratorBase$1.process(PersistentEnumeratorBase.java:324)
	at com.intellij.util.io.PersistentBTreeEnumerator$3.process(PersistentBTreeEnumerator.java:383)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.lambda$processMappings$1(IntToIntBtree.java:629)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.processMappings(IntToIntBtree.java:632)
	at com.intellij.util.io.IntToIntBtree.processLeafPages(IntToIntBtree.java:1045)
	at com.intellij.util.io.IntToIntBtree.processMappings(IntToIntBtree.java:1040)
	at com.intellij.util.io.PersistentBTreeEnumerator.traverseAllRecords(PersistentBTreeEnumerator.java:372)
	at com.intellij.util.io.PersistentEnumeratorBase.processAllDataObject(PersistentEnumeratorBase.java:320)
	at com.intellij.util.io.PersistentBTreeEnumerator.processAllDataObject(PersistentBTreeEnumerator.java:363)
	at com.intellij.util.io.PersistentMapImpl.processExistingKeys(PersistentMapImpl.java:590)
	at com.intellij.util.io.PersistentHashMap.processKeysWithExistingMapping(PersistentHashMap.java:192)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator.valueOf(PersistentSubIndexerVersionEnumerator.java:85)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getVersionByIndexerId(PersistentSubIndexerRetriever.java:117)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getStoredSubIndexerVersion(VfsAwareMapReduceIndex.java:235)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.determinePreviousFileElementType(PerFileElementTypeStubModificationTracker.java:197)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.fastCheck(PerFileElementTypeStubModificationTracker.java:101)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.lambda$endUpdatesBatch$2(PerFileElementTypeStubModificationTracker.java:76)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:59)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.endUpdatesBatch(PerFileElementTypeStubModificationTracker.java:75)
	at com.intellij.util.indexing.events.ChangedFilesCollector$4.endBatch(ChangedFilesCollector.java:246)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$endBatch$2(ChangedFilesCollector.java:283)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:258)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.endBatch(ChangedFilesCollector.java:282)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:109)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:265)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:224)
	at com.intellij.util.indexing.events.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:190)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:836)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:365)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:166)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.reference.resolver.atom.resolvable.Exact.resolve(Exact.kt:20)
	at org.elixir_lang.reference.resolver.Atom.resolve(Atom.java:20)
	at org.elixir_lang.reference.resolver.Atom.resolve(Atom.java:11)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.Atom.multiResolve(Atom.java:43)
	at org.elixir_lang.reference.Atom.resolve(Atom.java:49)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:176)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:164)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:209)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:253)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:232)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:297)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:175)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:136)
```

</details>

**Comment by KronicDeth** [comment]
Line 20 is where the call to `StubIndex.processElements` is

https://github.com/KronicDeth/intellij-elixir/blob/ea0233a9247fdcb2480763cd02d1eebc155c45db/src/org/elixir_lang/reference/resolver/atom/resolvable/Exact.kt#L20-L26

so, this is likely a problem where something unexpected is being persisted to the `StubIndex`. I would need your repository to reproduce the issue to figure out what is being put in that is `null` that shouldn't be.   Could you share your repository with me?

**Comment by sh41** [comment]
The trace passes through `Exact.resolve`, but nothing on the plugin's side of that call is on the failing path.

`StubIndex.processElements` calls `FileBasedIndex.ensureUpToDate` before the index key or the search scope the plugin supplied is used for anything. The `NullPointerException` fires inside that bulk maintenance pass, in `PersistentSubIndexerVersionEnumerator`, hashing a null key out of the platform's own persisted sub-indexer-version map. A stub index query from anywhere in the plugin would have reached the same corrupted on-disk state.

That is the same failure as #3182 and #2996: `PersistentEnumeratorBase` corruption in the platform's `perFileVersion` storage, which this plugin reaches through the platform API rather than writing itself. As on #2996, it needs reporting to JetBrains.

Closing as a duplicate of #2996, which carries that answer.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
