### ISSUE TITLE
@NotNull parameter 'element' of org/elixir_lang/psi/scope/Variable.execute must not be null

### ISSUE THREAD

**Issue by swieckib** [KronicDeth/intellij-elixir#326]
# Version

4.0.0

# Exception

## Message

Argument for @NotNull parameter 'element' of org/elixir_lang/psi/scope/Variable.execute must not be null

## Stacktrace

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'element' of org/elixir_lang/psi/scope/Variable.execute must not be null
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:460)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:341)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:102)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:486)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:475)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:109)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:460)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:341)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:102)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:417)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:453)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:90)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsInPreviousSibling(ElixirPsiImplUtil.java:1461)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1376)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:57)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1028)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:90)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:74)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:775)
	at org.elixir_lang.reference.Callable.resolve(Callable.java:799)
	at org.elixir_lang.annonator.Callable$1.visitCall(Callable.java:60)
	at org.elixir_lang.annonator.Callable$1.visitElement(Callable.java:48)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:38)
	at org.elixir_lang.annonator.Callable.annotate(Callable.java:39)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:135)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:99)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:285)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

```

**Comment by KronicDeth** [comment]
Any idea what code set this off?

**Comment by KronicDeth** [comment]
I reproduced at least one case of this where I deleted the right operand for a `|>` that had a following `|>`.

**Comment by swieckib** [comment]
So I guess it happened to me a couple of time when I copied some code from other module, say, I would recall it was something like this:

``
copied_and_undefinied_variable |> some_action
``

and the plugging crashed when I double clicked on ``some_action``

Hope it helps.
