### ISSUE TITLE
com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: stax at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.newModule(ModifiableModuleModelBridgeImpl.kt:83)

### ISSUE THREAD

**Issue by vivd-hbar** [KronicDeth/intellij-elixir#3265]
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Community Edition (2023.1.2)
Operating System: Linux (6.2.0-1003-lowlatency)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: stax
</summary>

```
com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: stax
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.newModule(ModifiableModuleModelBridgeImpl.kt:83)
	at org.elixir_lang.mix.Project.createModuleForOtpApp(Project.kt:103)
	at org.elixir_lang.mix.Project.createModulesForOtpApps(Project.kt:77)
	at org.elixir_lang.mix.project._import.Builder.commit(Builder.kt:107)
	at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:50)
	at com.intellij.projectImport.ProjectOpenProcessorBase$importToProject$2.invokeSuspend(ProjectOpenProcessorBase.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:35)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
```

</details>

**Comment by KronicDeth** [comment]
Is this an umbrella project and is the root directory and an app directory called stax?

**Comment by sh41** [comment]
Fixed, and the question you were asked here — whether your umbrella root directory shares a name with
an app inside it — is what this was. Each OTP app's `.iml` was named after the app, so a root and an
`apps/` child both declaring `app: :stax` resolved to one path and the second `newModule` call threw.

`fc3c45133` disambiguates the module names first — the root app keeps its plain name, the others get a
suffix from their path relative to it. First released in v23.0.5.

Closing as a duplicate of #2003, which describes the same collision and is where the fix is recorded.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
