### ISSUE TITLE
 Rubymine version 8 and java 1.8.0_40 does not have com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart

### ISSUE THREAD

**Issue by huyh** [KronicDeth/intellij-elixir#328]
# Version

4.0.0

# Exception

## Message

Error while indexing /Users/huy/dev/home/email_surveys/service/lib/email_surveys/endpoint.ex
To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z

## Stacktrace

```
java.lang.NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
	at org.elixir_lang.parser.ElixirParser.unmatchedCaptureNonNumericOperation(ElixirParser.java:6219)
	at org.elixir_lang.parser.ElixirParser.unmatchedExpression(ElixirParser.java:6100)
	at org.elixir_lang.parser.ElixirParser.expression(ElixirParser.java:2162)
	at org.elixir_lang.parser.ElixirParser.expressionList(ElixirParser.java:2174)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1_0(ElixirParser.java:2047)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1(ElixirParser.java:2038)
	at org.elixir_lang.parser.ElixirParser.elixirFile(ElixirParser.java:2023)
	at org.elixir_lang.parser.ElixirParser.parse_root_(ElixirParser.java:649)
	at org.elixir_lang.parser.ElixirParser.parseLight(ElixirParser.java:643)
	at org.elixir_lang.parser.ElixirParser.parse(ElixirParser.java:19)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:85)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:218)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getLastChild(SharedImplUtil.java:57)
	at com.intellij.psi.impl.source.PsiFileImpl.getLastChild(PsiFileImpl.java:789)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:72)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
	at com.intellij.psi.stubs.StubUpdatingIndex$3$1.run(StubUpdatingIndex.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:938)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:124)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:118)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1744)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1671)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1616)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:109)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:225)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:239)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

```

**Comment by KronicDeth** [comment]
I had anticipated that the new build process would have eliminated these NoSuchMethod errors, but I guess not.  I'll need more information to reproduce.

1. What version of IntelliJ are you using?
2. What version of JDK is that install of IntelliJ using?

**Comment by huyh** [comment]
I use Rubymine version 8 and java 1.8.0_40

**Comment by KronicDeth** [comment]
OK, I'll test an install in Rubymine 8.

I'm not sure you're aware, but the plugin  has more features available if you use it in IntelliJ: you can only make an Elixir project in IntelliJ, non-Ruby projects aren't supported using the extension points available to Rubymine.

The Community Edition of IntelliJ is a free download if you don't have the JetBrains Toolbox subscription that  allows you to download any of their IDEs.

**Comment by KronicDeth** [comment]
I installed [Rubymine 8.0.4 with the custom JDK](https://download.jetbrains.com/ruby/RubyMine-8.0.4-custom-jdk-bundled.dmg) and then opened my Phoenix project and its `endpoint.ex` and I wasn't able to trigger the problem.

If you move the `endpoint.ex` to a project by itself, can you still trigger the bug?  If that's the case, you could gist the `endpoint.ex` alone and I could test with that.  Until then, I can't reproduce and therefore fix this problem, sorry.

**Comment by KronicDeth** [comment]
Related to #391
