### ISSUE TITLE
Stub ids not found for key in index = elixir.all.name, file = file:///Users/hassan/projects/djo/oara/lib/oara/users/user.ex, file type = org.elixir_lang.ElixirFileType@50cacaf3, indexed file type = org.elixir_lang.ElixirFileType@50cacaf3 at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:65)

### ISSUE THREAD

**Issue by hassan** [KronicDeth/intellij-elixir#3295]
# System

Plugin Version: 15.0.1
Application: RubyMine (2023.1.2)
Operating System: Mac OS X (13.4.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name, file = file:///Users/hassan/projects/djo/oara/lib/oara/users/user.ex, file type = org.elixir_lang.ElixirFileType@50cacaf3, indexed file type = org.elixir_lang.ElixirFileType@50cacaf3
</summary>

```
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name, file = file:///Users/hassan/projects/djo/oara/lib/oara/users/user.ex, file type = org.elixir_lang.ElixirFileType@50cacaf3, indexed file type = org.elixir_lang.ElixirFileType@50cacaf3
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:65)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$6(StubIndexEx.java:203)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:196)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:91)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.accept(ElixirUnmatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:348)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:287)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:278)
```

</details>

**Comment by sh41** [comment]
Fixed in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0) (2026-05-15), and a duplicate of #2427.

The frame above the platform's throw here, `org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule`, was the resolver's global fallback into the `elixir.all.name` stub index. It was removed outright — not renamed — by [`60a8386`](https://github.com/KronicDeth/intellij-elixir/commit/60a8386986b131504a30fc137c7b994462496728). `Callable`'s resolve chain no longer queries that index at all, and `Issue463Test.testUnresolvedAliasQualifier` fails if the fallback comes back.

One thing this report added over #2427 and #2567: both of those hit the fallback while resolving against a decompiled `.beam` stub, whereas yours is a plain `.ex` source file — file type and indexed file type both `ElixirFileType`. Same call site, but it showed the race was reachable from ordinary source resolution too, not only from decompiler-produced stubs.

Other `elixir.all.name` reports stay open: the platform throw is still reachable from call sites that do query that index, and each needs checking on its own.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
