### ISSUE TITLE
After upgrading to Elixir 1.15.2, Erlang/OTP 26, Can not jump to String module functions by control + click

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#3309]
# System

Plugin Version: 15.0.2-pre+20230609212153
Application: IntelliJ IDEA Ultimate Edition (2023.1.3)
Operating System: Mac OS X (12.6.7)
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
Elixir 1.15.2 (compiled with Erlang/OTP 26)

# Event
After upgrading to Elixir 1.15.2, Erlang/OTP 26, Can not jump to String module functions by control + click.(Exception occurred)
In my case, I can not jump `String.valid?` and other function. (Can jump to `String` module)

```elixir
defmodule A do
  defp join(list) do
    Enum.map_join(list, " ", &if(String.valid?(&1), do: &1, else: "..."))
  end
end

```
I'm not sure this is related, but It seems failed to parse module doc of String module.

<img width="635" alt="スクリーンショット 2023-07-07 10 47 15" src="https://github.com/KronicDeth/intellij-elixir/assets/1321120/83c4505d-b6ff-4971-b65d-dd3946dc4ab2">

### Stacktrace

<details>

<summary>
java.lang.NullPointerException: mirror must not be null
</summary>

```
java.lang.NullPointerException: mirror must not be null
	at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.kt:70)
	at com.intellij.codeInsight.navigation.impl.CommonKt.gtdTargetNavigatable(common.kt:38)
	at com.intellij.codeInsight.navigation.impl.TargetGTDActionData.extractSingleTargetResult(gtd.kt:102)
	at com.intellij.codeInsight.navigation.impl.TargetGTDActionData.result(gtd.kt:69)
	at com.intellij.codeInsight.navigation.impl.GtduKt.toGTDUActionData(gtdu.kt:70)
	at com.intellij.codeInsight.navigation.impl.GtduKt.fromTargetData(gtdu.kt:64)
	at com.intellij.codeInsight.navigation.impl.GtduKt.gotoDeclarationOrUsagesInner(gtdu.kt:59)
	at com.intellij.codeInsight.navigation.impl.GtduKt.access$gotoDeclarationOrUsagesInner(gtdu.kt:1)
	at com.intellij.codeInsight.navigation.impl.GtduKt$gotoDeclarationOrUsages$1.invoke(gtdu.kt:20)
	at com.intellij.codeInsight.navigation.impl.GtduKt$gotoDeclarationOrUsages$1.invoke(gtdu.kt:20)
```

</details>

**Comment by odk211** [comment]
Attach Elixir.String.beam
[Elixir.String.beam.zip](https://github.com/KronicDeth/intellij-elixir/files/11973988/Elixir.String.beam.zip)

**Comment by sh41** [comment]
Fixed in 24.0.0, by the lexer work in #3850.

Your hunch about the module doc was the cause. `Elixir.String`'s `@moduledoc` documents `\u{NNNNNN}`,
and the lexer treated that backslash as an escape sequence inside a non-interpolating `~S` heredoc
rather than as literal text. It emitted `BAD_CHARACTER` for each character of the code point, which
corrupted the parse of everything after the doc — so no function declared below it was matched to its
decompiled source, and Ctrl+Click fell through to a partial name match in `Kernel.beam`.

Decompiling the `Elixir.String.beam` you attached, on current `main`: no parse errors, and all 144
definitions match their source, `valid?/1` and `valid?/2` among them. On the commit before the fix,
all 144 were unmatched. Thanks for attaching the file — it is what made this checkable years later.

24.0.1 is the current release and carries it.

---

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
