### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/james.isenhart/src/signals_processor/_build/dev/lib/signals_processor/ebin/Elixir.SignalsProcessor.Transform.TriggeredAction.beam (invalid) is invalid, invalidated at: no info at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)

### ISSUE THREAD

**Issue by JamesIsenloft** [KronicDeth/intellij-elixir#3316]
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Ultimate Edition (2023.1.2)
Operating System: Mac OS X (13.3.1)

# Event

### Stacktrace

<details>

<summary>
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/james.isenhart/src/signals_processor/_build/dev/lib/signals_processor/ebin/Elixir.SignalsProcessor.Transform.TriggeredAction.beam (invalid) is invalid
</summary>

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/james.isenhart/src/signals_processor/_build/dev/lib/signals_processor/ebin/Elixir.SignalsProcessor.Transform.TriggeredAction.beam (invalid) is invalid
invalidated at: no info
	at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)
	at org.jetbrains.plugins.scala.compiler.highlighting.TriggerCompilerHighlightingOnPsiChangeListener$PsiChangeListener.childRemoved(TriggerCompilerHighlightingOnPsiChangeListener.scala:32)
	at com.intellij.psi.impl.PsiManagerImpl.notifyPsiTreeChangeListener(PsiManagerImpl.java:396)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:351)
	at com.intellij.psi.impl.PsiManagerImpl.childRemoved(PsiManagerImpl.java:273)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$filesDeleted$2(PsiVFSListener.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:958)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.filesDeleted(PsiVFSListener.java:225)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$fireForGrouped$9(PsiVFSListener.java:759)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
```

</details>

**Comment by sh41** [comment]
Thanks for the report, and sorry nobody replied to it.

The frame below `BeamFileImpl.getContainingFile` in your trace is the Scala plugin's `TriggerCompilerHighlightingOnPsiChangeListener`, reached through `PsiManagerImpl.childRemoved` and `PsiVFSListener.filesDeleted` — the IDE delivering a file-deleted event for `Elixir.SignalsProcessor.Transform.TriggeredAction.beam` as a build rewrote it under `_build/dev`. That listener calls `getContainingFile()` without first checking `isValid()`.

The throw itself is deliberate: `BeamFileImpl` is modelled on the platform's `ClsFileImpl` for decompiled files, which raises the same exception on an invalid file, and that check has been in place since the class was added in `358cbe158` (December 2016). The missing validity check is on the calling side, not ours.

Closing as a duplicate of #2460, which carries the full explanation.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
