### ISSUE TITLE
com.intellij.diagnostic.PluginException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/aminjaipuri/Library/Caches/JetBrains/IntelliJIdea2023.1/caches/names.dat [Plugin: org.elixir_lang] at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1.invokeSuspend(EditorNotificationsImpl.kt:229)

### ISSUE THREAD

**Issue by amin-jaipuri** [KronicDeth/intellij-elixir#3317]
# System

Plugin Version: 15.1.0
Application: IntelliJ IDEA Ultimate Edition (2023.1.2)
Operating System: Mac OS X (13.5)

# Event

### Stacktrace

<details>

<summary>
com.intellij.diagnostic.PluginException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/aminjaipuri/Library/Caches/JetBrains/IntelliJIdea2023.1/caches/names.dat [Plugin: org.elixir_lang]
</summary>

```
com.intellij.diagnostic.PluginException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/aminjaipuri/Library/Caches/JetBrains/IntelliJIdea2023.1/caches/names.dat [Plugin: org.elixir_lang]
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1.invokeSuspend(EditorNotificationsImpl.kt:229)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/aminjaipuri/Library/Caches/JetBrains/IntelliJIdea2023.1/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSConnection.handleError(PersistentFSConnection.java:347)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.handleError(FSRecords.java:957)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameByNameId(FSRecords.java:696)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.getVFileName(FileNameCache.java:144)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.getVFileName(FileNameCache.java:153)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getNameSequence(VirtualFileSystemEntry.java:147)
	at com.intellij.spi.SPIFileType.isMyFileType(SPIFileType.java:28)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getByFile(FileTypeManagerImpl.java:790)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:750)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:692)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:356)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getFileType(VirtualFileSystemEntry.java:594)
	at org.elixir_lang.notification.setup_sdk.Provider.createNotificationPanel(Provider.kt:38)
	at org.elixir_lang.notification.setup_sdk.Provider.collectNotificationData$lambda$0(Provider.kt:32)
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1$2.invokeSuspend(EditorNotificationsImpl.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
```

</details>

**Comment by sh41** [comment]
This is a platform bug that named the plugin, not a plugin bug.

The `Caused by:` is a `PersistentEnumeratorBase$CorruptedException` on `names.dat`, thrown from `FSRecords.getNameByNameId` by way of `FileNameCache`. That file is the IDE's own virtual-file-system name storage — shared by every project and every language, owned and rebuilt by the platform. It is not a plugin index, and nothing in `org.elixir_lang` reads or writes it. Every frame from `PersistentFSConnection.handleError` down to `VirtualFile.getFileType` is platform code.

The only plugin frame is `Provider.createNotificationPanel`, and all it does there is call `VirtualFile.getFileType()` to check whether the file is Elixir before doing anything else. `EditorNotificationsImpl` runs each registered `EditorNotificationProvider` in turn and wraps anything one of them throws in a `PluginException` tagged with that provider's plugin id, whatever the exception actually was or wherever it came from. Elixir's provider was simply the one in flight when the damaged storage was touched; any other notification provider reading a `VirtualFile` at that moment would appear here instead, under its own name.

The corruption itself is on-disk damage to that cache file, usually left behind by a crash, a force-kill or a disk fault. The platform's own recovery for it is **File > Invalidate Caches / Restart**, which rebuilds the VFS. There is nothing here for the plugin to change.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
