### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match., Please report the problem to JetBrains with the files attached,  file=Elixir File, file.class=class org.elixir_lang.psi.ElixirFile, file.lang=Language: Elixir, modStamp=1,  tree consistent,  stub debugInfo=created in calcStubTree; with backReference,  viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file:///home/flavius/workblk/blockscout/apps/block_scout_web/lib/block_scout_web/views/transaction_log_view.ex, vFileId=265363, content=VirtualFileContent{size=195}, eventSystemEnabled=true},  viewProvider stamp: 0; file stamp: 0; file modCount: 1682424364000; file length: 195,  doc saved: true; doc stamp: 0; doc size: 195; committed: true, indexing info: indexing timestamp = 1682424364000, binary = false, byte size = 285, char size = 285, latestIndexedStub=null at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.doCreateCompleteException(StubTreeLoader.java:211)

### ISSUE THREAD

**Issue by artheraone** [KronicDeth/intellij-elixir#3318]
# System

Plugin Version: 15.1.0
Application: GoLand (2023.1.4)
Operating System: Linux (6.1.39-x64v3-xanmod1)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
</summary>

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=Elixir File, file.class=class org.elixir_lang.psi.ElixirFile, file.lang=Language: Elixir, modStamp=1
 tree consistent
 stub debugInfo=created in calcStubTree; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file:///home/flavius/workblk/blockscout/apps/block_scout_web/lib/block_scout_web/views/transaction_log_view.ex, vFileId=265363, content=VirtualFileContent{size=195}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1682424364000; file length: 195
 doc saved: true; doc stamp: 0; doc size: 195; committed: true
indexing info: indexing timestamp = 1682424364000, binary = false, byte size = 285, char size = 285
latestIndexedStub=null
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.doCreateCompleteException(StubTreeLoader.java:211)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.access$300(StubTreeLoader.java:151)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:72)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:151)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:93)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:72)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:146)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:210)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:196)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:91)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:876)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.accept(ElixirUnmatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:348)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:287)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:278)
```

</details>

**Comment by sh41** [comment]
Fixed in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0) (2026-05-15), and a duplicate of #2427.

The plugin frame in your trace, `org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule`, was the resolver's global fallback into the `elixir.all.name` stub index: whenever in-scope resolution found nothing, it searched every module in the project. It was removed outright — not renamed — by [`60a8386`](https://github.com/KronicDeth/intellij-elixir/commit/60a8386986b131504a30fc137c7b994462496728), and `Callable`'s resolve chain no longer queries that index at all. `Issue463Test.testUnresolvedAliasQualifier` fails if the fallback comes back.

Your report and #2427 trip different platform consistency checks around that index — yours the stub-tree/PSI type mismatch, #2427's a missing stub-id list — but the plugin-side trigger is the same call, and it is gone.

Other `elixir.all.name` reports stay open: the platform throw is still reachable from call sites that do query that index, and each needs checking on its own.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
