### ISSUE TITLE
Don't know how to fetch docs at org.elixir_lang.documentation.BeamDocsHelper.fetchDocs(BeamDocsHelper.kt:51)

### ISSUE THREAD

**Issue by kkyb123** [KronicDeth/intellij-elixir#3324]
# System

Plugin Version: 14.0.1
Application: IntelliJ IDEA Community Edition (2022.3.1)
Operating System: Mac OS X (13.3)

# Event

### Element

```
@type term :: any()
```

From: `~/.asdf/installs/erlang/25.2.2/lib/erts-13.1.4/ebin/erlang.beam:154`

#### Context

```

  @type stacktrace :: [({module(), atom(), (arity() | [term()]), [stacktrace_extrainfo()]} | {function(), (arity() | [term()]), [stacktrace_extrainfo()]})]

  @type string :: [char()]

  @type term :: any()

  @type time_unit :: (pos_integer() | :second | :millisecond | :microsecond | :nanosecond | :native | :perf_counter | deprecated_time_unit())

  @type timeout :: (:infinity | non_neg_integer())

```

From: `~/.asdf/installs/erlang/25.2.2/lib/erts-13.1.4/ebin/erlang.beam:149-159`
            
### Element Class Name

```
org.elixir_lang.beam.psi.impl.TypeDefinitionImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to fetch docs
</summary>

```
java.lang.Throwable: Don't know how to fetch docs
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.BeamDocsHelper.fetchDocs(BeamDocsHelper.kt:51)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:497)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:41)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:135)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDocHtml(PsiElementDocumentationTarget.kt:102)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:88)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:75)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2$documentationResult$1.invoke(impl.kt:58)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2$documentationResult$1.invoke(impl.kt:57)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:90)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:74)
```

</details>

### `~/.asdf/installs/erlang/25.2.2/lib/erts-13.1.4/ebin/erlang.beam`

**Comment by sh41** [comment]
Still live on `main`, and still reported — the most recent crash reports for this call site are from August 2026. Keeping this open as the canonical for it.

The cause: hovering a `@type` in a decompiled `.beam` hands `BeamDocsHelper.fetchDocs` a `TypeDefinitionImpl`. That `when` only enumerates `Module`, `MaybeExported` and `AtUnqualifiedNoParenthesesCall`, and `TypeDefinition` is none of them — it is a *sibling* of `Module`, declared with the identical super-interface list, not a subtype. So every builtin type falls through to the branch that files this report. It has never had a case; the branch's only edit swapped a `TODO()` crash for this report, a month after `TypeDefinitionImpl` was added.

Nothing about your `erlang.beam` is wrong — this fires on the element's class alone, regardless of whether the file has a docs chunk. The report is noisy rather than harmful: hover just shows nothing.

Most of the fix already exists. The docs chunk's `type` kind is already parsed and already used by the decompiler, and `FetchedDocs.TypeDocumentation` is already rendered — only the BEAM half of the lookup was never written, the source-file half being `SourceFileDocsHelper`. That change is deliberately not being taken yet: #3985 tracks this whole family and asks what these `when`s should do by default with a shape they do not model, rather than adding one arm per report. This issue is attached to it.

#3468, #3552 and #3553 are the same defect and close as duplicates of this one.

> This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
