### ISSUE TITLE
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.12.3` is missing Erlang SDK at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)

### ISSUE THREAD

**Issue by ORESoftware** [KronicDeth/intellij-elixir#3328]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.3)
Operating System: Mac OS X (12.6)

# Event

### Stacktrace

<details>

<summary>
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.12.3` is missing Erlang SDK
</summary>

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.12.3` is missing Erlang SDK
	at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:34)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.commandLine(MixFormatExternalFormatProcessor.kt:89)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.format(MixFormatExternalFormatProcessor.kt:84)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.access$format(MixFormatExternalFormatProcessor.kt:69)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda-7$lambda-6(MixFormatExternalFormatProcessor.kt:46)
```

</details>

**Comment by sh41** [comment]
This is fixed.

An Elixir SDK with no linked Erlang SDK used to hit this exact unhandled exception whenever the plugin tried to build a command line for it — whether that was importing a Mix project or running the formatter. b99ef2a8741a3faf833a153be29454cb83a709ce replaced it with the platform's own "can't run this" mechanism, which is caught and turned into a proper message instead of a crash, at both places this used to happen. There's a test that pins exactly this scenario, and it passes today. First shipped in v23.0.2 and unchanged since, including the current release, v24.0.1.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
