### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action or Event Dispatch Thread (EDT) only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details, Current thread: Thread[ApplicationImpl pooled thread 1051,4,main] 1735253895 (EventQueue.isDispatchThread()=false), SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1721195284 at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)

### ISSUE THREAD

**Issue by alpeshjamgade** [KronicDeth/intellij-elixir#3329]
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Ultimate Edition (2023.2)
Operating System: Linux (5.15.0-78-generic)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action or Event Dispatch Thread (EDT) only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
</summary>

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action or Event Dispatch Thread (EDT) only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 1051,4,main] 1735253895 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1721195284
	at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1038)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:132)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:74)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:97)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:90)
	at com.intellij.openapi.module.ModuleUtilCore.findModuleForPsiElement(ModuleUtilCore.java:127)
	at org.elixir_lang.sdk.elixir.Type$Companion.mostSpecificSdk(Type.kt:535)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda$7$lambda$6(MixFormatExternalFormatProcessor.kt:46)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
```

</details>

**Comment by sh41** [comment]
Thanks for the report — this was already fixed before it was filed.

The crash is `Type.mostSpecificSdk` calling `ModuleUtilCore.findModuleForPsiElement` outside a read action, on the pooled thread `mix format` runs on. That call was wrapped in a read action in June 2023 and first shipped in v15.1.0, released 2023-06-21. This report is against 15.0.1, which predates that release, so upgrading to v15.1.0 or later resolves it.

#3212 is the same crash — identical stack, same plugin version — so this is a duplicate of that one.

The code has moved on since: both `Type.mostSpecificSdk` and `MixFormatExternalFormatProcessor` have been deleted. SDK lookup now lives in `ElixirSdkLookup`, which declares `@RequiresReadLock` and asserts read access at runtime, and the `mix format` path wraps it in a non-blocking read action.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
