### ISSUE TITLE
java.lang.NoClassDefFoundError: com/intellij/psi/scope/ElementClassHint at org.elixir_lang.beam.psi.BeamFileImpl.processDeclarations(BeamFileImpl.kt:287)

### ISSUE THREAD

**Issue by nimrodleon** [KronicDeth/intellij-elixir#3333]
# System

Plugin Version: 12.2.1
Application: WebStorm (2021.2.2)
Operating System: Windows 10 (10.0)

# Event

### Stacktrace

```
java.lang.NoClassDefFoundError: com/intellij/psi/scope/ElementClassHint
	at org.elixir_lang.beam.psi.BeamFileImpl.processDeclarations(BeamFileImpl.kt:287)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1218)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:238)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:225)
	at org.elixir_lang.reference.resolver.Callable.resolveQualified(Callable.kt:148)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:98)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.CaptureNameArity.resolve(CaptureNameArity.kt:15)
	at org.elixir_lang.reference.resolver.CaptureNameArity.resolve(CaptureNameArity.kt:13)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.CaptureNameArity.resolveWithCaching$lambda-0(CaptureNameArity.kt:39)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at org.elixir_lang.reference.CaptureNameArity.resolveWithCaching(CaptureNameArity.kt:36)
	at org.elixir_lang.reference.CaptureNameArity.multiResolve(CaptureNameArity.kt:27)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedExpressionImpl.accept(ElixirUnmatchedExpressionImpl.java:27)
	at org.elixir_lang.psi.impl.ElixirUnmatchedCaptureNonNumericOperationImpl.accept(ElixirUnmatchedCaptureNonNumericOperationImpl.java:31)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by sh41** [comment]
This was fixed in v13.1.0 (2022-06-01).

`BeamFileImpl.processDeclarations` used to call `processor.getHint(ElementClassHint.KEY)`. `ElementClassHint` is part of the Java PSI module, which WebStorm does not bundle, so the class could not be loaded and the call threw `NoClassDefFoundError`. Commit c7d8f84ef03de585ebb393ea3aee61ba39f152ef removed the reference outright — the Elixir resolvers never used the hint system, so it was dead weight rather than something that needed a compatibility shim. The plugin has no references to `ElementClassHint` anywhere today.

This report is on plugin 12.2.1, the release immediately before the fix. #2592 is the same crash on the same plugin version, from RubyMine — another IDE without the Java module — and is the issue that commit closed, so this is a duplicate of it. #3336 is a third report of the same thing.

Updating the plugin resolves it.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
