### ISSUE TITLE
java.lang.NoSuchMethodError: org.intellij.markdown.flavours.gfm.GFMFlavourDescriptor: method 'void <init>(boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)' not found at org.elixir_lang.documentation.MarkdownFlavourDescriptor.<init>(MarkdownFlavourDescriptor.kt:21)

### ISSUE THREAD

**Issue by calebikhuohon** [KronicDeth/intellij-elixir#3337]
# System

Plugin Version: 14.0.1
Application: IntelliJ IDEA Community Edition (2023.2.1)
Operating System: Mac OS X (13.4.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.NoSuchMethodError: org.intellij.markdown.flavours.gfm.GFMFlavourDescriptor: method 'void <init>(boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)' not found
</summary>

```
java.lang.NoSuchMethodError: org.intellij.markdown.flavours.gfm.GFMFlavourDescriptor: method 'void <init>(boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)' not found
	at org.elixir_lang.documentation.MarkdownFlavourDescriptor.<init>(MarkdownFlavourDescriptor.kt:21)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.html(ElixirDocumentationProvider.kt:487)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateRenderedDoc(ElixirDocumentationProvider.kt:49)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateRenderedDoc(CompositeDocumentationProvider.java:159)
	at com.intellij.codeInsight.documentation.render.PsiCommentInlineDocumentation.renderText(PsiCommentInlineDocumentation.java:45)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory.calcText(DocRenderPassFactory.java:107)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory.calculateItemsToRender(DocRenderPassFactory.java:84)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory$DocRenderPass.doCollectInformation(DocRenderPassFactory.java:66)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
```

</details>

**Comment by sh41** [comment]
This was a binary-compatibility break rather than a bug in the plugin's own logic.

`MarkdownFlavourDescriptor` extends `GFMFlavourDescriptor`, which the plugin gets from the IDE's bundled Markdown plugin. `GFMFlavourDescriptor` is a Kotlin class with default constructor parameters, so the compiler emits a synthetic constructor carrying a `DefaultConstructorMarker` — the `<init>(boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)` in your trace. That signature changes shape whenever the parameter list does, and nothing in the plugin controls when that happens.

Plugin 14.0.1 was compiled against IntelliJ 2022.3. You were running 2023.2.1, and the constructor changed between those two releases, so the reference compiled into the plugin's class file no longer resolved at runtime. Quick Doc rendering was the first thing to touch it.

The plugin's minimum supported IDE build is now 253.28294.1 (2025.3), which puts 2023.x several years out of support, so this particular version pairing can't occur any more. Closing on that basis rather than on a fix — if you see a `NoSuchMethodError` in this area on a current IDE with a current plugin, please open a new issue and include both versions; that would be a different mismatch, not this one.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
