### ISSUE TITLE
com.ericsson.otp.erlang.OtpErlangExit: timeout at org.elixir_lang.MailBox.wait(MailBox.kt:205)

### ISSUE THREAD

**Issue by sahilchopra** [KronicDeth/intellij-elixir#3339]
# System

Plugin Version: 16.0.0-pre+20230810101552
Application: IntelliJ IDEA Ultimate Edition (2023.2)
Operating System: Mac OS X (13.4)

# Event

### Stacktrace

<details>

<summary>
com.ericsson.otp.erlang.OtpErlangExit: timeout
</summary>

```
com.ericsson.otp.erlang.OtpErlangExit: timeout
	at org.elixir_lang.MailBox.wait(MailBox.kt:205)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.interpret(Node.kt:119)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:356)
	at org.elixir_lang.debugger.Process$sessionInitialized$1.invoke(Process.kt:352)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:393)
	at org.elixir_lang.debugger.Process.asyncRunInitializers$lambda$14(Process.kt:375)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
```

</details>

**Comment by sh41** [comment]
Closing as a duplicate of #2715, which has the fuller diagnosis.

Short version: every request the IDE makes of the debugged node is wrapped in a hard-coded 60 second
timeout that has never been configurable, and this exit is that timeout expiring. #2715 also covers why
it can leave the session hanging rather than reporting an error.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
