### ISSUE TITLE
com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$InvalidStateException: com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(org.elixir_lang.ElixirLexer): Error updating  after DocumentEventImpl[myOffset=5918, myOldLength=7, myNewLength=0] Whole. at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:341)

### ISSUE THREAD

**Issue by hdtafur** [KronicDeth/intellij-elixir#3340]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.5)
Operating System: Mac OS X (13.4.1)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$InvalidStateException: com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(org.elixir_lang.ElixirLexer): Error updating  after DocumentEventImpl[myOffset=5918, myOldLength=7, myNewLength=0] Whole.
</summary>

```
com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$InvalidStateException: com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(org.elixir_lang.ElixirLexer): Error updating  after DocumentEventImpl[myOffset=5918, myOldLength=7, myNewLength=0] Whole.
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:341)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:918)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:822)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:663)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$setText$2(DocumentImpl.java:1086)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:1088)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda-7$lambda-6$lambda-5$lambda-4$lambda-3$lambda-2$lambda-1$lambda-0(MixFormatExternalFormatProcessor.kt:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda-7$lambda-6$lambda-5$lambda-4$lambda-3$lambda-2$lambda-1(MixFormatExternalFormatProcessor.kt:50)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:371)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda-7$lambda-6$lambda-5$lambda-4$lambda-3$lambda-2(MixFormatExternalFormatProcessor.kt:49)
```

</details>

**Comment by sh41** [comment]
Fixed in v23.1.0, and closing as a duplicate of #2708 — same defect, different symptom.

The title is misleading: this is not a lexer bug. `LexerEditorHighlighter` wraps any runtime exception thrown while updating its segments as `InvalidStateException`, and builds the message from the name of the registered highlighting lexer. `org.elixir_lang.ElixirLexer` appearing there says only that an Elixir file was open.

What the stack trace actually shows is that every frame below the highlighter is `MixFormatExternalFormatProcessor.format` calling `Document.setText`. That class ran `mix format` on a pooled thread, returned immediately, and later wrote the result into the document without checking that the document still held the text it had formatted. If the file changed while the external process was running, the stale result was applied as a diff against content it was never computed from, leaving the highlighter's bookkeeping describing text that no longer existed. #2708 is the same race seen from the other side, where the stale write silently undid a rollback.

`MixFormatExternalFormatProcessor` was deleted in "refactor(formatter): replace ExternalFormatProcessor with AsyncDocumentFormattingService" (#3816). Its replacement, `MixFormatFormattingService`, hands the formatted text to the platform's `AsyncDocumentFormattingService`, which captures the document's modification stamp when formatting starts and will not overwrite the document if that stamp has moved.

One note on the report itself: this exception normally carries the lexer's buffer as a `content.txt` attachment, but that stays with the JetBrains-side crash submission and was not copied into the auto-filed issue. There was never a reproducer here to ask you for.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
