### ISSUE TITLE
Stub ids not found for key in index = elixir.all.name, file = file:///Users/haoyu.liu/whatnot/whatnot_live/_build/test/lib/whatnot_live/ebin/Elixir.WhatnotLive.DA.DirectMessage.beam, file type = BEAM, indexed file type = BEAM at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:65)

### ISSUE THREAD

**Issue by gooooodfish** [KronicDeth/intellij-elixir#3341]
# System

Plugin Version: 15.1.0
Application: PyCharm Professional Edition (2023.1.4)
Operating System: Mac OS X (13.4)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name, file = file:///Users/haoyu.liu/whatnot/whatnot_live/_build/test/lib/whatnot_live/ebin/Elixir.WhatnotLive.DA.DirectMessage.beam, file type = BEAM, indexed file type = BEAM
</summary>

```
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name, file = file:///Users/haoyu.liu/whatnot/whatnot_live/_build/test/lib/whatnot_live/ebin/Elixir.WhatnotLive.DA.DirectMessage.beam, file type = BEAM, indexed file type = BEAM
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:65)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$6(StubIndexEx.java:203)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:196)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:91)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:876)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.accept(ElixirUnmatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:348)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:287)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:278)
```

</details>

**Comment by sh41** [comment]
Fixed in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0) (2026-05-15), and a duplicate of #2427.

The plugin frame in your trace, `org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule`, was the resolver's global fallback into the `elixir.all.name` stub index: when in-scope resolution found nothing, it searched every module in the project for a matching name. It was removed outright — not renamed — by [`60a8386`](https://github.com/KronicDeth/intellij-elixir/commit/60a8386986b131504a30fc137c7b994462496728), and `Callable`'s resolve chain no longer queries that index at all. [`Issue463Test.testUnresolvedAliasQualifier`](https://github.com/KronicDeth/intellij-elixir/blob/main/tests/org/elixir_lang/reference/callable/Issue463Test.kt) fails if the fallback comes back.

Your file is a decompiled `.beam` (`file type = BEAM, indexed file type = BEAM`), the same shape as #2427 and #2567; [#3295](https://github.com/KronicDeth/intellij-elixir/issues/3295) reached the identical call site from a plain `.ex` source file. The trigger was the call, not the kind of file.

Worth recording, because this looks like it was already fixed once. [`beefdb2e`](https://github.com/KronicDeth/intellij-elixir/commit/beefdb2e1ba1e28d10a3fca02bd2cf7c122f14c0) (2023-02-10, "Fixes #2945") wrapped that same call in a `try`/`catch` that swallowed exactly this message. It could never have worked: the platform reports it from [`StubProcessingHelper.retrieveStubIdList`](https://github.com/JetBrains/intellij-community/blob/master/platform/indexing-impl/src/com/intellij/psi/stubs/StubProcessingHelper.java) via `LOG.error(String)`, and [`Logger.error(String)`](https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/openapi/diagnostic/Logger.java) builds `new Throwable(message)` only to capture a stack for the log record — it does not throw it. Nothing propagates out of `StubIndex.processElements` for this failure, so the `catch` was dead on arrival, which is why your report six months later still shows the trace uncaught. Please don't re-add one: deleting the call site was the only thing that could stop it.

Other `elixir.all.name` reports stay open — [#1481](https://github.com/KronicDeth/intellij-elixir/issues/1481), [#1523](https://github.com/KronicDeth/intellij-elixir/issues/1523), [#3584](https://github.com/KronicDeth/intellij-elixir/issues/3584), [#3588](https://github.com/KronicDeth/intellij-elixir/issues/3588), [#3594](https://github.com/KronicDeth/intellij-elixir/issues/3594) — because the platform check is still reachable from call sites that do query that index. Each needs checking on its own.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
