### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by iaidan** [KronicDeth/intellij-elixir#3347]
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
  Failed to execute task (dumb mode task) org.elixir_lang.file.LevelPropertyPusher$1@59e94077. Found interface com.intellij.diagnostic.PerformanceWatcher$Snapshot, but class was expected
  
  java.lang.IncompatibleClassChangeError: Found interface com.intellij.diagnostic.PerformanceWatcher$Snapshot, but class was expected
at org.elixir_lang.file.LevelPropertyPusher$1.performInDumbMode(LevelPropertyPusher.java:264)
at com.intellij.openapi.project.DumbModeTask.perform(DumbModeTask.java:41)
at com.intellij.openapi.project.MergingTaskQueue$QueuedTask.executeTask(MergingTaskQueue.java:336)
at com.intellij.openapi.project.MergingTaskQueue$QueuedTask.executeTask(MergingTaskQueue.java:318)
at com.intellij.openapi.project.MergingQueueGuiExecutor.runSingleTask$lambda$6(MergingQueueGuiExecutor.kt:218)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.project.MergingQueueGuiExecutor.runSingleTask(MergingQueueGuiExecutor.kt:215)
at com.intellij.openapi.project.DumbServiceGuiExecutor.runSingleTask$lambda$1(DumbServiceGuiExecutor.kt:55)
at com.intellij.util.io.storage.HeavyProcessLatch.performOperation(HeavyProcessLatch.java:58)
at com.intellij.openapi.project.DumbServiceGuiExecutor.runSingleTask(DumbServiceGuiExecutor.kt:54)
at com.intellij.openapi.project.MergingQueueGuiExecutor.processTasksWithProgress$lambda$3(MergingQueueGuiExecutor.kt:129)
at com.intellij.openapi.project.MergingQueueGuiSuspender.setCurrentSuspenderAndSuspendIfRequested(MergingQueueGuiSuspender.kt:53)
at com.intellij.openapi.project.MergingQueueGuiExecutor.processTasksWithProgress(MergingQueueGuiExecutor.kt:113)
at com.intellij.openapi.project.DumbServiceGuiExecutor.processTasksWithProgress(DumbServiceGuiExecutor.kt:34)
at com.intellij.openapi.project.MergingQueueGuiExecutor.runBackgroundProcessWithSuspender(MergingQueueGuiExecutor.kt:206)
at com.intellij.openapi.project.MergingQueueGuiExecutor.lambda$1$lambda$0(MergingQueueGuiExecutor.kt:105)
at com.intellij.openapi.project.MergingQueueGuiExecutor.runWithCallbacks(MergingQueueGuiExecutor.kt:190)
at com.intellij.openapi.project.MergingQueueGuiExecutor._init_$lambda$1(MergingQueueGuiExecutor.kt:104)
at com.intellij.openapi.project.SingleTaskExecutor$StateAwareTask.run$lambda$0(SingleTaskExecutor.kt:37)
at com.intellij.openapi.project.SingleTaskExecutor.runWithStateHandling(SingleTaskExecutor.kt:63)
at com.intellij.openapi.project.SingleTaskExecutor.access$runWithStateHandling(SingleTaskExecutor.kt:22)
at com.intellij.openapi.project.SingleTaskExecutor$StateAwareTask.run(SingleTaskExecutor.kt:37)
at com.intellij.openapi.project.MergingQueueGuiExecutor$startBackgroundProcess$1$1.run(MergingQueueGuiExecutor.kt:153)
at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by KronicDeth** [comment]
This version is no longer supported.
