### ISSUE TITLE
java.lang.Exception at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)

### ISSUE THREAD

**Issue by seongwon-jeong** [KronicDeth/intellij-elixir#3350]
# System

Plugin Version: 14.0.1
Application: PyCharm Professional Edition (2022.3.3)
Operating System: Mac OS X (13.5.2)

# Event

## Message

Outdated stub in index: file:///Users/won/Workspace/issues/lib/issues.ex indexing timestamp = 1694874163949, binary = false, byte size = 198, char size = 203, doc=DocumentImpl[file:///Users/won/Workspace/issues/lib/issues.ex], docSaved=true, wasIndexedAlready=true, queried at 1694874163949
doc length=198
file length=198
cached PSI class org.elixir_lang.psi.ElixirFile
projects with file: 1
physical file exists; length = 198

### Stacktrace

<details>

<summary>
java.lang.Exception
</summary>

```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:49)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:634)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:956)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:255)
	at com.intellij.psi.stubs.StubProcessingHelperBase.lambda$getAllSpines$0(StubProcessingHelperBase.java:85)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1798)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getAllSpines(StubProcessingHelperBase.java:85)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:65)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:148)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:212)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:54)
	at org.elixir_lang.psi.scope.module.Variants$putProject$1.invoke(Variants.kt:74)
	at org.elixir_lang.psi.scope.module.Variants$putProject$1.invoke(Variants.kt:72)
	at org.elixir_lang.psi.scope.module.Variants.putProject$lambda$0(Variants.kt:72)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$iterateData$1(PersistentEnumeratorBase.java:417)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.lambda$processAll$3(AppendableStorageBackedByResizableMappedFile.java:127)
	at com.intellij.util.io.PagedFileStorage.lambda$readInputStream$1(PagedFileStorage.java:135)
	at com.intellij.util.io.PagedFileStorage.useChannel(PagedFileStorage.java:165)
	at com.intellij.util.io.PagedFileStorage.readInputStream(PagedFileStorage.java:133)
	at com.intellij.util.io.ResizeableMappedFile.readInputStream(ResizeableMappedFile.java:291)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.processAll(AppendableStorageBackedByResizableMappedFile.java:114)
	at com.intellij.util.io.PersistentEnumeratorBase.doIterateData(PersistentEnumeratorBase.java:429)
	at com.intellij.util.io.PersistentEnumeratorBase.iterateData(PersistentEnumeratorBase.java:417)
	at com.intellij.util.io.PersistentMapImpl.processKeys(PersistentMapImpl.java:498)
	at com.intellij.util.indexing.impl.ValueContainerMap.processKeys(ValueContainerMap.java:73)
	at com.intellij.util.indexing.impl.MapIndexStorage.doProcessKeys(MapIndexStorage.java:373)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.processKeys(VfsAwareMapIndexStorage.java:125)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.processKeys(TransientChangesIndexStorage.java:139)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.lambda$processAllKeys$0(MapReduceIndexBase.java:52)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.processAllKeys(MapReduceIndexBase.java:51)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.processAllKeys(CompositeInvertedIndexBase.java:121)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processAllKeys$8(StubIndexEx.java:323)
	at com.intellij.util.indexing.IndexUpToDateCheckIn.disableUpToDateCheckIn(IndexUpToDateCheckIn.kt:15)
	at com.intellij.util.indexing.FileBasedIndexEx.disableUpToDateCheckIn(FileBasedIndexEx.java:838)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processAllKeys$9(StubIndexEx.java:322)
	at com.intellij.util.indexing.diagnostic.IndexAccessValidator.validate(IndexAccessValidator.java:46)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:322)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:71)
	at org.elixir_lang.psi.scope.module.Variants.putProject(Variants.kt:72)
	at org.elixir_lang.psi.scope.module.Variants.access$putProject(Variants.kt:25)
	at org.elixir_lang.psi.scope.module.Variants$Companion.unfilteredLookupElements(Variants.kt:247)
	at org.elixir_lang.psi.scope.module.Variants$Companion.lookupElements(Variants.kt:107)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:18)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:15)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:233)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:122)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:63)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:80)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:134)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:117)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:78)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:48)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
```

</details>

**Comment by KronicDeth** [comment]
This version is no longer supported
