### ISSUE TITLE
java.lang.IllegalStateException: Application library named Erlang for Elixir 26 already exists at com.intellij.workspaceModel.ide.impl.legacyBridge.library.GlobalLibraryTableBridgeImpl.createLibrary(GlobalLibraryTableBridgeImpl.kt:232)

### ISSUE THREAD

**Issue by seongwon-jeong** [KronicDeth/intellij-elixir#3351]
# System

Plugin Version: 16.0.0
Application: PyCharm Professional Edition (2023.2.1)
Operating System: Mac OS X (13.5.2)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Application library named Erlang for Elixir 26 already exists
</summary>

```
java.lang.IllegalStateException: Application library named Erlang for Elixir 26 already exists
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.GlobalLibraryTableBridgeImpl.createLibrary(GlobalLibraryTableBridgeImpl.kt:232)
	at org.elixir_lang.facet.sdks.Configurable$addListeners$listener$1.sdkAdded$lambda$5$lambda$4(Configurable.kt:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:992)
	at org.elixir_lang.facet.sdks.Configurable$addListeners$listener$1.sdkAdded(Configurable.kt:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:118)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:83)
	at jdk.proxy2/jdk.proxy2.$Proxy181.sdkAdded(Unknown Source)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:525)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.setupSdk(ProjectSdksModel.java:509)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.addSdk(ProjectSdksModel.java:451)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.lambda$doAdd$7(ProjectSdksModel.java:445)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.lambda$selectSdkHome$7(SdkConfigurationUtil.java:298)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:149)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:102)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:296)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:274)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:445)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:425)
	at org.elixir_lang.facet.sdks.Configurable.addSdk(Configurable.kt:173)
	at org.elixir_lang.facet.sdks.Configurable.createComponent$lambda$1(Configurable.kt:66)
	at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:582)
	at com.intellij.ui.CommonActionsPanel$AddButton.actionPerformed(CommonActionsPanel.java:391)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:520)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
```

</details>

**Comment by sh41** [comment]
Fixed.

The crash was in the SDK listener shared by the Settings → Elixir → SDKs and → Internal Erlang SDKs pages. When an SDK was added, the listener mirrored it into an application-level library by calling `createLibrary` with the SDK's name unconditionally — and the platform refuses to create an application library whose name is already taken. So adding an SDK whose global library had survived an earlier add/remove cycle threw this. Both pages inherit that one listener, which is why the same crash also gets reported for names like "Elixir 1.15.5" (#3353) as well as "Erlang for Elixir 26" (#3565).

The listener now reuses an existing library rather than creating a second one, in the commit "Resolve `application library named XXX already exists` exception" — first released in v22.0.0.

A second, related defect made it easier to hit: every Settings open attached another copy of that listener to the shared SDK model and never removed it, so a single SDK addition fired the mirroring once per accumulated listener. That is a different defect, fixed separately in "fix(settings): stop SdkModel listener accumulation across Settings opens" — first released in 24.0.0.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
