### ISSUE TITLE
java.lang.IllegalStateException: Application library named Elixir 1.15.5 already exists at com.intellij.workspaceModel.ide.impl.legacyBridge.library.GlobalLibraryTableBridgeImpl.createLibrary(GlobalLibraryTableBridgeImpl.kt:232)

### ISSUE THREAD

**Issue by seongwon-jeong** [KronicDeth/intellij-elixir#3353]
# System

Plugin Version: 16.0.0
Application: PyCharm Professional Edition (2023.2.1)
Operating System: Mac OS X (13.5.2)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Application library named Elixir 1.15.5 already exists
</summary>

```
java.lang.IllegalStateException: Application library named Elixir 1.15.5 already exists
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.GlobalLibraryTableBridgeImpl.createLibrary(GlobalLibraryTableBridgeImpl.kt:232)
	at org.elixir_lang.facet.sdks.Configurable$addListeners$listener$1.sdkAdded$lambda$5$lambda$4(Configurable.kt:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:992)
	at org.elixir_lang.facet.sdks.Configurable$addListeners$listener$1.sdkAdded(Configurable.kt:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:118)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:83)
	at jdk.proxy2/jdk.proxy2.$Proxy181.sdkAdded(Unknown Source)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:525)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.setupSdk(ProjectSdksModel.java:509)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.lambda$doAdd$6(ProjectSdksModel.java:442)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.lambda$createSdkOfType$1(DependentSdkType.java:77)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.lambda$selectSdkHome$7(SdkConfigurationUtil.java:298)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:149)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:102)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:296)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:274)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.createSdkOfType(DependentSdkType.java:74)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.showCustomCreateUI(DependentSdkType.java:59)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:442)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:425)
	at org.elixir_lang.facet.sdks.Configurable.addSdk(Configurable.kt:173)
	at org.elixir_lang.facet.sdks.Configurable.createComponent$lambda$1(Configurable.kt:66)
	at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:582)
	at com.intellij.ui.CommonActionsPanel$AddButton.actionPerformed(CommonActionsPanel.java:391)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:520)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
```

</details>

**Comment by sh41** [comment]
Duplicate of #3351, and fixed.

Different library name, same defect: the Settings → Elixir → SDKs page and the → Internal Erlang SDKs page inherit one shared SDK listener, and it called `createLibrary` with the SDK's name unconditionally. The platform refuses to create an application library whose name is already taken, so adding an SDK whose global library already existed threw — as "Elixir 1.15.5" here and as "Erlang for Elixir 26" in #3351.

The listener now reuses an existing library, in the commit "Resolve `application library named XXX already exists` exception" — first released in v22.0.0. A related listener-accumulation defect that made it easier to hit was fixed separately, first released in 24.0.0. See #3351 for the full write-up.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
