### ISSUE TITLE
Stub index points to a file (file = file:///opt/homebrew/Cellar/erlang@25/25.3.2.6/lib/erlang/man/man3/wxSystemOptions.3, file type = com.intellij.openapi.fileTypes.PlainTextFileType@18c7b2c3, indexed file type = com.intellij.openapi.fileTypes.PlainTextFileType@18c7b2c3) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0 at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)

### ISSUE THREAD

**Issue by kpy3** [KronicDeth/intellij-elixir#3354]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Community Edition (2023.2.2)
Operating System: Mac OS X (13.5.2)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Stub index points to a file (file = file:///opt/homebrew/Cellar/erlang@25/25.3.2.6/lib/erlang/man/man3/wxSystemOptions.3, file type = com.intellij.openapi.fileTypes.PlainTextFileType@18c7b2c3, indexed file type = com.intellij.openapi.fileTypes.PlainTextFileType@18c7b2c3) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0
</summary>

```
java.lang.Throwable: Stub index points to a file (file = file:///opt/homebrew/Cellar/erlang@25/25.3.2.6/lib/erlang/man/man3/wxSystemOptions.3, file type = com.intellij.openapi.fileTypes.PlainTextFileType@18c7b2c3, indexed file type = com.intellij.openapi.fileTypes.PlainTextFileType@18c7b2c3) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$6(StubIndexEx.java:207)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:206)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.reference.resolver.atom.resolvable.Exact.resolve(Exact.kt:20)
	at org.elixir_lang.reference.resolver.Atom.resolve(Atom.java:20)
	at org.elixir_lang.reference.resolver.Atom.resolve(Atom.java:11)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at org.elixir_lang.reference.Atom.multiResolve(Atom.java:43)
	at org.elixir_lang.psi.impl.ElixirAtomImplKt.maybeModularNameToModulars(ElixirAtomImpl.kt:22)
	at org.elixir_lang.psi.impl.ElixirAtomImplKt.maybeModularNameToModulars(ElixirAtomImpl.kt:18)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:202)
	at org.elixir_lang.psi.impl.call.qualification.QualifiedImplKt.qualifiedToModulars(QualifiedImpl.kt:19)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:29)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:22)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.accept(ElixirMatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:360)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:291)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:320)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:286)
```

</details>

**Comment by alabama** [comment]
same same

---

# System

Plugin Version: 16.0.0
Application: WebStorm (2023.2.2)
Operating System: Linux (6.4.6-76060406-generic)


# Event


## Exception


### Stacktrace


<details>

<summary>
java.lang.Throwable: Stub index points to a file (file = file:///home/user1/src/app1/_build/test/lib/jason/ebin, file type = com.intellij.openapi.fileTypes.UnknownFileType@6ce8be07, indexed file type = null) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0
</summary>

```
java.lang.Throwable: Stub index points to a file (file = file:///home/user1/src/app1/_build/test/lib/jason/ebin, file type = com.intellij.openapi.fileTypes.UnknownFileType@6ce8be07, indexed file type = null) without indexed stub tree; indexing stamp = null, can have stubs = false, actual stub count = 0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$6(StubIndexEx.java:207)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:206)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:196)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:91)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:360)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:299)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:320)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:286)
```

</details>

---

This bug is causing the "Updating Indexes"  to appear every second

**Comment by sh41** [comment]
This is the missing guard #1481 tracks, reached through a different call site.

The atom reference resolvers query the `elixir.all.name` stub index with a scope narrowed to the module and its dependencies, but not restricted by file type. `StubIndexEx.processElements` skips a file the caller's scope does not contain before it asks `StubProcessingHelper` for a stub id list, so restricting that scope to the Elixir, Elixir script and BEAM file types would have skipped this entry — an Erlang man page the index still has a record for, and which is plain text — before the platform logged it.

The one comment on this issue is a different crash, through a call site removed in v23.2.0. It is not this report.

Closing as a duplicate of #1481, which has the diagnosis and now covers this call site.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
