### ISSUE TITLE
Don't know how process element as type at org.elixir_lang.psi.scope.Type$Companion.error(Type.kt:219)

### ISSUE THREAD

**Issue by hamicek** [KronicDeth/intellij-elixir#3356]
# System

Plugin Version: 13.2.1
Application: PyCharm Professional Edition (2022.2.2)
Operating System: Mac OS X (13.4.1)

# Event

### Element

```
Dictionary.Impl.Level
```

From: `/Users/miroslavhalabrin/projects/unikovky/dictionary/lib/dictionary.ex:3`

#### Context

```
defmodule Dictionary do
  alias Dictionary.Runtime.Server
  alias Dictionary.Impl.Room
  Dictionary.Impl.Level

  @spec room(name :: String.t) :: Room.t
  defdelegate room(name), to: Server
  
  @spec get_level(Room.t, String.t) :: 
```

From: `/Users/miroslavhalabrin/projects/unikovky/dictionary/lib/dictionary.ex:0-8`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how process element as type
</summary>

```
java.lang.Throwable: Don't know how process element as type
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.Type$Companion.error(Type.kt:219)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:53)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:358)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:687)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.processDeclarations(ElixirUnmatchedQualifiedAliasImpl.java:85)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:440)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:439)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:303)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:443)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:417)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:265)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:655)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults(MultiResolve.kt:186)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:178)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:42)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:23)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
```

</details>

**Comment by sh41** [comment]
Duplicate of #2550 — the same `ElixirUnmatchedQualifiedAliasImpl` reaching `Type.execute`'s `else` branch, and the same report as #3355 moments apart.

Fixed by `Skip bare Aliases when resolving Types`, first released in v15.1.0; you were on 13.2.1. #2550 carries the diagnosis and is tracked under #3985.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
