### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:99)

### ISSUE THREAD

**Issue by hamicek** [KronicDeth/intellij-elixir#3357]
# System

Plugin Version: 13.2.1
Application: PyCharm Professional Edition (2022.2.2)
Operating System: Mac OS X (13.4.1)

# Event

### Element

```
ken. Lorem
```

From: `/Users/miroslavhalabrin/projects/unikovky/erooms/lib/erooms_web/live/game/text.ex:23`

#### Context

```
  end

end


ken. Lorem Ipsum.</p> </div> <label for="auth-form_cookie">Cookie: </label> <input type="text" id="auth-form_cookie" name="auth[cookie]"/> <label for="auth-form_token">Token: <input type="text" id="auth-form_token" name="auth-form[token]"/> <button phx-disable-with="Saving...." type="submit">Uložit</button> </form>
```

From: `/Users/miroslavhalabrin/projects/unikovky/erooms/lib/erooms_web/live/game/text.ex:18-23`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:99)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:83)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:79)
```

</details>

**Comment by sh41** [comment]
This one was already fixed before it was filed. `ElixirUnmatchedQualifiedAliasImpl` implements `QualifiableAlias`, which `ElixirDocumentationProvider` has ignored when collecting doc comments since commit 4e63f673e, "Ignore top-level Aliases when collecting docs" — first released in v14.0.1 on 2023-03-26. This report is from v13.2.1, which predates that release, so upgrading clears it.

Two open issues share this title but are not the same problem: #3135 is a struct operation and #3675 is an unmatched `@` operation, and both of those PSI shapes are still unhandled. They are tracked under #3985.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
