### ISSUE TITLE
java.lang.IllegalMonitorStateException: current thread is not owner at java.base/java.lang.Object.notify(Native Method)

### ISSUE THREAD

**Issue by 6qat** [KronicDeth/intellij-elixir#3374]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.2.2)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalMonitorStateException: current thread is not owner
</summary>

```
java.lang.IllegalMonitorStateException: current thread is not owner
	at java.base/java.lang.Object.notify(Native Method)
	at org.elixir_lang.jps.HomePath.eachEbinPath(HomePath.java:50)
	at org.elixir_lang.sdk.Type.addCodePaths(Type.java:22)
	at org.elixir_lang.sdk.elixir.Type$Companion.configureSdkPaths(Type.kt:302)
	at org.elixir_lang.sdk.elixir.Type$Companion.access$configureSdkPaths(Type.kt:232)
	at org.elixir_lang.sdk.elixir.Type.setupSdkPaths(Type.kt:168)
	at com.intellij.openapi.projectRoots.SdkType.setupSdkPaths(SdkType.java:132)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.setupSdk(ProjectSdksModel.java:502)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$2.lambda$actionPerformed$0(ProjectSdksModel.java:413)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.lambda$createSdkOfType$1(DependentSdkType.java:77)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.lambda$selectSdkHome$7(SdkConfigurationUtil.java:298)
	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:138)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:102)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:296)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:274)
```

</details>

**Comment by sh41** [comment]
Fixed in v23.0.2.

The crash was a bare `.notify()` on a `com.intellij.notification.Notification`. That class declares only `notify(Project)`, so the zero-argument call bound to the inherited `Object.notify()` — a different method entirely, which throws `IllegalMonitorStateException` because nothing holds that object's monitor. It fired whenever the SDK home being configured had no `lib` directory.

The notification was added in a3c40a2305 to fix #2575, so the balloon that issue asked for never actually appeared — this crash took its place.

7498afd035 rewrote `HomePath` as `SdkEbinPaths` in Kotlin, where `Any` exposes no zero-argument `notify()`. The compiler required an argument, so the call now binds to `Notification.notify(Project)` and the missing `lib` directory is reported the way it was meant to be. That was a side effect of the rewrite rather than a deliberate fix, which makes it a better guarantee than a line-level patch would have been: the call shape that caused this can no longer be written in the language the file is now in.

#3450, #3521 and #3537 are the same crash and are closed as duplicates of this one.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
