### ISSUE TITLE
No decompiled source function with name (String.__info__) at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:103)

### ISSUE THREAD

**Issue by mengdaming** [KronicDeth/intellij-elixir#3403]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.2.3)
Operating System: Mac OS X (13.6)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: No decompiled source function with name (String.__info__)
</summary>

```
java.lang.Throwable: No decompiled source function with name (String.__info__)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:103)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:409)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda$6$lambda$5(BeamFileImpl.kt:389)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:388)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:147)
	at com.haulmont.jpb.reference.search.MappedByUsagesSearcher.execute$lambda$5(MappedByUsagesSearcher.kt:27)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:63)
	at com.haulmont.jpb.reference.search.MappedByUsagesSearcher.execute(MappedByUsagesSearcher.kt:26)
	at com.haulmont.jpb.reference.search.MappedByUsagesSearcher.execute(MappedByUsagesSearcher.kt:24)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:30)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:88)
```

</details>

**Comment by sh41** [comment]
Fixed. `Elixir.String`'s own documentation contains `\u{...}`, which the lexer read as a unicode
escape rather than as literal text. That broke the parse of the whole decompiled module, so its
functions were left without mirrors — which is what this message reports.

Fixed in the lexer by #3850, first released in [v24.0.0-pre-4](https://github.com/KronicDeth/intellij-elixir/releases/tag/v24.0.0-pre-4) and in
[v24.0.1](https://github.com/KronicDeth/intellij-elixir/releases/tag/v24.0.1). Verified against a reporter-supplied `Elixir.String.beam`: it now decompiles
with no parse errors and a mirror on all 144 of its definitions.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing
> it, but it might still be a mistake. If you think the reason above is wrong, please reopen the
> issue and tell us why.
