### ISSUE TITLE
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os at org.elixir_lang.exunit.ExUnitLineMarkerProvider.getInfo(TestLineMarkerProvider.kt:60)

### ISSUE THREAD

**Issue by ildomar-grings** [KronicDeth/intellij-elixir#3408]
# System

Plugin Version: 15.0.1
Application: RubyMine (2023.2.3)
Operating System: Mac OS X (14.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os
</summary>

```
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os
	at org.elixir_lang.exunit.ExUnitLineMarkerProvider.getInfo(TestLineMarkerProvider.kt:60)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:63)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:183)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectMarkers$2(LineMarkersPass.java:107)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectMarkers(LineMarkersPass.java:103)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
```

</details>

**Comment by sh41** [comment]
This was fixed in v15.1.0 (2023-07-08).

`ExUnitLineMarkerProvider` used to call `org.codehaus.plexus.interpolation.os.Os` to decide whether it was running on Windows. That class comes from `plexus-interpolation`, a library of the bundled Maven plugin's server modules, so it is present on IntelliJ IDEA and absent on WebStorm, PyCharm CE, RubyMine and GoLand. The old gradle-intellij-plugin put IDEA Community's entire bundled-plugin set on the compile classpath, so the import compiled cleanly and only failed to resolve at runtime, on the IDEs that don't ship Maven support. Every report of this crash is from one of those four IDEs; none is from IntelliJ IDEA.

Commit ea0233a9247fdcb2480763cd02d1eebc155c45db replaced it with `org.apache.commons.lang.SystemUtils`, which the platform bundles itself; a later commit narrowed it further to `com.intellij.util.system.OS`. The plugin has no reference to plexus anywhere today.

This report is on plugin 15.0.1, the release immediately before the fix, and was filed on 2023-10-19 — over three months after v15.1.0 shipped it. #3158 is the issue that commit closed, and is one of thirteen earlier reports of the same crash.

Updating the plugin resolves it.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
