### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented at org.elixir_lang.psi.impl.PsiNamedElementImpl.setName(PsiNamedElementImpl.kt:71)

### ISSUE THREAD

**Issue by dokisha** [KronicDeth/intellij-elixir#3413]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Linux (5.15.0-87-generic)

# Event

### Stacktrace

<details>

<summary>
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented
</summary>

```
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented
	at org.elixir_lang.psi.impl.PsiNamedElementImpl.setName(PsiNamedElementImpl.kt:71)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.setName(ElixirPsiImplUtil.java:1666)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.setName(ElixirAliasImpl.java:77)
```

</details>

**Comment by sh41** [comment]
Fixed in 24.0.0.

This crash came from the platform's legacy rename pipeline (`PsiElementRenameHandler` → `RenameUtil.doRenameGenericNamedElement`) reaching `PsiNamedElementImpl.setName`, whose generic overload is still `TODO("Rename not implemented")`. Rename was consolidated onto the Symbol API in "feat(symbol-api): consolidate rename onto Symbol API RenameTarget", which registers `ElixirVetoRenameCondition` to veto that legacy handler for every Elixir PSI element, so it can no longer be reached. Module alias rename — the element in this trace — now runs through `ModuleSymbol`, which implements `RenameTarget`, and is covered by the module `InPlaceRenameTest` and `RenameMatrixTest` suites.

First released in v24.0.0-pre-3, first stable in 24.0.0.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
