### ISSUE TITLE
unable to get stub builder for file with file = file://C:/Users/Faber/Desktop/phoenix/deps/castore/hex_metadata.config, file type = de.plushnikov.intellij.plugin.language.LombokConfigFileType@465bbf2f, indexed file type = de.plushnikov.intellij.plugin.language.LombokConfigFileType@465bbf2f, , stubBindingRoot = LombokConfigFile, languages = [Lombok.Config], fileTypes = [LOMBOK_CONFIG], files = [LombokConfigFile], roots = [], indexingInfo = null, isTooLarge = false at com.intellij.psi.stubs.StubProcessingHelperBase.handleNonPsiStubs(StubProcessingHelperBase.java:122)

### ISSUE THREAD

**Issue by mjangid-gp** [KronicDeth/intellij-elixir#3416]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Community Edition (2023.2.4)
Operating System: Windows 10 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: unable to get stub builder for file with file = file://C:/Users/Faber/Desktop/phoenix/deps/castore/hex_metadata.config, file type = de.plushnikov.intellij.plugin.language.LombokConfigFileType@465bbf2f, indexed file type = de.plushnikov.intellij.plugin.language.LombokConfigFileType@465bbf2f, , stubBindingRoot = LombokConfigFile, languages = [Lombok.Config], fileTypes = [LOMBOK_CONFIG], files = [LombokConfigFile], roots = [], indexingInfo = null, isTooLarge = false
</summary>

```
java.lang.Throwable: unable to get stub builder for file with file = file://C:/Users/Faber/Desktop/phoenix/deps/castore/hex_metadata.config, file type = de.plushnikov.intellij.plugin.language.LombokConfigFileType@465bbf2f, indexed file type = de.plushnikov.intellij.plugin.language.LombokConfigFileType@465bbf2f, , stubBindingRoot = LombokConfigFile, languages = [Lombok.Config], fileTypes = [LOMBOK_CONFIG], files = [LombokConfigFile], roots = [], indexingInfo = null, isTooLarge = false
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.stubs.StubProcessingHelperBase.handleNonPsiStubs(StubProcessingHelperBase.java:122)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:67)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:150)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:214)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:196)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:91)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedQualifiedNoArgumentsCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:360)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:299)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:320)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:286)
```

</details>

**Comment by sh41** [comment]
Fixed in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0) (2026-05-15), and a duplicate of #2427.

The plugin frame in your trace, `org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule`, was the resolver's global fallback into the `elixir.all.name` stub index: when in-scope resolution found nothing, it searched every function of that name in every module in the project, with no restriction on which files' index entries it would walk. It was removed outright — not renamed — by [`60a8386`](https://github.com/KronicDeth/intellij-elixir/commit/60a8386986b131504a30fc137c7b994462496728), so `Callable`'s resolve chain no longer queries that index at all. `Issue463Test.testUnresolvedAliasQualifier` fails if the fallback comes back.

Your report is worth distinguishing from its siblings, because the platform symptom is a third distinct one off that same fallback. #2427 and friends hit `StubProcessingHelperBase.checkType` — "Stub ids not found for key" or "PSI and index do not match"; #3317 hit `PersistentEnumeratorBase` corruption in the index storage itself. Yours reached `StubProcessingHelperBase.handleNonPsiStubs`, which is where the platform lands when the current PSI for an indexed file has no stubbed roots at all and no binary stub builder is registered for its file type either. `deps/castore/hex_metadata.config` is Hex package metadata, typed by the bundled Lombok plugin as `LombokConfigFileType` — a plain PSI file type with no stub builder, so that branch fires and logs against whichever plugin made the query. Three platform messages, one plugin cause.

What that call site could never explain is how a `.config` file came to hold an `elixir.all.name` entry in the first place. Nothing in the current dependency-root code can index it — a Mix dependency contributes only its `c_src`, `lib`, `priv` and `src` directories as source roots, and `deps` is excluded at the content-root level — but that code has been rewritten since 16.0.0 and we did not reconstruct the 2023 version, so the origin of the entry is genuinely unresolved. It does not change the outcome here: the query that read it is gone.

The underlying pattern is not gone, though, and it is tracked on #1481 — several atom and module resolution paths still query `elixir.all.name` without restricting the scope by file type, which is what stops a stale or foreign index entry from reaching the platform's checks. This issue closes because the specific call site it names was deleted, not because that class of report has been eliminated.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
