### ISSUE TITLE
java.lang.RuntimeException: com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///Users/vcarballo/workspace/query_membership_api/deps/aws; original:245896; found:-; File.exists()=false at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:131)

### ISSUE THREAD

**Issue by vcarballo** [KronicDeth/intellij-elixir#3434]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.2.4)
Operating System: Mac OS X (13.5.2)

# Event

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///Users/vcarballo/workspace/query_membership_api/deps/aws; original:245896; found:-; File.exists()=false
</summary>

```
java.lang.RuntimeException: com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///Users/vcarballo/workspace/query_membership_api/deps/aws; original:245896; found:-; File.exists()=false
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:131)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:471)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:490)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:185)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:181)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:176)
	at org.elixir_lang.DepsWatcher$syncLibraries$2$1.run(DepsWatcher.kt:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///Users/vcarballo/workspace/query_membership_api/deps/aws; original:245896; found:-; File.exists()=false
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.handleInvalidDirectory(VirtualDirectoryImpl.java:194)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.getChildren(VirtualDirectoryImpl.java:396)
	at org.elixir_lang.DepsWatcher.syncLibrary(DepsWatcher.kt:292)
	at org.elixir_lang.DepsWatcher.syncLibrary(DepsWatcher.kt:232)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:215)
	at org.elixir_lang.DepsWatcher.syncLibraries$lambda$15$lambda$14(DepsWatcher.kt:189)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:992)
	at org.elixir_lang.DepsWatcher.syncLibraries$lambda$15(DepsWatcher.kt:186)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:100)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
```

</details>

**Comment by sh41** [comment]
Same crash as #1815, and fixed by the same change. `DepsWatcher` read the children of a `deps/`
directory through a cached handle without checking it was still valid, so removing `deps/aws` while a
sync was in flight made the next read throw.

`f4e399504` replaced `DepsWatcher` and `Watcher` with a coroutine pipeline, `MixDepsSyncService`, which
checks a directory is still valid before reading its children and no longer recurses through
`invokeAndWait`. First released in 24.0.0 — well after the 16.0.0 you reported this against.

Closing as a duplicate of #1815 so the fix is recorded in one place; #1815 carries the fuller trace.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
