### ISSUE TITLE
com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: combine at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.newModule(ModifiableModuleModelBridgeImpl.kt:91)

### ISSUE THREAD

**Issue by tonylissick** [KronicDeth/intellij-elixir#3439]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.2.5)
Operating System: Mac OS X (14.0)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: combine
</summary>

```
com.intellij.openapi.module.ModuleWithNameAlreadyExists: Module already exists: combine
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.newModule(ModifiableModuleModelBridgeImpl.kt:91)
	at org.elixir_lang.mix.Project.createModuleForOtpApp(Project.kt:110)
	at org.elixir_lang.mix.Project.createModulesForOtpApps(Project.kt:79)
	at org.elixir_lang.mix.project._import.Builder.commit(Builder.kt:107)
	at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:50)
	at com.intellij.projectImport.ProjectOpenProcessorBase$importToProject$2.invokeSuspend(ProjectOpenProcessorBase.kt:204)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
```

</details>

**Comment by sh41** [comment]
Fixed. This crash came from opening an umbrella project whose root directory and one of its `apps/`
children declare the same `app:` — each OTP app's `.iml` was named after the app, so both `combine`
apps resolved to one path and the second `newModule` call threw.

`fc3c45133` disambiguates the module names first — the root app keeps its plain name, the others get a
suffix from their path relative to it. First released in v23.0.5.

Closing as a duplicate of #2003, which describes the same collision and is where the fix is recorded.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
