### ISSUE TITLE
java.lang.NullPointerException at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$virtualFile$1.invoke(PlatformProjectOpenProcessor.kt:285)

### ISSUE THREAD

**Issue by Shakarim** [KronicDeth/intellij-elixir#3444]
# System

Plugin Version: 16.0.0
Application: RubyMine (2023.2.5)
Operating System: Linux (5.15.0-88-generic)

# Event

### Stacktrace

<details>

<summary>
java.lang.NullPointerException
</summary>

```
java.lang.NullPointerException
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$virtualFile$1.invoke(PlatformProjectOpenProcessor.kt:285)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$virtualFile$1.invoke(PlatformProjectOpenProcessor.kt:284)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion.runDirectoryProjectConfigurators(PlatformProjectOpenProcessor.kt:284)
	at org.elixir_lang.mix.project.DirectoryConfigurator.newProject(DirectoryConfigurator.kt:128)
	at org.elixir_lang.mix.project.DirectoryConfigurator.configureDescendantOtpApp(DirectoryConfigurator.kt:84)
	at org.elixir_lang.mix.project.DirectoryConfigurator.access$configureDescendantOtpApp(DirectoryConfigurator.kt:35)
	at org.elixir_lang.mix.project.DirectoryConfigurator$configureProject$2$1.invokeSuspend(DirectoryConfigurator.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.elixir_lang.mix.project.DirectoryConfigurator.configureProject(DirectoryConfigurator.kt:54)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$3$1.invoke(PlatformProjectOpenProcessor.kt:299)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$3$1.invoke(PlatformProjectOpenProcessor.kt:298)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$runDirectoryProjectConfigurators$3.invokeSuspend(PlatformProjectOpenProcessor.kt:298)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
```

</details>

**Comment by sh41** [comment]
Thanks for the report, and sorry it sat this long.

This one is ours, not the platform's. In IDEs without module support (RubyMine, WebStorm and the like) the plugin's `DirectoryConfigurator` scans the directory you opened for `mix.exs` files, and for each OTP app *below* the root it creates a separate IDE project and calls back into the platform's `runDirectoryProjectConfigurators` to configure it. That platform method asserts that the directory it is given resolves to a `VirtualFile` and throws this `NullPointerException` when it does not — so the plugin is what put a path in front of it that the VFS could not resolve.

The common route into that loop was closed in v19.0.1: opening a directory that contains more than one OTP app now stops with an "Umbrella App detected" notification instead of walking the apps, so if you opened the umbrella directory directly, this crash cannot happen on a current version.

It is not fully closed, though. That guard only applies when the project was *opened*; when the project is *created* through the IDE's New Project flow the loop still runs, so the same call is still reachable today. That is why this issue stays open rather than being closed as fixed. Your report has no reproduction details attached, so I cannot tell which of the two routes you hit.

If you still see this on a recent version, the useful detail is how the project was created — opened an existing directory, or created through New Project — and roughly how the umbrella's apps are laid out.

Related: #3697 fails at this same nested call with a different symptom.

---

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
