### ISSUE TITLE
Don't know how to find reference variables in binding at org.elixir_lang.ecto.Query.executeOnBinding$Elixir(Query.kt:403)

### ISSUE THREAD

**Issue by JamesFerguson** [KronicDeth/intellij-elixir#3447]
# System

Plugin Version: 14.0.1
Application: RubyMine (2022.3.2)
Operating System: Mac OS X (13.6)

# Event

### Element

```
%{
                   "name" => "test",
                   "deleted_at" => nil,
                   "students_ids" => ["1", "2"],
                   "teachers_ids" => ["1", "4"]
                 }
```

From: `/Users/james.ferguson/Blake/gravity/test/gravity/rostering/school_class_test.exs:879-884`

#### Context

```
        |> create_fixtures(Gravity.Db.Repo)

      assert {:ok, school_class} =
               SchoolClass.update(
                 school_class,
                 %{
                   "name" => "test",
                   "deleted_at" => nil,
                   "students_ids" => ["1", "2"],
                   "teachers_ids" => ["1", "4"]
                 },
                 %{"check_teacher_trials" => "false"}
               )

      assert %{deleted_at: nil} = school_class

```

From: `/Users/james.ferguson/Blake/gravity/test/gravity/rostering/school_class_test.exs:874-889`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMapOperationImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to find reference variables in binding
</summary>

```
java.lang.Throwable: Don't know how to find reference variables in binding
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.ecto.Query.executeOnBinding$Elixir(Query.kt:403)
	at org.elixir_lang.ecto.Query.executeOnBinding$Elixir(Query.kt:334)
	at org.elixir_lang.ecto.QueryBindingExpr.walk(Query.kt:41)
	at org.elixir_lang.psi.NameArityRangeWalker.walk(NameArityRangeWalker.kt:29)
	at org.elixir_lang.psi.ModuleWalker.walkChild(ModuleWalker.kt:23)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:253)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:65)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:173)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.processDeclarations(ElixirMatchedQualifiedParenthesesCallImpl.java:157)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveInScope(MultiResolve.kt:133)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveResultList(MultiResolve.kt:116)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:122)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:103)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:89)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:304)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
```

</details>

**Comment by sh41** [comment]
Still live on `main`, and keeping this open as the canonical for it.

`Ecto.Query.executeOnBinding` matches nine PSI shapes and `ElixirMapOperation` — the class named in your report — is not one of them, so the map falls through to the branch that files this report. Its sibling `executeOnSelectExpression` was taught that shape in d74cf24e85c in March 2023; `executeOnBinding` was not, and its catch-all has been byte-identical since the function was written in April 2021. Nothing is broken for you as a result: the walk returns and carries on, so the report is noise rather than damage.

#3506 reported the same call site two months after you did and was closed by its own reporter without a fix, so this is the surviving tracker.

There is a second cause behind your report specifically, and it is the more consequential one. `SchoolClass.update/3` is a context function, not an Ecto query — it reaches the Ecto walker at all because qualified-call resolution treats a module's `import` directives as part of what that module exports. A context that does `import Ecto.Query, warn: false` therefore makes every 2- or 3-arity `update`, `select`, `where`, `preload` … call on it look like the `Ecto.Query` macro of the same name. Filed separately as #3989, with a failing test.

#3985 tracks this whole family and asks what these `when`s should do by default with a shape they do not model, rather than adding one arm per report. This issue is attached to it.

> This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
