### ISSUE TITLE
java.lang.IllegalMonitorStateException: current thread is not owner at java.base/java.lang.Object.notify(Native Method)

### ISSUE THREAD

**Issue by Petarj123** [KronicDeth/intellij-elixir#3450]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Community Edition (2023.2.4)
Operating System: Linux (6.5.11-300.fc39.x86_64)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalMonitorStateException: current thread is not owner
</summary>

```
java.lang.IllegalMonitorStateException: current thread is not owner
	at java.base/java.lang.Object.notify(Native Method)
	at org.elixir_lang.jps.HomePath.eachEbinPath(HomePath.java:50)
	at org.elixir_lang.sdk.Type.addCodePaths(Type.java:22)
	at org.elixir_lang.sdk.elixir.Type$Companion.configureSdkPaths(Type.kt:302)
	at org.elixir_lang.sdk.elixir.Type$Companion.access$configureSdkPaths(Type.kt:232)
	at org.elixir_lang.sdk.elixir.Type.setupSdkPaths(Type.kt:168)
	at com.intellij.openapi.projectRoots.SdkType.setupSdkPaths(SdkType.java:132)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.setupSdk(ProjectSdksModel.java:502)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$2.lambda$actionPerformed$0(ProjectSdksModel.java:413)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.lambda$createSdkOfType$1(DependentSdkType.java:77)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.lambda$selectSdkHome$7(SdkConfigurationUtil.java:298)
	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:138)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:102)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:296)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:274)
```

</details>

**Comment by sh41** [comment]
Same crash as #3374: a bare `.notify()` on a `com.intellij.notification.Notification` bound to the inherited `Object.notify()`, which throws because nothing holds that object's monitor. It fired whenever the SDK home being configured had no `lib` directory.

Fixed in v23.0.2 by 7498afd035, which rewrote the file in Kotlin — where the zero-argument call is not expressible, so the compiler forced the `Project` argument. The full diagnosis is on #3374.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
