### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:66)

### ISSUE THREAD

**Issue by Frid-Yuandu** [KronicDeth/intellij-elixir#3451]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Community Edition (2023.2.5)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
</summary>

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:66)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:859)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:807)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:369)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:170)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.psi.__module__.PsiScopeProcessor.execute(PsiScopeProcessor.kt:41)
	at org.elixir_lang.psi.__module__.PsiScopeProcessor.execute(PsiScopeProcessor.kt:24)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1271)
	at org.elixir_lang.psi.__module__.Resolver.resolve(Resolver.kt:18)
	at org.elixir_lang.psi.__module__.Resolver.resolve(Resolver.kt:13)
	at org.elixir_lang.psi.__module__.Resolver.resolve(Resolver.kt:11)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at org.elixir_lang.psi.__module__.ResolveWithCachingComputable.compute(Reference.kt:46)
	at org.elixir_lang.psi.__module__.ResolveWithCachingComputable.compute(Reference.kt:40)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at org.elixir_lang.psi.__module__.Reference.multiResolve(Reference.kt:30)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:360)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:299)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:320)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:286)
```

</details>

### `indexingStart.trace`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by sh41** [comment]
Still open, and still a real defect — but you will not see this crash any more, and the two facts are less connected than they look.

The trace bottoms out in `org.elixir_lang.psi.__module__.PsiScopeProcessor.execute`, which queries the stub index through `StubIndex.processElements`. That call has no `DumbService` guard. It is reached from the `Callable` annotator, which is registered `DumbAware` — so the platform deliberately runs it while indexing is still in progress — by way of `safeMultiResolve`, which catches only `StackOverflowError`. Nothing in that chain checks whether the index is ready, so a resolve that lands during dumb mode queries an index that is not there yet, and `IndexNotReadyException` is exactly what the platform raises in that situation.

That gap is still in `main` today. It is also a shape this codebase has fixed before, elsewhere: six sibling files in the resolver and scope layers — among them `reference/resolver/Module.kt`, `psi/scope/module/MultiResolve.kt` and `psi/scope/variable/MultiResolve.kt` — guard their index reads with `DumbService.isDumb`. The first of those landed in 7bfa70e0063a9cefa963aa6ea3c493dd26c6d59b, "Protect from IndexNotReady in resolver.Module.multiResolveProject", in June 2021. It never touched `PsiScopeProcessor`, and neither did anything since.

What has changed is on the platform's side, not the plugin's. In October 2024 IntelliJ added a top-level `catch (IndexNotReadyException)` around the highlighting pass in `PassExecutorService` (ba1c2052374dffa77ddee64d1a993c645ab47e16), which treats the pass as cancelled instead of logging a fatal error. That commit is present in every IDE build the plugin currently supports. So this specific report — the annotator path, surfacing as an IDE fatal error — can no longer happen, because the platform now absorbs it silently. **The plugin's missing guard was not fixed; the exception it throws simply stopped being reported.**

Keeping this open for that reason. The unguarded index read is still there, and the platform's catch is narrower than the defect: the same `__MODULE__` reference is what `CallImpl` hands back as an ordinary `PsiReference`, so go-to-declaration, Find Usages and completion reach the same code without going through the highlighting pass that catch protects. I have not established that any of those produces a visible failure today, only that they are not covered by the thing that made this report stop arriving.

If you are on a current release and hit anything that looks like this — a `__MODULE__` failing to resolve, or highlighting quietly giving up shortly after the project opens — that is worth a new report, because the silent-cancellation path leaves no stack trace to attach.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
