### ISSUE TITLE
(Mix) Cannot use application name "elixir" because it is already used

### ISSUE THREAD

**Issue by hu1buerger** [KronicDeth/intellij-elixir#3459]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.2.2)
Operating System: Mac OS X (14.1)

# Event

### Stacktrace

<details>

<summary>
java.io.IOException: mix new failed: ** (Mix) Cannot use application name "elixir" because it is already used by Erlang/OTP or Elixir. The application name is inferred from the path, if you'd like to explicitly name the application then use the "--app APP" option
</summary>

```
java.io.IOException: mix new failed: ** (Mix) Cannot use application name "elixir" because it is already used by Erlang/OTP or Elixir. The application name is inferred from the path, if you'd like to explicitly name the application then use the "--app APP" option

	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:172)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.setupProject(AbstractNewProjectWizardMultiStepBase.kt:75)
	at com.intellij.ide.wizard.NewProjectWizardLanguageStep.setupProject(NewProjectWizardLanguageStep.kt:93)
	at com.intellij.ide.wizard.NewProjectWizardChainStep.setupProject(NewProjectWizardChainStep.kt:44)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$commitModule$1.invoke(AbstractNewProjectWizardBuilder.kt:44)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$commitModule$1.invoke(AbstractNewProjectWizardBuilder.kt:43)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.detectCreatedModule(AbstractNewProjectWizardBuilder.kt:80)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.detectCreatedModule(AbstractNewProjectWizardBuilder.kt:68)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.access$detectCreatedModule(AbstractNewProjectWizardBuilder.kt:65)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder.commitModule(AbstractNewProjectWizardBuilder.kt:43)
```

</details>

**Comment by allenwyma** [comment]
this shouldn't be an issue of the plugin: it's an issue of the naming. For an elixir/mix application, there's already an application called elixir, so you'll need to choose another name

**Comment by sh41** [comment]
Confirmed, and it is the wizard's bug rather than just a naming mistake.

`mix new` checks the application name twice: once for character syntax, and once against the names already used by Erlang/OTP or Elixir — `elixir`, `kernel`, `mix`, `logger`, `erts` and so on. The wizard's `--app` validation ports the first check, down to the wording of its error message, and stops there. `elixir` passes it, so the wizard goes ahead and runs `mix new`, and Mix rejects it. The earlier comment here is right that the name is the problem; the wizard should be the one telling you that, before it runs Mix.

It matters more than a late error message, because the wizard deletes the empty project directory it created before invoking Mix — so when Mix refuses the name, you are left with nothing.

Leaving this open. The fix is to check the name against Mix's reserved list in the same `--app` validation that already checks the syntax.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
