### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action or Event Dispatch Thread (EDT) only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details, Current thread: Thread[ApplicationImpl pooled thread 222,4,main] 1429128031 (EventQueue.isDispatchThread()=false), SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 203066993 at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)

### ISSUE THREAD

**Issue by FedericoAlcantara** [KronicDeth/intellij-elixir#3460]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Community Edition (2023.2.5)
Operating System: Linux (6.2.0-36-generic)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action or Event Dispatch Thread (EDT) only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
</summary>

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action or Event Dispatch Thread (EDT) only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 222,4,main] 1429128031 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 203066993
	at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1038)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:421)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:217)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:206)
	at org.elixir_lang.psi.impl.QuotableImpl.quote(QuotableImpl.kt:990)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quote(ElixirPsiImplUtil.java:1370)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedParenthesesCallImpl.quote(ElixirUnmatchedUnqualifiedParenthesesCallImpl.java:151)
	at org.elixir_lang.mix.project.OtpAppKt$appList$7.invoke(OtpApp.kt:64)
	at org.elixir_lang.mix.project.OtpAppKt$appList$7.invoke(OtpApp.kt:63)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at org.elixir_lang.mix.project.OtpAppKt.appList(OtpApp.kt:68)
	at org.elixir_lang.mix.project.OtpAppKt.app(OtpApp.kt:32)
	at org.elixir_lang.mix.project.OtpAppKt.app(OtpApp.kt:25)
	at org.elixir_lang.mix.project.OtpAppKt.access$app(OtpApp.kt:1)
	at org.elixir_lang.mix.project.OtpApp.<init>(OtpApp.kt:92)
	at org.elixir_lang.mix.Project.createImportedOtpApp(Project.kt:153)
	at org.elixir_lang.mix.Project.access$createImportedOtpApp(Project.kt:22)
	at org.elixir_lang.mix.Project$findOtpApps$1.visitFile(Project.kt:54)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:106)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at org.elixir_lang.mix.Project.findOtpApps(Project.kt:42)
	at org.elixir_lang.mix.project.DirectoryConfigurator$configureProject$1.run(DirectoryConfigurator.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
```

</details>

**Comment by sh41** [comment]
Fixed in v23.8.2.

`OtpApp` walked the `mix.exs` PSI tree — the traversal that ends in `QuotableImpl.quote` — outside the read action that had built the `ElixirFile`. `DirectoryConfigurator.configureProject` scans for OTP apps on a background thread, so that walk ran with no read lock held and the platform's read-access assertion fired, exactly as in your trace.

Commit 1254fd7, "fix: wrap PSI traversal in read action in OtpApp", moves both the file construction and the traversal into a single `computeReadAction` block, so the tree is created and walked under the same lock. It first shipped in v23.8.2.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
