### ISSUE TITLE
java.lang.RuntimeException: java.io.IOException: Can't write to record[1577280]: it was deleted at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)

### ISSUE THREAD

**Issue by tom-dibble-powerschool** [KronicDeth/intellij-elixir#3465]
# System

Plugin Version: 16.0.0
Application: WebStorm (2023.2.5)
Operating System: Mac OS X (14.1)

# Event
During startup

## Exception
java.lang.RuntimeException: java.io.IOException: Can't write to record[1577280]: it was deleted at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: java.io.IOException: Can't write to record[1577280]: it was deleted
</summary>

```
java.lang.RuntimeException: java.io.IOException: Can't write to record[1577280]: it was deleted
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.lambda$static$0(FSRecordsImpl.java:96)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.handleError(FSRecordsImpl.java:1172)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.createRecord(FSRecordsImpl.java:353)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.createRecord(FSRecords.java:169)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.makeChildRecord(PersistentFSImpl.java:1968)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$persistAllChildren$2(PersistentFSImpl.java:288)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$persistAllChildren$3(PersistentFSImpl.java:288)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.update(FSRecordsImpl.java:531)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.update(FSRecords.java:256)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.persistAllChildren(PersistentFSImpl.java:258)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.listAll(PersistentFSImpl.java:321)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.loadAllChildren(VirtualDirectoryImpl.java:408)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.getChildren(VirtualDirectoryImpl.java:401)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:307)
	at org.elixir_lang.mix.Project.findOtpApps(Project.kt:42)
	at org.elixir_lang.mix.project.DirectoryConfigurator$configureProject$1.run(DirectoryConfigurator.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
```

</details>

**Comment by sh41** [comment]
This is a platform bug that named the plugin, not a plugin bug — the same one as #3549, which now carries the full explanation.

The throw is inside the IDE's own persistent virtual-file-system record store: `FSRecordsImpl.createRecord` fails because the record it was about to write is already marked deleted, reached through `PersistentFSImpl.persistAllChildren` and `VirtualDirectoryImpl.loadAllChildren`. Everything from `VirtualDirectoryImpl.getChildren` downwards is `com.intellij.openapi.vfs.newvfs.persistent` — storage shared by every project and every language, owned and rebuilt by the platform.

The only plugin frames are `Project.findOtpApps` and `DirectoryConfigurator.configureProject`, which walk the project root recursively on project open in small IDEs like WebStorm, looking for Mix apps. Listing directories is all they do; the plugin does not own or write the VFS record that failed, and its own stub indices are not reached at all, because this fails before any file's content is read.

#3549 is the same call site failing in the same store the other way round — reading an attribute record rather than writing a child record — on the storage engine that replaced the one here, which is why it is the one left carrying the diagnosis. The remedy is the same for both: **File | Invalidate Caches / Restart**, which discards and rebuilds the VFS record store.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
