### ISSUE TITLE
After use of use keyword, this happens, intellisense stops working.

### ISSUE THREAD

**Issue by Petarj123** [KronicDeth/intellij-elixir#3467]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Community Edition (2023.2.5)
Operating System: Linux (6.6.2-201.fc39.x86_64)

# What I was doing

After use of use keyword, this happens

# Event

### Stacktrace

<details>

<summary>
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
</summary>

```
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  2 != 3
  which is length of CachedValue dependencies: [UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL] and [PSI_MOD_COUNT_OPTIMIZATION, UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
  where values are  org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null) and org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null)

Recomputation gives com.intellij.util.CachedValueBase$Data@16164998 which is equivalent to 'fresh' [Plugin: org.elixir_lang]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:97)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:82)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:250)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:21)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at org.elixir_lang.psi.__MODULE__.reference(__MODULE__.kt:18)
	at org.elixir_lang.psi.impl.call.CallImplKt.maybeModularNameToModulars(CallImpl.kt:332)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:204)
	at org.elixir_lang.psi.Using.treeWalkUpFromLastChildCall(Using.kt:67)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:44)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:27)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:39)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:250)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:65)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:440)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:439)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:300)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:443)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:417)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:265)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:655)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1271)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveInScope(MultiResolve.kt:133)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveResultList(MultiResolve.kt:116)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:122)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:103)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:89)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.reference.Callable.resolve(Callable.kt:112)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:176)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:164)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:209)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:253)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:232)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:297)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:175)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:136)
```

</details>

**Comment by sh41** [comment]
Same defect as #3593: `__MODULE__.reference` cached its reference without the `use` call in the key, so two computations of one cache entry disagreed on their dependencies. Fixed in #3977.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
