### ISSUE TITLE
               , ### Element, , ```, @type non_neg_integer :: non_neg_integer(), ```, , From: `/Users/najam/.local/share/rtx/installs/erlang/25.2/lib/erts-13.1.3/ebin/erlang.beam:116`, , #### Context, , ```, ,   @type no_return :: none(), ,   @type node :: atom(), ,   @type non_neg_integer :: non_neg_integer(), ,   @type none :: none(), ,   @type nonempty_binary :: binary(8, 8), , ```, , From: `/Users/najam/.local/share/rtx/installs/erlang/25.2/lib/erts-13.1.3/ebin/erlang.beam:111-121`,             , ### Element Class Name, , ```, org.elixir_lang.beam.psi.impl.TypeDefinitionImpl, ```,    ,    java.lang.Throwable: Don't know how to fetch docs at org.elixir_lang.documentation.BeamDocsHelper.fetchDocs(BeamDocsHelper.kt:51)

### ISSUE THREAD

**Issue by NajamSafar** [KronicDeth/intellij-elixir#3468]
# System

Plugin Version: 16.0.0-pre+20231103194649
Application: IntelliJ IDEA Ultimate Edition (2023.2.5)
Operating System: Mac OS X (13.5.2)

# Event

## Message

*** exception class was changed or removed

### Stacktrace

<details>

<summary>
               
</summary>

```
               
### Element

```
@type non_neg_integer :: non_neg_integer()
```

From: `/Users/najam/.local/share/rtx/installs/erlang/25.2/lib/erts-13.1.3/ebin/erlang.beam:116`

#### Context

```

  @type no_return :: none()

  @type node :: atom()

  @type non_neg_integer :: non_neg_integer()

  @type none :: none()

  @type nonempty_binary :: binary(8, 8)

```

From: `/Users/najam/.local/share/rtx/installs/erlang/25.2/lib/erts-13.1.3/ebin/erlang.beam:111-121`
            
### Element Class Name

```
org.elixir_lang.beam.psi.impl.TypeDefinitionImpl
```
   
   java.lang.Throwable: Don't know how to fetch docs
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.BeamDocsHelper.fetchDocs(BeamDocsHelper.kt:51)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:497)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:41)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:135)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDocHtml(PsiElementDocumentationTarget.kt:112)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:97)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.doComputeDocumentation(PsiElementDocumentationTarget.kt:84)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.access$doComputeDocumentation(PsiElementDocumentationTarget.kt:28)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget$computeDocumentation$1.invoke(PsiElementDocumentationTarget.kt:78)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget$computeDocumentation$1.invoke(PsiElementDocumentationTarget.kt:77)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator$lambda$1(coroutines.kt:386)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
```

</details>

**Comment by sh41** [comment]
Duplicate of #3324 — the same `TypeDefinitionImpl` reaching `BeamDocsHelper.fetchDocs`'s `else` branch when a builtin `@type` is hovered in a decompiled `erlang.beam`.

Still live: `TypeDefinition` is a sibling of `Module`, not a subtype, so it matches no arm of that `when` and never has. #3324 carries the diagnosis and stays open; both are tracked under #3985, which asks what these `when`s should do with a shape they do not model instead of adding one arm per report.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
