### ISSUE TITLE
Max opcode (178) exceeds expected max opcode (176).  Additional opcodes have been added to the end of https://github.com/erlang/otp/blob/master/lib/compiler/src/genop.tab. at org.elixir_lang.beam.chunk.Code$Companion.from(Code.kt:193)

### ISSUE THREAD

**Issue by pappel-ig** [KronicDeth/intellij-elixir#3471]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.2.5)
Operating System: Mac OS X (14.1.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Max opcode (178) exceeds expected max opcode (176).  Additional opcodes have been added to the end of https://github.com/erlang/otp/blob/master/lib/compiler/src/genop.tab.
</summary>

```
java.lang.Throwable: Max opcode (178) exceeds expected max opcode (176).  Additional opcodes have been added to the end of https://github.com/erlang/otp/blob/master/lib/compiler/src/genop.tab.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at org.elixir_lang.beam.chunk.Code$Companion.from(Code.kt:193)
	at org.elixir_lang.beam.chunk.Code$Companion.from$default(Code.kt:171)
	at org.elixir_lang.beam.Beam.code(Beam.kt:83)
	at org.elixir_lang.beam.Cache$code$2.invoke(Cache.kt:11)
	at org.elixir_lang.beam.Cache$code$2.invoke(Cache.kt:11)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.elixir_lang.beam.Cache.getCode(Cache.kt:11)
	at org.elixir_lang.beam.assembly.Controls.computeDocumentText(Controls.kt:178)
	at org.elixir_lang.beam.assembly.Controls.<init>(Controls.kt:36)
	at org.elixir_lang.beam.chunk.code.Component.addChildren(Component.kt:31)
	at org.elixir_lang.beam.chunk.code.Component.ensureChildrenAdded(Component.kt:41)
	at org.elixir_lang.beam.chunk.code.Component.stateChanged(Component.kt:24)
	at com.intellij.ui.JBTabsPaneImpl.fireChanged(JBTabsPaneImpl.java:44)
	at com.intellij.ui.JBTabsPaneImpl$1.selectionChanged(JBTabsPaneImpl.java:35)
	at com.intellij.ui.tabs.impl.JBTabsImpl.fireSelectionChanged(JBTabsImpl.kt:1357)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.kt:1302)
	at com.intellij.ui.tabs.impl.JBTabsImpl.doSetSelected(JBTabsImpl.kt:1261)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.kt:1243)
	at com.intellij.ui.tabs.impl.TabLabel$1.mousePressed(TabLabel.java:93)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
```

</details>

**Comment by sh41** [comment]
Duplicate of #3105, and fixed in 24.0.0.

Same call site and same opcode: the BEAM `Code` chunk's opcode table stopped at 176, the last OTP 24 opcode, so `call_fun2` (178) from OTP 25 was unknown to it. Commit c9df46683 added opcodes 177–191 for OTP 25 through 29 plus the OTP 25 `TypedRegister` operand tag, and downgraded the max-opcode message from an error to a warning.

#3105 carries the full diagnosis and a reproducing `.beam`.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
