### ISSUE TITLE
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:,   2 != 3,   which is length of CachedValue dependencies: [UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL] and [PSI_MOD_COUNT_OPTIMIZATION, UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL],   where values are  org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null) and org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null), , Recomputation gives com.intellij.util.CachedValueBase$Data@36608e3c which is equivalent to 'fresh' [Plugin: org.elixir_lang] at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)

### ISSUE THREAD

**Issue by salseeg** [KronicDeth/intellij-elixir#3477]
# System

Plugin Version: 15.1.0
Application: WebStorm (2023.1.4)
Operating System: Mac OS X (13.3.1)

# Event

### Stacktrace

<details>

<summary>
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
</summary>

```
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  2 != 3
  which is length of CachedValue dependencies: [UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL] and [PSI_MOD_COUNT_OPTIMIZATION, UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
  where values are  org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null) and org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null)

Recomputation gives com.intellij.util.CachedValueBase$Data@36608e3c which is equivalent to 'fresh' [Plugin: org.elixir_lang]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:254)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at org.elixir_lang.psi.__MODULE__.reference(__MODULE__.kt:18)
	at org.elixir_lang.psi.impl.call.CallImplKt.maybeModularNameToModulars(CallImpl.kt:332)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:204)
	at org.elixir_lang.psi.Using.treeWalkUpFromLastChildCall(Using.kt:67)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:44)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:27)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:39)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:65)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:39)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:440)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:439)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:303)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:443)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:417)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:265)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:655)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1257)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:137)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:128)
	at org.elixir_lang.reference.resolver.Module.resolveInScope(Module.kt:83)
	at org.elixir_lang.reference.resolver.Module.resolveAll(Module.kt:78)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:72)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:35)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:31)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:23)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.reference.Module.resolve(Module.kt:38)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:176)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:164)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:209)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:253)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:232)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:297)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:175)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:136)
```

</details>

**Comment by sh41** [comment]
Same defect as #3593: `__MODULE__.reference` cached its reference without the `use` call in the key, so two computations of one cache entry disagreed on their dependencies. Fixed in #3977.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
