### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented at org.elixir_lang.psi.impl.PsiNamedElementImpl.setName(PsiNamedElementImpl.kt:68)

### ISSUE THREAD

**Issue by Holothuroid** [KronicDeth/intellij-elixir#3483]
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Community Edition (2021.3.3)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented
	at org.elixir_lang.psi.impl.PsiNamedElementImpl.setName(PsiNamedElementImpl.kt:68)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.setName(ElixirPsiImplUtil.java:1651)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.setName(ElixirAliasImpl.java:77)
```

**Comment by KronicDeth** [comment]
This is a really old version of the plugin that is no longer supported.
