### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details, Current thread: Thread[AWT-EventQueue-0,6,main] 1731415960 (EventQueue.isDispatchThread()=true), SystemEventQueueThread: (same) at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)

### ISSUE THREAD

**Issue by 0xtrou** [KronicDeth/intellij-elixir#3505]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.3.2)
Operating System: Mac OS X (14.2.1)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
</summary>

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[AWT-EventQueue-0,6,main] 1731415960 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1012)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:421)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:234)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:217)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:133)
	at org.elixir_lang.psi.Module.name(Module.kt:29)
	at org.elixir_lang.navigation.item_presentation.modular.Module$Companion.presentableText(Module.kt:51)
	at org.elixir_lang.navigation.item_presentation.modular.Module.getPresentableText(Module.kt:45)
	at com.intellij.ide.util.gotoByName.GotoFileCellRenderer.doCustomizeNonPsiElementLeftRenderer(GotoFileCellRenderer.java:118)
	at com.intellij.ide.actions.SearchEverywherePsiRenderer.customizeNonPsiElementLeftRenderer(SearchEverywherePsiRenderer.java:109)
	at com.intellij.ide.util.PsiElementListCellRenderer$LeftRenderer.customizeCellRenderer(PsiElementListCellRenderer.java:191)
	at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:45)
	at com.intellij.ide.util.PsiElementListCellRenderer.getListCellRendererComponent(PsiElementListCellRenderer.java:264)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper$WrapperRenderer.getListCellRendererComponent(PSIPresentationBgRendererWrapper.java:143)
	at com.intellij.ide.actions.searcheverywhere.SEResultsListFactory.getNonMoreElementRenderer(SEResultsListFactory.java:95)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:80)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
```

</details>

**Comment by sh41** [comment]
Duplicate of #3684 — the same crash from org.elixir_lang.navigation.item_presentation.modular.Module, via org.elixir_lang.psi.Module.name, painted by Search Everywhere on the EDT with no read action.

Fixed by IntelliJ Platform 2024.2, which moved presentation rendering for non-PSI navigation items onto a background thread inside a read action. All 34 reports of this crash were filed from 2023.3.x builds and none since; the plugin's minimum supported IDE is 2025.3. #3684 has the full reasoning, and the remaining contract gap in the plugin's own getters is tracked in #3995.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
