### ISSUE TITLE
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:,   3 != 2,   which is length of CachedValue dependencies: [PSI_MOD_COUNT_OPTIMIZATION, UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL] and [UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL],   where values are  org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null) and org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null), , Recomputation gives com.intellij.util.CachedValueBase$Data@65e7769b which is equivalent to 'fresh' [Plugin: org.elixir_lang] at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)

### ISSUE THREAD

**Issue by vincentopensourcetaiwan** [KronicDeth/intellij-elixir#3517]
# System

Plugin Version: 17.0.0
Application: RubyMine (2023.3.2)
Operating System: Mac OS X (12.7.2)

# Event

### Stacktrace

<details>

<summary>
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
</summary>

```
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  3 != 2
  which is length of CachedValue dependencies: [PSI_MOD_COUNT_OPTIMIZATION, UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL] and [UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
  where values are  org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null) and org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null)

Recomputation gives com.intellij.util.CachedValueBase$Data@65e7769b which is equivalent to 'fresh' [Plugin: org.elixir_lang]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:97)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:82)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:250)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:21)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at org.elixir_lang.psi.__MODULE__.reference(__MODULE__.kt:18)
	at org.elixir_lang.psi.impl.call.CallImplKt.maybeModularNameToModulars(CallImpl.kt:332)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:204)
	at org.elixir_lang.psi.Using.treeWalkUpFromLastChildCall(Using.kt:67)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:44)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:27)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:39)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:250)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:65)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:440)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:439)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:303)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:443)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:417)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:265)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:655)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1250)
	at org.elixir_lang.psi.scope.variable.Variants$Companion.lookupElementList(Variants.kt:46)
	at org.elixir_lang.reference.Callable.getVariants(Callable.kt:78)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:222)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:122)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:63)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:80)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:141)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:124)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:78)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:48)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
```

</details>

**Comment by sh41** [comment]
Same defect as #3593: `__MODULE__.reference` cached its reference without the `use` call in the key, so two computations of one cache entry disagreed on their dependencies. Fixed in #3977.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
