### ISSUE TITLE
Erlang Abst  is unknown at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.error(AbstractCode.kt:91)

### ISSUE THREAD

**Issue by AlexsandroBezerra** [KronicDeth/intellij-elixir#3535]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.3.2)
Operating System: Mac OS X (14.2.1)

# Event

### Term

{mc,{215,11},{map_field_assoc,{215,17},{var,{215,13},'Src'},{op,{215,24},'-',{var,{215,20},'Dst'},{var,{215,26},'Trim'}}},[{generate,{215,57},{tuple,{215,34},[{atom,{215,35},move},{tuple,{215,40},[{atom,{215,41},y},{var,{215,43},'Src'}]},{tuple,{215,48},[{atom,{215,49},y},{var,{215,51},'Dst'}]}]},{var,{215,60},'Moves'}}]}

### Stacktrace

<details>

<summary>
java.lang.Throwable: Erlang Abst  is unknown
</summary>

```
java.lang.Throwable: Erlang Abst  is unknown
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:70)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.error(AbstractCode.kt:91)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.unknown(AbstractCode.kt:88)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.MacroStringDeclaredScope$Companion.unknown(MacroStringDeclaredScope.kt:52)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:82)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toString(AbstractCode.kt:46)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Match.rightString(Match.kt:29)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Match.toMacroStringDeclaredScope(Match.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Match.ifToMacroStringDeclaredScope(Match.kt:10)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.AbstractCode.toMacroStringDeclaredScope(AbstractCode.kt:67)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.comprehension.Qualifier.toMacroStringDeclaredScope(Qualifier.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:79)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:47)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Sequence.toMacroStringDeclaredScope(Sequence.kt:93)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.clause.Body.toMacroStringDeclaredScope(Body.kt:14)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Clause.bodyString(Clause.kt:15)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.function.Clause.toMacroString(Clause.kt:20)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function$toMacroString$1.invoke(Function.kt:34)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function$toMacroString$1.invoke(Function.kt:34)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function.toMacroString(Function.kt:34)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:461)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:444)
	at org.elixir_lang.beam.Decompiler$Companion.appendMacroNameArity(Decompiler.kt:433)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:296)
	at org.elixir_lang.beam.Decompiler$Companion.appendCallDefinitions(Decompiler.kt:238)
	at org.elixir_lang.beam.Decompiler$Companion.decompiled(Decompiler.kt:76)
	at org.elixir_lang.beam.Decompiler$Companion.access$decompiled(Decompiler.kt:33)
	at org.elixir_lang.beam.Decompiler.decompile(Decompiler.kt:31)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:478)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.loadText(FileDocumentManagerBase.java:105)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:61)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:373)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:147)
	at org.elixir_lang.psi.scope.atom.Variants.projectLookupElementStream(Variants.java:49)
	at org.elixir_lang.psi.scope.atom.Variants.lookupElementList(Variants.java:24)
	at org.elixir_lang.reference.Atom.getVariants(Atom.java:25)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:222)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:122)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:63)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:80)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:141)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:124)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:78)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:48)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
```

</details>

**Comment by sh41** [comment]
Fixed. The term in your report is an `mc` — a map comprehension, a form Erlang/OTP 26 added to the abstract code. The decompiler's form table did not have it, so it fell through to the unknown-form branch that produced this report.

Two commits were needed:

- `20691ea0d` — *feat: handle OTP 26 map comprehension AST nodes in BEAM decompiler* (#3852) added the `mc` arm, so the form is recognised instead of reported. First stable release: **24.0.0**.
- `61c18295c` — *fix(decompiler): render zip and map comprehensions* (#3889) corrected what it then produces. Before it, a map comprehension decompiled to a `key => value` body outside a `%{}`, which is not valid Elixir. First stable release: **v24.0.1**.

So 24.0.0 stops the report you saw, and v24.0.1 is the one to be on for correct output — recognising the form without rendering it properly would only have been half of it.

Separately and earlier, `2ff897036` (*fix: downgrade non-critical decompiler/doc errors from error to warn*, v23.8.2) made this site log a warning rather than raise a reportable error. That changed only what you would have been shown; it did not model the form. The two commits above are what actually handle it.

Both steps are covered by tests: `ComprehensionTest` asserts an `mc` form is recognised and renders a `for`, with a companion test proving an unrecognised tag still falls through, and `DecompilerTest` decompiles `map_comprehension` and `zip_map_comprehension` `.beam` fixtures end to end.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
