### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot check provider org.elixir_lang.beam.file_editor.Provider [Plugin: org.elixir_lang] at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:111)

### ISSUE THREAD

**Issue by Tiikara** [KronicDeth/intellij-elixir#3543]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.3.3)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
com.intellij.diagnostic.PluginException: Cannot check provider org.elixir_lang.beam.file_editor.Provider [Plugin: org.elixir_lang]
</summary>

```
com.intellij.diagnostic.PluginException: Cannot check provider org.elixir_lang.beam.file_editor.Provider [Plugin: org.elixir_lang]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:191)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:501)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:109)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

</details>

**Comment by sh41** [comment]
The `Caused by` here is `kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms` — nothing in the plugin threw. "Cannot check provider" is the platform's own log line, written by `FileEditorProviderManagerImpl` for whichever registered `fileEditorProvider` extension's 30-second `withTimeout` around its `accept()` check expires. This plugin's provider is named because its coroutine genuinely was the one still pending, but the stack shows only the timer firing, not what was stalled — so it doesn't say what took the 30 seconds.

Reading the platform source at the build you were on (2023.3.3), there are at least three candidates, and none of them is logic this plugin owns:

- The wait for IntelliJ's read lock. `accept()` doesn't override `acceptRequiresReadAction`, whose default is `true`, so it runs inside a read action and the wait counts against the 30 seconds. Any provider leaving that default stalls the same way.
- First-time classloading of the provider, which on that build happens inside the timeout window.
- Resolving the file's type, which `accept()` does first. The platform's own comment on this loop names exactly that hazard — a provider can block getting the file type, for instance during TextMate bundle initialization.

I did check the one thing that would have made this ours: whether `accept()` reaches the project file index through its scratch-file mapping lookup. It doesn't. `ScratchFileServiceImpl` constructs that mapping without a project, and `PerFileMappingsBase` short-circuits on the null project before the index check is ever evaluated — same on 2023.3.3 and on current platform sources.

So there was a real 30-second stall behind this, but a single report with no thread dump can't say where, and nothing since has reproduced it. Closing on that basis. If it happens again, a thread dump from while the IDE was unresponsive would pin it immediately — IDEA writes those to `threadDumps-*` folders in its log directory whenever it detects a freeze. Please reopen with one attached.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
