### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/joedoe/git/eia/kata/_build/test/lib/kata/ebin/Elixir.Pilecubes.beam (invalid) is invalid, invalidated at: no info at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)

### ISSUE THREAD

**Issue by joedoehh** [KronicDeth/intellij-elixir#3548]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Community Edition (2023.3.4)
Operating System: Mac OS X (14.2.1)

# Event

### Stacktrace

<details>

<summary>
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/joedoe/git/eia/kata/_build/test/lib/kata/ebin/Elixir.Pilecubes.beam (invalid) is invalid
</summary>

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///Users/joedoe/git/eia/kata/_build/test/lib/kata/ebin/Elixir.Pilecubes.beam (invalid) is invalid
invalidated at: no info
	at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)
	at org.jetbrains.plugins.scala.compiler.highlighting.CompilerHighlightingPsiChangeListener.childRemoved(CompilerHighlightingPsiChangeListener.scala:17)
	at com.intellij.psi.impl.PsiManagerImpl.notifyPsiTreeChangeListener(PsiManagerImpl.java:402)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:357)
	at com.intellij.psi.impl.PsiManagerImpl.childRemoved(PsiManagerImpl.java:279)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$filesDeleted$2(PsiVFSListener.java:226)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:975)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.filesDeleted(PsiVFSListener.java:222)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$fireForGrouped$9(PsiVFSListener.java:763)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:535)
```

</details>

**Comment by sh41** [comment]
Same crash as #3546, which you filed two days earlier — the Scala plugin's `CompilerHighlightingPsiChangeListener` calling `getContainingFile()` on a `.beam` your build had just deleted under `_build/test`, without checking `isValid()` first. Only the module name differs.

The full explanation is on #2460, and I have replied on #3546 too. Closing this as a duplicate.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
