### ISSUE TITLE
java.lang.IllegalArgumentException: recordId(4799459) is not yet allocated: allocated ids are all < 4740649 at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageHelper.checkRecordIdExists(StreamlinedBlobStorageHelper.java:398)

### ISSUE THREAD

**Issue by chrisidakwo** [KronicDeth/intellij-elixir#3549]
# System

Plugin Version: 17.0.0
Application: PhpStorm (2023.3.2)
Operating System: Mac OS X (13.4)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalArgumentException: recordId(4799459) is not yet allocated: allocated ids are all < 4740649
</summary>

```
java.lang.IllegalArgumentException: recordId(4799459) is not yet allocated: allocated ids are all < 4740649
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageHelper.checkRecordIdExists(StreamlinedBlobStorageHelper.java:398)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageOverMMappedFile.readRecord(StreamlinedBlobStorageOverMMappedFile.java:200)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageHelper.readRecord(StreamlinedBlobStorageHelper.java:216)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttributeValue(AttributesStorageOverBlobStorage.java:1026)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttributeRaw(AttributesStorageOverBlobStorage.java:134)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSAttributeAccessor.readAttributeRaw(PersistentFSAttributeAccessor.java:72)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSTreeRawAccessor.mayHaveChildren(PersistentFSTreeRawAccessor.java:118)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.mayHaveChildren(FSRecordsImpl.java:662)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.mayHaveChildren(PersistentFSImpl.java:2322)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.loadAllChildren(VirtualDirectoryImpl.java:456)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.getChildren(VirtualDirectoryImpl.java:404)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:313)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:334)
	at org.elixir_lang.mix.Project.findOtpApps(Project.kt:42)
	at org.elixir_lang.mix.project.DirectoryConfigurator$configureProject$1.run(DirectoryConfigurator.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:518)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
```

</details>

**Comment by sh41** [comment]
This is a platform bug that named the plugin, not a plugin bug.

The throw is inside the IDE's own persistent virtual-file-system record store: `StreamlinedBlobStorageHelper.checkRecordIdExists` rejects an attribute record id the store itself says it never allocated, reached through `AttributesStorageOverBlobStorage`, `PersistentFSTreeRawAccessor.mayHaveChildren` and `VirtualDirectoryImpl.loadAllChildren`. Everything from `VirtualDirectoryImpl.getChildren` downwards is `com.intellij.openapi.vfs.newvfs.persistent` — storage shared by every project and every language, owned and rebuilt by the platform.

The only plugin frames are `Project.findOtpApps` and `DirectoryConfigurator.configureProject`. In small IDEs like PhpStorm, WebStorm and RubyMine, which have no Elixir project wizard, the plugin's directory configurator runs on project open and walks the project root recursively with `VfsUtilCore.visitChildrenRecursively` looking for Mix apps. Listing directories is all it does. It does not allocate, write or own the record that failed, and nothing in `org.elixir_lang` decides whether that read succeeds. A recursive walk touches much more of the record store, much faster, than incidental file access does, so it runs into an existing inconsistency sooner — but it cannot create one.

The plugin's own indices are not involved either. Elixir's stub indices are built from parsed file content, and this fails while establishing a directory entry's file identity — a stage that runs before any file's content is read.

I can't point you at an IDE build that fixes it. JetBrains have been working this exact subsystem — commit `2339b53294ced8d310b0608e381b7f7886edc737` (IJPL-199690, August 2025) moves the directory listing out from under the directory-data lock for this class of inconsistency — but its own comment says the path that produces it is still not understood, and the current platform still throws both this condition and the closely related one in #3465.

What does help is **File | Invalidate Caches / Restart**, which discards and rebuilds the VFS record store. This is on-disk state left inconsistent by something like an unclean shutdown, a force-kill or a disk fault, and rebuilding it is the platform's own recovery for it.

#3465 is the same call site failing in the same store the other way round — writing a new child record rather than reading an attribute — on the older storage engine that the one here replaced. Closing both: there is nothing here for the plugin to change.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
