### ISSUE TITLE
java.lang.IllegalStateException: Application library named Erlang for Elixir 26 already exists at com.intellij.workspaceModel.ide.impl.legacyBridge.library.GlobalLibraryTableBridgeImpl.createLibrary(GlobalLibraryTableBridgeImpl.kt:232)

### ISSUE THREAD

**Issue by xtrasmal** [KronicDeth/intellij-elixir#3565]
# System

Plugin Version: 17.0.0
Application: PyCharm Professional Edition (2023.3.5)
Operating System: Mac OS X (14.3.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Application library named Erlang for Elixir 26 already exists
</summary>

```
java.lang.IllegalStateException: Application library named Erlang for Elixir 26 already exists
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.GlobalLibraryTableBridgeImpl.createLibrary(GlobalLibraryTableBridgeImpl.kt:232)
	at org.elixir_lang.facet.sdks.Configurable$addListeners$listener$1.sdkAdded$lambda$5$lambda$4(Configurable.kt:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:975)
	at org.elixir_lang.facet.sdks.Configurable$addListeners$listener$1.sdkAdded(Configurable.kt:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:119)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:84)
	at jdk.proxy1/jdk.proxy1.$Proxy196.sdkAdded(Unknown Source)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:525)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.setupSdk(ProjectSdksModel.java:509)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.addSdk(ProjectSdksModel.java:451)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.lambda$doAdd$7(ProjectSdksModel.java:445)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.lambda$selectSdkHome$8(SdkConfigurationUtil.java:311)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:153)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:100)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:309)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:279)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:445)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:425)
	at org.elixir_lang.facet.sdks.Configurable.addSdk(Configurable.kt:173)
	at org.elixir_lang.facet.sdks.Configurable.createComponent$lambda$1(Configurable.kt:66)
	at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:535)
	at com.intellij.ui.CommonActionsPanel$AddButton.actionPerformed(CommonActionsPanel.java:387)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:381)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:524)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
```

</details>

**Comment by sh41** [comment]
Duplicate of #3351, and fixed.

Same crash, same call site: the SDK listener shared by the Settings → Elixir → SDKs and → Internal Erlang SDKs pages called `createLibrary` with the SDK's name unconditionally, and the platform refuses a name that already has an application library.

The listener now reuses an existing library, in the commit "Resolve `application library named XXX already exists` exception" — first released in v22.0.0. A related listener-accumulation defect that made it easier to hit was fixed separately, first released in 24.0.0. See #3351 for the full write-up.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
