### ISSUE TITLE
unable to get stub builder for file with file = file:///Users/sg/.asdf/installs/elixir/1.14.5-otp-25/lib/elixir/lib/kernel.ex, file type = org.elixir_lang.ElixirFileType@74c58c7c, indexed file type = org.elixir_lang.ElixirFileType@74c58c7c, , stubBindingRoot = PsiPlainTextFileImpl, languages = [TEXT], fileTypes = [Elixir], files = [PsiPlainTextFileImpl], roots = [], indexingInfo = indexing timestamp = 1684767701000, binary = false, byte size = 175616, char size = 175612, isTooLarge = true at com.intellij.psi.stubs.StubProcessingHelperBase.handleNonPsiStubs(StubProcessingHelperBase.java:122)

### ISSUE THREAD

**Issue by sgledunia** [KronicDeth/intellij-elixir#3581]
# System

Plugin Version: 16.0.0
Application: IntelliJ IDEA Community Edition (2023.2.5)
Operating System: Mac OS X (14.4.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: unable to get stub builder for file with file = file:///Users/sg/.asdf/installs/elixir/1.14.5-otp-25/lib/elixir/lib/kernel.ex, file type = org.elixir_lang.ElixirFileType@74c58c7c, indexed file type = org.elixir_lang.ElixirFileType@74c58c7c, , stubBindingRoot = PsiPlainTextFileImpl, languages = [TEXT], fileTypes = [Elixir], files = [PsiPlainTextFileImpl], roots = [], indexingInfo = indexing timestamp = 1684767701000, binary = false, byte size = 175616, char size = 175612, isTooLarge = true
</summary>

```
java.lang.Throwable: unable to get stub builder for file with file = file:///Users/sg/.asdf/installs/elixir/1.14.5-otp-25/lib/elixir/lib/kernel.ex, file type = org.elixir_lang.ElixirFileType@74c58c7c, indexed file type = org.elixir_lang.ElixirFileType@74c58c7c, , stubBindingRoot = PsiPlainTextFileImpl, languages = [TEXT], fileTypes = [Elixir], files = [PsiPlainTextFileImpl], roots = [], indexingInfo = indexing timestamp = 1684767701000, binary = false, byte size = 175616, char size = 175612, isTooLarge = true
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.stubs.StubProcessingHelperBase.handleNonPsiStubs(StubProcessingHelperBase.java:122)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:67)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:150)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:214)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImport(CallDefinitionClause.kt:300)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImports(CallDefinitionClause.kt:283)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:174)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:45)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1271)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:255)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:242)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:132)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:103)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:89)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.elixir_lang.psi.impl.ElixirMatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirMatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:360)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:291)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:320)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:286)
```

</details>

**Comment by sh41** [comment]
Thanks for this, and sorry it sat so long. It turns out to be a platform diagnostic rather than a plugin defect, and the reason is visible in the message you posted: `isTooLarge = true`, `stubBindingRoot = PsiPlainTextFileImpl`, `languages = [TEXT]`, `fileTypes = [Elixir]`.

That combination means IntelliJ had decided your `kernel.ex` was too large for intelligence and built its PSI as plain text, while still recognising the file type as Elixir — `SingleRootFileViewProvider` substitutes the plain-text language whenever a file exceeds the intellisense size limit. The stub index still held an entry for that file from an earlier indexing run, so when the plugin asked the index for the `Kernel` module — which is what resolving an ordinary unqualified call like `is_nil/1` does while you type — the platform found the entry, went to read stubs out of the file, found plain-text PSI with no stub tree, and fell back to looking for a *binary* stub builder. The Elixir plugin registers none, correctly, because `.ex` is source rather than a binary format, so the platform logs unconditionally. No plugin code runs between the index query and that log, so there is nothing the plugin could do differently here.

What is not explained is why a 171 KB file was considered too large in the first place. The platform's default intellisense limit is 2500 KB and has been since 2017, and no plugin can lower it — the extension point for per-extension size limits ignores any value below the default by design. That leaves two possibilities, both outside the plugin: `idea.max.intellisense.filesize` was set to something small in your custom properties (Help → Edit Custom Properties), or the file length IntelliJ had recorded in its virtual file system was wrong.

If you still hit this, `File → Invalidate Caches → Invalidate and Restart` should clear the stale index entry that triggers the message — though if the limit really is set low, resolution into that file will quietly stop working rather than crash. Either way, if you can tell which of the two it was, please reopen and say so; that would be worth reporting to JetBrains.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
