### ISSUE TITLE
Intellij freezes when using plugin.

### ISSUE THREAD

**Issue by Casper12345** [KronicDeth/intellij-elixir#3584]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.3.3)
Operating System: Mac OS X (14.3)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name, file = file:///Users/casper/IdeaProjects/elevio/elevio-data-hub/web/api/bulk_insert_article.ex, file type = org.elixir_lang.ElixirFileType@2e842caa, indexed file type = org.elixir_lang.ElixirFileType@2e842caa
</summary>

```
java.lang.Throwable: Stub ids not found for key in index = elixir.all.name, file = file:///Users/casper/IdeaProjects/elevio/elevio-data-hub/web/api/bulk_insert_article.ex, file type = org.elixir_lang.ElixirFileType@2e842caa, indexed file type = org.elixir_lang.ElixirFileType@2e842caa
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:61)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$6(StubIndexEx.java:196)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:195)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.psi.scope.module.Variants$putProject$1.invoke(Variants.kt:74)
	at org.elixir_lang.psi.scope.module.Variants$putProject$1.invoke(Variants.kt:72)
	at org.elixir_lang.psi.scope.module.Variants.putProject$lambda$0(Variants.kt:72)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$iterateData$1(PersistentEnumeratorBase.java:435)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.lambda$processAll$1(AppendableStorageBackedByResizableMappedFile.java:129)
	at com.intellij.util.io.PagedFileStorage.lambda$readInputStream$1(PagedFileStorage.java:114)
	at com.intellij.util.io.StorageLockContext.executeOp(StorageLockContext.java:113)
	at com.intellij.util.io.PagedFileStorage.executeOp(PagedFileStorage.java:140)
	at com.intellij.util.io.PagedFileStorage.readInputStream(PagedFileStorage.java:112)
	at com.intellij.util.io.ResizeableMappedFile.readInputStream(ResizeableMappedFile.java:281)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.processAll(AppendableStorageBackedByResizableMappedFile.java:116)
	at com.intellij.util.io.PersistentEnumeratorBase.iterateData(PersistentEnumeratorBase.java:447)
	at com.intellij.util.io.PersistentEnumeratorBase.iterateData(PersistentEnumeratorBase.java:435)
	at com.intellij.util.io.PersistentMapImpl.processKeys(PersistentMapImpl.java:556)
	at com.intellij.util.indexing.impl.ValueContainerMap.processKeys(ValueContainerMap.java:73)
	at com.intellij.util.indexing.impl.MapIndexStorage.doProcessKeys(MapIndexStorage.java:365)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.processKeys(VfsAwareMapIndexStorage.java:113)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.processKeys(TransientChangesIndexStorage.java:147)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.lambda$processAllKeys$0(MapReduceIndexBase.java:49)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.processAllKeys(MapReduceIndexBase.java:48)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.processAllKeys(CompositeInvertedIndexBase.java:122)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processAllKeys$11(StubIndexEx.java:313)
	at com.intellij.util.indexing.IndexUpToDateCheckIn.disableUpToDateCheckIn(IndexUpToDateCheckIn.kt:15)
	at com.intellij.util.indexing.FileBasedIndexEx.disableUpToDateCheckIn(FileBasedIndexEx.java:728)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:313)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:70)
	at org.elixir_lang.psi.scope.module.Variants.putProject(Variants.kt:72)
	at org.elixir_lang.psi.scope.module.Variants.access$putProject(Variants.kt:25)
	at org.elixir_lang.psi.scope.module.Variants$Companion.unfilteredLookupElements(Variants.kt:247)
	at org.elixir_lang.psi.scope.module.Variants$Companion.lookupElements(Variants.kt:107)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:18)
	at org.elixir_lang.reference.Module.getVariants(Module.kt:15)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:222)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:122)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:63)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:80)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:141)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:124)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:78)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:48)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
```

</details>

**Comment by sh41** [comment]
Duplicate of #1947, which was closed with the full diagnosis. Worth saying first that the title and the contents of this report describe two different things: there is no log, screenshot or thread dump attached here and nothing in the body records a duration, so the freeze itself can't be checked from this issue. What the body does carry is one logged error, and that part is answerable.

`Stub ids not found for key in index = elixir.all.name` is the IntelliJ Platform's own consistency check — `StubProcessingHelper.retrieveStubIdList` logs it when a file's entry in the stub index and that same file's stored stub tree disagree about whether a name is present. Both sides are written by a single indexing pass, so no plugin code can write them apart. The report names this plugin only because the IDE attributes an error to the first plugin frame on the stack, and `psi.scope.module.Variants` is there as the caller doing module-name autocomplete. The platform re-indexes the offending file on the spot and the search carries on, so the cost is one name missing from one completion popup. **File > Invalidate Caches / Restart** clears it.

Your frame, `Variants$putProject`, is the same call site #1947 reported, and it is unchanged in current source — [`Variants.kt#L67-L86`](https://github.com/KronicDeth/intellij-elixir/blob/febbe48846931666845b6f886a24aa1421ca6bb2/src/org/elixir_lang/psi/scope/module/Variants.kt#L67-L86), lines 72 and 74 matching your trace exactly. The sibling reports #2427, #2567, #3295 and #3341 were fixed in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0), but that fix removed a different frame (`Callable.nameArityInAnyModule`, [`60a8386`](https://github.com/KronicDeth/intellij-elixir/commit/60a8386986b131504a30fc137c7b994462496728)) which does not appear in your stack, so it does not reach this one.

On the freeze: there is a real, separate reason module-name completion can feel like a hang on a large project. `putProject` enumerates every module name in the project's stub index and does a second index lookup for each, over an all-project scope, and neither it nor the platform code beneath it checks for cancellation — so once that walk starts it runs to the end and typing won't interrupt it. That is tracked at #1789 rather than here, since this report has no timing evidence of its own to add to it.

---

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
