### ISSUE TITLE
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{int,interpreted,[],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/private/var/folders/82/ml58sd892l1889x_57thjlbc0000gp/T/intellij_elixir1/debugger/lib/intellij_elixir/debugger/server.ex"},{line,166}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,1131}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1160}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]} at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)

### ISSUE THREAD

**Issue by javamichi18** [KronicDeth/intellij-elixir#3585]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.3.6)
Operating System: Mac OS X (14.4.1)

# Event

### Stacktrace

<details>

<summary>
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{int,interpreted,[],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/private/var/folders/82/ml58sd892l1889x_57thjlbc0000gp/T/intellij_elixir1/debugger/lib/intellij_elixir/debugger/server.ex"},{line,166}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,1131}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1160}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}
</summary>

```
java.util.concurrent.ExecutionException: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{int,interpreted,[],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/private/var/folders/82/ml58sd892l1889x_57thjlbc0000gp/T/intellij_elixir1/debugger/lib/intellij_elixir/debugger/server.ex"},{line,166}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,1131}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1160}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.elixir_lang.MailBox.wait(MailBox.kt:203)
	at org.elixir_lang.MailBox.receive(MailBox.kt:177)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:127)
	at org.elixir_lang.MailBox.genericUnmonitoredCall(MailBox.kt:114)
	at org.elixir_lang.MailBox.genericServerUnmonitoredCall(MailBox.kt:101)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:45)
	at org.elixir_lang.MailBox.genericServerCall(MailBox.kt:39)
	at org.elixir_lang.debugger.Node.callDebugged(Node.kt:255)
	at org.elixir_lang.debugger.Node.setBreakpoint(Node.kt:83)
	at org.elixir_lang.debugger.Process.addBreakpoint(Process.kt:160)
	at org.elixir_lang.debugger.Process.access$addBreakpoint(Process.kt:74)
	at org.elixir_lang.debugger.Process$addBreakpoint$1$3$1.invoke(Process.kt:134)
	at org.elixir_lang.debugger.Process$addBreakpoint$1$3$1.invoke(Process.kt:134)
	at org.elixir_lang.debugger.Process.runInitializers(Process.kt:393)
	at org.elixir_lang.debugger.Process.asyncRunInitializers$lambda$14(Process.kt:375)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.ericsson.otp.erlang.OtpErlangExit: {undef,[{int,interpreted,[],[]},{'Elixir.IntelliJElixir.Debugger.Server',handle_call,3,[{file,"/private/var/folders/82/ml58sd892l1889x_57thjlbc0000gp/T/intellij_elixir1/debugger/lib/intellij_elixir/debugger/server.ex"},{line,166}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,1131}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1160}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}
	at com.ericsson.otp.erlang.OtpMbox.receiveMsg(OtpMbox.java:274)
	at com.ericsson.otp.erlang.OtpMbox.receive(OtpMbox.java:170)
	at org.elixir_lang.MailBox.loop(MailBox.kt:219)
	at org.elixir_lang.MailBox._init_$lambda$0(MailBox.kt:26)
	... 12 more

```

</details>

**Comment by sh41** [comment]
This is the same defect as #3793, which has the fuller diagnosis — closing as a duplicate of it.

Briefly: `int:interpreted/0` failing with `undef` here is not a missing function, it is `:int` itself being unloadable in the debug session's node. `:int` belongs to OTP's `debugger` application, and OTP's code server only scans `$ROOT/lib/*` to populate the code path when a node boots in interactive mode — so the module can be present in your OTP install and still unavailable to that node.

Fixed by `IntelliJElixir.Debugged.ensure_debugger_path/0`, in commit 2e33113eaa61de02589062a2a4d355534ad046b1, first released in v23.0.2: it globs `debugger-*/ebin` under `:code.root_dir()` and adds it to the code path when `:code.lib_dir(:debugger)` cannot resolve the application.

No one has confirmed this on a build carrying the fix, so if you still see it on a current release, please reopen.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
