### ISSUE TITLE
psiElement is not instance of requiredClass.

### ISSUE THREAD

**Issue by pheller** [KronicDeth/intellij-elixir#3588]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.3.6)
Operating System: Mac OS X (14.5)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: psiElement is not instance of requiredClass.
</summary>

```
java.lang.Throwable: psiElement is not instance of requiredClass.
psiElement=null, requiredClass=interface org.elixir_lang.psi.NamedElement, operation=Looking for setopts in elixir.all.name, stubIdList=[30].
ref: 50cf572587cf
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file={}, file.class=class org.elixir_lang.beam.psi.BeamFileImpl, file.lang=Language: Elixir, modStamp=15324
 stub debugInfo=created from index; with backReference
 viewProvider=org.elixir_lang.beam.FileViewProvider{vFile=file:///Users/pheller/IdeaProjects/Prodigy/delivery-system/_build/test/lib/ranch/ebin/ranch_tcp.beam, vFileId=60355, content=VirtualFileContent{size=11024}, eventSystemEnabled=true}
 viewProvider stamp: 15324; file stamp: 15324; file modCount: 1716410751739; file length: 11024
indexing info: indexing timestamp = 1716410751739, binary = true, byte size = 11024, char size = -1
ref: 50cf572587cf
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiFileStubImpl}1967608288
   same size=false
   debugInfo=created from index; with backReference
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:156)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:90)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:61)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$5(StubIndexEx.java:152)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule(Callable.kt:196)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:91)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:607)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:597)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.accept(ElixirUnmatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:128)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:106)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:361)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:321)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:324)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:91)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:324)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:287)
```

</details>

**Comment by sh41** [comment]
Fixed in [v23.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v23.2.0) (2026-05-15), and a duplicate of #2427.

The plugin frame in your trace, `org.elixir_lang.reference.resolver.Callable.nameArityInAnyModule`, was the resolver's global fallback into the `elixir.all.name` stub index: when in-scope resolution found nothing, it searched every module in the project. It was removed outright — not renamed — by [`60a8386`](https://github.com/KronicDeth/intellij-elixir/commit/60a8386986b131504a30fc137c7b994462496728), so `Callable`'s resolve chain no longer queries that index at all. `Issue463Test.testUnresolvedAliasQualifier` fails if the fallback comes back.

The throw is the platform's own stub/index consistency check, and reports through this one call site have tripped it three different ways: #3387 crashed inside the platform's diagnostic formatting, since null-guarded upstream, while yours and #3318's reach the controlled "PSI and index do not match" branch a step earlier. Yours is a compiled `.beam` file and #3318's an Elixir source file, so it is not specific to either. The plugin-side trigger is the same in all of them, and it is gone.

#3594 is the same crash on a different `.beam` file and closes alongside this one.

Other `elixir.all.name` reports stay open: the platform throw is still reachable from call sites that do query that index, and each needs checking on its own.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
