### ISSUE TITLE
java.lang.NullPointerException: getContainingDirectory(...) must not be null at org.elixir_lang.exunit.configuration.ProducerKt.workingDirectory(Producer.kt:202)

### ISSUE THREAD

**Issue by akosasante** [KronicDeth/intellij-elixir#3590]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Ultimate Edition (2023.3.6)
Operating System: Mac OS X (14.4.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.NullPointerException: getContainingDirectory(...) must not be null
</summary>

```
java.lang.NullPointerException: getContainingDirectory(...) must not be null
	at org.elixir_lang.exunit.configuration.ProducerKt.workingDirectory(Producer.kt:202)
	at org.elixir_lang.exunit.configuration.ProducerKt.setupConfigurationFromContextImpl(Producer.kt:156)
	at org.elixir_lang.exunit.configuration.ProducerKt.access$setupConfigurationFromContextImpl(Producer.kt:1)
	at org.elixir_lang.exunit.configuration.MixExUnitRunConfigurationProducer.setupConfigurationFromContext(Producer.kt:27)
	at org.elixir_lang.exunit.configuration.MixExUnitRunConfigurationProducer.setupConfigurationFromContext(Producer.kt:18)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:98)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:119)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:100)
	at com.intellij.execution.actions.ConfigurationContext.createConfigurationsFromContext(ConfigurationContext.java:425)
	at com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.getRunConfigsForCurrentFile(ExecutorRegistryImpl.java:513)
	at com.intellij.execution.ui.RedesignedRunToolbarWrapper.isSomeRunningNow(RedesignedRunWidget.kt:184)
	at com.intellij.execution.ui.RedesignedRunToolbarWrapper.update(RedesignedRunWidget.kt:166)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:187)
```

</details>

**Comment by sh41** [comment]
This is still there, thanks for the report.

`MixExUnitRunConfigurationProducer` is asked for a configuration every time the run toolbar updates, over whatever file the editor has focus on. To work out the working directory it walks up from the file's containing directory — and `PsiFile.getContainingDirectory()` is nullable, documented by the platform to return null for a file that exists only in memory. The producer dereferences it without a check, which is the NPE in your trace: the message names the Java accessor because it is Kotlin's compiler-inserted null check that throws, not a check in the plugin's own code.

What lets an in-memory file get that far is the plugin's own gate. `Test.isTestFile` checks that the file has a `VirtualFile` and that its name ends in `_test.exs`; it does not check that the `VirtualFile` has a parent. A `LightVirtualFile` — the backing for a diff view, a VCS compare, a refactoring or completion preview — is a perfectly non-null `VirtualFile` with the right name and no parent, so it passes the gate and reaches the unguarded call. The line has been there unchanged since 2018.

The fix is for the producer to decline the context outright when the file has no containing directory, rather than just guarding the dereference: even guarded, a configuration built for an in-memory file would point `mix test` at a path that is not on disk. That is a small change, but it has not been done yet, so I am leaving this open rather than closing it.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
