### ISSUE TITLE
Don't know if Mix.Dep option `allow_pre` is important for determining location of dependency at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:57)

### ISSUE THREAD

**Issue by alpeshjamgade** [KronicDeth/intellij-elixir#3597]
# System

Plugin Version: 17.0.0
Application: IntelliJ IDEA Community Edition (2023.3.6)
Operating System: Linux (6.8.10-300.fc40.x86_64)

# Event

### Element

```
{:opentelemetry, "~> 1.0.0-rc", allow_pre: true}
```

From: `/home/voyager/Codebase/Primus/deps/opentelemetry_ecto/mix.exs:44`

#### Context

```

  defp deps do
    [
      {:telemetry, "~> 0.4.2"},
      {:opentelemetry_api, "~> 1.0.0-rc", allow_pre: true},
      {:opentelemetry, "~> 1.0.0-rc", allow_pre: true},
      {:ex_doc, "~> 0.21.0", only: [:dev], runtime: false},
      {:ecto_sql, ">= 3.0.0", only: [:test]},
      {:postgrex, ">= 0.15.0", only: [:test]}
    ]
  end
```

From: `/home/voyager/Codebase/Primus/deps/opentelemetry_ecto/mix.exs:39-49`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirTupleImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know if Mix.Dep option `allow_pre` is important for determining location of dependency
</summary>

```
java.lang.Throwable: Don't know if Mix.Dep option `allow_pre` is important for determining location of dependency
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:57)
	at org.elixir_lang.mix.Deps.fromTuple(Deps.kt:61)
	at org.elixir_lang.mix.Deps.from(Deps.kt:18)
	at org.elixir_lang.mix.DepGathererKt$deps$2.invoke(DepGatherer.kt:140)
	at org.elixir_lang.mix.DepGathererKt$deps$2.invoke(DepGatherer.kt:140)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:816)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:140)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:42)
	at org.elixir_lang.mix.DepGathererKt.access$deps(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:34)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:33)
	at org.elixir_lang.mix.DepGathererKt.foldDepsDefinersWhile(DepGatherer.kt:62)
	at org.elixir_lang.mix.DepGathererKt.access$foldDepsDefinersWhile(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer.visitElement(DepGatherer.kt:33)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:183)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:748)
	at org.elixir_lang.mix.DepGatherer$visitFile$1.invoke(DepGatherer.kt:23)
	at org.elixir_lang.mix.DepGatherer$visitFile$1.invoke(DepGatherer.kt:22)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at org.elixir_lang.mix.DepGatherer.visitFile(DepGatherer.kt:22)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:59)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$1.invoke$lambda$2(Resolution.kt:119)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$1.invoke(Resolution.kt:116)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$1.invoke(Resolution.kt:115)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packagePsiFileToDepSet(Resolution.kt:115)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packageVirtualFileToDepSet(Resolution.kt:105)
	at org.elixir_lang.mix.watcher.Resolution$Companion.rootVirtualFileToDepSet(Resolution.kt:82)
	at org.elixir_lang.mix.watcher.Resolution$Companion.resolution(Resolution.kt:39)
	at org.elixir_lang.mix.watcher.TransitiveResolution.transitiveResolution(TransitiveResolution.kt:17)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:64)
	at org.elixir_lang.mix.Watcher$contentsChanged$1$1.run(Watcher.kt:52)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
```

</details>

**Comment by sh41** [comment]
Duplicate of #2487, which reports the same option reaching the same branch of `Dep` from the same place — `allow_pre` in the `opentelemetry` family's own `mix.exs`, not in anything the reporter wrote.

The two traces name different lines only because an unrelated change, b27a5696c, added two lines above that call in the meantime; nothing about `allow_pre` differs between them.

#2487 is the one to follow — the fix is tracked there.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
