### ISSUE TITLE
do blocks no longer parse with 2024.x (241.xx)

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#3601]
do blocks no longer parse correctly, but the good news is that [tests picked this up](https://github.com/joshuataylor/intellij-elixir/blob/6f55b2ce073fcf277ac1dc62ffccca6b75501f4b/tests/org/elixir_lang/code_insight/highlighting/brace_matcher/Issue443.java#L17)! :tada:

This is how it currently renders:
![img.png](img.png)

And this is how it should look:
![img_1.png](img_1.png)

[github actions run](https://github.com/KronicDeth/intellij-elixir/actions/runs/9927006033/job/27421396816#step:12:94)
```kt
org.elixir_lang.code_insight.highlighting.brace_matcher.Issue443 > testDoBlock FAILED
    junit.framework.AssertionFailedError: `do` not matched to `end`
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.TestCase.assertTrue(TestCase.java:192)
        at org.elixir_lang.code_insight.highlighting.brace_matcher.Issue443.testDoBlock(Issue443.java:21)
```

The code that builds it is this:
```kotlin
private boolean isLBraceTokenBrace() {
    int offset = myFixture.getCaretOffset();
    Editor editor = myFixture.getEditor();
    CharSequence text = editor.getDocument().getCharsSequence();
    FileType fileType = ElixirFileType.INSTANCE;
    HighlighterIterator iterator = ((EditorEx) editor).getHighlighter().createIterator(offset);

    // easier to debug
    BraceMatcher braceMatcher = getBraceMatcher(fileType, iterator);
    var is_brace = BraceMatchingUtil.isLBraceToken(iterator, text, fileType);
    IElementType tokenType = iterator.getTokenType();

    return is_brace;
}
```

tokenType before: "do"
[/gen/org/elixir_lang/psi/ElixirTypes.java#L44](https://github.com/joshuataylor/intellij-elixir/blob/73ad91be461f79352fae02096e6049368c077bca/gen/org/elixir_lang/psi/ElixirTypes.java#L44)
```java
  IElementType DO_BLOCK = new ElixirElementType("DO_BLOCK");
```

tokenType now: empty token (which is any language)

braceMatcher before: NonTrivial
[/src/org/elixir_lang/code_insight/highlighting/brace_matcher/NonTrivial.java#L12-L15](https://github.com/joshuataylor/intellij-elixir/blob/73ad91be461f79352fae02096e6049368c077bca/src/org/elixir_lang/code_insight/highlighting/brace_matcher/NonTrivial.java#L12-L15)
```java
public class NonTrivial extends PairedBraceMatcherAdapter {
  public NonTrivial() {
    super(new Paired(), ElixirLanguage.INSTANCE);
  }

```

braceMatcher now: PairedBraceMatcherAdapter (the parent class)

---

So now we need to figure out how to make tokenType back to do.

If anyone has any ideas why this is happening, please post them here. Thanks!

#3598 #3569

**Comment by joshuataylor** [comment]
fixed by setting language instead of key.. https://github.com/KronicDeth/intellij-elixir/pull/3569/files#diff-6ce03e028ee0ab9572d21f9158240e43894b4f8d1ef8e678a0202dc89c8bf089R216
