### ISSUE TITLE
Phase 2 Meta Issue - Build Environment Improvements

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#3616]
## Support IntelliJ Gradle 2.0.0
Benefits include a much nicer Developer Experience, easier way of testing both IntelliJ IDEA + RubyMine, faster builds, etc.

[IntelliJ Platform Gradle Plugin (2.x)](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html)
[Migration](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html)

[intellij-platform-plugin-template GitHub repository](https://github.com/JetBrains/intellij-platform-plugin-template)
https://github.com/JetBrains/intellij-platform-gradle-plugin

[intellij-platform-gradle-plugin 2.0.0 release notes](https://github.com/JetBrains/intellij-platform-gradle-plugin/releases/tag/v2.0.0)

[my branch]()

## Support 2024.2
With 2024.2 around the corner, this should be a priority to support.

Support for 2024.1.4 exists, with some weird issues with RubyMine and the SDK. You can grab this from the releases, it's not a tagged release due to the previous issue - I have been using it with IDEA and it's been fine.

It seems like 2024.2 contains quite some substantial updates, so we'll need to double check everything works as expected.

[Incompatible Changes in IntelliJ Platform and Plugins API 2024.x](https://plugins.jetbrains.com/docs/intellij/api-changes-list-2024.html)

[Incompatible Changes in IntelliJ Platform and Plugins API 2024.x](https://plugins.jetbrains.com/docs/intellij/api-changes-list-2024.html)

[Verifying Plugin Compatibility](https://plugins.jetbrains.com/docs/intellij/verifying-plugin-compatibility.html)

## Docs
Update contributing and other documentation for the latest IntelliJ IDEA changes, tips for contributing, etc - if/as needed.

**Comment by joshuataylor** [comment]
There have been a few deprecations, nothing too major, should have a release out in the next day or so.

**Comment by nulian** [comment]
Yeah only real error I have seen is this one.
Tnx again for your work.

```
java.lang.Throwable: No decompiled source function with name (String.at)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.kt:103)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
```

**Comment by sh41** [comment]
All done now. Closing this one.
