### ISSUE TITLE
Debugger fails to start (elixir 1.17.2/ OTP 27.0.1

### ISSUE THREAD

**Issue by psteininger** [KronicDeth/intellij-elixir#3629]
I tried running a `mix phx.server` configuration in debug mode . I have OTP 27.0.1 and elixir 1.17.2-otp-27 installed via mise/asdf.
The erlang and Elixir SDKs are the only ones in the list and the elixir 1.17.2-otp-27 is the selected SDK.

**To Reproduce**
1. Setup a run configuration as a mix task with `phx.server` as mix arguments
2. Run the configuration in debug

**Expected behavior**
Debugger starts and attaches to the process

**Screenshots**
<img width="785" alt="image" src="https://github.com/user-attachments/assets/ca2d647d-49db-4f20-b6ed-1f252f090e6a">

**Logs**
```
Waiting for debugger to attach...
Interpreting modules under /Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/eex/ebin...  ...skipped
Interpreting modules under /Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/elixir/ebin...  ...skipped
Interpreting modules under /Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/ex_unit/ebin...  ...skipped
Interpreting modules under /Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/iex/ebin...  ...skipped
Interpreting modules under /Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/logger/ebin...  ...skipped
Interpreting modules under /Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/mix/ebin...  ...skipped
Interpreting modules under /Users/piotr/.local/share/mise/installs/erlang/27.0.1/lib/asn1-5.3/ebin...

23:11:18.169 [error] GenServer IntelliJElixir.Debugger.Server terminating
** (UndefinedFunctionError) function :int.interpretable/1 is undefined (module :int is not available)
    :int.interpretable(:asn1_db)
    /private/var/folders/br/smkky7lx2zlf42fz6fh6yv280000gn/T/intellij_elixir11/debugger/lib/intellij_elixir/debugger/server.ex:400: anonymous fn/1 in IntelliJElixir.Debugger.Server.interpret_modules_in/2
    (elixir 1.17.2) lib/stream.ex:523: anonymous fn/4 in Stream.filter/2
    (elixir 1.17.2) lib/enum.ex:4858: Enumerable.List.reduce/3
    (elixir 1.17.2) lib/stream.ex:1891: Enumerable.Stream.do_each/4
    (elixir 1.17.2) lib/enum.ex:4423: Enum.each/2
    /private/var/folders/br/smkky7lx2zlf42fz6fh6yv280000gn/T/intellij_elixir11/debugger/lib/intellij_elixir/debugger/server.ex:401: IntelliJElixir.Debugger.Server.interpret_modules_in/2
    /private/var/folders/br/smkky7lx2zlf42fz6fh6yv280000gn/T/intellij_elixir11/debugger/lib/intellij_elixir/debugger/server.ex:133: anonymous fn/3 in IntelliJElixir.Debugger.Server.handle_call/3
Last message (from #PID<11621.4.0>): {:interpret, %{sdk_paths: ["/Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/logger/ebin", "/Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/elixir/ebin", "/Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/ex_unit/ebin", "/Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/mix/ebin", "/Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/eex/ebin", "/Users/piotr/.local/share/mise/installs/elixir/1.17.2-otp-27/lib/iex/ebin"], reject_elixir_module_name_patterns: [":cow*", ":crypto", ":elixir_*", ":erocksdb", ":lz4", ":ranch*", ":re2", "Access", "Agent", "Agent.*", "Application", "Atom", "Base", "Bcrypt.Base", "Behaviour", "Benchee", "Benchee.*", "Bitwise", "Calendar", "Calendar.*", "Code", "Code.*", "Collectable", "Collectable.*", "Connection", "Credo", "Credo.*", "DBConnection", "DBConnection.*", "Date", "Date.*", "DateTime", "Decimal", "Dict", "DynamicSupervisor", "ESpec", "ESpec.*", "Earmark", "Earmark.*", "Ecto", "Ecto.*", "Enum", "Enumerable", "Enumerable.*", "ExCoveralls", "ExCoveralls.*", ...]}}
State: %IntelliJElixir.Debugger.Server{attached: nil, evaluate_meta_pid_to_froms: %{}}
Client #PID<11621.4.0> is remote on node :"debugger8b0874dd-fab3-4517-b03c-0378eff29bfc@127.0.0.1"

```

**Desktop:**
 - OS: macOS
 - Version  14.0

**Erlang:**
- Installer mise/asdf
- Version 27.0.1

**Elixir:**
- Installer mise
- Version 1.17.2-otp-27

**Plugin:**
- Version 18.0.1 (installed from disk)

**Comment by psteininger** [comment]
this is quite odd, because when I run `iex`, the module `:int` and all the functions are there. Also running the line below returns true
```shell
iex(1)>  :int.interpretable(:asn1_db)
true
```

**Comment by psteininger** [comment]
Small Update:
I managed to get further by adding `:*` to the list of interpreted modules:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/ac0e3a57-51ee-41ef-bba2-467c975720d1">

However, I got a different error:
```
23:33:49.981 [error] GenServer IntelliJElixir.Debugger.Server terminating
** (UndefinedFunctionError) function :int.auto_attach/2 is undefined (module :int is not available)
    :int.auto_attach([:break], {IntelliJElixir.Debugger.Server, :breakpoint_reached, []})
    /private/var/folders/br/smkky7lx2zlf42fz6fh6yv280000gn/T/intellij_elixir9/debugger/lib/intellij_elixir/debugger/server.ex:94: IntelliJElixir.Debugger.Server.handle_call/3
    (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
    (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
    (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message (from #PID<12153.4.0>): :attach
State: %IntelliJElixir.Debugger.Server{attached: nil, evaluate_meta_pid_to_froms: %{}}
Client #PID<12153.4.0> is remote on node :"debuggerff782bc2-b96a-469a-80a5-c5f434e80272@127.0.0.1"

```

Would anyone suggest other things to try or a workaround?

**Comment by amplexdenmark** [comment]
I am having the exact same issue. The setup guide would be much appreciated

**Comment by ativ97** [comment]
Did anyone find a workaround yet? Been struggling with this issue for a few days. I'm also fairly new to elixir.

**Comment by Fahani** [comment]
Having the same issue, I posted it here https://elixirforum.com/t/error-while-debugging-phoenix-app-ubuntu-24-intellij-ultimate/66239

**Comment by jpulgarin** [comment]
I'm running into this issue with Erlang `27.2`, Elixir `1.18.1`, IntelliJ `2024.3.1.1` and plugin version `20.0.1`.

**Comment by jpulgarin** [comment]
I was able to fix this by adding `:debugger` to `extra_applications` in my `mix.exs`.

**Comment by Fahani** [comment]
> I was able to fix this by adding `:debugger` to `extra_applications` in my `mix.exs`.

Thanks, that worked!

**Comment by amplexdenmark** [comment]
> I was able to fix this by adding `:debugger` to `extra_applications` in my `mix.exs`.

You are amazing! Worked like a charm!

**Comment by sh41** [comment]
This is the same defect as #3793, which has the fuller diagnosis — closing as a duplicate of it.

The evidence in this thread is what made the diagnosis possible, so thank you. Two things in particular. `:int.interpretable(:asn1_db)` returning `true` from a plain `iex` on the same machine is the key observation: it shows the OTP install is not missing the `debugger` application at all. And hitting a second `:int` failure at `auto_attach` after suppressing interpretation with `:*` shows the problem is not specific to module interpretation — `:int` is simply not loadable in that node.

The reason is that `:int` lives in OTP's `debugger` application, and OTP's code server only scans `$ROOT/lib/*` to populate the code path when a node boots in interactive mode. So the same install can resolve `:int` in an interactive shell and not in the node the debug session runs in.

Fixed by `IntelliJElixir.Debugged.ensure_debugger_path/0`, in commit 2e33113eaa61de02589062a2a4d355534ad046b1, first released in v23.0.2: when `:code.lib_dir(:debugger)` cannot resolve the application it locates `debugger-*/ebin` under `:code.root_dir()` by a filesystem glob and adds it to the code path, which works regardless of why the lookup failed. It runs from `Debugged.start/0`, so every debug configuration gets it.

That should also make the `:debugger` in `extra_applications` workaround unnecessary — it was a good find and it addressed the same missing code path from the other end.

No one has confirmed this on a build carrying the fix, so if it still happens on a current release, please reopen and say so.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
