### ISSUE TITLE
Exception while: debugging and clicking "continue to cursor/line"

### ISSUE THREAD

**Issue by szymon-jez** [KronicDeth/intellij-elixir#3645]
# System

Plugin Version: 19.0.0
Application: IntelliJ IDEA Community Edition (2024.2.0.2)
Operating System: Mac OS X (14.5)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation. Dumb mode start trace is in the cause.
</summary>

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation. Dumb mode start trace is in the cause.
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:68)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:879)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:827)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:358)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:168)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:58)
	at org.elixir_lang.psi.__module__.PsiScopeProcessor.execute(PsiScopeProcessor.kt:41)
	at org.elixir_lang.psi.__module__.PsiScopeProcessor.execute(PsiScopeProcessor.kt:24)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1264)
	at org.elixir_lang.psi.__module__.Resolver.resolve(Resolver.kt:18)
	at org.elixir_lang.psi.__module__.Resolver.resolve(Resolver.kt:13)
	at org.elixir_lang.psi.__module__.Resolver.resolve(Resolver.kt:11)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:167)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:242)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:221)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:148)
	at org.elixir_lang.psi.__module__.ResolveWithCachingComputable.compute(Reference.kt:46)
	at org.elixir_lang.psi.__module__.ResolveWithCachingComputable.compute(Reference.kt:40)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$3(AnyThreadWriteThreadingSupport.kt:219)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:228)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.psi.__module__.Reference.multiResolve(Reference.kt:30)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.runAnnotatorWithContext(AnnotationHolderImpl.java:216)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotator$3(AnnotatorRunner.java:139)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotator(AnnotatorRunner.java:129)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$0(AnnotatorRunner.java:66)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$1(AnnotatorRunner.java:66)
	at com.intellij.concurrency.JobLauncherImpl$2MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:494)
```

</details>

**Comment by joshuataylor** [comment]
Assigned this to me, but if anyone else wants to take a look -- feel free!

**Comment by sh41** [comment]
Closing as a duplicate of #3451, on the stack trace rather than the title.

Every `org.elixir_lang` frame in this report is identical to the one in #3451 — the same eleven, from `__module__.Resolver.resolve` down through `ProcessDeclarationsImpl.processDeclarations` and `__module__.PsiScopeProcessor.execute` to the `IndexNotReadyException`, and up through `safeMultiResolve` to `annotator.Callable.annotate`. The only differences are the platform's own internal line numbers and the frames above `Callable.annotate`, and those differ solely because 2024.2 dispatches annotators through a newer asynchronous API than 2023.2 did.

Worth stating plainly, because the title points the wrong way: **the debugger is not involved in this crash.** No `org.elixir_lang.debugger` frame appears anywhere in either report. What is in the trace is the ordinary background highlighting annotator, which is registered `DumbAware` and therefore runs during indexing, resolving a `__MODULE__` reference through an unguarded stub-index read. "Continue to cursor" is what you happened to be doing when the highlighter ran; it is not what triggered the exception.

#3451 has the details of the underlying gap and stays open for it — including why this exception stopped being reported without the plugin-side cause being fixed.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
