### ISSUE TITLE
Error when opening Elixir project on Windows

### ISSUE THREAD

**Issue by StragaSevera** [KronicDeth/intellij-elixir#3647]
**Describe the bug**
Whenever I open an Elixir project, or when I try to run tests or server from within the IDE, I receive this error:

`
Internal error (java.lang.UnsupportedClassVersionError): org/elixir_lang/jps/model/SerializerExtension has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
java.lang.UnsupportedClassVersionError: org/elixir_lang/jps/model/SerializerExtension has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at com.intellij.util.containers.ContainerUtil.newArrayList(ContainerUtil.java:149)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl$SingleClassLoaderPluginManager.loadExtensions(JpsServiceManagerImpl.java:113)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.loadExtensions(JpsServiceManagerImpl.java:105)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.getExtensions(JpsServiceManagerImpl.java:58)
	at org.jetbrains.jps.model.serialization.JpsModelSerializerExtension.getExtensions(JpsModelSerializerExtension.java:48)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.getSdkPropertiesSerializer(JpsSdkTableSerializer.java:134)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.loadSdk(JpsSdkTableSerializer.java:69)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.loadSdks(JpsSdkTableSerializer.java:61)
	at org.jetbrains.jps.model.serialization.JpsGlobalSettingsLoading$SdkTableSerializer.loadExtension(JpsGlobalSettingsLoading.java:69)
	at org.jetbrains.jps.model.serialization.JpsGlobalSettingsLoading$SdkTableSerializer.loadExtension(JpsGlobalSettingsLoading.java:62)
	at org.jetbrains.jps.model.serialization.JpsLoaderBase.loadComponents(JpsLoaderBase.java:46)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalComponents(JpsGlobalLoader.java:52)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.load(JpsGlobalLoader.java:36)
	at org.jetbrains.jps.model.serialization.JpsGlobalSettingsLoading.loadGlobalSettings(JpsGlobalSettingsLoading.java:33)
	at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:25)
	at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:35)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:68)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:363)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:212)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:211)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**To Reproduce**
1. Open a project;

**Expected behavior**
Error is not shown, mix commands run normally from IDE/

**Desktop:**
 - OS: Windows 10

**Erlang:**
- Installer: Scoop
- Version: 27

**Elixir:**
- Installer: Scoop
- Version: 1.17.2

**Plugin:**
- Version: 19.0.1

**Additional context**
I tried to solve it by manually setting up IntelliJ JVM to the OpenJDK 21, but it did not help.

**Comment by formingform** [comment]
I'm having a similar issue. I use IDEA for JAVA and Elixir projects. Yesterday, I just opened the previous Elixir project. TODAY I FOUND OUT THAT MY JAVA PROJECT IS NOT RUNNING, AND THE ERROR MESSAGE IS THE SAME AS THIS.

**Comment by sh41** [comment]
Same failure as #3688, which @formingform filed after commenting here — and #3688 has the answer.

The class file version 65 vs 61 mismatch isn't the IDE's own JVM — it's the JDK that IntelliJ launches its external build process with, which comes from the project/module SDK under Settings → Build, Execution, Deployment → Compiler. That's why setting the IntelliJ JVM to OpenJDK 21 didn't help here. On #3688, raising the project JDK to 21 fixed it. Since IntelliJ 2024.2 the platform requires plugins to be compiled at Java 21, and the plugin's JPS classes are built at the same level as the rest of it.

Whether they should be is a fair question, so I've opened #3996 to track it: JetBrains still compiles its own JPS classes at Java 11, so a lower target for the plugin's JPS modules looks available. No promise that it happens, but it's now written down rather than lost in a duplicate.

Closing as a duplicate of #3688.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
