### ISSUE TITLE
Do not know whether to inject Markdown in documentation at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:75)

### ISSUE THREAD

**Issue by hsuyuanyuanlunar** [KronicDeth/intellij-elixir#3650]
# System

Plugin Version: 17.0.0
Application: PyCharm Professional Edition (2023.3.2)
Operating System: Mac OS X (14.3)

# Event

### Element

```
@doc_header
```

From: `/Users/yuanxu/lunar-dev/lunar/deps/oban/lib/oban.ex:23`

#### Context

```
  @doc_footer readme
              |> File.read!()
              |> String.split("<!-- MDOC -->")
              |> Enum.fetch!(1)

  @moduledoc @doc_header <> @doc_footer

  use Supervisor

  alias Ecto.{Changeset, Multi}
  alias Oban.{Config, Engine, Job, Midwife, Notifier, Peer, Registry, Sonar, Stager}
```

From: `/Users/yuanxu/lunar-dev/lunar/deps/oban/lib/oban.ex:18-28`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMatchedAtOperationImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Do not know whether to inject Markdown in documentation
</summary>

```
java.lang.Throwable: Do not know whether to inject Markdown in documentation
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:75)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:25)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:495)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUpInner(InjectedLanguageUtilBase.java:234)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.lambda$probeElementsUp$0(InjectedLanguageUtilBase.java:214)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl$allowInWriteAction$1.invoke(ReadActionCacheImpl.kt:41)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl$allowInWriteAction$1.invoke(ReadActionCacheImpl.kt:41)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl.allowInWriteAction(ReadActionCacheImpl.kt:29)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl.allowInWriteAction(ReadActionCacheImpl.kt:41)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:213)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:156)
```

</details>

**Comment by sh41** [comment]
Fixed. `ElixirMatchedAtOperation` — the `@doc_header` in `@moduledoc @doc_header <> @doc_footer` — is now handled by the markdown injector and skipped quietly instead of being reported.

The fix is commit 733198b22, merged in #3763 and first released in v23.0.2. Its commit message cites the same Oban `@moduledoc` shape your report came from.

The same message can still appear for other documentation expressions the injector does not model yet; that general gap is tracked in #3985.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
