### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented. at org.elixir_lang.documentation.SourceFileDocsHelper.fetchTypeDocs(SourceFileDocsHelper.kt:43)

### ISSUE THREAD

**Issue by kannan-stx** [KronicDeth/intellij-elixir#3653]
# System

Plugin Version: 13.2.1
Application: RubyMine (2022.1.4)
Operating System: Mac OS X (14.6.1)

# Event

## Message

Unhandled exception in [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelling}@6ec89e7a, Dispatchers.Default]

### Stacktrace

<details>

<summary>
kotlin.NotImplementedError: An operation is not implemented.
</summary>

```
kotlin.NotImplementedError: An operation is not implemented.
	at org.elixir_lang.documentation.SourceFileDocsHelper.fetchTypeDocs(SourceFileDocsHelper.kt:43)
	at org.elixir_lang.documentation.SourceFileDocsHelper.fetchDocs(SourceFileDocsHelper.kt:25)
	at org.elixir_lang.documentation.SourceFileDocsHelper.fetchDocs(SourceFileDocsHelper.kt:18)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:494)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:41)
```

</details>

**Comment by sh41** [comment]
Fixed. `@typedoc` and `@doc` were only ever modelled as heredocs (`"""…"""`), so a single-line documentation string — `@typedoc "…"` — fell through to a `TODO()` and threw `kotlin.NotImplementedError` while Quick Documentation was being rendered.

[`fbfbd3a`](https://github.com/KronicDeth/intellij-elixir/commit/fbfbd3a93a1f12fb80f951036176aae2e204bf2d) in [#3819](https://github.com/KronicDeth/intellij-elixir/pull/3819) models that shape: documentation text extraction moved into a shared `documentationMarkdownText()`, which handles a single-line string alongside a heredoc. `SourceFileDocsHelper` now returns the doc text instead of throwing.

The first release users can install with the fix is [24.0.0](https://plugins.jetbrains.com/plugin/7522-elixir/versions/stable/1125433), published 2026-08-04 — the `23.x` tags carry the same commit but were never published to the Marketplace. Note that 24.0.0 requires RubyMine 2025.3 or newer; 13.2.1 is the last build compatible with RubyMine 2022.1, so picking the fix up means upgrading the IDE as well as the plugin.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
