### ISSUE TITLE
Don't know how to prepend qualifier at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:221)

### ISSUE THREAD

**Issue by DougReeder** [KronicDeth/intellij-elixir#3658]
# System

Plugin Version: 14.0.1
Application: RubyMine (2022.3.3)
Operating System: Mac OS X (14.6.1)

# Event

### Element

```
<%= @hub.IntellijIdeaRulezzz  %>
```

From: `/Users/doug/git/hubs-compose/services/reticulum/lib/ret_web/templates/page/hub-meta.html.eex:9`

#### Context

```
        "@context": "https://schema.org/",
        "@type": "WebSite",
        "name": "<%= @hub.name %> | <%= @translations["app-name"] %>",
        "url": "<%= @hub |> Ret.Hub.url_for %>",
        "description": "<%= @translations["app-description"] %>",
        "disambiguatingDescription": "<%= @hub.IntellijIdeaRulezzz  %>",
        "alternativeHeadline": "<%= @translations["app-tagline"] %>",
        "author": {"@type":"Organization","name":"<%= @translations["company-name"] %>","email":"<%= @translations["contact-email"] %>"},
        "keywords": ["Hubs", "immersive spaces", "social VR", "<%= @translations["share-hashtag"] %>"]
    }
</script>
```

From: `/Users/doug/git/hubs-compose/services/reticulum/lib/ret_web/templates/page/hub-meta.html.eex:4-14`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirEexTagImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to prepend qualifier
</summary>

```
java.lang.Throwable: Don't know how to prepend qualifier
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.prependQualifiers(QualifiableAliasImpl.kt:221)
	at org.elixir_lang.psi.impl.QualifiableAliasImpl.fullyQualifiedName(QualifiableAliasImpl.kt:127)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyQualifiedName(ElixirPsiImplUtil.java:834)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.fullyQualifiedName(ElixirUnmatchedQualifiedAliasImpl.java:55)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.computeReference(QualifiableAliasImpl.kt:40)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference$lambda$0(QualifiableAliasImpl.kt:57)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.getReference(QualifiableAliasImpl.kt:56)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1083)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.getReference(ElixirUnmatchedQualifiedAliasImpl.java:75)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.getReference(ElixirUnmatchedQualifiedAliasImpl.java:18)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getReferences(SharedPsiElementImplUtil.java:76)
	at com.intellij.psi.impl.PsiElementBase.getReferences(PsiElementBase.java:70)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:59)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:33)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findReferenceAt(MultiplePsiFilesPerDocumentFileViewProvider.java:184)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:531)
	at com.intellij.codeInsight.completion.CompletionUtil.findReferencePrefix(CompletionUtil.java:157)
	at com.intellij.codeInsight.completion.CompletionData.findPrefixStatic(CompletionData.java:133)
	at com.intellij.codeInsight.completion.CompletionData.findPrefixStatic(CompletionData.java:148)
```

</details>

**Comment by sh41** [comment]
Fixed in June 2023 — before the build you reported this from.

`QualifiableAliasImpl.prependQualifiers` matches every ancestor it walks against a `when`, and an EEx tag was missing from it — so `<%= @hub.… %>` in a `.eex` template fell through to the catch-all that logs "Don't know how to prepend qualifier". Your report names the ancestor it did not recognise: `ElixirEexTagImpl`.

`ca0b1ae5` *Stop prependingQualifiers at EEx tags.* added EEx tags to that list, first released in [v15.1.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v15.1.0) on 2023-07-08. You reported this on plugin version 14.0.1, published 2023-04-07 — three months before the fix existed. Upgrading is all that is needed.

Same defect as #2414, #2468 and #3278.

> Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
