### ISSUE TITLE
Don't know if Mix.Dep option `depth` is important for determining location of dependency at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:55)

### ISSUE THREAD

**Issue by sebindelmanne** [KronicDeth/intellij-elixir#3668]
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Community Edition (2021.3)
Operating System: Windows 11 (10.0)

# Event

### Excerpt

```
{:heroicons,
       github: "tailwindlabs/heroicons",
       tag: "v2.1.1",
       sparse: "optimized",
       app: false,
       compile: false,
       depth: 1}
```

From: `C:/Users/s7472b/proj/kyc_test/mix.exs:43`
To: `C:/Users/s7472b/proj/kyc_test/mix.exs:49`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirTupleImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know if Mix.Dep option `depth` is important for determining location of dependency
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:55)
	at org.elixir_lang.mix.Deps.fromTuple(Deps.kt:61)
	at org.elixir_lang.mix.Deps.from(Deps.kt:18)
	at org.elixir_lang.mix.DepGathererKt$deps$2.invoke(DepGatherer.kt:140)
	at org.elixir_lang.mix.DepGathererKt$deps$2.invoke(DepGatherer.kt:140)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:140)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:42)
	at org.elixir_lang.mix.DepGathererKt.access$deps(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:34)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:33)
	at org.elixir_lang.mix.DepGathererKt.foldDepsDefinersWhile(DepGatherer.kt:62)
	at org.elixir_lang.mix.DepGathererKt.access$foldDepsDefinersWhile(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer.visitElement(DepGatherer.kt:33)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at org.elixir_lang.mix.DepGatherer$visitFile$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.mix.DepGatherer.visitFile(DepGatherer.kt:142)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$1$1.compute(Resolution.kt:111)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packagePsiFileToDepSet(Resolution.kt:122)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packageVirtualFileToDepSet(Resolution.kt:97)
	at org.elixir_lang.mix.watcher.Resolution$Companion.rootVirtualFileToDepSet(Resolution.kt:80)
	at org.elixir_lang.mix.watcher.Resolution$Companion.resolution(Resolution.kt:38)
	at org.elixir_lang.mix.watcher.TransitiveResolution.transitiveResolution(TransitiveResolution.kt:17)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:57)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:198)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:181)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:176)
	at org.elixir_lang.mix.Project$createModulesForOtpApps$3.run(Project.kt:90)
```

**Comment by sh41** [comment]
`depth` has been on `Dep`'s list of known Mix dep options since 1e6d02519 (PR #3635), which shipped in v19.0.1 on 2024-08-20 — about three and a half months before this report. The build named here is 12.2.1, from April 2022, so the error came from a plugin predating the fix and updating clears it. That release's notes do not mention the change, so there was no way to tell from the outside.

The message reads like a failure but is not one. The plugin keeps a list of Mix dep options because a few of them change where a dependency is checked out on disk, and it logs anything it does not recognise so that the option gets checked. The dependency is resolved normally in the meantime. `depth` is a git clone depth and does not move the dep, so it only needed adding to the list.

One thing worth flagging from the same dep tuple, since it is the stock `mix phx.new` `:heroicons` entry and so is very widely used: `sparse:` *does* move the checkout — `Mix.SCM.Git` joins it onto the dep's destination — and the plugin currently ignores it. That is a real bug, and it is recorded on #3928, which is where the underlying cause is tracked. It has no practical effect on `heroicons` itself, which ships no Elixir source to index, but it does on a `sparse:` or `subdir:` dep that ships code.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.
