### ISSUE TITLE
Fresh Intellij install - fresh plugin install - create new elixir project not working when adding SDK

### ISSUE THREAD

**Issue by yssoe** [KronicDeth/intellij-elixir#3669]
2024-12-10 07:36:25,155 [    427]   WARN - c.i.o.u.r.overrides - Conflicting registry key definition for key kotlin.mpp.tests.force.gradle: it was defined by plugin org.jetbrains.kotlin but redefined by plugin org.jetbrains.kotlin. Consider adding overrides="true" for one of the plugins, see the documentation for com.intellij.openapi.util.registry.RegistryKeyBean.overrides for more details.
2024-12-10 07:36:31,171 [   6443]   WARN - #c.i.o.u.WindowStateService - cannot find a project frame for ProjectDefault (Template) Project
2024-12-10 07:36:31,171 [   6443]   WARN - #c.i.o.u.WindowStateService - cannot find a project frame for ProjectDefault (Template) Project
2024-12-10 07:36:39,783 [  15055] SEVERE - #c.i.o.p.i.ProjectJdkImpl - Forbidden to mutate SDK outside of the `SdkModificator`. Please, use `com.intellij.openapi.projectRoots.Sdk.getSdkModificator`
java.lang.Throwable: Forbidden to mutate SDK outside of the `SdkModificator`. Please, use `com.intellij.openapi.projectRoots.Sdk.getSdkModificator`
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.setHomePath(ProjectJdkImpl.java:122)
	at org.elixir_lang.sdk.elixir.Type$Companion.createDefaultErlangSdk(Type.kt:474)
	at org.elixir_lang.sdk.elixir.Type$Companion.createDefaultErlangSdk(Type.kt:495)
	at org.elixir_lang.sdk.elixir.Type$Companion.defaultErlangSdk(Type.kt:513)
	at org.elixir_lang.sdk.elixir.Type$Companion.configureInternalErlangSdk(Type.kt:341)
	at org.elixir_lang.sdk.elixir.Type$Companion.configureSdkPaths(Type.kt:333)
	at org.elixir_lang.sdk.elixir.Type$Companion.access$configureSdkPaths(Type.kt:251)
	at org.elixir_lang.sdk.elixir.Type.setupSdkPaths(Type.kt:188)
	at com.intellij.openapi.projectRoots.SdkType.setupSdkPaths(SdkType.java:125)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.lambda$setupSdk$10(ProjectSdksModel.java:522)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:342)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$10(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:85)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-10 07:36:39,789 [  15061] SEVERE - #c.i.o.p.i.ProjectJdkImpl - IntelliJ IDEA 2024.3.1  Build #IU-243.22562.145
2024-12-10 07:36:39,789 [  15061] SEVERE - #c.i.o.p.i.ProjectJdkImpl - JDK: 21.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-12-10 07:36:39,789 [  15061] SEVERE - #c.i.o.p.i.ProjectJdkImpl - OS: Linux
2024-12-10 07:36:39,789 [  15061] SEVERE - #c.i.o.p.i.ProjectJdkImpl - Plugin to blame: Elixir version: 20.0.1
2024-12-10 07:36:39,789 [  15061] SEVERE - #c.i.o.p.i.ProjectJdkImpl - Last Action: WelcomeScreen.CreateNewProject
2024-12-10 07:36:39,814 [  15086] SEVERE - #c.i.o.p.Task - current thread is not owner
java.lang.IllegalMonitorStateException: current thread is not owner
	at java.base/java.lang.Object.notify(Native Method)
	at org.elixir_lang.jps.HomePath.eachEbinPath(HomePath.java:50)
	at org.elixir_lang.sdk.Type.addCodePaths(Type.kt:14)
	at org.elixir_lang.sdk.erlang.Type.setupSdkPaths(Type.kt:119)
	at org.elixir_lang.sdk.elixir.Type$Companion.createDefaultErlangSdk(Type.kt:475)
	at org.elixir_lang.sdk.elixir.Type$Companion.createDefaultErlangSdk(Type.kt:495)
	at org.elixir_lang.sdk.elixir.Type$Companion.defaultErlangSdk(Type.kt:513)
	at org.elixir_lang.sdk.elixir.Type$Companion.configureInternalErlangSdk(Type.kt:341)
	at org.elixir_lang.sdk.elixir.Type$Companion.configureSdkPaths(Type.kt:333)
	at org.elixir_lang.sdk.elixir.Type$Companion.access$configureSdkPaths(Type.kt:251)
	at org.elixir_lang.sdk.elixir.Type.setupSdkPaths(Type.kt:188)
	at com.intellij.openapi.projectRoots.SdkType.setupSdkPaths(SdkType.java:125)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.lambda$setupSdk$10(ProjectSdksModel.java:522)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:342)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$10(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:85)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-10 07:36:39,815 [  15087] SEVERE - #c.i.o.p.Task - IntelliJ IDEA 2024.3.1  Build #IU-243.22562.145
2024-12-10 07:36:39,815 [  15087] SEVERE - #c.i.o.p.Task - JDK: 21.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-12-10 07:36:39,815 [  15087] SEVERE - #c.i.o.p.Task - OS: Linux
2024-12-10 07:36:39,815 [  15087] SEVERE - #c.i.o.p.Task - Plugin to blame: Elixir version: 20.0.1
2024-12-10 07:36:39,815 [  15087] SEVERE - #c.i.o.p.Task - Last Action: WelcomeScreen.CreateNewProject

**Comment by victornoel** [comment]
Hi, I'm seeing the same issue with elixir and erlang installed via pacman on archlinux.

**Comment by victornoel** [comment]
looks like a duplicate of https://github.com/KronicDeth/intellij-elixir/issues/3655, cc @joshuataylor :)
