### ISSUE TITLE
NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.enter_section_

### ISSUE THREAD

**Issue by RatanPaul** [KronicDeth/intellij-elixir#391]
# Version

4.2.0

# Exception

## Message

com.intellij.lang.parser.GeneratedParserUtilBase.enter_section_(Lcom/intellij/lang/PsiBuilder;II)Lcom/intellij/lang/PsiBuilder$Marker;

## Stacktrace

```
java.lang.NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.enter_section_(Lcom/intellij/lang/PsiBuilder;II)Lcom/intellij/lang/PsiBuilder$Marker;
	at org.elixir_lang.parser.ElixirParser.expression(ElixirParser.java:1985)
	at org.elixir_lang.parser.ElixirParser.expressionList(ElixirParser.java:1999)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1_0(ElixirParser.java:1872)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1(ElixirParser.java:1863)
	at org.elixir_lang.parser.ElixirParser.elixirFile(ElixirParser.java:1848)
	at org.elixir_lang.parser.ElixirParser.parse_root_(ElixirParser.java:472)
	at org.elixir_lang.parser.ElixirParser.parseLight(ElixirParser.java:466)
	at org.elixir_lang.parser.ElixirParser.parse(ElixirParser.java:19)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.f(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:769)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstC

**Comment by KronicDeth** [comment]
* Which IDE
* Which version of the IDE
* Which version of JDK
* Which Operating System

**Comment by KronicDeth** [comment]
Opened a [question](https://intellij-support.jetbrains.com/hc/en-us/community/posts/207852029-Some-users-of-my-plugin-get-java-lang-NoSuchMethodError-com-intellij-lang-parser-GeneratedParserUtilBase-enter-section-) on the OpenAPI forum to see if JetBrains has any guidance.
