### ISSUE TITLE
Shipped GeneratedParserUtilBase not being used

### ISSUE THREAD

**Issue by dima-starosud** [KronicDeth/intellij-elixir#415]
# Version

4.3.0

# Exception

## Message

com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z

## Stacktrace

```
java.lang.NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
	at org.elixir_lang.parser.ElixirParser.unmatchedCaptureNonNumericOperation(ElixirParser.java:6114)
	at org.elixir_lang.parser.ElixirParser.unmatchedExpression(ElixirParser.java:5991)
	at org.elixir_lang.parser.ElixirParser.expression(ElixirParser.java:1987)
	at org.elixir_lang.parser.ElixirParser.expressionList(ElixirParser.java:1999)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1_0(ElixirParser.java:1872)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1(ElixirParser.java:1863)
	at org.elixir_lang.parser.ElixirParser.elixirFile(ElixirParser.java:1848)
	at org.elixir_lang.parser.ElixirParser.parse_root_(ElixirParser.java:472)
	at org.elixir_lang.parser.ElixirParser.parseLight(ElixirParser.java:466)
	at org.elixir_lang.parser.ElixirParser.parse(ElixirParser.java:19)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:85)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:784)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:520)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:506)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:592)
	at com.intellij.psi.util.PsiUtilCore.getElementAtOffset(PsiUtilCore.java:420)
	at com.intellij.psi.util.PsiUtilBase.getLanguageInEditor(PsiUtilBase.java:100)
	at com.intellij.psi.util.PsiUtilBase.getPsiFileInEditor(PsiUtilBase.java:134)
	at com.intellij.psi.util.PsiUtilBase.getPsiFileInEditor(PsiUtilBase.java:123)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lookForInjectedAndMatchBracesInOtherThread(BraceHighlightingHandler.java:116)
	at com.intellij.codeInsight.highlighting.BraceHighlighter.updateBraces(BraceHighlighter.java:127)
	at com.intellij.codeInsight.highlighting.BraceHighlighter$4.focusGained(BraceHighlighter.java:108)
	at sun.reflect.GeneratedMethodAccessor378.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy31.focusGained(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorImpl.fireFocusGained(EditorImpl.java:1159)
	at com.intellij.openapi.editor.impl.EditorImpl.access$4300(EditorImpl.java:124)
	at com.intellij.openapi.editor.impl.EditorImpl$11.focusGained(EditorImpl.java:1001)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.Component.processFocusEvent(Component.java:6422)
	at java.awt.Component.processEvent(Component.java:6289)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:986)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:610)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by KronicDeth** [comment]
Well, shit, I specifically fixed this in #406 (https://github.com/KronicDeth/intellij-elixir/pull/406/files#diff-dd52b9808466b58e76a25d50835004e7), but it got overwritten when I regenerated the parser for `canonicalNameSet` in https://github.com/KronicDeth/intellij-elixir/commit/9fa92ae3072e9ed1dc5b134c5b35cfd159405748#diff-dd52b9808466b58e76a25d50835004e7.  I'll need to add a test to ensure that the generate ElixirParser.java has then patch always present.
