### ISSUE TITLE
QualifiableAlias#fullyQualifiedName fails when there aren't 3 children

### ISSUE THREAD

**Issue by claudio-dalicandro** [KronicDeth/intellij-elixir#417]
# Version

4.2.0

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyQualifiedName(ElixirPsiImplUtil.java:2015)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl.fullyQualifiedName(ElixirUnmatchedQualifiedAliasImpl.java:51)
	at org.elixir_lang.reference.Module.resolvableName(Module.java:38)
	at org.elixir_lang.reference.Module.multiResolve(Module.java:165)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.a(PsiMultiReference.java:62)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.access$000(PsiMultiReference.java:37)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference$1.compare(PsiMultiReference.java:46)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference$1.compare(PsiMultiReference.java:38)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.a(PsiMultiReference.java:81)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.getRangeInElement(PsiMultiReference.java:97)
	at com.intellij.psi.ReferenceRange.getRanges(ReferenceRange.java:38)
	at com.intellij.codeInsight.completion.CompletionData.getReferencePrefix(CompletionData.java:161)
	at com.intellij.codeInsight.completion.CompletionData.findPrefixStatic(CompletionData.java:192)
	at com.intellij.codeInsight.completion.CompletionData.findPrefixStatic(CompletionData.java:203)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.createResultSet(CompletionServiceImpl.java:91)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:80)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:776)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:90)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:758)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
Is your source in a public github repo where I can clone it to reproduce the problem?  If not, can you give me your deps (assuming those are public projects), so I can see if it's the deps or your code that is causing the problem?  If you can make a smaller reproduction case yourself that would be helpful.  It will likely be while you're typing as it a `QualifiableAlias` should only not have 3 children when error recovery is active, so test if typing or pasting triggers it and report those steps.

The [line has moved to 2132 in v4.3.0](https://github.com/KronicDeth/intellij-elixir/blob/v4.3.0/src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java#L2132).

If you can't isolate the code causing the problem, then I'll "fix" this by changing the `assert` to a logged error that can report the element text to make it easier to debug next time it happens.
