### ISSUE TITLE
Null passed to highlightTypesAndTypeParameterUsages when start of atom is typed

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#420]
# Version

4.4.0-dev+20160908134805

# Excerpt

```
@spec ensure_closed(%AMQP.Channel{}) :: :
```

# Exception

## Message

Argument for @NotNull parameter 'psiElement' of org/elixir_lang/annonator/ModuleAttribute.highlightTypesAndTypeParameterUsages must not be null

## Stacktrace

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'psiElement' of org/elixir_lang/annonator/ModuleAttribute.highlightTypesAndTypeParameterUsages must not be null
	at org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java)
	at org.elixir_lang.annonator.ModuleAttribute.highlightSpecification(ModuleAttribute.java:507)
	at org.elixir_lang.annonator.ModuleAttribute.highlightSpecification(ModuleAttribute.java:257)
	at org.elixir_lang.annonator.ModuleAttribute.access$400(ModuleAttribute.java:37)
	at org.elixir_lang.annonator.ModuleAttribute$1.visitDeclaration(ModuleAttribute.java:105)
	at org.elixir_lang.annonator.ModuleAttribute$1.visitElement(ModuleAttribute.java:70)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:38)
	at org.elixir_lang.annonator.ModuleAttribute.annotate(ModuleAttribute.java:53)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:159)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:340)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:205)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:204)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

```

**Comment by KronicDeth** [comment]
So, if I had just listened to the warnings from IntelliJ this wouldn't have happened:

![screen shot 2016-09-10 at 4 37 36 pm](https://cloud.githubusercontent.com/assets/298259/18413683/f34ed794-7774-11e6-9c98-026d6a533eae.png)
