### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by andybeak** [KronicDeth/intellij-elixir#421]
# Version

4.4.0-dev+20160908134805

# Description

I'm using the Windows install method of getting Elixir.  The plugin is not recognizing the directory.  When I add elixir/bin as the directory I get this error.

# Exception

## Message

Argument for @NotNull parameter 'workDir' of org/elixir_lang/sdk/ElixirSystemUtil.getProcessOutput must not be null

## Stacktrace

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'workDir' of org/elixir_lang/sdk/ElixirSystemUtil.getProcessOutput must not be null
	at org.elixir_lang.sdk.ElixirSystemUtil.getProcessOutput(ElixirSystemUtil.java)
	at org.elixir_lang.mix.settings.MixConfigurationForm.validateMixPath(MixConfigurationForm.java:126)
	at org.elixir_lang.mix.settings.MixConfigurationForm.access$100(MixConfigurationForm.java:36)
	at org.elixir_lang.mix.settings.MixConfigurationForm$2.textChanged(MixConfigurationForm.java:77)
	at com.intellij.ui.DocumentAdapter.insertUpdate(DocumentAdapter.java:27)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1669)
	at com.intellij.ui.components.JBTextField.setText(JBTextField.java:59)
	at com.intellij.openapi.ui.TextComponentAccessor$1.setText(TextComponentAccessor.java:44)
	at com.intellij.openapi.ui.TextComponentAccessor$1.setText(TextComponentAccessor.java:36)
	at com.in

**Comment by andybeak** [comment]
Using the base Elixir directory works just fine.
