### ISSUE TITLE
PSI and index do not match in JSFile called from org.elixir_lang.psi.scope.module.Variants.addProjectNameElementsTo

### ISSUE THREAD

**Issue by kevinblade** [KronicDeth/intellij-elixir#433]
# Version

4.3.0

# Exception

## Message

PSI and index do not match

## Stacktrace

```
Please report the problem to JetBrains with the file attached
 file=JSFile:padStart.js, file.class=class com.intellij.lang.javascript.psi.impl.JSFileImpl, file.lang=Language: JavaScript, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(), no AST; with backReference
 document before=null
latestIndexedStub=null
 viewProvider={myVirtualFile=file:///Users/user1/Works/bia_project/cood_api_service/node_modules/lodash/padStart.js, content=VirtualFileContent{size=1026}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1471012454000; file length: 1026
 doc saved: true; doc stamp: 0; doc size: 1026; committed: true
in many projects: false
indexing info: no data
java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:497)
	at com.intellij.psi.stubs.StubProcessingHelper.stubTreeAndIndexDoNotMatch(StubProcessingHelper.java:43)
	at com.intellij.psi.stubs.StubProcessingHelperBase.a(StubProcessingHelperBase.java:172)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:162)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$1.process(StubIndexImpl.java:231)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:582)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:570)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:252)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:223)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at org.elixir_lang.psi.scope.module.Variants.addProjectNameElementsTo(Variants.java:150)
	at org.elixir_lang.psi.scope.module.Variants.lookupElementList(Variants.java:47)
	at org.elixir_lang.reference.Module.getVariants(Module.java:112)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:292)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:164)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:97)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor$1.consume(LegacyCompletionContributor.java:73)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor$1.consume(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:127)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:101)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:843)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:825)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:951)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:89)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

```

**Comment by KronicDeth** [comment]
This is weird, the error is going through my code, but the file is a JS file:
```
 file=JSFile:padStart.js, file.class=class com.intellij.lang.javascript.psi.impl.JSFileImpl, file.lang=Language: JavaScript, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(), no AST; with backReference
```

Is the file an EEX file for generating JS?

**Comment by KronicDeth** [comment]
Closing due to lack of feedback.  If you have more info to add that helps me reproduce I'll reopen.
