### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by BlueHotDog** [KronicDeth/intellij-elixir#446]
# Version

4.4.0

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.primaryArguments(ElixirPsiImplUtil.java:1428)
	at org.elixir_lang.psi.impl.ElixirUnmatchedCaptureNonNumericOperationImpl.primaryArguments(ElixirUnmatchedCaptureNonNumericOperationImpl.java:102)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.finalArguments(ElixirPsiImplUtil.java:2113)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.keywordArguments(ElixirPsiImplUtil.java:681)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.keywordArgument(ElixirPsiImplUtil.java:729)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasDoBlockOrKeyword(ElixirPsiImplUtil.java:2861)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:318)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:107)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:488)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:346)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:107)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:488)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:346)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:107)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:444)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:480)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:95)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsInPreviousSibling(ElixirPsiImplUtil.java:1644)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1543)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:57)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1046)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:84)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:800)
	at org.elixir_lang.reference.Callable.resolve(Callable.java:824)
	at org.elixir_lang.annonator.Callable$1.visitCall(Callable.java:60)
	at org.elixir_lang.annonator.Callable$1.visitElement(Callable.java:48)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:41)
	at org.elixir_lang.annonator.Callable.annotate(Callable.java:39)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:334)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:293)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:207)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by KronicDeth** [comment]
Do you have the code for when this was triggered?  It would be some code that is using a prefix operator as `org.elixir_lang.psi.impl.ElixirPsiImplUtil.primaryArguments(ElixirPsiImplUtil.java:1428)` is asserting that a prefix operation has only 2 children (the operator and operand).  It could have not 2 children due to the error recovery leaving no operand OR multiple operands.

**Comment by KronicDeth** [comment]
I don't now if it was your reproduction case, but I found one that will work as a regression test for now if you can't reproduce yours:

```
defmodule Prefix do
  !<<a
end
```

The `<<a` is an incomplete bitstring and so doesn't count as a valid operation and the `!` operation ends up with only the operator as the child.
