### ISSUE TITLE
Cannot Detect SDK Version - stacktrace in IDEA log

### ISSUE THREAD

**Issue by inkblot** [KronicDeth/intellij-elixir#489]
When I follow the directions in the README for adding an SDK that was not auto-detected, I get the error dialog with title "Cannot Detect SDK Version" and message "Probably SDK installed in '/path/to/sdk/lib/elixir' is corrupt. In the `idea.log` I see this stack trace:

```
java.lang.IllegalArgumentException: Must specify non-empty 'commandLine' parameter
        at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:65)
        at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:68)
        at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:58)
        at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:45)
        at org.elixir_lang.sdk.ElixirSystemUtil.execute(ElixirSystemUtil.java:95)
        at org.elixir_lang.sdk.ElixirSystemUtil.getProcessOutput(ElixirSystemUtil.java:85)
        at org.elixir_lang.sdk.ElixirSystemUtil.transformStdoutLine(ElixirSystemUtil.java:61)
        at org.elixir_lang.sdk.ElixirSdkType.detectSdkVersion(ElixirSdkType.java:190)
        at org.elixir_lang.sdk.ElixirSdkType.getRelease(ElixirSdkType.java:230)
```

**Comment by KronicDeth** [comment]
* Which version of the plug in are you using?
* Which OS are you on?
* How did you install Elixir?
* What path did you put in exactly?

**Comment by inkblot** [comment]
Plugin: version 4.4.0
OS: Ubuntu 14.04

Elixir: Installed version 1.3.0 using [`conda`](http://conda.pydata.org/docs/) in a path like `~/conda/envs/environment_name` which contains the Elixir SDK in `lib/elixir` and Erlang in `lib/erlang`, with symlinks to executables in `bin`.

SDK path: The `.../lib/elixir` directory which contains `bin/{elixir,elixirc,iex,mix}`.

Some contextual information from a basic unadulterated shell:
```
~/conda/envs/scratch $ echo $PS1
\w $ 
~/conda/envs/scratch $ ls -1 lib/elixir/bin
elixir
elixirc
iex
mix
~/conda/envs/scratch $ which elixir
~/conda/envs/scratch $ which erl
~/conda/envs/scratch $ file bin/elixir
/home/inkblot/conda/envs/scratch/bin/elixir: symbolic link to '../lib/elixir/bin/elixir'
~/conda/envs/scratch $ file bin/erl
/home/inkblot/conda/envs/scratch/bin/erl: symbolic link to '../lib/erlang/bin/erl'
~/conda/envs/scratch $ bin/elixir -v
bin/elixir: 126: exec: erl: not found
```

And after "entering" the conda environment:
```
~/conda/envs/scratch $ source activate scratch
discarding /home/inkblot/conda/bin from PATH
prepending /home/inkblot/conda/envs/scratch/bin to PATH
~/conda/envs/scratch $ which elixir
/home/inkblot/conda/envs/scratch/bin/elixir
~/conda/envs/scratch $ which erl
/home/inkblot/conda/envs/scratch/bin/erl
~/conda/envs/scratch $ elixir -v
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:12:12] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.0
~/conda/envs/scratch $ mix --version
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:12:12] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.3.0
```

It seems like what's needed is a way to detect that this SDK is in a conda environment and infer what the `PATH` for the environment would be after activation.

**Comment by sh41** [comment]
Fixed in [v24.0.1](https://github.com/KronicDeth/intellij-elixir/releases/tag/v24.0.1).

You were right about the cause — detecting the version ran the SDK's `elixir`, which needs `erl` on
`PATH`. Rather than infer a conda environment's `PATH`, version detection stopped running anything:
it reads `lib/elixir/ebin/elixir.app` and `releases/<N>/OTP_VERSION` off disk
([#3845](https://github.com/KronicDeth/intellij-elixir/pull/3845)). I didn't reproduce it with conda;
the claim is that no `PATH` is consulted anywhere on that path now.

Conda environments still aren't auto-detected, so you'd still add `lib/elixir` by hand. Worth its own
issue if you want that.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it,
but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and
tell us why.
