### ISSUE TITLE
StackOverflow through org.elixir_lang.psi.scope.module.MultiResolve.indexedNamedElements

### ISSUE THREAD

**Issue by roman462** [KronicDeth/intellij-elixir#511]
# Version

4.6.0

# Exception

## Message

null

## Stacktrace

```
java.lang.StackOverflowError
	at com.intellij.util.containers.ConcurrentHashSet.isEmpty(ConcurrentHashSet.java:50)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getUnsavedDocuments(FileDocumentManagerImpl.java:523)
	at com.intellij.util.indexing.FileBasedIndexImpl.getUnsavedDocuments(FileBasedIndexImpl.java:1165)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocuments(FileBasedIndexImpl.java:1184)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:714)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:681)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:335)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:316)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at org.elixir_lang.psi.scope.module.MultiResolve.indexedNamedElements(MultiResolve.java:44)
	at org.elixir_lang.psi.scope.module.MultiResolve.addUnaliasedNamedElementsToResolveResultList(MultiResolve.java:172)
	at org.elixir_lang.psi.scope.module.MultiResolve.executeOnAliasedName(MultiResolve.java:151)
	at org.elixir_lang.psi.scope.Module.executeOnMaybeAliasedName(Module.java:277)
	at org.elixir_lang.psi.scope.Module.execute(Module.java:56)
	at org.elixir_lang.psi.scope.module.MultiResolve.execute(MultiResolve.java:110)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1543)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations

**Comment by KronicDeth** [comment]
Related to #512

**Comment by KronicDeth** [comment]
@roman462, do you have a open source reproduction case I can use to reproduce the bug?
