### ISSUE TITLE
StackOverflow through getElementDescription

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#528]
Worker exited due to exception

```
java.lang.StackOverflowError
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:327)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:35)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:99)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:87)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:30)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:66)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:39)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:66)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:39)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at
<snip (basically a thousand of the previous lines repeating)>
```

**Comment by Havvy** [comment]
Unfortunately, I don't know what the actual elixir code that causes this is. I've ran into it twice though.

**Comment by KronicDeth** [comment]
Is your repository open source or can you make a minimal repo that reproduces the problem and share that?  If that doesn't work you could make a private repo and add me as a collaborator and finally if you can't do that we could screenshare using your computer and debug it on your computer.  We would need to setup the dev environment for the plugin on your machine though.

**Comment by Havvy** [comment]
The issue is more that it happens invisibly to me, so I don't notice it happening until after the fact. It's due to some invalid code while editing, but since I don't see it happening.

My repo is at @Havvy/gald but since that only contains valid compiling code, I don't think it'd actually help.

It might help to look at the logic of those three methods to see why they can recurse infinitely.

**Comment by Havvy** [comment]
I haven't seen it in the past few days, so it seems rare. I would not have this block v4.7.0.

**Comment by KronicDeth** [comment]
@Havvy have you been able to reproduce on `4.7.0` or should I close?

**Comment by Havvy** [comment]
I haven't been able to reproduce on v4.6.0 since I filed. Like I said, I have no clue what is actually causing this, as I only noticed well after the fact.

I guess closing it for now, until somebody spots it as it happens would be better?
