### ISSUE TITLE
org.elixir_lang.structure_view.element.CallDefinition.<init>(CallDefinition.java:121) AssertionError

### ISSUE THREAD

**Issue by Eiamnacken** [KronicDeth/intellij-elixir#544]
# Version

4.6.0

# Description

created new function defp()

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.structure_view.element.CallDefinition.<init>(CallDefinition.java:121)
	at org.elixir_lang.structure_view.element.CallDefinitionClause.<init>(CallDefinitionClause.java:303)
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderElement(CallDefinitionClause.java:44)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:396)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.b(LookupImpl.java:434)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:234)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:408)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addDelayedMiddleMatches(CompletionProgressIndicator.java:428)
	at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:108)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:877)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
[Line 121](https://github.com/KronicDeth/intellij-elixir/blob/v4.6.0/src/org/elixir_lang/structure_view/element/CallDefinition.java#L121) means that the `nameArityRange` is `null`

```java
    public CallDefinition(@NotNull Call call) {
        Pair<String, IntRange> nameArityRange = CallDefinitionClause.nameArityRange(call);

        assert nameArityRange != null;
```

The caller of `CallDefinition` clause should be guaranteeing this would be the case, but that's not the case; however, `CallDefinition(Call)` was replaced with `fromCall(Call)` in #537, so this fixed by that.
