### ISSUE TITLE
[auto-generated] java.lang.AssertionError at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderElement

### ISSUE THREAD

**Issue by szymon-jez** [KronicDeth/intellij-elixir#563]
# Version

4.7.0

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderElement(CallDefinitionClause.java:38)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:396)
	at com.intellij.codeInsight.lookup.impl.LookupCellRenderer.getListCellRendererComponent(LookupCellRenderer.java:147)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.updateListHeight(LookupImpl.java:419)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.updateList(LookupImpl.java:396)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.refreshUi(LookupImpl.java:1086)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.resort(LookupImpl.java:230)
	at com.intellij.codeInsight.lookup.impl.LookupUi.updateSorting(LookupUi.java:220)
	at com.intellij.codeInsight.lookup.impl.LookupUi.<init>(LookupUi.java:112)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.showLookup(LookupImpl.java:664)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.updateLookup(CompletionProgressIndicator.java:344)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$000(CompletionProgressIndicator.java:91)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1.run(CompletionProgressIndicator.java:103)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2489)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:288)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by szymon-jez** [comment]
:cool: Thanks!
