### ISSUE TITLE
Exception: Short name not matched for class org.elixir_lang.inspection.MatchOperatorInsteadOfTypeOperator: getShortName() = KeywordPairColonInsteadOfTypeOperator; ep.shortName = MatchOperatorInsteadOfTypeOperator

### ISSUE THREAD

**Issue by mfn** [KronicDeth/intellij-elixir#572]
Getting this pretty much every time I open a project.

Using PhpStorm 2017.1 EAP
Build #PS-171.1834.12, built on December 22, 2016
PhpStorm EAP User
Expiration date: January 21, 2017
JRE: 1.8.0_112-release-b620 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```
Short name not matched for class org.elixir_lang.inspection.MatchOperatorInsteadOfTypeOperator: getShortName() = KeywordPairColonInsteadOfTypeOperator; ep.shortName = MatchOperatorInsteadOfTypeOperator
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:85)
	at com.intellij.codeInspection.ex.ScopeToolState.equalTo(ScopeToolState.java:139)
	at com.intellij.codeInspection.ex.ToolsImpl.equals(ToolsImpl.java:473)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:43)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.a(InspectionProfileImpl.java:124)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.b(InspectionProfileImpl.java:846)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeExternal(InspectionProfileImpl.java:245)
	at com.intellij.profile.ProfileEx.writeScheme(ProfileEx.java:95)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeScheme(InspectionProfileImpl.java:215)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeScheme(InspectionProfileImpl.java:206)
	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:61)
	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:52)
	at com.intellij.configurationStore.SchemeManagerImpl$SchemeDataHolderImpl.updateDigest(SchemeManagerImpl.kt:378)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.a(InspectionProfileImpl.java:544)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initInspectionTools(InspectionProfileImpl.java:485)
	at com.intellij.profile.codeInspection.ProjectInspectionProfileManager$ProjectInspectionProfileStartUpActivity$runActivity$$inlined$apply$lambda$1.consume(ProjectInspectionProfileManager.kt:176)
	at org.jetbrains.concurrency.AsyncPromise.setHandler(AsyncPromise.kt:210)
	at org.jetbrains.concurrency.AsyncPromise.done(AsyncPromise.kt:43)
	at com.intellij.profile.codeInspection.ProjectInspectionProfileManager$ProjectInspectionProfileStartUpActivity.runActivity(ProjectInspectionProfileManager.kt:175)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:149)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:352)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:167)
	at com.intellij.openapi.project.DumbServiceImpl.c(DumbServiceImpl.java:294)
	at com.intellij.openapi.project.DumbServiceImpl.h(DumbServiceImpl.java:274)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:258)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:94)
	at com.intellij.openapi.project.DumbServiceImpl.d(DumbServiceImpl.java:257)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:89)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:39)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:408)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:397)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:809)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
Likely a copy and paste error since it's got the name of one of the older inspections.

**Comment by anstarovoyt** [comment]
172
Short name not matched for class org.elixir_lang.inspection.MatchOperatorInsteadOfTypeOperator: getShortName() = KeywordPairColonInsteadOfTypeOperator; ep.shortName = MatchOperatorInsteadOfTypeOperator

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:85)
	at com.intellij.codeInspection.ex.ScopeToolState.equalTo(ScopeToolState.java:132)
	at com.intellij.codeInspection.ex.ToolsImpl.equals(ToolsImpl.java:469)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:43)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.toolSettingsAreEqual(InspectionProfileImpl.java:118)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getChangedToolNames(InspectionProfileImpl.java:804)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeExternal(InspectionProfileImpl.java:239)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeScheme(InspectionProfileImpl.java:210)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeScheme(InspectionProfileImpl.java:200)
	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:64)
	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:54)
	at com.intellij.configurationStore.SchemeManagerImpl.saveScheme(SchemeManagerImpl.kt:586)
	at com.intellij.configurationStore.SchemeManagerImpl.save(SchemeManagerImpl.kt:532)
	at com.intellij.configurationStore.SchemeManagerFactoryBase.save(SchemeManagerFactoryImpl.kt:101)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:185)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:46)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:349)
	at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:137)
	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:125)
	at com.intellij.ide.SaveAndSyncHandlerImpl$2.lambda$onFrameDeactivated$0(SaveAndSyncHandlerImpl.java:94)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.ide.SaveAndSyncHandlerImpl$2.onFrameDeactivated(SaveAndSyncHandlerImpl.java:92)
	at com.intellij.ide.FrameStateManagerImpl.fireDeactivationEvent(FrameStateManagerImpl.java:84)
	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
	at com.intellij.ide.FrameStateManagerImpl$2.lambda$applicationDeactivated$0(FrameStateManagerImpl.java:70)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:224)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by KronicDeth** [comment]
@anstarovoyt https://github.com/KronicDeth/intellij-elixir/commit/3da22f7f07659f41414a2d35cf5fec1a481d7e83 was released in 4.8.0.  The current latest version of the plugin is 5.1.0.  Are you using the latest version of the plugin?

**Comment by anstarovoyt** [comment]
@KronicDeth Hi. I don't use the plugin I just inform you about the exception from our (JetBrains) internal exception analyzing system.

**Comment by KronicDeth** [comment]
@anstarovoyt do you have the user information or JetBrains ticket, so I can contact the users to tell them to upgrade the plugin?   Or I guess you could do that too so you don't have to disclose user information.

**Comment by anstarovoyt** [comment]
@mfn sorry the system doesn't contain the information. It just an exception + IDE version.
