### ISSUE TITLE
Unexpected content storage modification in org.elixir_lang.psi.scope.module.MultiResolve.indexedNamedElement

### ISSUE THREAD

**Issue by josuehenrique** [KronicDeth/intellij-elixir#628]
# Version

4.7.0

# Exception

## Message

Unexpected content storage modification

## Stacktrace

```
java.lang.AssertionError: Unexpected content storage modification
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.a(FSRecords.java:1754)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.access$2500(FSRecords.java:60)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$ContentOutputStream.writeBytes(FSRecords.java:1661)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeContent(FSRecords.java:1580)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.a(PersistentFSImpl.java:236)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:511)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:127)
	at com.intellij.ide.caches.FileContent.getBytes(FileContent.java:49)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1541)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:507)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1528)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1513)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1493)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1649)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1646)
	at com.intellij.util.indexing.UpdateTask.a(UpdateTask.java:80)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:47)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1668)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:687)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:655)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:344)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:325)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at org.elixir_lang.psi.scope.module.MultiResolve.indexedNamedElements(MultiResolve.java:45)
	at org.elixir_lang.psi.scope.module.MultiResolve.addUnaliasedNamedElementsToResolveResultList(MultiResolve.java:174)
	at org.elixir_lang.psi.scope.module.MultiResolve.executeOnAliasedName(MultiResolve.java:144)
	at org.elixir_lang.psi.scope.Module.executeOnMaybeAliasedName(Module.java:277)
	at org.elixir_lang.psi.scope.Module.executeOnAliasCallArgument(Module.java:224)
	at org.elixir_lang.psi.scope.Module.executeOnAliasCallArgument(Module.java:137)
	at org.elixir_lang.psi.scope.Module.executeOnAliasCall(Module.java:113)
	at org.elixir_lang.psi.scope.Module.execute(Module.java:58)
	at org.elixir_lang.psi.scope.module.MultiResolve.execute(MultiResolve.java:112)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsInPreviousSibling(ElixirPsiImplUtil.java:1689)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1588)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:57)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1058)
	at org.elixir_lang.psi.scope.module.MultiResolve.resolveResultList(MultiResolve.java:61)
	at org.elixir_lang.psi.scope.module.MultiResolve.resolveResultList(MultiResolve.java:34)
	at org.elixir_lang.reference.Module.multiResolve(Module.java:52)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.fullyResolveAlias(ElixirPsiImplUtil.java:2258)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.aliasToModular(ElixirPsiImplUtil.java:5542)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.maybeAliasToModular(ElixirPsiImplUtil.java:5532)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.qualifiedToModular(ElixirPsiImplUtil.java:5392)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:617)
	at org.elixir_lang.annonator.Callable$1.visitCall(Callable.java:69)
	at org.elixir_lang.annonator.Callable$1.visitElement(Callable.java:52)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedParenthesesCallImpl.accept(ElixirUnmatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annonator.Callable.annotate(Callable.java:43)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by KronicDeth** [comment]
I can't reproduce.  If you figure out more specific steps, add a comment and I'll reopen.
