### ISSUE TITLE
Dependency on org.junit in non-test code

### ISSUE THREAD

**Issue by jansenm** [KronicDeth/intellij-elixir#714]
# Version

5.1.0

# Description

Happens when looking at vutuv/lib/vutuv/browserstack.ex from vutuv/vutuv here on github in !!WebStorm!! with this plugin enabled.

# Exception

## Message

org/junit/ComparisonFailure

## Stacktrace

```
java.lang.NoClassDefFoundError: org/junit/ComparisonFailure
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quoteLiteral(ElixirPsiImplUtil.java:4714)
	at org.elixir_lang.psi.impl.ElixirStringLineImpl.quoteLiteral(ElixirStringLineImpl.java:90)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quotedChildNodes(ElixirPsiImplUtil.java:5772)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quotedChildNodes(ElixirPsiImplUtil.java:5730)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quote(ElixirPsiImplUtil.java:3530)
	at org.elixir_lang.psi.impl.ElixirStringLineImpl.quote(ElixirStringLineImpl.java:70)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quoteAsAtom(ElixirPsiImplUtil.java:3301)
	at org.elixir_lang.psi.impl.ElixirStringLineImpl.quoteAsAtom(ElixirStringLineImpl.java:75)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quote(ElixirPsiImplUtil.java:3690)
	at org.elixir_lang.psi.impl.ElixirKeywordKeyImpl.quote(ElixirKeywordKeyImpl.java:56)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasKeywordKey(ElixirPsiImplUtil.java:3107)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.keywordValue(ElixirPsiImplUtil.java:778)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.keywordArgument(ElixirPsiImplUtil.java:750)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasDoBlockOrKeyword(ElixirPsiImplUtil.java:3084)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.useScopeSelector(ElixirPsiImplUtil.java:586)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.createsNewScope(ElixirPsiImplUtil.java:599)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsInPreviousSibling(ElixirPsiImplUtil.java:1705)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1605)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:57)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1075)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:90)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:693)
	at org.elixir_lang.annonator.Callable$1.visitNonModuleAttributeCall(Callable.java:103)
	at org.elixir_lang.annonator.Callable$1.visitCall(Callable.java:68)
	at org.elixir_lang.annonator.Callable$1.visitElement(Callable.java:57)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:42)
	at org.elixir_lang.annonator.Callable.annotate(Callable.java:48)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.junit.ComparisonFailure PluginClassLoader[org.elixir_lang, 5.1.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 57 more

```

**Comment by DenisGorbachev** [comment]
Same here.

Linux Mint 18.1 Serena

![1501337462232](https://user-images.githubusercontent.com/829578/28745423-ca29c838-7467-11e7-9046-09af85c4009b.jpg)

**Comment by KronicDeth** [comment]
`org/junit/ComparisonFailure` is a test-only dependency.  I'll have to look into how a test dependency got into the normal runtime code.
