### ISSUE TITLE
[auto-generated] Argument for @NotNull parameter 'obj' of com/intellij/util/containers/SmartHashSet.add must not be null

### ISSUE THREAD

**Issue by JanStevens** [KronicDeth/intellij-elixir#718]
# Version

5.1.0

# Exception

## Message

Argument for @NotNull parameter 'obj' of com/intellij/util/containers/SmartHashSet.add must not be null

## Stacktrace

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'obj' of com/intellij/util/containers/SmartHashSet.add must not be null
	at com.intellij.util.containers.SmartHashSet.add(SmartHashSet.java)
	at org.elixir_lang.psi.stub.type.call.Stub.readNameSet(Stub.java:38)
	at org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes$2.deserialize(ModuleStubElementTypes.java:94)
	at org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes$2.deserialize(ModuleStubElementTypes.java:70)
	at com.intellij.psi.stubs.StubSerializationHelper.a(StubSerializationHelper.java:197)
	at com.intellij.psi.stubs.StubSerializationHelper.a(StubSerializationHelper.java:203)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:151)
	at com.intellij.psi.stubs.SerializationManagerImpl.deserialize(SerializationManagerImpl.java:164)
	at com.intellij.psi.stubs.SerializedStubTree.getStub(SerializedStubTree.java:89)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:52)
	at org.elixir_lang.beam.psi.BeamFileImpl.getStubTree(BeamFileImpl.java:261)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:73)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:53)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:331)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:615)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:603)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:360)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at org.elixir_lang.reference.Module.namedElementCollection(Module.java:104)
	at org.elixir_lang.reference.Module.forEachNavigationElement(Module.java:60)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImports(CallDefinitionClause.java:132)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.java:122)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.java:44)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1555)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:147)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1103)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.resolveResultList(MultiResolve.java:42)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.resolveResultList(MultiResolve.java:32)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:705)
	at org.elixir_lang.reference.Callable.resolve(Callable.java:730)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:389)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:366)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:236)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:208)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by asheehan** [comment]
I'm getting the same issue with the latest IDEA and Elixir plugin `Argument for @NotNull parameter 'obj' of com/intellij/util/containers/SmartHashSet.add must not be null`

**Comment by asheehan** [comment]
@KronicDeth a `mix new repo --sup` project that exhibits this issue: https://github.com/asheehan/bug_test

stacktrace:
```
In file: file:///Users/asheehan/work/repos/dev-tools/code/bug_test/lib/bug_test/application.ex: Argument for @NotNull parameter 'obj' of com/intellij/util/containers/SmartHashSet.add must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'obj' of com/intellij/util/containers/SmartHashSet.add must not be null
	at com.intellij.util.containers.SmartHashSet.add(SmartHashSet.java)
	at org.elixir_lang.psi.stub.type.call.Stub.readNameSet(Stub.java:38)
	at org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes$2.deserialize(ModuleStubElementTypes.java:94)
	at org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes$2.deserialize(ModuleStubElementTypes.java:70)
	at com.intellij.psi.stubs.StubSerializationHelper.a(StubSerializationHelper.java:197)
	at com.intellij.psi.stubs.StubSerializationHelper.a(StubSerializationHelper.java:203)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:151)
	at com.intellij.psi.stubs.SerializationManagerImpl.deserialize(SerializationManagerImpl.java:164)
	at com.intellij.psi.stubs.SerializedStubTree.getStub(SerializedStubTree.java:89)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:52)
	at org.elixir_lang.beam.psi.BeamFileImpl.getStubTree(BeamFileImpl.java:261)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:73)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:53)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:331)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:615)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:603)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:360)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at org.elixir_lang.reference.Module.namedElementCollection(Module.java:104)
	at org.elixir_lang.reference.Module.forEachNavigationElement(Module.java:60)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImports(CallDefinitionClause.java:132)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.java:122)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.java:44)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1555)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:147)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1103)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.resolveResultList(MultiResolve.java:42)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.resolveResultList(MultiResolve.java:32)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:705)
	at org.elixir_lang.annonator.Callable$1.visitNonModuleAttributeCall(Callable.java:103)
	at org.elixir_lang.annonator.Callable$1.visitCall(Callable.java:68)
	at org.elixir_lang.annonator.Callable$1.visitElement(Callable.java:57)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at org.elixir_lang.annonator.Callable.annotate(Callable.java:48)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
