### ISSUE TITLE
Failed to setup debugger environment

### ISSUE THREAD

**Issue by ctrlpz** [KronicDeth/intellij-elixir#739]
Plugin version: source code from Github (today - 20/7/2017)
IntelliJ IDEA 2017.1.5
OS: macOS Sierra

I set a line breakpoint and clicked on Debug button on toolbar. I got this message 
```Error running ElixirRun: Failed to setup debugger environment``` 

This is the stack trace I got from the IOException in class `ElixirXDebugProcess`, method `setUpElixirDebuggerCodePath`. I also print the values of `file` and `tempDirectory` variables.

Stacktrace:
<details>
/Users/carmentorres/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.1.5/d5ace92941f28d3221839192f3cedab1fa908cde/ideaIC-2017.1.5/bin/mac/idea.properties:` 'apple.laf.useScreenMenuBar' already defined
--file Elixir.Mix.Tasks.IntellijElixir.DebugTask.beam
--tempDirectory /private/var/folders/3m/6zgj5lkj28s2nq5xcjzrk7bh0000gn/T/intellij_elixir_debugger
java.io.IOException: Failed to locate debugger module: Elixir.Mix.Tasks.IntellijElixir.DebugTask.beam
        at org.elixir_lang.debugger.xdebug.ElixirXDebugProcess.copyFileTo(ElixirXDebugProcess.java:141)
        at org.elixir_lang.debugger.xdebug.ElixirXDebugProcess.setUpElixirDebuggerCodePath(ElixirXDebugProcess.java:127)
        at org.elixir_lang.debugger.xdebug.ElixirXDebugProcess.runDebugTarget(ElixirXDebugProcess.java:358)
        at org.elixir_lang.debugger.xdebug.ElixirXDebugProcess.<init>(ElixirXDebugProcess.java:107)
        at org.elixir_lang.debugger.xdebug.ElixirDebugRunner$1.start(ElixirDebugRunner.java:47)
        at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:217)
        at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:178)
        at org.elixir_lang.debugger.xdebug.ElixirDebugRunner.doExecute(ElixirDebugRunner.java:43)
        at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:40)
        at com.intellij.execution.RunProfileStarter.executeAsync(RunProfileStarter.java:43)
        at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$7(ExecutionManagerImpl.java:390)
        at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
        at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
        at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
        at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$8(ExecutionManagerImpl.java:447)
        at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:304)
        at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:447)
        at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:37)
        at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
        at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
        at com.intellij.execution.ProgramRunnerUtil.executeConfigurationAsync(ProgramRunnerUtil.java:125)
        at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:58)
        at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:122)
        at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:69)
        at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:539)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
        at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
        at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
        at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</details>

Note: 
With version 5.1.0 of the plugin the breakpoint does not trigger. In console I read this `*DBG* 'Elixir.IntellijElixir.DebugServer' got {'DOWN',
                                               #Ref<0.804846805.1348468737.145948>,
                                               process,<0.104.0>,normal}`

**Comment by KronicDeth** [comment]
I removed the compiled `.beam` files in https://github.com/KronicDeth/intellij-elixir/commit/58e7d4aafa6ad44279d15dd92f40c35e00d7357e#diff-3e16e76db06abea583aa30d40012fa15, but that shipped with v5.1.0, so I think however you're building it locally is not rebuilding the `.beam` on-demand.  The normal, non-debug runner copies the `.ex` files into a directory, not the `.beam`, so it may be that the debugger setup needs to be changed to do that, but I'm not having the same problem locally, but my sandbox may be preserving the old built `.beam`s

**Comment by ctrlpz** [comment]
Thanks for your reply!
I had problems for rebuilding the .beam files. Right now I do not have this folder in the project `intellij-elixir/resources/debugger/_build/`.
I tried to generate it with `./gradlew build` but I got some failing tests: org.elixir_lang.beam.BeamTest > erlangModule FAILED
    java.io.FileNotFoundException: /Users/carmentorres/GitHub-repositories/IntelliJ-Plugins/IntelliJ-Elixir/intellij-elixir-master/cache/elixir-1.4.5/lib/elixir/ebin/elixir_interpolation.beam (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.elixir_lang.beam.BeamTest.beam(BeamTest.java:104)
        at org.elixir_lang.beam.BeamTest.erlangModule(BeamTest.java:66)

org.elixir_lang.beam.BeamTest > elixirModule FAILED
    java.io.FileNotFoundException: /Users/carmentorres/GitHub-repositories/IntelliJ-Plugins/IntelliJ-Elixir/intellij-elixir-master/cache/elixir-1.4.5/lib/elixir/ebin/Elixir.Kernel.beam (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.elixir_lang.beam.BeamTest.beam(BeamTest.java:104)
        at org.elixir_lang.beam.BeamTest.elixirModule(BeamTest.java:26)

org.elixir_lang.beam.DecompilerTest > testIssue575 FAILED
    junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertNotNull(Assert.java:256)
        at junit.framework.Assert.assertNotNull(Assert.java:248)
        at junit.framework.TestCase.assertNotNull(TestCase.java:417)
        at org.elixir_lang.beam.DecompilerTest.testIssue575(DecompilerTest.java:27)

Could you tell me what I'm missing here that I cannot build the `.beam` files?

**Comment by KronicDeth** [comment]
@ctrlpz you should being building the install plugin with `./gradlew buildPlugin`, which puts it in `build/distributions` OR you can just use the sandbox version and use the `runIde` task from the Gradle menu in IntelliJ.

**Comment by erikreedstrom** [comment]
This bit me today too after upgrading to v6 of the plugin. Reverting to v5.1 resolved.

**Comment by KronicDeth** [comment]
Thanks for a confirmation that's it's a 5.1.0 vs 6.0.0; I guess it wasn't the delete the `.beam` change since that was in `5.1.0`.

**Comment by KronicDeth** [comment]
I can reproduce in the Windows VM I used for #603.

**Comment by KronicDeth** [comment]
@erikreedstrom 6.1.0 is out with the fix.  Let me know if it's still broke.

**Comment by erikreedstrom** [comment]
Failing now with different error:
```
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :enetunreach}
        /private/var/folders/1_/dx377ms93lj304_fft0nm5kh0000gp/T/intellij_elixir391/debugger/lib/debug_server.ex:9: IntellijElixir.DebugServer.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

on this line

```elixir
{:ok, socket} = :gen_tcp.connect(host, port, opts)
```

**Comment by erikreedstrom** [comment]
Checks out! Thanks for the fast turn around!!! 🙇

**Comment by KronicDeth** [comment]
@erikreedstrom I'm curious, how did you fix the first error you got? In case other users hit it, I'd like the error and fix to be searchable here.

> Failing now with different error:
>
> ** (EXIT from #PID<0.73.0>) an exception was raised:
>    ** (MatchError) no match of right hand side value: {:error, :enetunreach}
> /private/var/folders/1_/dx377ms93lj304_fft0nm5kh0000gp/T/intellij_elixir391/debugger/lib/debug_server.ex:9: IntellijElixir.DebugServer.init/1
>        (stdlib) gen_server.erl:365: :gen_server.init_it/2
>        (stdlib) gen_server.erl:333: :gen_server.init_it/6
>        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
> on this line
>
> {:ok, socket} = :gen_tcp.connect(host, port, opts)

**Comment by erikreedstrom** [comment]
☝️ That was just an open port 😬
