### ISSUE TITLE
Error when begin breakpoint-debugging

### ISSUE THREAD

**Issue by sintro** [KronicDeth/intellij-elixir#794]
# Version

6.1.0

# Exception

## Message

org/intellij/erlang/icons/ErlangIcons

## Stacktrace

```
java.lang.NoClassDefFoundError: org/intellij/erlang/icons/ErlangIcons
	at org.elixir_lang.debugger.xdebug.xvalue.ElixirArrayXValueBase.getIcon(ElixirXValueBase.java:162)
	at org.elixir_lang.debugger.xdebug.xvalue.ElixirXValueBase.computePresentation(ElixirXValueBase.java:70)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:70)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.a(XValueContainerNode.java:97)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:86)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:83)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:102)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by sintro** [comment]
The problem is solved. 
It turns out, you need to install Erlang plugin for IDEA for everything work fine. It is weird to require whole plugin to use some icons in another plugin...

**Comment by KronicDeth** [comment]
@sintro intellij-erlang use to be an accidental hard-dependency, instead of a soft-dependency, but that was fixed in #754; however, the debugger was added in the time when intellij-erlang was an accidental hard-dependency, so the PR for the debugger assumed it was safe to use the icons directly from intellij-erlang.  The fix is to copy the icons out of intellij-erlang instead of depending on intellij-erlang

**Comment by KronicDeth** [comment]
🤦‍♂️  All the ErlangIcon references actually point to icons that ship with Intellij-community, so the indirection through ErlangIcons was complete unnecessary.  No need to copy them form intellij-erlang
![screen shot 2017-08-15 at 8 54 40 pm](https://user-images.githubusercontent.com/298259/29344273-33fbd64c-81fc-11e7-8139-eac2f70b1222.png)
 because they're not really in there.

![screen shot 2017-08-15 at 8 54 52 pm](https://user-images.githubusercontent.com/298259/29344274-381dee68-81fc-11e7-9ec7-8cbfa8e6edde.png)

![screen shot 2017-08-15 at 8 55 02 pm](https://user-images.githubusercontent.com/298259/29344280-4453dce2-81fc-11e7-85fc-1f6af5b05d5d.png)

**Comment by sintro** [comment]
Ok, I see.

PS. Speaking of breakpoint debugger. Is it planned (or even possible?) to add "Code Evaluation" for breakpoint debug mode?
