### ISSUE TITLE
Debug process OTP/Elixir version problem

### ISSUE THREAD

**Issue by merqlove** [KronicDeth/intellij-elixir#815]
Looks like debug process running under another OTP than selected Elixir.
Also in current case `INTELLIJ_ELIXIR_DEBUG_BLACKLIST` won't help.

```
/usr/local/Cellar/asdf/0.3.0/installs/Elixir/1.5.1/bin/elixir -r /private/var/folders/2w/nqmp105j08z9pvgf475p56sh0000gn/T/intellij_elixir983/debugger/lib/debug_server.ex -r /private/var/folders/2w/nqmp105j08z9pvgf475p56sh0000gn/T/intellij_elixir983/debugger/lib/debug_task.ex /usr/local/Cellar/asdf/0.3.0/installs/Elixir/1.5.1/bin/mix intellij_elixir.debug_task --debugger-port 50525 -- phx.server

```

```
INTELLIJ_ELIXIR_DEBUG_BLACKLIST=bcrypt_elixir,iconv,comeonin,elixir_make
```

```
07:44:22.483 [error] Process #PID<0.7660.0> raised an exception
** (RuntimeError) You need to have Erlang 20 installed to use this version of bcrypt_elixir.
Either upgrade to Erlang 20 or use version 0.12 of bcrypt_elixir.

    lib/bcrypt/base.ex:14: Bcrypt.Base.init/0
    (kernel) code_server.erl:1333: anonymous fn/1 in :code_server.handle_on_load/5

07:44:22.492 [warn]  The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{message: "You need to have Erlang 20 installed to use this version of bcrypt_elixir.\nEither upgrade to Erlang 20 or use version 0.12 of bcrypt_elixir.\n"},
 [{Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 14]},
  {:code_server, :"-handle_on_load/5-fun-0-", 1,
   [file: 'code_server.erl', line: 1333]}]}

** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    int.erl:531: anonymous fn/3 in :int.load/2
    int.erl:527: :int.load/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    /private/var/folders/2w/nqmp105j08z9pvgf475p56sh0000gn/T/intellij_elixir983/debugger/lib/debug_task.ex:17: Mix.Tasks.IntellijElixir.DebugTask.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
```

**Comment by merqlove** [comment]
Seems it's because of few atom's.

Success list:
```
INTELLIJ_ELIXIR_DEBUG_BLACKLIST=Elixir.Bcrypt.Base,Elixir.Bcrypt.Stats,Elixir.Bcrypt,bcrypt_elixir,iconv,comeonin
```

**Comment by merqlove** [comment]
Added PR's #817  #816
