### ISSUE TITLE
java.lang.AssertionError while just looking at a file

### ISSUE THREAD

**Issue by raarts** [KronicDeth/intellij-elixir#868]
# Version

6.3.0

# Description

Actually I was just looking at a file (router.ex)

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.annotator.Credo.stripEdge(Credo.java:190)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
	at org.elixir_lang.annotator.Credo.explanationToToolTip(Credo.java:288)
	at org.elixir_lang.annotator.Credo.lambda$apply$1(Credo.java:273)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.elixir_lang.annotator.Credo.apply(Credo.java:272)
	at org.elixir_lang.annotator.Credo.apply(Credo.java:38)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.applyRelevant(ExternalToolPass.java:190)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$700(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
1. Which version of `credo` do you have installed.
2. Run `mix credo` in a terminal and post the output.

The credo output is a format I wasn't expecting, so it's triggering the assertion.

**Comment by raarts** [comment]
credo version 0.8.8

here's the output:

```
mix credo
info: Some source files could not be parsed correctly and are excluded:

   1) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.channel/channel.ex
   2) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.json/view.ex
   3) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.html/view.ex
   4) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.channel/channel_test.exs
   5) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.embedded/embedded_schema.ex
   6) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.json/controller.ex
   7) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.model/model_test.exs
   8) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.html/controller.ex
   9) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.html/controller_test.exs
  10) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.html/controller_test.exs
  11) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.json/changeset_view.ex
  12) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.channel/channel.ex
  13) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.context/context_test.exs
  14) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.schema/migration.exs
  15) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.model/migration.exs
  16) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.context/context.ex
  17) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.html/view.ex
  18) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.channel/channel_test.exs
  19) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.json/changeset_view.ex
  20) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.html/controller.ex
  21) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.context/access_no_schema.ex
  22) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.context/schema_access.ex
  23) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.json/fallback_controller.ex
  24) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.schema/schema.ex
  25) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.json/controller.ex
  26) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.presence/presence.ex
  27) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.json/controller_test.exs
  28) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.json/controller_test.exs
  29) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.json/view.ex
  30) apps/api_web/assets/node_modules/phoenix/priv/templates/phoenix.gen.model/model.ex
  31) apps/api_web/assets/node_modules/phoenix/priv/templates/phx.gen.context/test_cases.exs

Checking 131 source files (this might take a while) ...

  Software Design
┃
┃ [D] → Found a TODO tag in a comment: # TODO: Remove me on 3.0
┃       apps/api_web/assets/node_modules/phoenix_html/lib/phoenix_html/form.ex:382 #(Phoenix.HTML.Form.input_type)
┃ [D] → Found a TODO tag in a comment: # TODO: Remove me on 3.0
┃       apps/api_web/assets/node_modules/phoenix_html/lib/phoenix_html/form.ex:350 #(Phoenix.HTML.Form.input_validations)
┃ [D] → Found a TODO tag in a comment: # TODO v1.4: Deprecate {:system, env_var}
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/socket/transport.ex:477 #(Phoenix.Socket.Transport.compare_host?)
┃ [D] → Found a TODO tag in a comment: # TODO v2: Remove 2-arity
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/socket/transport.ex:316 #(Phoenix.Socket.Transport.on_exit_message)
┃ [D] → Found a TODO tag in a comment: # TODO v1.4: No longer support old
┃       manifests
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/endpoint/supervisor.ex:333 #(Phoenix.Endpoint.Supervisor.cache_static_manifest)
┃  ...  (14 more, use `-a` to show them)

  Code Readability
┃
┃ [R] ↗ Large numbers should be written with underscores: 1_209_600
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/transports/long_poll.ex:47:24 #(Phoenix.Transports.LongPoll.default_config)
┃ [R] ↗ Large numbers should be written with underscores: 86_400
┃       apps/api_web/test/api_web/controllers/hammer_test.exs:70:34 #(APIWeb.HammerUserTest)
┃ [R] ↗ Large numbers should be written with underscores: 86_400
┃       apps/api_web/test/api_web/controllers/my_api_test.exs:78:23 #(APIWeb.MyAPITest)
┃ [R] ↗ Large numbers should be written with underscores: 26_379
┃       apps/api_web/config/prod.exs:64:93 #()
┃ [R] ↗ Large numbers should be written with underscores: 26_379
┃       apps/api_web/config/prod.exs:64:53 #()
┃  ...  (8 more, use `-a` to show them)

  Refactoring opportunities
┃
┃ [F] → Function takes too many parameters (arity is 8, max is 5).
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/transports/long_poll_server.ex:36:7 #(Phoenix.Transports.LongPoll.Server.start_link)
┃ [F] → Function takes too many parameters (arity is 7, max is 5).
┃       apps/api_web/assets/node_modules/phoenix_html/lib/phoenix_html/form.ex:1186:8 #(Phoenix.HTML.Form.datetime_options)
┃ [F] → Function takes too many parameters (arity is 7, max is 5).
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/socket/transport.ex:181:8 #(Phoenix.Socket.Transport.do_connect)
┃ [F] → Function takes too many parameters (arity is 7, max is 5).
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/router/scope.ex:21:7 #(Phoenix.Router.Scope.route)
┃ [F] → Function takes too many parameters (arity is 6, max is 5).
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/socket/transport.ex:147:7 #(Phoenix.Socket.Transport.connect)
┃  ...  (50 more, use `-a` to show them)

  Warnings - please take a look
┃
┃ [W] ↗ Prefer lazy Logger calls.
┃       apps/api_web/lib/plugs/subject.ex:93 #(APIWeb.Plugs.Subject.save_in_redis)
┃ [W] ↗ Prefer lazy Logger calls.
┃       apps/api_web/lib/plugs/subject.ex:82 #(APIWeb.Plugs.Subject.store_result_in_conn)
┃ [W] ↗ Prefer lazy Logger calls.
┃       apps/api_web/lib/plugs/subject.ex:78 #(APIWeb.Plugs.Subject.store_result_in_conn)
┃ [W] ↗ There should be no calls to IO.inspect/1.
┃       apps/api_web/lib/api_web/controllers/my_controller.ex:31:34 #(APIWeb.MyController.method)
┃ [W] ↗ Prefer lazy Logger calls.
┃       apps/api_web/lib/plugs/subject.ex:109 #(APIWeb.Plugs.Subject.load_from_oapi)
┃  ...  (5 more, use `-a` to show them)

  Consistency
┃
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       apps/api_web/assets/node_modules/phoenix_html/lib/phoenix_html/form.ex:1166:61 #(Phoenix.HTML.Form.datetime_builder)
┃ [C] ↗ There is no whitespace around parentheses/brackets most of the time, but
┃       here there is.
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/socket/transport.ex:301 #(Phoenix.Socket.Transport.log)
┃ [C] ↗ There is no whitespace around parentheses/brackets most of the time, but
┃       here there is.
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/socket/transport.ex:300 #(Phoenix.Socket.Transport.log)
┃ [C] ↗ File has the variable name before the pattern while most of the files
┃       have the variable name after the pattern when naming parameter pattern
┃       matches
┃       apps/api_web/assets/node_modules/phoenix/lib/phoenix/socket.ex:230:14 #(Phoenix.Socket.assign)
┃ [C] ↗ There is no whitespace around parentheses/brackets most of the time, but
┃       here there is.
┃       apps/api_web/lib/api_web/controllers/my_controller.ex:93 #(APIWeb.MyController.put_resp_headers_safe)
┃  ...  (14 more, use `-a` to show them)

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 9.5 seconds (0.4s to load, 9.0s running checks)
1513 mods/funs, found 19 consistency issues, 10 warnings, 55 refactoring opportunities, 13 code readability issues, 19 software design suggestions.

Showing priority issues: ↑ ↗ →  (use `--strict` to show all issues, `--help` for options).
```
