### ISSUE TITLE
Runtime error when loading Bcrypt (ERL 20 / Elixir 1.5.2)

### ISSUE THREAD

**Issue by DominikGuzei** [KronicDeth/intellij-elixir#891]
Im using Bcrypt 1.0 in my project and when i try to debug the application from Webstorm im getting this error:

```
10:17:01.408 [error] Process #PID<0.6721.0> raised an exception
** (RuntimeError) An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.

    lib/bcrypt/base.ex:14: Bcrypt.Base.init/0
    (kernel) code_server.erl:1333: anonymous fn/1 in :code_server.handle_on_load/5
** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    int.erl:531: anonymous fn/3 in :int.load/2
    int.erl:527: :int.load/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    /private/var/folders/cz/fnf__xc15sn5lg_drgbyfl9c0000gn/T/intellij_elixir/debugger/lib/debug_task.ex:17: Mix.Tasks.IntellijElixir.DebugTask.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2

10:17:01.414 [warn]  The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{message: "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse version 0.12 of bcrypt_elixir.\nSee the Comeonin wiki for more information.\n"},
 [{Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 14]},
  {:code_server, :"-handle_on_load/5-fun-0-", 1,
   [file: 'code_server.erl', line: 1333]}]}
```

This error does not happen when i run it from the command line with `mix phx.server`

**Comment by DominikGuzei** [comment]
For anyone running into the same issue, i could solve it by switching from `bcrypt_elixir` to `{:pbkdf2_elixir, "~> 0.12.3"},` instead
