### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by herokuprojects666** [KronicDeth/intellij-elixir#892]
# Version

6.1.1

# Exception

## Message

Error while indexing /Users/adamcragg/Desktop/new-dash/deploy/docker/var/dash/assets/lib/ace/demo/kitchen-sink/docs/elixir.ex
To reindex this file IDEA has to be restarted: com/ericsson/otp/erlang/OtpErlangAtom

## Stacktrace

```
java.lang.NoClassDefFoundError: com/ericsson/otp/erlang/OtpErlangAtom
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.<clinit>(ElixirPsiImplUtil.java:87)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.isCallingMacro(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:128)
	at org.elixir_lang.structure_view.element.CallDefinitionClause.isCallingKernelMacroOrHead(CallDefinitionClause.java:292)
	at org.elixir_lang.structure_view.element.CallDefinitionClause.isPrivateFunction(CallDefinitionClause.java:190)
	at org.elixir_lang.structure_view.element.CallDefinitionClause.isFunction(CallDefinitionClause.java:182)
	at org.elixir_lang.structure_view.element.CallDefinitionClause.is(CallDefinitionClause.java:178)
	at org.elixir_lang.psi.stub.type.call.Stub.isEnclosableByModular(Stub.java:58)
	at org.elixir_lang.psi.stub.type.call.Stub.isNameable(Stub.java:67)
	at org.elixir_lang.psi.stub.type.call.Stub.shouldCreateStub(Stub.java:79)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:69)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.a(StubUpdatingIndex.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:843)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:208)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:191)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:457)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1633)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1559)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1516)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1501)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:107)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:236)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.ericsson.otp.erlang.OtpErlangAtom PluginClassLoader[org.elixir_lang, 6.1.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more

```

**Comment by KronicDeth** [comment]
Update to latest release (6.4.0) and re-report if you still have the error.
