### ISSUE TITLE
[Auto-generated] java.lang.NoClassDefFoundError: com/intellij/mock/MockProjectEx

### ISSUE THREAD

**Issue by RamanBut-Husaim** [KronicDeth/intellij-elixir#903]
# Version

6.5.0

# Exception

## Message

com/intellij/mock/MockProjectEx

## Stacktrace

```
java.lang.NoClassDefFoundError: com/intellij/mock/MockProjectEx
	at org.elixir_lang.parser.ExternalRules.ifVersion(ExternalRules.java:18)
	at org.elixir_lang.parser.ElixirParser.unmatchedUnaryNonNumericOperation_0(ElixirParser.java:6528)
	at org.elixir_lang.parser.ElixirParser.unmatchedUnaryNonNumericOperation(ElixirParser.java:6516)
	at org.elixir_lang.parser.ElixirParser.unmatchedExpression(ElixirParser.java:6325)
	at org.elixir_lang.parser.ElixirParser.expression(ElixirParser.java:2028)
	at org.elixir_lang.parser.ElixirParser.expressionList(ElixirParser.java:2040)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1_0(ElixirParser.java:1913)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1(ElixirParser.java:1904)
	at org.elixir_lang.parser.ElixirParser.elixirFile(ElixirParser.java:1889)
	at org.elixir_lang.parser.ElixirParser.parse_root_(ElixirParser.java:479)
	at org.elixir_lang.parser.ElixirParser.parseLight(ElixirParser.java:473)
	at org.elixir_lang.parser.ElixirParser.parse(ElixirParser.java:20)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.keepTreeFromChameleoningBack(MultiHostRegistrarImpl.java:358)
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.doneInjecting(MultiHostRegistrarImpl.java:235)
	at org.intellij.plugins.markdown.injection.CodeFenceInjector.getLanguagesToInject(CodeFenceInjector.java:42)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:461)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:312)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:144)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryLineMarkersForInjected(LineMarkersPass.java:241)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:203)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.mock.MockProjectEx PluginClassLoader[org.elixir_lang, 6.5.0] com.intellij.ide.plugins.cl.PluginClassLoader@5a4221ac
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more

```

**Comment by KronicDeth** [comment]
🤦‍♂️  Goddamn it, that's code to make sure the tests don't fuck up and it done fucked up the release.

Thanks for the report.  This probably affects *everyone* for this release.

**Comment by KronicDeth** [comment]
@RamanBut-Husaim which IDE are you using?

**Comment by RamanBut-Husaim** [comment]
@KronicDeth Hello. [JetBrains Rider](https://www.jetbrains.com/rider/).

Sorry for this. The exception occurred in the folder that contain a bunch of `eex` files and some static content - just test folder for some git training that I'm preparing right now.

**Comment by KronicDeth** [comment]
The code that triggered is in the part of the parser that decides whether or not 1.5.0 parser changes should run.  It has nothing to do with the code that triggered it really because almost any realistic code will pass through those grammar rules.

JetBrains Rider *may* ship with different test code than IntelliJ, but it probably means that Rubymine will also be affected.

**Comment by RamanBut-Husaim** [comment]
@KronicDeth Thanks a lot!
