### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by nkitiyakara** [KronicDeth/intellij-elixir#906]
# Version

6.5.0

# Description

Just typing in a case statement.

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getKeywordValue(ElixirPsiImplUtil.java:3039)
	at org.elixir_lang.psi.impl.ElixirKeywordPairImpl.getKeywordValue(ElixirKeywordPairImpl.java:47)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:520)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:509)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:113)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:375)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:382)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:72)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:390)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:78)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1806)
	at org.elixir_lang.psi.impl.ElixirStabOperationImpl.processDeclarations(ElixirStabOperationImpl.java:66)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1103)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:90)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.java:58)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:142)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:666)
	at org.elixir_lang.annotator.Callable$1.visitPlainCall(Callable.java:172)
	at org.elixir_lang.annotator.Callable$1.visitNonModuleAttributeCall(Callable.java:156)
	at org.elixir_lang.annotator.Callable$1.visitCall(Callable.java:114)
	at org.elixir_lang.annotator.Callable$1.visitElement(Callable.java:148)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:42)
	at org.elixir_lang.annotator.Callable.annotate(Callable.java:105)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by KronicDeth** [comment]
Typing `case` isn't going to trigger code walking keyword pairs.  Can you post any more details?

**Comment by nkitiyakara** [comment]
@KronicDeth ,

Sorry, I don't think I can really give you any more detail.  I was typing (it was more likely in the body of the case statement than the word "case," but I can't swear to it at this point) and got this error.  The problem hasn't happened since then, but I'll try to be aware of other details if it does happen again.
