### ISSUE TITLE
Cannot read typeID from rabbit_common/ebin/rabbit_binary_parser.beam

### ISSUE THREAD

**Issue by charangas** [KronicDeth/intellij-elixir#908]
# Version

6.5.1

# Exception

## Message

Could not read typeID: read only 3 of 4 bytes from deps/rabbit_common/ebin/rabbit_binary_parser.beam

## Stacktrace

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at org.elixir_lang.beam.chunk.Chunk.typeID(Chunk.java:71)
	at org.elixir_lang.beam.chunk.Chunk.from(Chunk.java:32)
	at org.elixir_lang.beam.Beam.from(Beam.java:107)
	at org.elixir_lang.beam.Beam.lambda$from$0(Beam.java:132)
	at java.util.Optional.flatMap(Optional.java:241)
	at org.elixir_lang.beam.Beam.from(Beam.java:132)
	at org.elixir_lang.beam.psi.BeamFileImpl.buildFileStub(BeamFileImpl.java:89)
	at org.elixir_lang.beam.StubBuilder.buildStubTree(StubBuilder.java:31)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:63)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.a(StubUpdatingIndex.java:211)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:926)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:210)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:193)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:251)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:96)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:194)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1582)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1518)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:516)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1479)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1464)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1443)
	at com.intellij.util.indexing.FileBasedIndexProjectHandler.a(FileBasedIndexProjectHandler.java:146)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
@charangas can you put the `deps/rabbit_common/ebin/rabbit_binary_parser.beam` in a `zip` file and drop in it in a comment to this issue?  Then I can look at it in the debugger and hexeditor to figure out what's going on.
