### ISSUE TITLE
HomePath.mergeHomebrew does not handle `HEAD-<SHA1>` correctly

### ISSUE THREAD

**Issue by geekerzp** [KronicDeth/intellij-elixir#912]
<img width="800" alt="2017-11-22 12 31 21" src="https://user-images.githubusercontent.com/2854886/33084294-86eee5b6-cf1c-11e7-8d3f-c10f56147b59.png">

# Version

6.5.1

# Exception

## Message

Argument for @NotNull parameter 'version' of com/intellij/openapi/util/Version.compareTo must not be null

## Stacktrace

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'version' of com/intellij/openapi/util/Version.compareTo must not be null
	at com.intellij.openapi.util.Version.$$$reportNull$$$0(Version.java)
	at com.intellij.openapi.util.Version.compareTo(Version.java)
	at org.elixir_lang.sdk.elixir.Type.lambda$homePathByVersion$8(Type.java:569)
	at java.util.TreeMap.put(TreeMap.java:552)
	at org.elixir_lang.sdk.HomePath.mergeNameSubdirectories(HomePath.java:76)
	at org.elixir_lang.sdk.HomePath.mergeHomebrew(HomePath.java:57)
	at org.elixir_lang.sdk.elixir.Type.homePathByVersion(Type.java:574)
	at org.elixir_lang.sdk.elixir.Type.suggestHomePaths(Type.java:662)
	at org.elixir_lang.sdk.elixir.Type.suggestHomePath(Type.java:649)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.getSuggestedSdkRoot(SdkConfigurationUtil.java:310)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:294)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.createSdkOfType(DependentSdkType.java:82)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.showCustomCreateUI(DependentSdkType.java:69)
	at com.intellij.openapi.projectRoots.SdkType.showCustomCreateUI(SdkType.java:258)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:273)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$1.actionPerformed(ProjectSdksModel.java:259)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:966)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:956)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:950)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1431)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:734)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:456)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:51)
	at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:41)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by geekerzp** [comment]
@KronicDeth

**Comment by gw4e** [comment]
+1 @KronicDeth 
On mac os Sierra 10.12.6 with IntelliJ 2017.2

**Comment by KronicDeth** [comment]
You don't need to ping me by name.  I'm the only Contributor on the repo.  I see everything. 

@geekerzp what versions of Elixir do you have installed under homebrew?

**Comment by KronicDeth** [comment]
@geekerzp sorry, no, that's not what I meant, I want the directory names under `ls /usr/local/Cellar/elixir`.  

- [ ] `ls /usr/local/Cellar/elixir`

The code is reading the name of the directories and that's what's causing a `null`.

**Comment by geekerzp** [comment]
Oh, sorry
<img width="469" alt="2017-11-22 11 35 18" src="https://user-images.githubusercontent.com/2854886/33135616-e0decd0e-cfdd-11e7-81bd-3139b08eeafb.png">

**Comment by geekerzp** [comment]
BTW, `HEAD-1c0d588` is the elixir 1.6.0-dev

**Comment by KronicDeth** [comment]
Ok, yeah, so the `HEAD-<SHA1>` format is messing it up.

**Comment by KronicDeth** [comment]
Unfortunately, the only work-around for now is to `mv` `HEAD-1c0d588` to a name like `1.6.0` that the current version parser can parse.

**Comment by geekerzp** [comment]
Cool 👏，thanks very much! Very appreciate! 🙏

**Comment by geekerzp** [comment]
BTW Thank you for bringing me such a great plugin 🙏

**Comment by KronicDeth** [comment]
@geekerzp don't close the issue.  I just gave you a work-around.  I still need to fix the version parser to handle `HEAD-<SHA1>`.

**Comment by geekerzp** [comment]
OK, I see 😊
