### ISSUE TITLE
java.lang.StackOverflowError in FindUsageProdiver.getType

### ISSUE THREAD

**Issue by simapetr85** [KronicDeth/intellij-elixir#919]
# Version

6.5.1

# Exception

## Message

Worker exited due to exception

## Stacktrace

```
java.lang.StackOverflowError
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:35)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:101)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:29)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageVi

**Comment by KronicDeth** [comment]
@simapetr85 any idea what type of element you were trying to FInd Usage on?
