### ISSUE TITLE
accessExpressions should be flattened with buildAccessExpressionChildren

### ISSUE THREAD

**Issue by iwasaki-kenta** [KronicDeth/intellij-elixir#921]
# Version

6.5.1

# Exception

## Message

accessExpressions should be flattened with buildAccessExpressionChildren

## Stacktrace

```
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren
	at org.elixir_lang.formatter.Block.<init>(Block.java:306)
	at org.elixir_lang.formatter.Block.buildChild(Block.java:790)
	at org.elixir_lang.formatter.Block.lambda$buildMapUpdateArgumentsChildren$27(Block.java:1516)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:325)
	at org.elixir_lang.formatter.Block.buildMapUpdateArgumentsChildren(Block.java:1506)
	at org.elixir_lang.formatter.Block.lambda$buildMapArgumentsChildren$24(Block.java:1419)
	at org.elixir_lang.formatter.Block.lambda$buildContainerChildren$14(Block.java:1079)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:325)
	at org.elixir_lang.formatter.Block.buildContainerChildren(Block.java:1069)
	at org.elixir_lang.formatter.Block.buildMapArgumentsChildren(Block.java:1407)
	at org.elixir_lang.formatter.Block.lambda$buildMapChildren$25(Block.java:1439)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:325)
	at org.elixir_lang.formatter.Block.buildMapChildren(Block.java:1434)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:876)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:963)
	at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:61)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:164)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:264)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:136)
	at com.intellij.formatting.engine.WrapBlocksState.doIteration(WrapBlocksState.java:47)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:41)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:107)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:926)
	at com.intellij.util.SequentialModalProgressTask.a(SequentialModalProgressTask.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:680)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:693)
	at com.intellij.util.SequentialModalProgressTask.doRun(SequentialModalProgressTask.java:89)
	at com.intellij.util.SequentialModalProgressTask.run(SequentialModalProgressTask.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:581)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:414)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:332)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:317)
	at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:343)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:295)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processText(CodeFormatterFacade.java:249)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:236)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:174)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:160)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.a(ReformatCodeProcessor.java:129)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:239)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1030)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:239)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:342)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.c(AbstractLayoutCodeProcessor.java:422)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:420)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by KronicDeth** [comment]
There would indicate something unexpected happened in the code.   Pprobably error handling was engaged and the formatted doesn't handle the partial node correctly.  Any idea what your code looked like when this happened, so I can reproduce the error?

**Comment by KronicDeth** [comment]
No feedback received.
