### ISSUE TITLE
7.1.0 @NotNull method com/intellij/openapi/roots/OrderRootType.getOrderRootType must not return null

### ISSUE THREAD

**Issue by nitingupta910** [KronicDeth/intellij-elixir#961]
Just upgrade to 7.1.0 of this plugin and now I'm unable to configure Elixir SDK in CLion 2017.3.1.  I could set Erlang (20.1) SDK but when setting Elixir (1.5.3) SDK, I'm getting this backtrace from this plugin:

version 7.0.0 worked fine.

```
@NotNull method com/intellij/openapi/roots/OrderRootType.getOrderRootType must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/openapi/roots/OrderRootType.getOrderRootType must not return null
	at com.intellij.openapi.roots.OrderRootType.$$$reportNull$$$0(OrderRootType.java)
	at com.intellij.openapi.roots.OrderRootType.getOrderRootType(OrderRootType.java:127)
	at com.intellij.openapi.roots.JavadocOrderRootType.getInstance(JavadocOrderRootType.java:35)
	at org.elixir_lang.sdk.elixir.Type.documentationRootType(Type.java:118)
	at org.elixir_lang.sdk.elixir.Type.addDocumentationPath(Type.java:105)
	at org.elixir_lang.sdk.elixir.Type.addDocumentationPath(Type.java:131)
	at org.elixir_lang.sdk.elixir.Type.lambda$addDocumentationPaths$0(Type.java:139)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.elixir_lang.sdk.HomePath.lambda$eachEbinPath$0(HomePath.java:39)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.elixir_lang.sdk.HomePath.eachEbinPath(HomePath.java:36)
	at org.elixir_lang.sdk.elixir.Type.addDocumentationPaths(Type.java:137)
	at org.elixir_lang.sdk.elixir.Type.configureSdkPaths(Type.java:171)
	at org.elixir_lang.sdk.elixir.Type.setupSdkPaths(Type.java:620)
	at com.intellij.openapi.projectRoots.SdkType.setupSdkPaths(SdkType.java:102)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.a(ProjectSdksModel.java:290)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.a(ProjectSdksModel.java:273)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.a(DependentSdkType.java:87)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.a(SdkConfigurationUtil.java:297)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:174)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:114)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:91)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:294)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.createSdkOfType(DependentSdkType.java:82)
	at com.intellij.openapi.projectRoots.impl.DependentSdkType.showCustomCreateUI(DependentSdkType.java:69)
	at com.intellij.openapi.projectRoots.SdkType.showCustomCreateUI(SdkType.java:258)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:273)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:267)
	at org.elixir_lang.facet.sdks.Configurable.addSdk(Configurable.kt:123)
	at org.elixir_lang.facet.sdks.Configurable.access$addSdk(Configurable.kt:22)
	at org.elixir_lang.facet.sdks.Configurable$createComponent$decorator$1.run(Configurable.kt:57)
	at org.elixir_lang.facet.sdks.Configurable$createComponent$decorator$1.run(Configurable.kt:56)
	at com.intellij.ui.ToolbarDecorator$2.doAdd(ToolbarDecorator.java:440)
	at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:72)
	at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:263)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:151)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:344)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:734)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:456)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:83)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:97)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:118)
	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:212)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.b(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment]
huh, I specifically added `org.elixir_lang.sdk.elixir.Type.documentationRootType` to prevent errors when accessing `JavaDocRootType.getInstance()` when it's not defined, but I guess in CLion an earlier point in the code needs to be `catch`ed or I need a different way of avoiding that call.

**Comment by KronicDeth** [comment]
The `@NotNull` annotation was added 4 months ago.

![screen shot 2017-12-30 at 8 37 20 pm](https://user-images.githubusercontent.com/298259/34458690-54d50eb8-eda1-11e7-8992-9c324bfc9680.png)
