### ISSUE TITLE
[auto-generated] Argument for @NotNull parameter 'file' of com/intellij/lang/ExternalLanguageAnnotators.allForFile must not be null

### ISSUE THREAD

**Issue by h6ak** [KronicDeth/intellij-elixir#968]
# Version

7.2.0

# Exception

## Message

Argument for @NotNull parameter 'file' of com/intellij/lang/ExternalLanguageAnnotators.allForFile must not be null

## Stacktrace

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/lang/ExternalLanguageAnnotators.allForFile must not be null
	at com.intellij.lang.ExternalLanguageAnnotators.allForFile(ExternalLanguageAnnotators.java)
	at org.elixir_lang.credo.inspection_tool.Local.checkFile(Local.kt:22)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
	at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:74)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:282)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:250)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:222)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by h6ak** [comment]
This exception appear on IntelliJ IDEA 2017.1.1 .
After I updated my IntelliJ to the newest version, this exception disappeared.
