### ISSUE TITLE
Upgrade not supported by this NIF library

### ISSUE THREAD

**Issue by hopewise** [KronicDeth/intellij-elixir#989]
I have used the env var `INTELLIJ_ELIXIR_DEBUG_BLACKLIST ` to exclude `lz4 ` that caused an error while compiling, I get different error:

```
16:48:36.901 [warn]  The on_load function for module re2 returned:
{:error, {:upgrade, 'Upgrade not supported by this NIF library.'}}

** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    int.erl:531: anonymous fn/3 in :int.load/2
    int.erl:527: :int.load/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    /private/var/folders/m4/b74csk195j1f1x4vdpp6m6x80000gp/T/intellij_elixir/debugger/lib/debug_task.ex:19: Mix.Tasks.IntellijElixir.DebugTask.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
```

Any idea?

**Comment by hopewise** [comment]
Any one?

**Comment by KronicDeth** [comment]
Try adding `re2` to the blacklist too?

**Comment by hopewise** [comment]
Thanks, I tried, but I get error: "Debug process stopped" after I start the server, I get this as the last logged lines:

```
*DBG* 'Elixir.IntellijElixir.DebugServer' got {'DOWN',
                                               #Ref<0.3002285534.772276227.262029>,
                                               process,<0.1598.0>,normal}
```

and before it I got:


```
*DBG* 'Elixir.IntellijElixir.DebugServer' got {tcp,#Port<0.78500>,
                                               <<131,104,4,100,0,14,115,101,
                                                 116,95,98,114,101,97,107,112,
                                                 111,105,110,116,100,0,31,69,
                                                 108,105,120,105,114,46,84,
                                                 114,97,99,107,119,97,114,101,
                                                 46,80,97,103,101,67,111,110,
                                                 116,114,111,108,108,101,114,
                                                 97,9,107,0,73,47,85,115,101,
                                                 114,115,47,115,97,109,105,
                                                 114,47,68,111,99,117,109,101,
                                                 110,116,115,47,112,114,111,
                                                 106,101,99,116,115,47,101,
                                                 108,105,120,105,114,47,119,
                                                 101,98,47,99,111,110,116,114,
                                                 111,108,108,101,114,115,47,
                                                 112,97,103,101,95,99,111,110,
                                                 116,114,111,108,108,101,114,
                                                 46,101,120>>}
*DBG* 'Elixir.IntellijElixir.DebugServer' new state #{ref => nil,
                                                      socket => #Port<0.78500>,
                                                      task => {<<"run">>,[]}}
*DBG* 'Elixir.IntellijElixir.DebugServer' got {tcp,#Port<0.78500>,
                                               <<131,104,1,100,0,8,114,117,
                                                 110,95,116,97,115,107>>}
*DBG* 'Elixir.IntellijElixir.DebugServer' new state #{ref =>
                                                          #Ref<0.795360951.3456630785.87346>,
                                                      socket => #Port<0.78500>,
                                                      task => {<<"run">>,[]}}
```

I hope I am getting closer to finally debug my code 🤒
