### ISSUE TITLE
NoSuchMethodError: one.util.streamex.StreamEx.nonNull()

### ISSUE THREAD

**Issue by MrFlorius** [KronicDeth/intellij-elixir#992]
# Version

7.2.1

# Exception

## Message

one.util.streamex.StreamEx.nonNull()Lone/util/streamex/StreamEx;

## Stacktrace

```
java.lang.NoSuchMethodError: one.util.streamex.StreamEx.nonNull()Lone/util/streamex/StreamEx;
	at org.elixir_lang.file.LevelPropertyPusher.initExtra(LevelPropertyPusher.java:164)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.initializeProperties(PushedFilePropertiesUpdaterImpl.java:128)
	at com.intellij.util.indexing.FileBasedIndexProjectHandler.a(FileBasedIndexProjectHandler.java:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:359)
	at com.intellij.ide.startup.impl.StartupManagerImpl.f(StartupManagerImpl.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:926)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivities(StartupManagerImpl.java:122)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:393)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:422)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:485)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:476)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:326)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:590)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
1. Which IDE?
2. What version of that IDE?
3. What was your SDK set to when this happened?
4. Were you changing your SDK when this happened?

**Comment by gr8bit** [comment]
I HAD the same error and was about to report it here but I wanted to update to the latest version before. Now that I've updated RubyMine, Elixir and Erlang to the following versions, everything started working again:
* RubyMine 2017.3.1 (=latest stable) on OSX 10.12.6
* Elixir 1.5.3, installed via brew (`/usr/local/Cellar/elixir/1.5.3_1/`)
* Erlang 20 (`/usr/local/Cellar/erlang/20.2.2/`)
Maybe that helps someone...
