### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by dkotrada** [KronicDeth/intellij-elixir#995]
# Version

7.2.1

# Exception

## Message

unable to get stub builder for com.intellij.openapi.fileTypes.UnknownFileType@79c543f9, , stubBindingRoot = PsiBinaryFileImpl, languages = [], fileTypes = [UNKNOWN], files = [PsiBinaryFileImpl], roots = []

## Stacktrace

```
java.lang.Throwable: unable to get stub builder for com.intellij.openapi.fileTypes.UnknownFileType@79c543f9, , stubBindingRoot = PsiBinaryFileImpl, languages = [], fileTypes = [UNKNOWN], files = [PsiBinaryFileImpl], roots = []
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.psi.stubs.StubProcessingHelperBase.a(StubProcessingHelperBase.java:103)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:54)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:327)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:618)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:606)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:356)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:319)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at org.elixir_lang.psi.scope.module.Variants.addProjectNameElementsTo(Variants.java:302)
	at org.elixir_lang.psi.scope.module.Variants.lookupElementList(Variants.java:52)
	at org.elixir_lang.reference.Module.getVariants(Module.java:67)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:273)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:137)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:81)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:71)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:125)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:108)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:152)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:112)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:839)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:92)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:821)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.b(CompletionProgressIndicator.java:832)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment]
You show open this as a bug with JetBrains and give them your complete plugin list.  They might be able to help with which plugin is giving you "UnknownFileType".
